#if 0
* hhh-vars.h
* variable declarations
* generated by FormCalc 8.4 on 13-Apr-2015 11:52
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hhh-renconst.h"

	ComplexType Sub11, Sub1, Sub2, Sub5, Sub3, Sub6, Sub4, Sub7
	ComplexType Sub9, Sub8, Sub10, Sub12
	ComplexType Opt1, Sub645, Sub416, Sub741, Sub447, Sub449
	ComplexType Sub479, Sub643, Sub493, Sub485, Sub311, Sub451
	ComplexType Sub453, Sub565, Sub313, Sub316, Sub318, Sub556
	ComplexType Sub752, Sub749, Sub558, Sub718, Sub454, Sub452
	ComplexType Sub550, Sub202, Sub264, Sub214, Sub209, Sub211
	ComplexType Sub216, Sub206, Sub210, Sub212, Sub215, Sub217
	ComplexType Sub262, Sub234, Sub230, Sub232, Sub236, Sub229
	ComplexType Sub228, Sub231, Sub233, Sub235, Sub237, Sub756
	ComplexType Sub761, Sub753, Sub762, Sub755, Sub750, Sub332
	ComplexType Sub487, Sub483, Sub365, Sub368, Sub366, Sub369
	ComplexType Sub581, Sub582, Sub619, Sub342, Sub349, Sub354
	ComplexType Sub357, Sub361, Sub399, Sub374, Sub398, Sub594
	ComplexType Sub593, Sub382, Sub384, Sub383, Sub386, Sub392
	ComplexType Sub397, Sub707, Sub405, Sub456, Sub457, Sub629
	ComplexType Sub631, Sub625, Sub627, Sub720, Sub424, Sub429
	ComplexType Sub433, Sub435, Sub439, Sub448, Sub450, Sub460
	ComplexType Sub461, Sub634, Sub636, Sub471, Sub510, Sub498
	ComplexType Sub478, Sub486, Sub488, Sub496, Sub501, Sub641
	ComplexType Sub639, Sub521, Sub524, Sub528, Sub531, Sub534
	ComplexType Sub537, Sub548, Sub549, Sub551, Sub554, Sub557
	ComplexType Sub559, Sub561, Sub564, Sub566, Sub568, Sub571
	ComplexType Sub578, Sub584, Sub592, Sub320, Sub618, Sub624
	ComplexType Sub626, Sub628, Sub630, Sub632, Sub635, Sub637
	ComplexType Sub640, Sub642, Sub661, Sub664, Sub665, Sub675
	ComplexType Sub679, Sub686, Sub695, Sub698, Sub660, Sub704
	ComplexType Sub708, Sub733, Sub735, Sub751, Sub754, Sub764
	ComplexType Sub767, Sub323, Sub358, Sub24, Sub191, Sub267
	ComplexType Sub269, Sub268, Sub745, Sub363, Sub739, Sub768
	ComplexType Sub256, Sub257, Sub258, Sub413, Sub612, Sub611
	ComplexType Sub759, Sub359, Sub757, Sub758, Sub360, Sub355
	ComplexType Sub356, Sub430, Sub570, Sub608, Sub668, Sub596
	ComplexType Sub351, Sub747, Sub763, Sub746, Sub744, Sub511
	ComplexType Sub504, Sub544, Sub529, Sub431, Sub595, Sub567
	ComplexType Sub535, Sub673, Sub522, Sub462, Sub555, Sub445
	ComplexType Sub469, Sub560, Sub468, Sub465, Sub552, Sub467
	ComplexType Sub523, Sub532, Sub458, Sub477, Sub421, Sub546
	ComplexType Sub547, Sub638, Sub683, Sub530, Sub432, Sub676
	ComplexType Sub583, Sub667, Sub545, Sub633, Sub694, Sub540
	ComplexType Sub492, Sub481, Sub396, Sub600, Sub506, Sub495
	ComplexType Sub586, Sub601, Sub684, Sub574, Sub434, Sub677
	ComplexType Sub516, Sub644, Sub587, Sub512, Sub576, Sub700
	ComplexType Sub562, Sub403, Sub517, Sub541, Sub602, Sub525
	ComplexType Sub588, Sub423, Sub599, Sub575, Sub436, Sub515
	ComplexType Sub671, Sub585, Sub426, Sub513, Sub503, Sub692
	ComplexType Sub577, Sub401, Sub569, Sub563, Sub553, Sub404
	ComplexType Sub508, Sub388, Sub500, Sub428, Sub690, Sub518
	ComplexType Sub394, Sub693, Sub542, Sub507, Sub395, Sub603
	ComplexType Sub400, Sub703, Sub526, Sub505, Sub494, Sub367
	ComplexType Sub589, Sub370, Sub422, Sub604, Sub669, Sub685
	ComplexType Sub580, Sub437, Sub678, Sub519, Sub509, Sub497
	ComplexType Sub670, Sub590, Sub425, Sub197, Sub242, Sub327
	ComplexType Sub337, Sub740, Sub218, Sub334, Sub346, Sub389
	ComplexType Sub340, Sub473, Sub647, Sub390, Sub391, Sub743
	ComplexType Sub607, Sub606, Sub742, Sub748, Sub766, Sub224
	ComplexType Sub221, Sub205, Sub198, Sub199, Sub243, Sub325
	ComplexType Sub336, Sub219, Sub333, Sub344, Sub379, Sub339
	ComplexType Sub472, Sub646, Sub244, Sub440, Sub380, Sub381
	ComplexType Sub329, Sub335, Sub338, Sub341, Sub348, Sub597
	ComplexType Sub609, Sub225, Sub222, Sub200, Sub201, Sub330
	ComplexType Sub331, Sub687, Sub441, Sub245, Sub717, Sub406
	ComplexType Sub443, Sub470, Sub674, Sub682, Sub689, Sub203
	ComplexType Sub247, Sub466, Sub409, Sub220, Sub444, Sub446
	ComplexType Sub474, Sub459, Sub417, Sub70, Sub248, Sub711
	ComplexType Sub250, Sub714, Sub315, Sub475, Sub476, Sub223
	ComplexType Sub226, Sub204, Sub207, Sub352, Sub353, Sub724
	ComplexType Sub249, Sub722, Sub732, Sub28, Sub29, Sub728
	ComplexType Sub251, Sub723, Sub734, Sub817(2), Sub252(3)
	ComplexType Sub255(3), Sub246(3), Sub65(3), Sub52(3)
	ComplexType Sub64(3), Sub50(3), Sub59(3), Sub57(3)
	ComplexType Sub180(3), Sub179(3), Sub176(3), Sub105(3)
	ComplexType Sub175(3), Sub103(3), Sub98(3), Sub96(3)
	ComplexType Sub111(3), Sub110(3), Sub145(3), Sub132(3)
	ComplexType Sub144(3), Sub130(3), Sub139(3), Sub137(3)
	ComplexType Sub184(3), Sub183(3), Sub56(3), Sub60(3)
	ComplexType Sub40(3), Sub41(3), Sub189(3), Sub34(3)
	ComplexType Sub35(3), Sub49(3), Sub53(3), Sub38(3), Sub37(3)
	ComplexType Sub46(3), Sub45(3), Sub239(3), Sub95(3)
	ComplexType Sub99(3), Sub91(3), Sub86(3), Sub87(3), Sub92(3)
	ComplexType Sub192(3), Sub83(3), Sub84(3), Sub106(3)
	ComplexType Sub102(3), Sub81(3), Sub80(3), Sub227(3)
	ComplexType Sub136(3), Sub140(3), Sub120(3), Sub121(3)
	ComplexType Sub194(3), Sub114(3), Sub115(3), Sub129(3)
	ComplexType Sub133(3), Sub118(3), Sub117(3), Sub126(3)
	ComplexType Sub125(3), Sub259(3), Sub240(3), Sub196(3)
	ComplexType Sub208(3), Sub213(3), Sub253(3), Sub254(3)
	ComplexType Sub260(3), Sub261(3), Sub271(3), Sub272(3)
	ComplexType Sub266(3), Sub958(4), Sub275(4), Sub273(4)
	ComplexType Sub278(4), Sub281(4), Sub290(4), Sub287(4)
	ComplexType Sub293(4), Sub296(4), Sub299(4), Sub285(4)
	ComplexType Sub274(4), Sub276(4), Sub279(4), Sub282(4)
	ComplexType Sub291(4), Sub286(4), Sub294(4), Sub297(4)
	ComplexType Sub300(4), Sub288(4), Sub926(4), Sub927(4)
	ComplexType Sub929(4), Sub931(4), Sub934(4), Sub935(4)
	ComplexType Sub937(4), Sub939(4), Sub32(2,2), Sub23(2,2)
	ComplexType Sub30(2,2), Sub27(2,2), Sub14(2,2), Sub16(2,2)
	ComplexType Sub15(2,2), Sub789(2,2), Sub791(2,2)
	ComplexType Sub790(2,2), Sub18(2,2), Sub777(2,2)
	ComplexType Sub779(2,2), Sub778(2,2), Sub13(2,2), Sub19(2,2)
	ComplexType Sub21(2,2), Sub20(2,2), Sub793(2,2), Sub795(2,2)
	ComplexType Sub794(2,2), Sub801(2,2), Sub803(2,2)
	ComplexType Sub802(2,2), Sub769(2,2), Sub771(2,2)
	ComplexType Sub770(2,2), Sub781(2,2), Sub783(2,2)
	ComplexType Sub782(2,2), Sub773(2,2), Sub775(2,2)
	ComplexType Sub774(2,2), Sub785(2,2), Sub787(2,2)
	ComplexType Sub786(2,2), Sub797(2,2), Sub799(2,2)
	ComplexType Sub798(2,2), Sub805(2,2), Sub807(2,2)
	ComplexType Sub806(2,2), Sub823(3,2), Sub824(3,2)
	ComplexType Sub826(3,2), Sub827(3,2), Sub860(3,2)
	ComplexType Sub861(3,2), Sub857(3,2), Sub858(3,2)
	ComplexType Sub891(3,2), Sub892(3,2), Sub894(3,2)
	ComplexType Sub895(3,2), Sub190(3,2), Sub193(3,2)
	ComplexType Sub195(3,2), Sub51(3,2), Sub54(3,2), Sub58(3,2)
	ComplexType Sub61(3,2), Sub104(3,2), Sub107(3,2), Sub97(3,2)
	ComplexType Sub100(3,2), Sub131(3,2), Sub134(3,2)
	ComplexType Sub138(3,2), Sub141(3,2), Sub832(3,2)
	ComplexType Sub833(3,2), Sub835(3,2), Sub836(3,2)
	ComplexType Sub869(3,2), Sub870(3,2), Sub866(3,2)
	ComplexType Sub867(3,2), Sub900(3,2), Sub901(3,2)
	ComplexType Sub903(3,2), Sub904(3,2), Sub277(4,4)
	ComplexType Sub280(4,4), Sub283(4,4), Sub289(4,4)
	ComplexType Sub292(4,4), Sub295(4,4), Sub298(4,4)
	ComplexType Sub301(4,4), Sub309(4,4), Sub303(4,4)
	ComplexType Sub307(4,4), Sub306(4,4), Sub305(4,4)
	ComplexType Sub304(4,4), Sub942(4,4), Sub943(4,4)
	ComplexType Sub944(4,4), Sub936(4,4), Sub938(4,4)
	ComplexType Sub940(4,4), Sub928(4,4), Sub930(4,4)
	ComplexType Sub932(4,4), Sub946(4,4), Sub947(4,4)
	ComplexType Sub948(4,4), Sub813(2,2,2), Sub819(2,2,2)
	ComplexType Sub815(2,2,2), Sub814(2,2,2), Sub816(2,2,2)
	ComplexType Sub820(2,2,2), Sub821(2,2,2), Sub822(2,2,2)
	ComplexType Sub174(3,2,2), Sub178(3,2,2), Sub182(3,2,2)
	ComplexType Sub186(3,2,2), Sub173(3,2,2), Sub187(3,2,2)
	ComplexType Sub169(3,2,2), Sub55(3,2,2), Sub62(3,2,2)
	ComplexType Sub66(3,2,2), Sub101(3,2,2), Sub108(3,2,2)
	ComplexType Sub112(3,2,2), Sub135(3,2,2), Sub142(3,2,2)
	ComplexType Sub146(3,2,2), Sub841(3,2,2), Sub842(3,2,2)
	ComplexType Sub181(3,2,2), Sub844(3,2,2), Sub171(3,2,2)
	ComplexType Sub36(3,2,2), Sub39(3,2,2), Sub42(3,2,2)
	ComplexType Sub47(3,2,2), Sub875(3,2,2), Sub876(3,2,2)
	ComplexType Sub878(3,2,2), Sub177(3,2,2), Sub170(3,2,2)
	ComplexType Sub82(3,2,2), Sub85(3,2,2), Sub88(3,2,2)
	ComplexType Sub93(3,2,2), Sub909(3,2,2), Sub910(3,2,2)
	ComplexType Sub912(3,2,2), Sub185(3,2,2), Sub172(3,2,2)
	ComplexType Sub116(3,2,2), Sub119(3,2,2), Sub122(3,2,2)
	ComplexType Sub127(3,2,2), Sub158(3,2,2), Sub163(3,2,2)
	ComplexType Sub74(3,2,2), Sub843(3,2,2), Sub877(3,2,2)
	ComplexType Sub911(3,2,2), Sub159(3,2,2), Sub164(3,2,2)
	ComplexType Sub75(3,2,2), Sub845(3,2,2), Sub879(3,2,2)
	ComplexType Sub913(3,2,2), Sub123(3,2,2), Sub43(3,2,2)
	ComplexType Sub89(3,2,2), Sub148(3,2,2), Sub153(3,2,2)
	ComplexType Sub68(3,2,2), Sub124(3,2,2), Sub44(3,2,2)
	ComplexType Sub90(3,2,2), Sub149(3,2,2), Sub154(3,2,2)
	ComplexType Sub69(3,2,2), Sub128(3,2,2), Sub48(3,2,2)
	ComplexType Sub94(3,2,2), Sub155(3,2,2), Sub71(3,2,2)
	ComplexType Sub150(3,2,2), Sub165(3,2,2), Sub76(3,2,2)
	ComplexType Sub160(3,2,2), Sub109(3,2,2), Sub143(3,2,2)
	ComplexType Sub63(3,2,2), Sub156(3,2,2), Sub72(3,2,2)
	ComplexType Sub151(3,2,2), Sub166(3,2,2), Sub77(3,2,2)
	ComplexType Sub161(3,2,2), Sub113(3,2,2), Sub147(3,2,2)
	ComplexType Sub67(3,2,2), Sub157(3,2,2), Sub73(3,2,2)
	ComplexType Sub152(3,2,2), Sub167(3,2,2), Sub78(3,2,2)
	ComplexType Sub162(3,2,2), Sub846(3,2,2), Sub847(3,2,2)
	ComplexType Sub849(3,2,2), Sub880(3,2,2), Sub881(3,2,2)
	ComplexType Sub883(3,2,2), Sub914(3,2,2), Sub915(3,2,2)
	ComplexType Sub917(3,2,2), Sub825(3,2,2), Sub828(3,2,2)
	ComplexType Sub830(3,2,2), Sub859(3,2,2), Sub862(3,2,2)
	ComplexType Sub864(3,2,2), Sub893(3,2,2), Sub896(3,2,2)
	ComplexType Sub898(3,2,2), Sub829(3,2,2), Sub848(3,2,2)
	ComplexType Sub863(3,2,2), Sub882(3,2,2), Sub897(3,2,2)
	ComplexType Sub916(3,2,2), Sub831(3,2,2), Sub850(3,2,2)
	ComplexType Sub865(3,2,2), Sub884(3,2,2), Sub899(3,2,2)
	ComplexType Sub918(3,2,2), Sub834(3,2,2), Sub837(3,2,2)
	ComplexType Sub839(3,2,2), Sub868(3,2,2), Sub871(3,2,2)
	ComplexType Sub873(3,2,2), Sub902(3,2,2), Sub905(3,2,2)
	ComplexType Sub907(3,2,2), Sub851(3,2,2), Sub852(3,2,2)
	ComplexType Sub854(3,2,2), Sub885(3,2,2), Sub886(3,2,2)
	ComplexType Sub888(3,2,2), Sub919(3,2,2), Sub920(3,2,2)
	ComplexType Sub922(3,2,2), Sub838(3,2,2), Sub853(3,2,2)
	ComplexType Sub872(3,2,2), Sub887(3,2,2), Sub906(3,2,2)
	ComplexType Sub921(3,2,2), Sub840(3,2,2), Sub855(3,2,2)
	ComplexType Sub874(3,2,2), Sub889(3,2,2), Sub908(3,2,2)
	ComplexType Sub923(3,2,2), Sub952(4,4,4), Sub959(4,4,4)
	ComplexType Sub950(4,4,4), Sub951(4,4,4), Sub956(4,4,4)
	ComplexType Sub960(4,4,4), Sub954(4,4,4), Sub955(4,4,4)
	ComplexType Sub957(4,4,4), Sub961(4,4,4), Sub962(4,4,4)
	ComplexType Sub963(4,4,4), Sub856(3,2,2,2), Sub890(3,2,2,2)
	ComplexType Sub924(3,2,2,2), Sub925(3,2,2,2), Sub324, Sub343
	ComplexType Sub350, Sub371, Sub385, Sub407, Sub463, Sub484
	ComplexType Sub514, Sub538, Sub539, Sub543, Sub573, Sub579
	ComplexType Sub652, Sub672, Sub699, Sub411, Sub412, Sub616
	ComplexType Sub765, Sub438, Sub415, Sub502, Sub489, Sub697
	ComplexType Sub393, Sub696, Sub536, Sub533, Sub691, Sub410
	ComplexType Sub427, Sub328, Sub347, Sub377, Sub375, Sub620
	ComplexType Sub326, Sub345, Sub373, Sub376, Sub378, Sub598
	ComplexType Sub622, Sub706, Sub419, Sub442, Sub709, Sub464
	ComplexType Sub617, Sub705, Sub727, Sub725, Sub731, Sub729
	ComplexType Sub490, Sub491, Sub362, Sub658, Sub710, Sub712
	ComplexType Sub659, Sub662, Sub713, Sub715, Sub663
	ComplexType Sub238(3), Sub265(3), Sub270(3), Sub31(2,2)
	ComplexType Sub33(2,2), Sub26(2,2), Sub25(2,2), Sub17(2,2)
	ComplexType Sub22(2,2), Sub780(2,2), Sub792(2,2)
	ComplexType Sub772(2,2), Sub784(2,2), Sub796(2,2)
	ComplexType Sub804(2,2), Sub776(2,2), Sub788(2,2)
	ComplexType Sub800(2,2), Sub808(2,2), Sub308(4,4)
	ComplexType Sub310(4,4), Sub284(4,4), Sub302(4,4)
	ComplexType Sub941(4,4), Sub945(4,4), Sub933(4,4)
	ComplexType Sub949(4,4), Sub812(2,2,2), Sub188(3,2,2)
	ComplexType Sub79(3,2,2), Sub953(4,4,4), Sub480, Sub482
	ComplexType Sub408, Sub520, Sub572, Sub621, Sub719, Sub649
	ComplexType Sub648, Sub760, Sub702, Sub527, Sub499, Sub701
	ComplexType Sub364, Sub387, Sub610, Sub688, Sub681, Sub721
	ComplexType Sub653, Sub654, Sub811(2,2,2), Sub818(2,2,2)
	ComplexType Sub809(2,2,2), Sub810(2,2,2), Sub591, Sub605
	ComplexType Sub623, Sub312, Sub314, Sub317, Sub319, Sub716
	ComplexType Sub414, Sub657, Sub656, Sub614, Sub615, Sub737
	ComplexType Sub321, Sub322, Sub455, Sub650, Sub651
	ComplexType Sub168(3,2,2), Sub241(3), Sub736, Sub666, Sub738
	ComplexType pave1(2), pave2(2,2), pave3(2,2), pave4(3,2)
	ComplexType pave5(3,2), pave6(3,2), pave7(4), pave8(4,4)
	ComplexType pave9(4,4), pave10(2,2), pave11(Ncc,2,2,2)
	ComplexType pave12(Ncc,3,2,2,2), pave13(4,4)
	ComplexType pave14(Ncc,4,4,4), pave15, pave16, pave17
	ComplexType pave18, pave19, pave20, pave21, pave22, pave23
	ComplexType pave24, pave25, pave26, pave27, pave28, pave29
	ComplexType pave30, pave31, pave32, pave33, pave34, pave35
	ComplexType pave36, pave37, pave38, pave39(Ncc), pave40(Ncc)
	ComplexType pave41(Ncc), pave42(Ncc), pave43(Ncc)
	ComplexType pave44(Ncc), pave45(Ncc), pave46(Ncc)
	ComplexType pave47(Ncc), pave48(Ncc), pave49(Ncc)
	ComplexType pave50(Ncc), pave51(Ncc), pave52(Ncc)
	ComplexType pave53(Ncc), pave54(Ncc), pave55(Ncc)
	ComplexType pave56(Ncc), pave57(Ncc), pave58(Ncc)
	ComplexType pave59(Ncc), pave60(Ncc), pave61(Ncc)
	ComplexType pave62(Ncc), pave63(Ncc), pave64(Ncc)
	ComplexType pave65(Ncc), pave66(Ncc), pave67(Ncc)
	ComplexType pave68(Ncc), pave69(Ncc), pave70(Ncc)
	ComplexType pave71(Ncc), pave72(Ncc), pave73(Ncc)
	ComplexType pave74(Ncc), pave75(Ncc), pave76(Ncc)
	ComplexType pave77(Ncc), pave78(Ncc), pave79(Ncc)
	ComplexType pave80(Ncc), pave81(Ncc), pave82(Ncc)
	ComplexType pave83(Ncc), pave84(Ncc), pave85(Ncc)
	ComplexType pave86(Ncc), pave87(Ncc), pave88(Ncc)
	ComplexType pave89(Ncc), pave90(Ncc), pave91(Ncc)
	ComplexType pave92(Ncc), pave93(Ncc), pave94(Ncc)
	ComplexType pave95(Ncc), pave96(Ncc), pave97(Ncc)
	ComplexType pave98(Ncc), pave99(Ncc), pave100(Ncc)
	ComplexType pave101(Ncc), pave102(Ncc), pave103(Ncc)
	ComplexType pave104(Ncc), pave105(Ncc), pave106(Ncc)
	ComplexType pave107(Ncc), pave108(Ncc), pave109(Ncc)
	ComplexType pave110(Ncc), pave111(Ncc), pave112(Ncc)
	ComplexType pave113(Ncc), pave114(Ncc), pave115(Ncc)
	ComplexType pave116(Ncc), pave117(Ncc), pave118(Ncc)
	ComplexType pave119(Ncc), pave120(Ncc), pave121(Ncc)
	ComplexType pave122(Ncc), pave123(Ncc), pave124(Ncc)
	ComplexType pave125(Ncc), pave126(Ncc), pave127(Ncc)
	ComplexType pave128(Ncc), pave129(Ncc), pave130(Ncc)
	ComplexType pave131(Ncc), pave132(Ncc), pave133(Ncc)
	ComplexType pave134(Ncc), pave135(Ncc), pave136(Ncc)
	ComplexType pave137(Ncc), pave138(Ncc), pave139(Ncc)
	ComplexType pave140(Ncc), pave141(Ncc), pave142(Ncc)
	ComplexType pave143(Ncc), pave144(Ncc), pave145(Ncc)
	ComplexType pave146(Ncc), pave147(Ncc), pave148(Ncc)
	ComplexType pave149(Ncc), pave150, pave151, pave152
	ComplexType pave153(3), pave154(3), pave155(3), pave156(3)
	ComplexType pave157(Ncc,3), pave158(3), pave159(3)
	ComplexType pave160(3), pave161(3), pave162(Ncc,3)
	ComplexType pave163(Ncc,3), pave164(3), pave165(3)
	ComplexType pave166(3,2,2), pave167(3,2,2), pave168(3,2,2)
	ComplexType pave169(3,2,2), pave170(3,2,2)
	ComplexType pave171(Ncc,3,2,2,2), pave172(Ncc,3,2,2,2)
	ComplexType pave173, pave174(Ncc), pave175, pave176(Ncc)
	ComplexType pave177(Ncc), pave178(Ncc), pave179(Ncc)
	ComplexType pave180(Ncc), pave181(Ncc), pave182(Ncc)
	ComplexType pave183(Ncc), pave184(Ncc), pave185(3)
	ComplexType pave186(Ncc,3), pave187(3), pave188(3)
	ComplexType pave189(3), pave190(3), pave191(3), pave192(3)
	ComplexType pave193(3,2,2), pave194(3,2,2), pave195(3,2,2)
	ComplexType pave196, pave197, pave198, pave199, pave200(Ncc)
	ComplexType pave201, pave202, pave203, pave204, pave205(Ncc)
	ComplexType pave206(Ncc), pave207(3,2,2), pave208(3,2,2)
	ComplexType pave209(3,2,2), pave210(3,2,2), pave211, pave212
	ComplexType pave213, pave214, pave215, pave216, pave217
	ComplexType pave218, pave219, pave220, pave221, pave222
	ComplexType pave223, pave224
	common /hhh_varXs/ Sub11, Sub1, Sub2, Sub5, Sub3, Sub6, Sub4
	common /hhh_varXs/ Sub7, Sub9, Sub8, Sub10, Sub12, Opt1
	common /hhh_varXs/ Sub645, Sub416, Sub741, Sub447, Sub449
	common /hhh_varXs/ Sub479, Sub643, Sub493, Sub485, Sub311
	common /hhh_varXs/ Sub451, Sub453, Sub565, Sub313, Sub316
	common /hhh_varXs/ Sub318, Sub556, Sub752, Sub749, Sub558
	common /hhh_varXs/ Sub718, Sub454, Sub452, Sub550, Sub202
	common /hhh_varXs/ Sub264, Sub214, Sub209, Sub211, Sub216
	common /hhh_varXs/ Sub206, Sub210, Sub212, Sub215, Sub217
	common /hhh_varXs/ Sub262, Sub234, Sub230, Sub232, Sub236
	common /hhh_varXs/ Sub229, Sub228, Sub231, Sub233, Sub235
	common /hhh_varXs/ Sub237, Sub756, Sub761, Sub753, Sub762
	common /hhh_varXs/ Sub755, Sub750, Sub332, Sub487, Sub483
	common /hhh_varXs/ Sub365, Sub368, Sub366, Sub369, Sub581
	common /hhh_varXs/ Sub582, Sub619, Sub342, Sub349, Sub354
	common /hhh_varXs/ Sub357, Sub361, Sub399, Sub374, Sub398
	common /hhh_varXs/ Sub594, Sub593, Sub382, Sub384, Sub383
	common /hhh_varXs/ Sub386, Sub392, Sub397, Sub707, Sub405
	common /hhh_varXs/ Sub456, Sub457, Sub629, Sub631, Sub625
	common /hhh_varXs/ Sub627, Sub720, Sub424, Sub429, Sub433
	common /hhh_varXs/ Sub435, Sub439, Sub448, Sub450, Sub460
	common /hhh_varXs/ Sub461, Sub634, Sub636, Sub471, Sub510
	common /hhh_varXs/ Sub498, Sub478, Sub486, Sub488, Sub496
	common /hhh_varXs/ Sub501, Sub641, Sub639, Sub521, Sub524
	common /hhh_varXs/ Sub528, Sub531, Sub534, Sub537, Sub548
	common /hhh_varXs/ Sub549, Sub551, Sub554, Sub557, Sub559
	common /hhh_varXs/ Sub561, Sub564, Sub566, Sub568, Sub571
	common /hhh_varXs/ Sub578, Sub584, Sub592, Sub320, Sub618
	common /hhh_varXs/ Sub624, Sub626, Sub628, Sub630, Sub632
	common /hhh_varXs/ Sub635, Sub637, Sub640, Sub642, Sub661
	common /hhh_varXs/ Sub664, Sub665, Sub675, Sub679, Sub686
	common /hhh_varXs/ Sub695, Sub698, Sub660, Sub704, Sub708
	common /hhh_varXs/ Sub733, Sub735, Sub751, Sub754, Sub764
	common /hhh_varXs/ Sub767, Sub323, Sub358, Sub24, Sub191
	common /hhh_varXs/ Sub267, Sub269, Sub268, Sub745, Sub363
	common /hhh_varXs/ Sub739, Sub768, Sub256, Sub257, Sub258
	common /hhh_varXs/ Sub413, Sub612, Sub611, Sub759, Sub359
	common /hhh_varXs/ Sub757, Sub758, Sub360, Sub355, Sub356
	common /hhh_varXs/ Sub430, Sub570, Sub608, Sub668, Sub596
	common /hhh_varXs/ Sub351, Sub747, Sub763, Sub746, Sub744
	common /hhh_varXs/ Sub511, Sub504, Sub544, Sub529, Sub431
	common /hhh_varXs/ Sub595, Sub567, Sub535, Sub673, Sub522
	common /hhh_varXs/ Sub462, Sub555, Sub445, Sub469, Sub560
	common /hhh_varXs/ Sub468, Sub465, Sub552, Sub467, Sub523
	common /hhh_varXs/ Sub532, Sub458, Sub477, Sub421, Sub546
	common /hhh_varXs/ Sub547, Sub638, Sub683, Sub530, Sub432
	common /hhh_varXs/ Sub676, Sub583, Sub667, Sub545, Sub633
	common /hhh_varXs/ Sub694, Sub540, Sub492, Sub481, Sub396
	common /hhh_varXs/ Sub600, Sub506, Sub495, Sub586, Sub601
	common /hhh_varXs/ Sub684, Sub574, Sub434, Sub677, Sub516
	common /hhh_varXs/ Sub644, Sub587, Sub512, Sub576, Sub700
	common /hhh_varXs/ Sub562, Sub403, Sub517, Sub541, Sub602
	common /hhh_varXs/ Sub525, Sub588, Sub423, Sub599, Sub575
	common /hhh_varXs/ Sub436, Sub515, Sub671, Sub585, Sub426
	common /hhh_varXs/ Sub513, Sub503, Sub692, Sub577, Sub401
	common /hhh_varXs/ Sub569, Sub563, Sub553, Sub404, Sub508
	common /hhh_varXs/ Sub388, Sub500, Sub428, Sub690, Sub518
	common /hhh_varXs/ Sub394, Sub693, Sub542, Sub507, Sub395
	common /hhh_varXs/ Sub603, Sub400, Sub703, Sub526, Sub505
	common /hhh_varXs/ Sub494, Sub367, Sub589, Sub370, Sub422
	common /hhh_varXs/ Sub604, Sub669, Sub685, Sub580, Sub437
	common /hhh_varXs/ Sub678, Sub519, Sub509, Sub497, Sub670
	common /hhh_varXs/ Sub590, Sub425, Sub197, Sub242, Sub327
	common /hhh_varXs/ Sub337, Sub740, Sub218, Sub334, Sub346
	common /hhh_varXs/ Sub389, Sub340, Sub473, Sub647, Sub390
	common /hhh_varXs/ Sub391, Sub743, Sub607, Sub606, Sub742
	common /hhh_varXs/ Sub748, Sub766, Sub224, Sub221, Sub205
	common /hhh_varXs/ Sub198, Sub199, Sub243, Sub325, Sub336
	common /hhh_varXs/ Sub219, Sub333, Sub344, Sub379, Sub339
	common /hhh_varXs/ Sub472, Sub646, Sub244, Sub440, Sub380
	common /hhh_varXs/ Sub381, Sub329, Sub335, Sub338, Sub341
	common /hhh_varXs/ Sub348, Sub597, Sub609, Sub225, Sub222
	common /hhh_varXs/ Sub200, Sub201, Sub330, Sub331, Sub687
	common /hhh_varXs/ Sub441, Sub245, Sub717, Sub406, Sub443
	common /hhh_varXs/ Sub470, Sub674, Sub682, Sub689, Sub203
	common /hhh_varXs/ Sub247, Sub466, Sub409, Sub220, Sub444
	common /hhh_varXs/ Sub446, Sub474, Sub459, Sub417, Sub70
	common /hhh_varXs/ Sub248, Sub711, Sub250, Sub714, Sub315
	common /hhh_varXs/ Sub475, Sub476, Sub223, Sub226, Sub204
	common /hhh_varXs/ Sub207, Sub352, Sub353, Sub724, Sub249
	common /hhh_varXs/ Sub722, Sub732, Sub28, Sub29, Sub728
	common /hhh_varXs/ Sub251, Sub723, Sub734, Sub817, Sub252
	common /hhh_varXs/ Sub255, Sub246, Sub65, Sub52, Sub64
	common /hhh_varXs/ Sub50, Sub59, Sub57, Sub180, Sub179
	common /hhh_varXs/ Sub176, Sub105, Sub175, Sub103, Sub98
	common /hhh_varXs/ Sub96, Sub111, Sub110, Sub145, Sub132
	common /hhh_varXs/ Sub144, Sub130, Sub139, Sub137, Sub184
	common /hhh_varXs/ Sub183, Sub56, Sub60, Sub40, Sub41
	common /hhh_varXs/ Sub189, Sub34, Sub35, Sub49, Sub53, Sub38
	common /hhh_varXs/ Sub37, Sub46, Sub45, Sub239, Sub95, Sub99
	common /hhh_varXs/ Sub91, Sub86, Sub87, Sub92, Sub192, Sub83
	common /hhh_varXs/ Sub84, Sub106, Sub102, Sub81, Sub80
	common /hhh_varXs/ Sub227, Sub136, Sub140, Sub120, Sub121
	common /hhh_varXs/ Sub194, Sub114, Sub115, Sub129, Sub133
	common /hhh_varXs/ Sub118, Sub117, Sub126, Sub125, Sub259
	common /hhh_varXs/ Sub240, Sub196, Sub208, Sub213, Sub253
	common /hhh_varXs/ Sub254, Sub260, Sub261, Sub271, Sub272
	common /hhh_varXs/ Sub266, Sub958, Sub275, Sub273, Sub278
	common /hhh_varXs/ Sub281, Sub290, Sub287, Sub293, Sub296
	common /hhh_varXs/ Sub299, Sub285, Sub274, Sub276, Sub279
	common /hhh_varXs/ Sub282, Sub291, Sub286, Sub294, Sub297
	common /hhh_varXs/ Sub300, Sub288, Sub926, Sub927, Sub929
	common /hhh_varXs/ Sub931, Sub934, Sub935, Sub937, Sub939
	common /hhh_varXs/ Sub32, Sub23, Sub30, Sub27, Sub14, Sub16
	common /hhh_varXs/ Sub15, Sub789, Sub791, Sub790, Sub18
	common /hhh_varXs/ Sub777, Sub779, Sub778, Sub13, Sub19
	common /hhh_varXs/ Sub21, Sub20, Sub793, Sub795, Sub794
	common /hhh_varXs/ Sub801, Sub803, Sub802, Sub769, Sub771
	common /hhh_varXs/ Sub770, Sub781, Sub783, Sub782, Sub773
	common /hhh_varXs/ Sub775, Sub774, Sub785, Sub787, Sub786
	common /hhh_varXs/ Sub797, Sub799, Sub798, Sub805, Sub807
	common /hhh_varXs/ Sub806, Sub823, Sub824, Sub826, Sub827
	common /hhh_varXs/ Sub860, Sub861, Sub857, Sub858, Sub891
	common /hhh_varXs/ Sub892, Sub894, Sub895, Sub190, Sub193
	common /hhh_varXs/ Sub195, Sub51, Sub54, Sub58, Sub61
	common /hhh_varXs/ Sub104, Sub107, Sub97, Sub100, Sub131
	common /hhh_varXs/ Sub134, Sub138, Sub141, Sub832, Sub833
	common /hhh_varXs/ Sub835, Sub836, Sub869, Sub870, Sub866
	common /hhh_varXs/ Sub867, Sub900, Sub901, Sub903, Sub904
	common /hhh_varXs/ Sub277, Sub280, Sub283, Sub289, Sub292
	common /hhh_varXs/ Sub295, Sub298, Sub301, Sub309, Sub303
	common /hhh_varXs/ Sub307, Sub306, Sub305, Sub304, Sub942
	common /hhh_varXs/ Sub943, Sub944, Sub936, Sub938, Sub940
	common /hhh_varXs/ Sub928, Sub930, Sub932, Sub946, Sub947
	common /hhh_varXs/ Sub948, Sub813, Sub819, Sub815, Sub814
	common /hhh_varXs/ Sub816, Sub820, Sub821, Sub822, Sub174
	common /hhh_varXs/ Sub178, Sub182, Sub186, Sub173, Sub187
	common /hhh_varXs/ Sub169, Sub55, Sub62, Sub66, Sub101
	common /hhh_varXs/ Sub108, Sub112, Sub135, Sub142, Sub146
	common /hhh_varXs/ Sub841, Sub842, Sub181, Sub844, Sub171
	common /hhh_varXs/ Sub36, Sub39, Sub42, Sub47, Sub875
	common /hhh_varXs/ Sub876, Sub878, Sub177, Sub170, Sub82
	common /hhh_varXs/ Sub85, Sub88, Sub93, Sub909, Sub910
	common /hhh_varXs/ Sub912, Sub185, Sub172, Sub116, Sub119
	common /hhh_varXs/ Sub122, Sub127, Sub158, Sub163, Sub74
	common /hhh_varXs/ Sub843, Sub877, Sub911, Sub159, Sub164
	common /hhh_varXs/ Sub75, Sub845, Sub879, Sub913, Sub123
	common /hhh_varXs/ Sub43, Sub89, Sub148, Sub153, Sub68
	common /hhh_varXs/ Sub124, Sub44, Sub90, Sub149, Sub154
	common /hhh_varXs/ Sub69, Sub128, Sub48, Sub94, Sub155
	common /hhh_varXs/ Sub71, Sub150, Sub165, Sub76, Sub160
	common /hhh_varXs/ Sub109, Sub143, Sub63, Sub156, Sub72
	common /hhh_varXs/ Sub151, Sub166, Sub77, Sub161, Sub113
	common /hhh_varXs/ Sub147, Sub67, Sub157, Sub73, Sub152
	common /hhh_varXs/ Sub167, Sub78, Sub162, Sub846, Sub847
	common /hhh_varXs/ Sub849, Sub880, Sub881, Sub883, Sub914
	common /hhh_varXs/ Sub915, Sub917, Sub825, Sub828, Sub830
	common /hhh_varXs/ Sub859, Sub862, Sub864, Sub893, Sub896
	common /hhh_varXs/ Sub898, Sub829, Sub848, Sub863, Sub882
	common /hhh_varXs/ Sub897, Sub916, Sub831, Sub850, Sub865
	common /hhh_varXs/ Sub884, Sub899, Sub918, Sub834, Sub837
	common /hhh_varXs/ Sub839, Sub868, Sub871, Sub873, Sub902
	common /hhh_varXs/ Sub905, Sub907, Sub851, Sub852, Sub854
	common /hhh_varXs/ Sub885, Sub886, Sub888, Sub919, Sub920
	common /hhh_varXs/ Sub922, Sub838, Sub853, Sub872, Sub887
	common /hhh_varXs/ Sub906, Sub921, Sub840, Sub855, Sub874
	common /hhh_varXs/ Sub889, Sub908, Sub923, Sub952, Sub959
	common /hhh_varXs/ Sub950, Sub951, Sub956, Sub960, Sub954
	common /hhh_varXs/ Sub955, Sub957, Sub961, Sub962, Sub963
	common /hhh_varXs/ Sub856, Sub890, Sub924, Sub925, Sub324
	common /hhh_varXs/ Sub343, Sub350, Sub371, Sub385, Sub407
	common /hhh_varXs/ Sub463, Sub484, Sub514, Sub538, Sub539
	common /hhh_varXs/ Sub543, Sub573, Sub579, Sub652, Sub672
	common /hhh_varXs/ Sub699, Sub411, Sub412, Sub616, Sub765
	common /hhh_varXs/ Sub438, Sub415, Sub502, Sub489, Sub697
	common /hhh_varXs/ Sub393, Sub696, Sub536, Sub533, Sub691
	common /hhh_varXs/ Sub410, Sub427, Sub328, Sub347, Sub377
	common /hhh_varXs/ Sub375, Sub620, Sub326, Sub345, Sub373
	common /hhh_varXs/ Sub376, Sub378, Sub598, Sub622, Sub706
	common /hhh_varXs/ Sub419, Sub442, Sub709, Sub464, Sub617
	common /hhh_varXs/ Sub705, Sub727, Sub725, Sub731, Sub729
	common /hhh_varXs/ Sub490, Sub491, Sub362, Sub658, Sub710
	common /hhh_varXs/ Sub712, Sub659, Sub662, Sub713, Sub715
	common /hhh_varXs/ Sub663, Sub238, Sub265, Sub270, Sub31
	common /hhh_varXs/ Sub33, Sub26, Sub25, Sub17, Sub22, Sub780
	common /hhh_varXs/ Sub792, Sub772, Sub784, Sub796, Sub804
	common /hhh_varXs/ Sub776, Sub788, Sub800, Sub808, Sub308
	common /hhh_varXs/ Sub310, Sub284, Sub302, Sub941, Sub945
	common /hhh_varXs/ Sub933, Sub949, Sub812, Sub188, Sub79
	common /hhh_varXs/ Sub953, Sub480, Sub482, Sub408, Sub520
	common /hhh_varXs/ Sub572, Sub621, Sub719, Sub649, Sub648
	common /hhh_varXs/ Sub760, Sub702, Sub527, Sub499, Sub701
	common /hhh_varXs/ Sub364, Sub387, Sub610, Sub688, Sub681
	common /hhh_varXs/ Sub721, Sub653, Sub654, Sub811, Sub818
	common /hhh_varXs/ Sub809, Sub810, Sub591, Sub605, Sub623
	common /hhh_varXs/ Sub312, Sub314, Sub317, Sub319, Sub716
	common /hhh_varXs/ Sub414, Sub657, Sub656, Sub614, Sub615
	common /hhh_varXs/ Sub737, Sub321, Sub322, Sub455, Sub650
	common /hhh_varXs/ Sub651, Sub168, Sub241, Sub736, Sub666
	common /hhh_varXs/ Sub738, pave1, pave2, pave3, pave4, pave5
	common /hhh_varXs/ pave6, pave7, pave8, pave9, pave10
	common /hhh_varXs/ pave11, pave12, pave13, pave14, pave15
	common /hhh_varXs/ pave16, pave17, pave18, pave19, pave20
	common /hhh_varXs/ pave21, pave22, pave23, pave24, pave25
	common /hhh_varXs/ pave26, pave27, pave28, pave29, pave30
	common /hhh_varXs/ pave31, pave32, pave33, pave34, pave35
	common /hhh_varXs/ pave36, pave37, pave38, pave39, pave40
	common /hhh_varXs/ pave41, pave42, pave43, pave44, pave45
	common /hhh_varXs/ pave46, pave47, pave48, pave49, pave50
	common /hhh_varXs/ pave51, pave52, pave53, pave54, pave55
	common /hhh_varXs/ pave56, pave57, pave58, pave59, pave60
	common /hhh_varXs/ pave61, pave62, pave63, pave64, pave65
	common /hhh_varXs/ pave66, pave67, pave68, pave69, pave70
	common /hhh_varXs/ pave71, pave72, pave73, pave74, pave75
	common /hhh_varXs/ pave76, pave77, pave78, pave79, pave80
	common /hhh_varXs/ pave81, pave82, pave83, pave84, pave85
	common /hhh_varXs/ pave86, pave87, pave88, pave89, pave90
	common /hhh_varXs/ pave91, pave92, pave93, pave94, pave95
	common /hhh_varXs/ pave96, pave97, pave98, pave99, pave100
	common /hhh_varXs/ pave101, pave102, pave103, pave104
	common /hhh_varXs/ pave105, pave106, pave107, pave108
	common /hhh_varXs/ pave109, pave110, pave111, pave112
	common /hhh_varXs/ pave113, pave114, pave115, pave116
	common /hhh_varXs/ pave117, pave118, pave119, pave120
	common /hhh_varXs/ pave121, pave122, pave123, pave124
	common /hhh_varXs/ pave125, pave126, pave127, pave128
	common /hhh_varXs/ pave129, pave130, pave131, pave132
	common /hhh_varXs/ pave133, pave134, pave135, pave136
	common /hhh_varXs/ pave137, pave138, pave139, pave140
	common /hhh_varXs/ pave141, pave142, pave143, pave144
	common /hhh_varXs/ pave145, pave146, pave147, pave148
	common /hhh_varXs/ pave149, pave150, pave151, pave152
	common /hhh_varXs/ pave153, pave154, pave155, pave156
	common /hhh_varXs/ pave157, pave158, pave159, pave160
	common /hhh_varXs/ pave161, pave162, pave163, pave164
	common /hhh_varXs/ pave165, pave166, pave167, pave168
	common /hhh_varXs/ pave169, pave170, pave171, pave172
	common /hhh_varXs/ pave173, pave174, pave175, pave176
	common /hhh_varXs/ pave177, pave178, pave179, pave180
	common /hhh_varXs/ pave181, pave182, pave183, pave184
	common /hhh_varXs/ pave185, pave186, pave187, pave188
	common /hhh_varXs/ pave189, pave190, pave191, pave192
	common /hhh_varXs/ pave193, pave194, pave195, pave196
	common /hhh_varXs/ pave197, pave198, pave199, pave200
	common /hhh_varXs/ pave201, pave202, pave203, pave204
	common /hhh_varXs/ pave205, pave206, pave207, pave208
	common /hhh_varXs/ pave209, pave210, pave211, pave212
	common /hhh_varXs/ pave213, pave214, pave215, pave216
	common /hhh_varXs/ pave217, pave218, pave219, pave220
	common /hhh_varXs/ pave221, pave222, pave223, pave224

	integer seq(2), Hel(3)
	common /hhh_helind/ seq, Hel

	integer Cha4, Cha5, Cha6, Gen4, Neu4, Neu5, Neu6, Sfe4, Sfe5
	integer Sfe6
	common /hhh_indices/ Cha4, Cha5, Cha6, Gen4, Neu4, Neu5, Neu6
	common /hhh_indices/ Sfe4, Sfe5, Sfe6

	ComplexType Ctree(1), Cloop(1)
	common /hhh_formfactors/ Ctree, Cloop

#endif
