#if 0
* hhh-vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Feb-2015 17:20
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hhh-renconst.h"

	ComplexType Sub6, Sub11, Sub2, Sub4, Sub3, Sub5, Sub1, Sub7
	ComplexType Sub9, Sub8, Sub10
	ComplexType Opt1, Sub647, Sub418, Sub743, Sub449, Sub451
	ComplexType Sub481, Sub645, Sub495, Sub487, Sub313, Sub453
	ComplexType Sub455, Sub567, Sub315, Sub318, Sub320, Sub558
	ComplexType Sub754, Sub751, Sub560, Sub720, Sub456, Sub454
	ComplexType Sub552, Sub213, Sub265, Sub225, Sub220, Sub222
	ComplexType Sub227, Sub217, Sub221, Sub223, Sub226, Sub228
	ComplexType Sub235, Sub263, Sub245, Sub241, Sub243, Sub247
	ComplexType Sub239, Sub242, Sub244, Sub246, Sub248, Sub758
	ComplexType Sub763, Sub755, Sub764, Sub757, Sub752, Sub334
	ComplexType Sub489, Sub485, Sub367, Sub370, Sub368, Sub371
	ComplexType Sub583, Sub584, Sub621, Sub344, Sub351, Sub356
	ComplexType Sub359, Sub363, Sub401, Sub376, Sub400, Sub596
	ComplexType Sub595, Sub384, Sub386, Sub385, Sub388, Sub394
	ComplexType Sub399, Sub709, Sub407, Sub458, Sub459, Sub631
	ComplexType Sub633, Sub627, Sub629, Sub722, Sub426, Sub431
	ComplexType Sub435, Sub437, Sub441, Sub450, Sub452, Sub462
	ComplexType Sub463, Sub636, Sub638, Sub473, Sub512, Sub500
	ComplexType Sub480, Sub488, Sub490, Sub498, Sub503, Sub643
	ComplexType Sub322, Sub641, Sub523, Sub526, Sub530, Sub533
	ComplexType Sub536, Sub539, Sub550, Sub551, Sub553, Sub556
	ComplexType Sub559, Sub561, Sub563, Sub566, Sub568, Sub570
	ComplexType Sub573, Sub580, Sub586, Sub594, Sub620, Sub626
	ComplexType Sub628, Sub630, Sub632, Sub634, Sub637, Sub639
	ComplexType Sub642, Sub644, Sub663, Sub666, Sub667, Sub677
	ComplexType Sub681, Sub688, Sub662, Sub697, Sub700, Sub706
	ComplexType Sub710, Sub735, Sub737, Sub753, Sub756, Sub766
	ComplexType Sub769, Sub325, Sub360, Sub23, Sub190, Sub268
	ComplexType Sub270, Sub269, Sub747, Sub365, Sub741, Sub770
	ComplexType Sub257, Sub258, Sub259, Sub415, Sub614, Sub613
	ComplexType Sub761, Sub361, Sub759, Sub760, Sub362, Sub357
	ComplexType Sub358, Sub432, Sub572, Sub610, Sub670, Sub598
	ComplexType Sub353, Sub749, Sub765, Sub748, Sub746, Sub513
	ComplexType Sub506, Sub546, Sub531, Sub433, Sub597, Sub569
	ComplexType Sub537, Sub675, Sub524, Sub464, Sub557, Sub447
	ComplexType Sub471, Sub562, Sub470, Sub467, Sub554, Sub469
	ComplexType Sub525, Sub534, Sub460, Sub479, Sub423, Sub548
	ComplexType Sub549, Sub640, Sub685, Sub532, Sub434, Sub678
	ComplexType Sub585, Sub669, Sub547, Sub635, Sub696, Sub542
	ComplexType Sub494, Sub483, Sub398, Sub602, Sub508, Sub497
	ComplexType Sub588, Sub603, Sub686, Sub576, Sub436, Sub679
	ComplexType Sub518, Sub646, Sub589, Sub514, Sub578, Sub702
	ComplexType Sub564, Sub405, Sub519, Sub543, Sub604, Sub527
	ComplexType Sub590, Sub425, Sub601, Sub577, Sub438, Sub517
	ComplexType Sub673, Sub587, Sub428, Sub515, Sub505, Sub694
	ComplexType Sub579, Sub403, Sub571, Sub565, Sub555, Sub406
	ComplexType Sub510, Sub390, Sub502, Sub430, Sub692, Sub520
	ComplexType Sub396, Sub695, Sub544, Sub509, Sub397, Sub605
	ComplexType Sub402, Sub705, Sub528, Sub507, Sub496, Sub369
	ComplexType Sub591, Sub372, Sub424, Sub606, Sub671, Sub687
	ComplexType Sub582, Sub439, Sub680, Sub521, Sub511, Sub499
	ComplexType Sub672, Sub592, Sub427, Sub208, Sub195, Sub329
	ComplexType Sub339, Sub742, Sub230, Sub336, Sub348, Sub391
	ComplexType Sub342, Sub475, Sub649, Sub392, Sub393, Sub745
	ComplexType Sub609, Sub608, Sub744, Sub750, Sub768, Sub238
	ComplexType Sub231, Sub216, Sub209, Sub210, Sub196, Sub327
	ComplexType Sub338, Sub232, Sub335, Sub346, Sub381, Sub341
	ComplexType Sub474, Sub648, Sub197, Sub442, Sub382, Sub383
	ComplexType Sub331, Sub337, Sub340, Sub343, Sub350, Sub599
	ComplexType Sub611, Sub233, Sub234, Sub211, Sub212, Sub332
	ComplexType Sub333, Sub689, Sub443, Sub198, Sub719, Sub408
	ComplexType Sub445, Sub472, Sub676, Sub684, Sub691, Sub214
	ComplexType Sub200, Sub468, Sub411, Sub236, Sub446, Sub448
	ComplexType Sub476, Sub461, Sub419, Sub69, Sub201, Sub713
	ComplexType Sub203, Sub716, Sub317, Sub477, Sub478, Sub237
	ComplexType Sub240, Sub215, Sub218, Sub354, Sub355, Sub726
	ComplexType Sub202, Sub724, Sub734, Sub27, Sub28, Sub730
	ComplexType Sub204, Sub725, Sub736, Sub818(2), Sub205(3)
	ComplexType Sub256(3), Sub199(3), Sub249(3), Sub64(3)
	ComplexType Sub51(3), Sub63(3), Sub49(3), Sub58(3), Sub56(3)
	ComplexType Sub179(3), Sub178(3), Sub175(3), Sub104(3)
	ComplexType Sub174(3), Sub102(3), Sub97(3), Sub95(3)
	ComplexType Sub110(3), Sub109(3), Sub144(3), Sub131(3)
	ComplexType Sub143(3), Sub129(3), Sub138(3), Sub136(3)
	ComplexType Sub183(3), Sub182(3), Sub55(3), Sub59(3)
	ComplexType Sub39(3), Sub40(3), Sub188(3), Sub33(3)
	ComplexType Sub34(3), Sub48(3), Sub52(3), Sub37(3), Sub36(3)
	ComplexType Sub45(3), Sub44(3), Sub229(3), Sub94(3)
	ComplexType Sub98(3), Sub90(3), Sub85(3), Sub86(3), Sub91(3)
	ComplexType Sub191(3), Sub82(3), Sub83(3), Sub105(3)
	ComplexType Sub101(3), Sub80(3), Sub79(3), Sub251(3)
	ComplexType Sub135(3), Sub139(3), Sub119(3), Sub120(3)
	ComplexType Sub193(3), Sub113(3), Sub114(3), Sub128(3)
	ComplexType Sub132(3), Sub117(3), Sub116(3), Sub125(3)
	ComplexType Sub124(3), Sub264(3), Sub260(3), Sub271(3)
	ComplexType Sub252(3), Sub207(3), Sub219(3), Sub224(3)
	ComplexType Sub206(3), Sub250(3), Sub253(3), Sub255(3)
	ComplexType Sub261(3), Sub262(3), Sub266(3), Sub272(3)
	ComplexType Sub273(3), Sub274(3), Sub267(3), Sub959(4)
	ComplexType Sub277(4), Sub275(4), Sub280(4), Sub283(4)
	ComplexType Sub292(4), Sub289(4), Sub295(4), Sub298(4)
	ComplexType Sub301(4), Sub287(4), Sub276(4), Sub278(4)
	ComplexType Sub281(4), Sub284(4), Sub293(4), Sub288(4)
	ComplexType Sub296(4), Sub299(4), Sub302(4), Sub290(4)
	ComplexType Sub927(4), Sub928(4), Sub930(4), Sub932(4)
	ComplexType Sub935(4), Sub936(4), Sub938(4), Sub940(4)
	ComplexType Sub31(2,2), Sub22(2,2), Sub29(2,2), Sub26(2,2)
	ComplexType Sub13(2,2), Sub15(2,2), Sub14(2,2), Sub791(2,2)
	ComplexType Sub793(2,2), Sub792(2,2), Sub17(2,2)
	ComplexType Sub779(2,2), Sub781(2,2), Sub780(2,2)
	ComplexType Sub12(2,2), Sub18(2,2), Sub20(2,2), Sub19(2,2)
	ComplexType Sub795(2,2), Sub797(2,2), Sub796(2,2)
	ComplexType Sub803(2,2), Sub805(2,2), Sub804(2,2)
	ComplexType Sub771(2,2), Sub773(2,2), Sub772(2,2)
	ComplexType Sub783(2,2), Sub785(2,2), Sub784(2,2)
	ComplexType Sub775(2,2), Sub777(2,2), Sub776(2,2)
	ComplexType Sub787(2,2), Sub789(2,2), Sub788(2,2)
	ComplexType Sub799(2,2), Sub801(2,2), Sub800(2,2)
	ComplexType Sub807(2,2), Sub809(2,2), Sub808(2,2)
	ComplexType Sub824(3,2), Sub825(3,2), Sub827(3,2)
	ComplexType Sub828(3,2), Sub861(3,2), Sub862(3,2)
	ComplexType Sub858(3,2), Sub859(3,2), Sub892(3,2)
	ComplexType Sub893(3,2), Sub895(3,2), Sub896(3,2)
	ComplexType Sub189(3,2), Sub192(3,2), Sub194(3,2)
	ComplexType Sub50(3,2), Sub53(3,2), Sub57(3,2), Sub60(3,2)
	ComplexType Sub103(3,2), Sub106(3,2), Sub96(3,2), Sub99(3,2)
	ComplexType Sub130(3,2), Sub133(3,2), Sub137(3,2)
	ComplexType Sub140(3,2), Sub833(3,2), Sub834(3,2)
	ComplexType Sub836(3,2), Sub837(3,2), Sub870(3,2)
	ComplexType Sub871(3,2), Sub867(3,2), Sub868(3,2)
	ComplexType Sub901(3,2), Sub902(3,2), Sub904(3,2)
	ComplexType Sub905(3,2), Sub279(4,4), Sub282(4,4)
	ComplexType Sub285(4,4), Sub291(4,4), Sub294(4,4)
	ComplexType Sub297(4,4), Sub300(4,4), Sub303(4,4)
	ComplexType Sub311(4,4), Sub305(4,4), Sub309(4,4)
	ComplexType Sub308(4,4), Sub307(4,4), Sub306(4,4)
	ComplexType Sub943(4,4), Sub944(4,4), Sub945(4,4)
	ComplexType Sub937(4,4), Sub939(4,4), Sub941(4,4)
	ComplexType Sub929(4,4), Sub931(4,4), Sub933(4,4)
	ComplexType Sub947(4,4), Sub948(4,4), Sub949(4,4)
	ComplexType Sub816(2,2,2), Sub820(2,2,2), Sub817(2,2,2)
	ComplexType Sub821(2,2,2), Sub822(2,2,2), Sub173(3,2,2)
	ComplexType Sub177(3,2,2), Sub181(3,2,2), Sub185(3,2,2)
	ComplexType Sub172(3,2,2), Sub186(3,2,2), Sub168(3,2,2)
	ComplexType Sub54(3,2,2), Sub61(3,2,2), Sub65(3,2,2)
	ComplexType Sub107(3,2,2), Sub100(3,2,2), Sub111(3,2,2)
	ComplexType Sub134(3,2,2), Sub141(3,2,2), Sub145(3,2,2)
	ComplexType Sub842(3,2,2), Sub843(3,2,2), Sub180(3,2,2)
	ComplexType Sub845(3,2,2), Sub170(3,2,2), Sub35(3,2,2)
	ComplexType Sub38(3,2,2), Sub41(3,2,2), Sub46(3,2,2)
	ComplexType Sub876(3,2,2), Sub877(3,2,2), Sub879(3,2,2)
	ComplexType Sub176(3,2,2), Sub169(3,2,2), Sub81(3,2,2)
	ComplexType Sub84(3,2,2), Sub87(3,2,2), Sub92(3,2,2)
	ComplexType Sub910(3,2,2), Sub911(3,2,2), Sub913(3,2,2)
	ComplexType Sub184(3,2,2), Sub171(3,2,2), Sub115(3,2,2)
	ComplexType Sub118(3,2,2), Sub121(3,2,2), Sub126(3,2,2)
	ComplexType Sub157(3,2,2), Sub162(3,2,2), Sub73(3,2,2)
	ComplexType Sub844(3,2,2), Sub878(3,2,2), Sub912(3,2,2)
	ComplexType Sub158(3,2,2), Sub163(3,2,2), Sub74(3,2,2)
	ComplexType Sub846(3,2,2), Sub880(3,2,2), Sub914(3,2,2)
	ComplexType Sub122(3,2,2), Sub42(3,2,2), Sub88(3,2,2)
	ComplexType Sub147(3,2,2), Sub152(3,2,2), Sub67(3,2,2)
	ComplexType Sub123(3,2,2), Sub43(3,2,2), Sub89(3,2,2)
	ComplexType Sub148(3,2,2), Sub153(3,2,2), Sub68(3,2,2)
	ComplexType Sub127(3,2,2), Sub47(3,2,2), Sub93(3,2,2)
	ComplexType Sub154(3,2,2), Sub70(3,2,2), Sub149(3,2,2)
	ComplexType Sub164(3,2,2), Sub75(3,2,2), Sub159(3,2,2)
	ComplexType Sub108(3,2,2), Sub142(3,2,2), Sub62(3,2,2)
	ComplexType Sub155(3,2,2), Sub71(3,2,2), Sub150(3,2,2)
	ComplexType Sub165(3,2,2), Sub76(3,2,2), Sub160(3,2,2)
	ComplexType Sub112(3,2,2), Sub146(3,2,2), Sub66(3,2,2)
	ComplexType Sub156(3,2,2), Sub72(3,2,2), Sub151(3,2,2)
	ComplexType Sub166(3,2,2), Sub77(3,2,2), Sub161(3,2,2)
	ComplexType Sub847(3,2,2), Sub848(3,2,2), Sub850(3,2,2)
	ComplexType Sub881(3,2,2), Sub882(3,2,2), Sub884(3,2,2)
	ComplexType Sub915(3,2,2), Sub916(3,2,2), Sub918(3,2,2)
	ComplexType Sub826(3,2,2), Sub829(3,2,2), Sub831(3,2,2)
	ComplexType Sub860(3,2,2), Sub863(3,2,2), Sub865(3,2,2)
	ComplexType Sub894(3,2,2), Sub897(3,2,2), Sub899(3,2,2)
	ComplexType Sub830(3,2,2), Sub849(3,2,2), Sub864(3,2,2)
	ComplexType Sub883(3,2,2), Sub898(3,2,2), Sub917(3,2,2)
	ComplexType Sub832(3,2,2), Sub851(3,2,2), Sub866(3,2,2)
	ComplexType Sub885(3,2,2), Sub900(3,2,2), Sub919(3,2,2)
	ComplexType Sub835(3,2,2), Sub838(3,2,2), Sub840(3,2,2)
	ComplexType Sub869(3,2,2), Sub872(3,2,2), Sub874(3,2,2)
	ComplexType Sub903(3,2,2), Sub906(3,2,2), Sub908(3,2,2)
	ComplexType Sub852(3,2,2), Sub853(3,2,2), Sub855(3,2,2)
	ComplexType Sub887(3,2,2), Sub886(3,2,2), Sub889(3,2,2)
	ComplexType Sub920(3,2,2), Sub921(3,2,2), Sub923(3,2,2)
	ComplexType Sub839(3,2,2), Sub854(3,2,2), Sub873(3,2,2)
	ComplexType Sub888(3,2,2), Sub907(3,2,2), Sub922(3,2,2)
	ComplexType Sub841(3,2,2), Sub856(3,2,2), Sub875(3,2,2)
	ComplexType Sub890(3,2,2), Sub909(3,2,2), Sub924(3,2,2)
	ComplexType Sub953(4,4,4), Sub960(4,4,4), Sub951(4,4,4)
	ComplexType Sub952(4,4,4), Sub957(4,4,4), Sub961(4,4,4)
	ComplexType Sub955(4,4,4), Sub956(4,4,4), Sub958(4,4,4)
	ComplexType Sub962(4,4,4), Sub963(4,4,4), Sub964(4,4,4)
	ComplexType Sub857(3,2,2,2), Sub891(3,2,2,2)
	ComplexType Sub925(3,2,2,2), Sub926(3,2,2,2), Sub326, Sub345
	ComplexType Sub352, Sub373, Sub387, Sub409, Sub465, Sub486
	ComplexType Sub516, Sub540, Sub541, Sub545, Sub575, Sub581
	ComplexType Sub654, Sub674, Sub701, Sub413, Sub414, Sub618
	ComplexType Sub767, Sub440, Sub417, Sub504, Sub491, Sub699
	ComplexType Sub395, Sub698, Sub538, Sub535, Sub693, Sub412
	ComplexType Sub429, Sub330, Sub349, Sub379, Sub377, Sub622
	ComplexType Sub328, Sub347, Sub375, Sub378, Sub380, Sub600
	ComplexType Sub624, Sub708, Sub421, Sub444, Sub711, Sub466
	ComplexType Sub619, Sub707, Sub729, Sub727, Sub733, Sub731
	ComplexType Sub492, Sub493, Sub364, Sub660, Sub712, Sub714
	ComplexType Sub661, Sub664, Sub715, Sub717, Sub665
	ComplexType Sub30(2,2), Sub32(2,2), Sub25(2,2), Sub24(2,2)
	ComplexType Sub16(2,2), Sub21(2,2), Sub782(2,2), Sub794(2,2)
	ComplexType Sub774(2,2), Sub786(2,2), Sub798(2,2)
	ComplexType Sub806(2,2), Sub778(2,2), Sub790(2,2)
	ComplexType Sub802(2,2), Sub810(2,2), Sub310(4,4)
	ComplexType Sub312(4,4), Sub286(4,4), Sub304(4,4)
	ComplexType Sub942(4,4), Sub946(4,4), Sub934(4,4)
	ComplexType Sub950(4,4), Sub814(2,2,2), Sub815(2,2,2)
	ComplexType Sub823(2,2,2), Sub187(3,2,2), Sub78(3,2,2)
	ComplexType Sub954(4,4,4), Sub482, Sub484, Sub410, Sub522
	ComplexType Sub574, Sub623, Sub721, Sub651, Sub650, Sub762
	ComplexType Sub704, Sub529, Sub501, Sub703, Sub366, Sub389
	ComplexType Sub612, Sub690, Sub683, Sub723, Sub655, Sub656
	ComplexType Sub813(2,2,2), Sub819(2,2,2), Sub811(2,2,2)
	ComplexType Sub812(2,2,2), Sub593, Sub607, Sub625, Sub314
	ComplexType Sub316, Sub319, Sub321, Sub718, Sub416, Sub659
	ComplexType Sub658, Sub616, Sub617, Sub739, Sub323, Sub324
	ComplexType Sub457, Sub652, Sub653, Sub254(3), Sub167(3,2,2)
	ComplexType Sub738, Sub668, Sub740, pave1(2), pave2(2,2)
	ComplexType pave3(2,2), pave4(3,2), pave5(3,2), pave6(3,2)
	ComplexType pave7(4), pave8(4,4), pave9(4,4), pave10(2,2)
	ComplexType pave11(Ncc,3,2,2,2), pave12(4,4)
	ComplexType pave13(Ncc,4,4,4), pave14, pave15, pave16
	ComplexType pave17, pave18, pave19, pave20, pave21, pave22
	ComplexType pave23, pave24, pave25, pave26, pave27, pave28
	ComplexType pave29, pave30, pave31, pave32, pave33, pave34
	ComplexType pave35, pave36, pave37, pave38(Ncc), pave39(Ncc)
	ComplexType pave40(Ncc), pave41(Ncc), pave42(Ncc)
	ComplexType pave43(Ncc), pave44(Ncc), pave45(Ncc)
	ComplexType pave46(Ncc), pave47(Ncc), pave48(Ncc)
	ComplexType pave49(Ncc), pave50(Ncc), pave51(Ncc)
	ComplexType pave52(Ncc), pave53(Ncc), pave54(Ncc)
	ComplexType pave55(Ncc), pave56(Ncc), pave57(Ncc)
	ComplexType pave58(Ncc), pave59(Ncc), pave60(Ncc)
	ComplexType pave61(Ncc), pave62(Ncc), pave63(Ncc)
	ComplexType pave64(Ncc), pave65(Ncc), pave66(Ncc)
	ComplexType pave67(Ncc), pave68(Ncc), pave69(Ncc)
	ComplexType pave70(Ncc), pave71(Ncc), pave72(Ncc)
	ComplexType pave73(Ncc), pave74(Ncc), pave75(Ncc)
	ComplexType pave76(Ncc), pave77(Ncc), pave78(Ncc)
	ComplexType pave79(Ncc), pave80(Ncc), pave81(Ncc)
	ComplexType pave82(Ncc), pave83(Ncc), pave84(Ncc)
	ComplexType pave85(Ncc), pave86(Ncc), pave87(Ncc)
	ComplexType pave88(Ncc), pave89(Ncc), pave90(Ncc)
	ComplexType pave91(Ncc), pave92(Ncc), pave93(Ncc)
	ComplexType pave94(Ncc), pave95(Ncc), pave96(Ncc)
	ComplexType pave97(Ncc), pave98(Ncc), pave99(Ncc)
	ComplexType pave100(Ncc), pave101(Ncc), pave102(Ncc)
	ComplexType pave103(Ncc), pave104(Ncc), pave105(Ncc)
	ComplexType pave106(Ncc), pave107(Ncc), pave108(Ncc)
	ComplexType pave109(Ncc), pave110(Ncc), pave111(Ncc)
	ComplexType pave112(Ncc), pave113(Ncc), pave114(Ncc)
	ComplexType pave115(Ncc), pave116(Ncc), pave117(Ncc)
	ComplexType pave118(Ncc), pave119(Ncc), pave120(Ncc)
	ComplexType pave121(Ncc), pave122(Ncc), pave123(Ncc)
	ComplexType pave124(Ncc), pave125(Ncc), pave126(Ncc)
	ComplexType pave127(Ncc), pave128(Ncc), pave129(Ncc)
	ComplexType pave130(Ncc), pave131(Ncc), pave132(Ncc)
	ComplexType pave133(Ncc), pave134(Ncc), pave135(Ncc)
	ComplexType pave136(Ncc), pave137(Ncc), pave138(Ncc)
	ComplexType pave139(Ncc), pave140(Ncc), pave141(Ncc)
	ComplexType pave142(Ncc), pave143(Ncc), pave144(Ncc)
	ComplexType pave145(Ncc), pave146(Ncc), pave147(Ncc)
	ComplexType pave148(Ncc), pave149, pave150, pave151
	ComplexType pave152(3), pave153(3), pave154(3), pave155(3)
	ComplexType pave156(Ncc,3), pave157(Ncc,3), pave158(3)
	ComplexType pave159(3), pave160(3), pave161(3), pave162(3)
	ComplexType pave163(3), pave164(3), pave165(3)
	ComplexType pave166(Ncc,3), pave167(Ncc,3), pave168(3)
	ComplexType pave169(3), pave170(3), pave171(3), pave172(3)
	ComplexType pave173(3,2,2), pave174(3,2,2), pave175(3,2,2)
	ComplexType pave176(3,2,2), pave177(3,2,2)
	ComplexType pave178(Ncc,3,2,2,2), pave179(Ncc,3,2,2,2)
	ComplexType pave180, pave181(Ncc), pave182, pave183(Ncc)
	ComplexType pave184(Ncc), pave185(Ncc), pave186(Ncc)
	ComplexType pave187(Ncc), pave188(Ncc), pave189(Ncc)
	ComplexType pave190(Ncc), pave191(Ncc), pave192(Ncc,2,2,2)
	ComplexType pave193(3,2,2), pave194(3,2,2), pave195(3,2,2)
	ComplexType pave196, pave197, pave198, pave199, pave200(Ncc)
	ComplexType pave201, pave202, pave203, pave204, pave205(Ncc)
	ComplexType pave206(Ncc), pave207(3,2,2), pave208(3,2,2)
	ComplexType pave209(3,2,2), pave210(3,2,2), pave211, pave212
	ComplexType pave213, pave214, pave215, pave216, pave217
	ComplexType pave218, pave219, pave220, pave221, pave222
	ComplexType pave223, pave224
	common /hhh_varXs/ Sub6, Sub11, Sub2, Sub4, Sub3, Sub5, Sub1
	common /hhh_varXs/ Sub7, Sub9, Sub8, Sub10, Opt1, Sub647
	common /hhh_varXs/ Sub418, Sub743, Sub449, Sub451, Sub481
	common /hhh_varXs/ Sub645, Sub495, Sub487, Sub313, Sub453
	common /hhh_varXs/ Sub455, Sub567, Sub315, Sub318, Sub320
	common /hhh_varXs/ Sub558, Sub754, Sub751, Sub560, Sub720
	common /hhh_varXs/ Sub456, Sub454, Sub552, Sub213, Sub265
	common /hhh_varXs/ Sub225, Sub220, Sub222, Sub227, Sub217
	common /hhh_varXs/ Sub221, Sub223, Sub226, Sub228, Sub235
	common /hhh_varXs/ Sub263, Sub245, Sub241, Sub243, Sub247
	common /hhh_varXs/ Sub239, Sub242, Sub244, Sub246, Sub248
	common /hhh_varXs/ Sub758, Sub763, Sub755, Sub764, Sub757
	common /hhh_varXs/ Sub752, Sub334, Sub489, Sub485, Sub367
	common /hhh_varXs/ Sub370, Sub368, Sub371, Sub583, Sub584
	common /hhh_varXs/ Sub621, Sub344, Sub351, Sub356, Sub359
	common /hhh_varXs/ Sub363, Sub401, Sub376, Sub400, Sub596
	common /hhh_varXs/ Sub595, Sub384, Sub386, Sub385, Sub388
	common /hhh_varXs/ Sub394, Sub399, Sub709, Sub407, Sub458
	common /hhh_varXs/ Sub459, Sub631, Sub633, Sub627, Sub629
	common /hhh_varXs/ Sub722, Sub426, Sub431, Sub435, Sub437
	common /hhh_varXs/ Sub441, Sub450, Sub452, Sub462, Sub463
	common /hhh_varXs/ Sub636, Sub638, Sub473, Sub512, Sub500
	common /hhh_varXs/ Sub480, Sub488, Sub490, Sub498, Sub503
	common /hhh_varXs/ Sub643, Sub322, Sub641, Sub523, Sub526
	common /hhh_varXs/ Sub530, Sub533, Sub536, Sub539, Sub550
	common /hhh_varXs/ Sub551, Sub553, Sub556, Sub559, Sub561
	common /hhh_varXs/ Sub563, Sub566, Sub568, Sub570, Sub573
	common /hhh_varXs/ Sub580, Sub586, Sub594, Sub620, Sub626
	common /hhh_varXs/ Sub628, Sub630, Sub632, Sub634, Sub637
	common /hhh_varXs/ Sub639, Sub642, Sub644, Sub663, Sub666
	common /hhh_varXs/ Sub667, Sub677, Sub681, Sub688, Sub662
	common /hhh_varXs/ Sub697, Sub700, Sub706, Sub710, Sub735
	common /hhh_varXs/ Sub737, Sub753, Sub756, Sub766, Sub769
	common /hhh_varXs/ Sub325, Sub360, Sub23, Sub190, Sub268
	common /hhh_varXs/ Sub270, Sub269, Sub747, Sub365, Sub741
	common /hhh_varXs/ Sub770, Sub257, Sub258, Sub259, Sub415
	common /hhh_varXs/ Sub614, Sub613, Sub761, Sub361, Sub759
	common /hhh_varXs/ Sub760, Sub362, Sub357, Sub358, Sub432
	common /hhh_varXs/ Sub572, Sub610, Sub670, Sub598, Sub353
	common /hhh_varXs/ Sub749, Sub765, Sub748, Sub746, Sub513
	common /hhh_varXs/ Sub506, Sub546, Sub531, Sub433, Sub597
	common /hhh_varXs/ Sub569, Sub537, Sub675, Sub524, Sub464
	common /hhh_varXs/ Sub557, Sub447, Sub471, Sub562, Sub470
	common /hhh_varXs/ Sub467, Sub554, Sub469, Sub525, Sub534
	common /hhh_varXs/ Sub460, Sub479, Sub423, Sub548, Sub549
	common /hhh_varXs/ Sub640, Sub685, Sub532, Sub434, Sub678
	common /hhh_varXs/ Sub585, Sub669, Sub547, Sub635, Sub696
	common /hhh_varXs/ Sub542, Sub494, Sub483, Sub398, Sub602
	common /hhh_varXs/ Sub508, Sub497, Sub588, Sub603, Sub686
	common /hhh_varXs/ Sub576, Sub436, Sub679, Sub518, Sub646
	common /hhh_varXs/ Sub589, Sub514, Sub578, Sub702, Sub564
	common /hhh_varXs/ Sub405, Sub519, Sub543, Sub604, Sub527
	common /hhh_varXs/ Sub590, Sub425, Sub601, Sub577, Sub438
	common /hhh_varXs/ Sub517, Sub673, Sub587, Sub428, Sub515
	common /hhh_varXs/ Sub505, Sub694, Sub579, Sub403, Sub571
	common /hhh_varXs/ Sub565, Sub555, Sub406, Sub510, Sub390
	common /hhh_varXs/ Sub502, Sub430, Sub692, Sub520, Sub396
	common /hhh_varXs/ Sub695, Sub544, Sub509, Sub397, Sub605
	common /hhh_varXs/ Sub402, Sub705, Sub528, Sub507, Sub496
	common /hhh_varXs/ Sub369, Sub591, Sub372, Sub424, Sub606
	common /hhh_varXs/ Sub671, Sub687, Sub582, Sub439, Sub680
	common /hhh_varXs/ Sub521, Sub511, Sub499, Sub672, Sub592
	common /hhh_varXs/ Sub427, Sub208, Sub195, Sub329, Sub339
	common /hhh_varXs/ Sub742, Sub230, Sub336, Sub348, Sub391
	common /hhh_varXs/ Sub342, Sub475, Sub649, Sub392, Sub393
	common /hhh_varXs/ Sub745, Sub609, Sub608, Sub744, Sub750
	common /hhh_varXs/ Sub768, Sub238, Sub231, Sub216, Sub209
	common /hhh_varXs/ Sub210, Sub196, Sub327, Sub338, Sub232
	common /hhh_varXs/ Sub335, Sub346, Sub381, Sub341, Sub474
	common /hhh_varXs/ Sub648, Sub197, Sub442, Sub382, Sub383
	common /hhh_varXs/ Sub331, Sub337, Sub340, Sub343, Sub350
	common /hhh_varXs/ Sub599, Sub611, Sub233, Sub234, Sub211
	common /hhh_varXs/ Sub212, Sub332, Sub333, Sub689, Sub443
	common /hhh_varXs/ Sub198, Sub719, Sub408, Sub445, Sub472
	common /hhh_varXs/ Sub676, Sub684, Sub691, Sub214, Sub200
	common /hhh_varXs/ Sub468, Sub411, Sub236, Sub446, Sub448
	common /hhh_varXs/ Sub476, Sub461, Sub419, Sub69, Sub201
	common /hhh_varXs/ Sub713, Sub203, Sub716, Sub317, Sub477
	common /hhh_varXs/ Sub478, Sub237, Sub240, Sub215, Sub218
	common /hhh_varXs/ Sub354, Sub355, Sub726, Sub202, Sub724
	common /hhh_varXs/ Sub734, Sub27, Sub28, Sub730, Sub204
	common /hhh_varXs/ Sub725, Sub736, Sub818, Sub205, Sub256
	common /hhh_varXs/ Sub199, Sub249, Sub64, Sub51, Sub63
	common /hhh_varXs/ Sub49, Sub58, Sub56, Sub179, Sub178
	common /hhh_varXs/ Sub175, Sub104, Sub174, Sub102, Sub97
	common /hhh_varXs/ Sub95, Sub110, Sub109, Sub144, Sub131
	common /hhh_varXs/ Sub143, Sub129, Sub138, Sub136, Sub183
	common /hhh_varXs/ Sub182, Sub55, Sub59, Sub39, Sub40
	common /hhh_varXs/ Sub188, Sub33, Sub34, Sub48, Sub52, Sub37
	common /hhh_varXs/ Sub36, Sub45, Sub44, Sub229, Sub94, Sub98
	common /hhh_varXs/ Sub90, Sub85, Sub86, Sub91, Sub191, Sub82
	common /hhh_varXs/ Sub83, Sub105, Sub101, Sub80, Sub79
	common /hhh_varXs/ Sub251, Sub135, Sub139, Sub119, Sub120
	common /hhh_varXs/ Sub193, Sub113, Sub114, Sub128, Sub132
	common /hhh_varXs/ Sub117, Sub116, Sub125, Sub124, Sub264
	common /hhh_varXs/ Sub260, Sub271, Sub252, Sub207, Sub219
	common /hhh_varXs/ Sub224, Sub206, Sub250, Sub253, Sub255
	common /hhh_varXs/ Sub261, Sub262, Sub266, Sub272, Sub273
	common /hhh_varXs/ Sub274, Sub267, Sub959, Sub277, Sub275
	common /hhh_varXs/ Sub280, Sub283, Sub292, Sub289, Sub295
	common /hhh_varXs/ Sub298, Sub301, Sub287, Sub276, Sub278
	common /hhh_varXs/ Sub281, Sub284, Sub293, Sub288, Sub296
	common /hhh_varXs/ Sub299, Sub302, Sub290, Sub927, Sub928
	common /hhh_varXs/ Sub930, Sub932, Sub935, Sub936, Sub938
	common /hhh_varXs/ Sub940, Sub31, Sub22, Sub29, Sub26, Sub13
	common /hhh_varXs/ Sub15, Sub14, Sub791, Sub793, Sub792
	common /hhh_varXs/ Sub17, Sub779, Sub781, Sub780, Sub12
	common /hhh_varXs/ Sub18, Sub20, Sub19, Sub795, Sub797
	common /hhh_varXs/ Sub796, Sub803, Sub805, Sub804, Sub771
	common /hhh_varXs/ Sub773, Sub772, Sub783, Sub785, Sub784
	common /hhh_varXs/ Sub775, Sub777, Sub776, Sub787, Sub789
	common /hhh_varXs/ Sub788, Sub799, Sub801, Sub800, Sub807
	common /hhh_varXs/ Sub809, Sub808, Sub824, Sub825, Sub827
	common /hhh_varXs/ Sub828, Sub861, Sub862, Sub858, Sub859
	common /hhh_varXs/ Sub892, Sub893, Sub895, Sub896, Sub189
	common /hhh_varXs/ Sub192, Sub194, Sub50, Sub53, Sub57
	common /hhh_varXs/ Sub60, Sub103, Sub106, Sub96, Sub99
	common /hhh_varXs/ Sub130, Sub133, Sub137, Sub140, Sub833
	common /hhh_varXs/ Sub834, Sub836, Sub837, Sub870, Sub871
	common /hhh_varXs/ Sub867, Sub868, Sub901, Sub902, Sub904
	common /hhh_varXs/ Sub905, Sub279, Sub282, Sub285, Sub291
	common /hhh_varXs/ Sub294, Sub297, Sub300, Sub303, Sub311
	common /hhh_varXs/ Sub305, Sub309, Sub308, Sub307, Sub306
	common /hhh_varXs/ Sub943, Sub944, Sub945, Sub937, Sub939
	common /hhh_varXs/ Sub941, Sub929, Sub931, Sub933, Sub947
	common /hhh_varXs/ Sub948, Sub949, Sub816, Sub820, Sub817
	common /hhh_varXs/ Sub821, Sub822, Sub173, Sub177, Sub181
	common /hhh_varXs/ Sub185, Sub172, Sub186, Sub168, Sub54
	common /hhh_varXs/ Sub61, Sub65, Sub107, Sub100, Sub111
	common /hhh_varXs/ Sub134, Sub141, Sub145, Sub842, Sub843
	common /hhh_varXs/ Sub180, Sub845, Sub170, Sub35, Sub38
	common /hhh_varXs/ Sub41, Sub46, Sub876, Sub877, Sub879
	common /hhh_varXs/ Sub176, Sub169, Sub81, Sub84, Sub87
	common /hhh_varXs/ Sub92, Sub910, Sub911, Sub913, Sub184
	common /hhh_varXs/ Sub171, Sub115, Sub118, Sub121, Sub126
	common /hhh_varXs/ Sub157, Sub162, Sub73, Sub844, Sub878
	common /hhh_varXs/ Sub912, Sub158, Sub163, Sub74, Sub846
	common /hhh_varXs/ Sub880, Sub914, Sub122, Sub42, Sub88
	common /hhh_varXs/ Sub147, Sub152, Sub67, Sub123, Sub43
	common /hhh_varXs/ Sub89, Sub148, Sub153, Sub68, Sub127
	common /hhh_varXs/ Sub47, Sub93, Sub154, Sub70, Sub149
	common /hhh_varXs/ Sub164, Sub75, Sub159, Sub108, Sub142
	common /hhh_varXs/ Sub62, Sub155, Sub71, Sub150, Sub165
	common /hhh_varXs/ Sub76, Sub160, Sub112, Sub146, Sub66
	common /hhh_varXs/ Sub156, Sub72, Sub151, Sub166, Sub77
	common /hhh_varXs/ Sub161, Sub847, Sub848, Sub850, Sub881
	common /hhh_varXs/ Sub882, Sub884, Sub915, Sub916, Sub918
	common /hhh_varXs/ Sub826, Sub829, Sub831, Sub860, Sub863
	common /hhh_varXs/ Sub865, Sub894, Sub897, Sub899, Sub830
	common /hhh_varXs/ Sub849, Sub864, Sub883, Sub898, Sub917
	common /hhh_varXs/ Sub832, Sub851, Sub866, Sub885, Sub900
	common /hhh_varXs/ Sub919, Sub835, Sub838, Sub840, Sub869
	common /hhh_varXs/ Sub872, Sub874, Sub903, Sub906, Sub908
	common /hhh_varXs/ Sub852, Sub853, Sub855, Sub887, Sub886
	common /hhh_varXs/ Sub889, Sub920, Sub921, Sub923, Sub839
	common /hhh_varXs/ Sub854, Sub873, Sub888, Sub907, Sub922
	common /hhh_varXs/ Sub841, Sub856, Sub875, Sub890, Sub909
	common /hhh_varXs/ Sub924, Sub953, Sub960, Sub951, Sub952
	common /hhh_varXs/ Sub957, Sub961, Sub955, Sub956, Sub958
	common /hhh_varXs/ Sub962, Sub963, Sub964, Sub857, Sub891
	common /hhh_varXs/ Sub925, Sub926, Sub326, Sub345, Sub352
	common /hhh_varXs/ Sub373, Sub387, Sub409, Sub465, Sub486
	common /hhh_varXs/ Sub516, Sub540, Sub541, Sub545, Sub575
	common /hhh_varXs/ Sub581, Sub654, Sub674, Sub701, Sub413
	common /hhh_varXs/ Sub414, Sub618, Sub767, Sub440, Sub417
	common /hhh_varXs/ Sub504, Sub491, Sub699, Sub395, Sub698
	common /hhh_varXs/ Sub538, Sub535, Sub693, Sub412, Sub429
	common /hhh_varXs/ Sub330, Sub349, Sub379, Sub377, Sub622
	common /hhh_varXs/ Sub328, Sub347, Sub375, Sub378, Sub380
	common /hhh_varXs/ Sub600, Sub624, Sub708, Sub421, Sub444
	common /hhh_varXs/ Sub711, Sub466, Sub619, Sub707, Sub729
	common /hhh_varXs/ Sub727, Sub733, Sub731, Sub492, Sub493
	common /hhh_varXs/ Sub364, Sub660, Sub712, Sub714, Sub661
	common /hhh_varXs/ Sub664, Sub715, Sub717, Sub665, Sub30
	common /hhh_varXs/ Sub32, Sub25, Sub24, Sub16, Sub21, Sub782
	common /hhh_varXs/ Sub794, Sub774, Sub786, Sub798, Sub806
	common /hhh_varXs/ Sub778, Sub790, Sub802, Sub810, Sub310
	common /hhh_varXs/ Sub312, Sub286, Sub304, Sub942, Sub946
	common /hhh_varXs/ Sub934, Sub950, Sub814, Sub815, Sub823
	common /hhh_varXs/ Sub187, Sub78, Sub954, Sub482, Sub484
	common /hhh_varXs/ Sub410, Sub522, Sub574, Sub623, Sub721
	common /hhh_varXs/ Sub651, Sub650, Sub762, Sub704, Sub529
	common /hhh_varXs/ Sub501, Sub703, Sub366, Sub389, Sub612
	common /hhh_varXs/ Sub690, Sub683, Sub723, Sub655, Sub656
	common /hhh_varXs/ Sub813, Sub819, Sub811, Sub812, Sub593
	common /hhh_varXs/ Sub607, Sub625, Sub314, Sub316, Sub319
	common /hhh_varXs/ Sub321, Sub718, Sub416, Sub659, Sub658
	common /hhh_varXs/ Sub616, Sub617, Sub739, Sub323, Sub324
	common /hhh_varXs/ Sub457, Sub652, Sub653, Sub254, Sub167
	common /hhh_varXs/ Sub738, Sub668, Sub740, pave1, pave2
	common /hhh_varXs/ pave3, pave4, pave5, pave6, pave7, pave8
	common /hhh_varXs/ pave9, pave10, pave11, pave12, pave13
	common /hhh_varXs/ pave14, pave15, pave16, pave17, pave18
	common /hhh_varXs/ pave19, pave20, pave21, pave22, pave23
	common /hhh_varXs/ pave24, pave25, pave26, pave27, pave28
	common /hhh_varXs/ pave29, pave30, pave31, pave32, pave33
	common /hhh_varXs/ pave34, pave35, pave36, pave37, pave38
	common /hhh_varXs/ pave39, pave40, pave41, pave42, pave43
	common /hhh_varXs/ pave44, pave45, pave46, pave47, pave48
	common /hhh_varXs/ pave49, pave50, pave51, pave52, pave53
	common /hhh_varXs/ pave54, pave55, pave56, pave57, pave58
	common /hhh_varXs/ pave59, pave60, pave61, pave62, pave63
	common /hhh_varXs/ pave64, pave65, pave66, pave67, pave68
	common /hhh_varXs/ pave69, pave70, pave71, pave72, pave73
	common /hhh_varXs/ pave74, pave75, pave76, pave77, pave78
	common /hhh_varXs/ pave79, pave80, pave81, pave82, pave83
	common /hhh_varXs/ pave84, pave85, pave86, pave87, pave88
	common /hhh_varXs/ pave89, pave90, pave91, pave92, pave93
	common /hhh_varXs/ pave94, pave95, pave96, pave97, pave98
	common /hhh_varXs/ pave99, pave100, pave101, pave102
	common /hhh_varXs/ pave103, pave104, pave105, pave106
	common /hhh_varXs/ pave107, pave108, pave109, pave110
	common /hhh_varXs/ pave111, pave112, pave113, pave114
	common /hhh_varXs/ pave115, pave116, pave117, pave118
	common /hhh_varXs/ pave119, pave120, pave121, pave122
	common /hhh_varXs/ pave123, pave124, pave125, pave126
	common /hhh_varXs/ pave127, pave128, pave129, pave130
	common /hhh_varXs/ pave131, pave132, pave133, pave134
	common /hhh_varXs/ pave135, pave136, pave137, pave138
	common /hhh_varXs/ pave139, pave140, pave141, pave142
	common /hhh_varXs/ pave143, pave144, pave145, pave146
	common /hhh_varXs/ pave147, pave148, pave149, pave150
	common /hhh_varXs/ pave151, pave152, pave153, pave154
	common /hhh_varXs/ pave155, pave156, pave157, pave158
	common /hhh_varXs/ pave159, pave160, pave161, pave162
	common /hhh_varXs/ pave163, pave164, pave165, pave166
	common /hhh_varXs/ pave167, pave168, pave169, pave170
	common /hhh_varXs/ pave171, pave172, pave173, pave174
	common /hhh_varXs/ pave175, pave176, pave177, pave178
	common /hhh_varXs/ pave179, pave180, pave181, pave182
	common /hhh_varXs/ pave183, pave184, pave185, pave186
	common /hhh_varXs/ pave187, pave188, pave189, pave190
	common /hhh_varXs/ pave191, pave192, pave193, pave194
	common /hhh_varXs/ pave195, pave196, pave197, pave198
	common /hhh_varXs/ pave199, pave200, pave201, pave202
	common /hhh_varXs/ pave203, pave204, pave205, pave206
	common /hhh_varXs/ pave207, pave208, pave209, pave210
	common /hhh_varXs/ pave211, pave212, pave213, pave214
	common /hhh_varXs/ pave215, pave216, pave217, pave218
	common /hhh_varXs/ pave219, pave220, pave221, pave222
	common /hhh_varXs/ pave223, pave224

	integer seq(2), Hel(3)
	common /hhh_helind/ seq, Hel

	integer Cha4, Cha5, Cha6, Gen4, Neu4, Neu5, Neu6, Sfe4, Sfe5
	integer Sfe6
	common /hhh_indices/ Cha4, Cha5, Cha6, Gen4, Neu4, Neu5, Neu6
	common /hhh_indices/ Sfe4, Sfe5, Sfe6

	ComplexType Ctree(1), Cloop(1)
	common /hhh_formfactors/ Ctree, Cloop

#endif
