#if 0
* hhh-vars.h
* variable declarations
* generated by FormCalc 8.4 on 30-Apr-2014 7:31
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hhh-renconst.h"

	ComplexType Sub3, Sub2, Sub4, Sub1, Sub6, Sub8, Sub7, Sub9
	ComplexType Sub5
	ComplexType Opt1, Sub483, Sub490, Sub486, Sub493, Sub350
	ComplexType Sub842, Sub496, Sub848, Sub413, Sub423, Sub418
	ComplexType Sub408, Sub478, Sub375, Sub371, Sub512, Sub367
	ComplexType Sub783, Sub509, Sub782, Sub364, Sub780, Sub779
	ComplexType Sub506, Sub777, Sub776, Sub686, Sub712, Sub635
	ComplexType Sub827, Sub833, Sub385, Sub610, Sub572, Sub388
	ComplexType Sub853, Sub647, Sub796, Sub547, Sub685, Sub389
	ComplexType Sub510, Sub513, Sub590, Sub482, Sub489, Sub386
	ComplexType Sub587, Sub485, Sub492, Sub830, Sub854, Sub611
	ComplexType Sub826, Sub507, Sub640, Sub711, Sub381, Sub573
	ComplexType Sub642, Sub383, Sub576, Sub578, Sub584, Sub495
	ComplexType Sub841, Sub834, Sub634, Sub615, Sub847, Sub836
	ComplexType Sub368, Sub365, Sub716, Sub549, Sub373, Sub394
	ComplexType Sub591, Sub377, Sub392, Sub588, Sub856, Sub673
	ComplexType Sub829, Sub651, Sub575, Sub579, Sub585, Sub689
	ComplexType Sub844, Sub614, Sub850, Sub837, Sub240, Sub244
	ComplexType Sub248, Sub250, Sub266, Sub269, Sub272, Sub274
	ComplexType Sub372, Sub376, Sub382, Sub384, Sub409, Sub414
	ComplexType Sub419, Sub443, Sub480, Sub479, Sub529, Sub528
	ComplexType Sub535, Sub863, Sub558, Sub560, Sub605, Sub620
	ComplexType Sub623, Sub626, Sub630, Sub633, Sub653, Sub663
	ComplexType Sub666, Sub670, Sub679, Sub680, Sub687, Sub744
	ComplexType Sub889, Sub883, Sub893, Sub895, Sub947, Sub404
	ComplexType Sub406, Sub426, Sub416, Sub412, Sub405, Sub422
	ComplexType Sub425, Sub359, Sub400, Sub407, Sub358, Sub246
	ComplexType Sub251, Sub397, Sub774, Sub794, Sub792, Sub772
	ComplexType Sub789, Sub787, Sub944, Sub452, Sub569, Sub668
	ComplexType Sub554, Sub361, Sub380, Sub355, Sub357, Sub595
	ComplexType Sub440, Sub676, Sub618, Sub556, Sub648, Sub441
	ComplexType Sub631, Sub624, Sub641, Sub652, Sub442, Sub625
	ComplexType Sub621, Sub552, Sub439, Sub677, Sub678, Sub840
	ComplexType Sub707, Sub619, Sub557, Sub462, Sub650, Sub859
	ComplexType Sub669, Sub470, Sub471, Sub516, Sub786, Sub655
	ComplexType Sub501, Sub637, Sub617, Sub559, Sub603, Sub553
	ComplexType Sub656, Sub448, Sub596, Sub472, Sub675, Sub644
	ComplexType Sub518, Sub598, Sub467, Sub658, Sub473, Sub747
	ComplexType Sub740, Sub627, Sub499, Sub659, Sub437, Sub756
	ComplexType Sub434, Sub561, Sub602, Sub697, Sub704, Sub654
	ComplexType Sub445, Sub597, Sub474, Sub739, Sub607, Sub517
	ComplexType Sub649, Sub741, Sub645, Sub667, Sub519, Sub502
	ComplexType Sub692, Sub734, Sub599, Sub468, Sub660, Sub475
	ComplexType Sub515, Sub743, Sub785, Sub582, Sub628, Sub593
	ComplexType Sub530, Sub498, Sub661, Sub488, Sub436, Sub433
	ComplexType Sub730, Sub562, Sub456, Sub604, Sub539, Sub696
	ComplexType Sub429, Sub662, Sub446, Sub752, Sub211, Sub195
	ComplexType Sub460, Sub431, Sub763, Sub356, Sub875, Sub758
	ComplexType Sub15, Sub454, Sub564, Sub432, Sub750, Sub714
	ComplexType Sub813, Sub360, Sub723, Sub798, Sub930, Sub16
	ComplexType Sub224, Sub227, Sub209, Sub212, Sub243, Sub263
	ComplexType Sub241, Sub267, Sub239, Sub271, Sub249, Sub273
	ComplexType Sub247, Sub291, Sub289, Sub287, Sub285, Sub352
	ComplexType Sub296, Sub363, Sub399, Sub217, Sub215, Sub216
	ComplexType Sub256, Sub260, Sub196, Sub283, Sub21, Sub461
	ComplexType Sub435, Sub762, Sub546, Sub876, Sub896, Sub197
	ComplexType Sub457, Sub567, Sub922, Sub222, Sub455, Sub565
	ComplexType Sub28, Sub721, Sub522, Sub503, Sub757, Sub923
	ComplexType Sub449, Sub525, Sub548, Sub531, Sub722, Sub523
	ComplexType Sub751, Sub720, Sub450, Sub526, Sub504, Sub532
	ComplexType Sub727, Sub369, Sub378, Sub390, Sub395, Sub481
	ComplexType Sub484, Sub487, Sub491, Sub494, Sub497, Sub508
	ComplexType Sub511, Sub514, Sub865, Sub544, Sub542, Sub864
	ComplexType Sub550, Sub612, Sub616, Sub636, Sub674, Sub719
	ComplexType Sub797, Sub832, Sub839, Sub846, Sub852, Sub858
	ComplexType Sub929, Sub927, Sub44, Sub259, Sub255, Sub234
	ComplexType Sub237, Sub949, Sub870, Sub911, Sub917, Sub242
	ComplexType Sub228, Sub225, Sub286, Sub284, Sub290, Sub288
	ComplexType Sub766, Sub768, Sub767, Sub681, Sub754, Sub765
	ComplexType Sub753, Sub760, Sub800, Sub759, Sub764, Sub799
	ComplexType Sub232, Sub231, Sub715, Sub444, Sub459, Sub463
	ComplexType Sub521, Sub570, Sub732, Sub745, Sub709, Sub464
	ComplexType Sub200, Sub293, Sub20, Sub466, Sub538, Sub555
	ComplexType Sub201, Sub807, Sub808, Sub223, Sub571, Sub710
	ComplexType Sub27, Sub683, Sub693, Sub698, Sub823, Sub583
	ComplexType Sub699, Sub694, Sub366, Sub374, Sub387, Sub393
	ComplexType Sub824, Sub574, Sub577, Sub580, Sub586, Sub589
	ComplexType Sub592, Sub688, Sub690, Sub713, Sub778, Sub781
	ComplexType Sub784, Sub803, Sub890, Sub828, Sub831, Sub835
	ComplexType Sub838, Sub845, Sub843, Sub851, Sub849, Sub855
	ComplexType Sub857, Sub891, Sub805, Sub72, Sub305, Sub957
	ComplexType Sub934, Sub938, Sub226, Sub229, Sub793, Sub795
	ComplexType Sub22, Sub29, Sub294, Sub370, Sub379, Sub391
	ComplexType Sub396, Sub788, Sub790, Sub245, Sub818, Sub817
	ComplexType Sub814, Sub300, Sub303, Sub820, Sub819, Sub728
	ComplexType Sub295, Sub301, Sub304, Sub204(3), Sub208(3)
	ComplexType Sub199(3), Sub292(3), Sub252(3), Sub275(3)
	ComplexType Sub67(3), Sub54(3), Sub66(3), Sub52(3), Sub61(3)
	ComplexType Sub59(3), Sub979(3), Sub982(3), Sub987(3)
	ComplexType Sub990(3), Sub996(3), Sub999(3), Sub107(3)
	ComplexType Sub105(3), Sub100(3), Sub98(3), Sub113(3)
	ComplexType Sub112(3), Sub147(3), Sub134(3), Sub146(3)
	ComplexType Sub132(3), Sub141(3), Sub139(3), Sub58(3)
	ComplexType Sub62(3), Sub41(3), Sub42(3), Sub189(3)
	ComplexType Sub35(3), Sub36(3), Sub51(3), Sub55(3), Sub39(3)
	ComplexType Sub38(3), Sub297(3), Sub48(3), Sub47(3)
	ComplexType Sub97(3), Sub101(3), Sub93(3), Sub88(3)
	ComplexType Sub89(3), Sub94(3), Sub191(3), Sub85(3)
	ComplexType Sub86(3), Sub108(3), Sub104(3), Sub83(3)
	ComplexType Sub82(3), Sub230(3), Sub138(3), Sub142(3)
	ComplexType Sub122(3), Sub123(3), Sub193(3), Sub116(3)
	ComplexType Sub117(3), Sub131(3), Sub135(3), Sub120(3)
	ComplexType Sub119(3), Sub306(3), Sub128(3), Sub127(3)
	ComplexType Sub205(3), Sub213(3), Sub206(3), Sub207(3)
	ComplexType Sub214(3), Sub219(3), Sub220(3), Sub253(3)
	ComplexType Sub254(3), Sub276(3), Sub298(3), Sub299(3)
	ComplexType Sub307(3), Sub308(3), Sub309(3), Sub978(3)
	ComplexType Sub981(3), Sub221(3), Sub986(3), Sub989(3)
	ComplexType Sub995(3), Sub998(3), Sub312(4), Sub310(4)
	ComplexType Sub315(4), Sub318(4), Sub327(4), Sub324(4)
	ComplexType Sub330(4), Sub333(4), Sub336(4), Sub322(4)
	ComplexType Sub311(4), Sub313(4), Sub316(4), Sub319(4)
	ComplexType Sub328(4), Sub323(4), Sub331(4), Sub334(4)
	ComplexType Sub337(4), Sub325(4), Sub1097(4), Sub1098(4)
	ComplexType Sub1100(4), Sub1102(4), Sub1105(4), Sub1106(4)
	ComplexType Sub1108(4), Sub1110(4), Sub23(2,2), Sub19(2,2)
	ComplexType Sub30(2,2), Sub32(2,2), Sub26(2,2), Sub31(2,2)
	ComplexType Sub33(2,2), Sub34(2,2), Sub18(2,2), Sub10(2,2)
	ComplexType Sub948(2,2), Sub14(2,2), Sub959(2,2), Sub13(2,2)
	ComplexType Sub950(2,2), Sub953(2,2), Sub956(2,2)
	ComplexType Sub960(2,2), Sub958(2,2), Sub961(2,2)
	ComplexType Sub952(2,2), Sub954(2,2), Sub1021(3,2)
	ComplexType Sub1023(3,2), Sub1024(3,2), Sub1020(3,2)
	ComplexType Sub190(3,2), Sub192(3,2), Sub194(3,2)
	ComplexType Sub980(3,2), Sub983(3,2), Sub1009(3,2)
	ComplexType Sub1010(3,2), Sub1054(3,2), Sub1055(3,2)
	ComplexType Sub1057(3,2), Sub1058(3,2), Sub53(3,2)
	ComplexType Sub56(3,2), Sub60(3,2), Sub63(3,2), Sub102(3,2)
	ComplexType Sub106(3,2), Sub109(3,2), Sub99(3,2)
	ComplexType Sub133(3,2), Sub136(3,2), Sub140(3,2)
	ComplexType Sub143(3,2), Sub1004(3,2), Sub1005(3,2)
	ComplexType Sub997(3,2), Sub1000(3,2), Sub1071(3,2)
	ComplexType Sub1072(3,2), Sub1074(3,2), Sub1075(3,2)
	ComplexType Sub1030(3,2), Sub1032(3,2), Sub1033(3,2)
	ComplexType Sub1029(3,2), Sub988(3,2), Sub991(3,2)
	ComplexType Sub1014(3,2), Sub1015(3,2), Sub1062(3,2)
	ComplexType Sub1063(3,2), Sub1065(3,2), Sub1066(3,2)
	ComplexType Sub314(4,4), Sub317(4,4), Sub320(4,4)
	ComplexType Sub326(4,4), Sub329(4,4), Sub332(4,4)
	ComplexType Sub335(4,4), Sub338(4,4), Sub347(4,4)
	ComplexType Sub340(4,4), Sub344(4,4), Sub343(4,4)
	ComplexType Sub345(4,4), Sub346(4,4), Sub348(4,4)
	ComplexType Sub349(4,4), Sub342(4,4), Sub341(4,4)
	ComplexType Sub1113(4,4), Sub1114(4,4), Sub1115(4,4)
	ComplexType Sub1107(4,4), Sub1109(4,4), Sub1111(4,4)
	ComplexType Sub1099(4,4), Sub1101(4,4), Sub1103(4,4)
	ComplexType Sub1117(4,4), Sub1118(4,4), Sub1119(4,4)
	ComplexType Sub962(2,2,2), Sub965(2,2,2), Sub969(2,2,2)
	ComplexType Sub967(2,2,2), Sub974(2,2,2), Sub971(2,2,2)
	ComplexType Sub970(2,2,2), Sub972(2,2,2), Sub975(2,2,2)
	ComplexType Sub976(2,2,2), Sub977(2,2,2), Sub176(3,2,2)
	ComplexType Sub179(3,2,2), Sub182(3,2,2), Sub183(3,2,2)
	ComplexType Sub186(3,2,2), Sub188(3,2,2), Sub175(3,2,2)
	ComplexType Sub171(3,2,2), Sub1006(3,2,2), Sub1080(3,2,2)
	ComplexType Sub1081(3,2,2), Sub984(3,2,2), Sub1056(3,2,2)
	ComplexType Sub1059(3,2,2), Sub57(3,2,2), Sub64(3,2,2)
	ComplexType Sub68(3,2,2), Sub103(3,2,2), Sub110(3,2,2)
	ComplexType Sub114(3,2,2), Sub137(3,2,2), Sub144(3,2,2)
	ComplexType Sub148(3,2,2), Sub177(3,2,2), Sub1007(3,2,2)
	ComplexType Sub173(3,2,2), Sub37(3,2,2), Sub40(3,2,2)
	ComplexType Sub43(3,2,2), Sub49(3,2,2), Sub1038(3,2,2)
	ComplexType Sub1039(3,2,2), Sub180(3,2,2), Sub181(3,2,2)
	ComplexType Sub1041(3,2,2), Sub172(3,2,2), Sub84(3,2,2)
	ComplexType Sub87(3,2,2), Sub90(3,2,2), Sub95(3,2,2)
	ComplexType Sub184(3,2,2), Sub1083(3,2,2), Sub174(3,2,2)
	ComplexType Sub118(3,2,2), Sub121(3,2,2), Sub124(3,2,2)
	ComplexType Sub129(3,2,2), Sub1040(3,2,2), Sub1060(3,2,2)
	ComplexType Sub1082(3,2,2), Sub160(3,2,2), Sub165(3,2,2)
	ComplexType Sub76(3,2,2), Sub1008(3,2,2), Sub1042(3,2,2)
	ComplexType Sub1084(3,2,2), Sub161(3,2,2), Sub1061(3,2,2)
	ComplexType Sub166(3,2,2), Sub77(3,2,2), Sub985(3,2,2)
	ComplexType Sub125(3,2,2), Sub45(3,2,2), Sub91(3,2,2)
	ComplexType Sub150(3,2,2), Sub155(3,2,2), Sub70(3,2,2)
	ComplexType Sub126(3,2,2), Sub46(3,2,2), Sub92(3,2,2)
	ComplexType Sub151(3,2,2), Sub156(3,2,2), Sub71(3,2,2)
	ComplexType Sub130(3,2,2), Sub50(3,2,2), Sub96(3,2,2)
	ComplexType Sub157(3,2,2), Sub73(3,2,2), Sub152(3,2,2)
	ComplexType Sub167(3,2,2), Sub78(3,2,2), Sub162(3,2,2)
	ComplexType Sub111(3,2,2), Sub145(3,2,2), Sub65(3,2,2)
	ComplexType Sub158(3,2,2), Sub74(3,2,2), Sub153(3,2,2)
	ComplexType Sub168(3,2,2), Sub79(3,2,2), Sub163(3,2,2)
	ComplexType Sub115(3,2,2), Sub149(3,2,2), Sub69(3,2,2)
	ComplexType Sub159(3,2,2), Sub75(3,2,2), Sub154(3,2,2)
	ComplexType Sub169(3,2,2), Sub80(3,2,2), Sub164(3,2,2)
	ComplexType Sub992(3,2,2), Sub1064(3,2,2), Sub1067(3,2,2)
	ComplexType Sub1011(3,2,2), Sub1085(3,2,2), Sub1086(3,2,2)
	ComplexType Sub1012(3,2,2), Sub1043(3,2,2), Sub1044(3,2,2)
	ComplexType Sub1046(3,2,2), Sub1088(3,2,2), Sub993(3,2,2)
	ComplexType Sub1022(3,2,2), Sub1025(3,2,2), Sub1027(3,2,2)
	ComplexType Sub1069(3,2,2), Sub1026(3,2,2), Sub1045(3,2,2)
	ComplexType Sub1068(3,2,2), Sub1087(3,2,2), Sub1013(3,2,2)
	ComplexType Sub1028(3,2,2), Sub1047(3,2,2), Sub1070(3,2,2)
	ComplexType Sub1089(3,2,2), Sub994(3,2,2), Sub1016(3,2,2)
	ComplexType Sub1090(3,2,2), Sub1091(3,2,2), Sub1001(3,2,2)
	ComplexType Sub1073(3,2,2), Sub1076(3,2,2), Sub1002(3,2,2)
	ComplexType Sub1031(3,2,2), Sub1034(3,2,2), Sub1036(3,2,2)
	ComplexType Sub1078(3,2,2), Sub1017(3,2,2), Sub1048(3,2,2)
	ComplexType Sub1049(3,2,2), Sub1051(3,2,2), Sub1093(3,2,2)
	ComplexType Sub1035(3,2,2), Sub1050(3,2,2), Sub1077(3,2,2)
	ComplexType Sub1092(3,2,2), Sub1003(3,2,2), Sub1018(3,2,2)
	ComplexType Sub1037(3,2,2), Sub1052(3,2,2), Sub1079(3,2,2)
	ComplexType Sub1094(3,2,2), Sub1126(4,4,4), Sub1129(4,4,4)
	ComplexType Sub1127(4,4,4), Sub1130(4,4,4), Sub1131(4,4,4)
	ComplexType Sub1121(4,4,4), Sub1123(4,4,4), Sub1128(4,4,4)
	ComplexType Sub1122(4,4,4), Sub1095(3,2,2,2)
	ComplexType Sub1096(3,2,2,2), Sub1053(3,2,2,2)
	ComplexType Sub1019(3,2,2,2), Sub761, Sub718, Sub926, Sub898
	ComplexType Sub928, Sub871, Sub900, Sub438, Sub453, Sub469
	ComplexType Sub500, Sub520, Sub534, Sub600, Sub606, Sub646
	ComplexType Sub657, Sub671, Sub417, Sub738, Sub769, Sub770
	ComplexType Sub882, Sub427, Sub921, Sub402, Sub802, Sub804
	ComplexType Sub866, Sub411, Sub421, Sub424, Sub540, Sub410
	ComplexType Sub909, Sub912, Sub908, Sub415, Sub420, Sub403
	ComplexType Sub354, Sub398, Sub563, Sub771, Sub613, Sub465
	ComplexType Sub643, Sub581, Sub862, Sub861, Sub742, Sub594
	ComplexType Sub537, Sub447, Sub430, Sub737, Sub884, Sub888
	ComplexType Sub735, Sub887, Sub736, Sub749, Sub632, Sub622
	ComplexType Sub885, Sub701, Sub733, Sub748, Sub608, Sub609
	ComplexType Sub703, Sub879, Sub11, Sub941, Sub877, Sub12
	ComplexType Sub210, Sub17, Sub279, Sub282, Sub351, Sub362
	ComplexType Sub791, Sub874, Sub906, Sub902, Sub914, Sub919
	ComplexType Sub936, Sub940, Sub233, Sub236, Sub878, Sub955
	ComplexType Sub932, Sub880, Sub916, Sub910, Sub904, Sub899
	ComplexType Sub872, Sub873, Sub280, Sub264, Sub277, Sub265
	ComplexType Sub268, Sub278, Sub913, Sub918, Sub905, Sub901
	ComplexType Sub682, Sub942, Sub943, Sub524, Sub868, Sub198
	ComplexType Sub451, Sub731, Sub545, Sub505, Sub527, Sub533
	ComplexType Sub551, Sub924, Sub235, Sub238, Sub568, Sub458
	ComplexType Sub931, Sub708, Sub725, Sub867, Sub302, Sub903
	ComplexType Sub907, Sub951, Sub915, Sub920, Sub937, Sub933
	ComplexType Sub258, Sub262, Sub270, Sub935, Sub939, Sub886
	ComplexType Sub812, Sub202, Sub773, Sub806, Sub695, Sub700
	ComplexType Sub825, Sub809, Sub892, Sub684, Sub726, Sub203
	ComplexType Sub775, Sub810, Sub702, Sub705, Sub860, Sub691
	ComplexType Sub811, Sub894, Sub218(3), Sub25(2,2)
	ComplexType Sub24(2,2), Sub321(4,4), Sub339(4,4)
	ComplexType Sub1112(4,4), Sub1116(4,4), Sub1104(4,4)
	ComplexType Sub1120(4,4), Sub966(2,2,2), Sub964(2,2,2)
	ComplexType Sub963(2,2,2), Sub968(2,2,2), Sub187(3,2,2)
	ComplexType Sub81(3,2,2), Sub178(3,2,2), Sub185(3,2,2)
	ComplexType Sub1124(4,4,4), Sub1125(4,4,4), Sub1132(4,4,4)
	ComplexType Sub401, Sub717, Sub536, Sub601, Sub639, Sub664
	ComplexType Sub672, Sub706, Sub746, Sub801, Sub881, Sub541
	ComplexType Sub543, Sub353, Sub566, Sub821, Sub724, Sub261
	ComplexType Sub257, Sub729, Sub428, Sub973(2,2,2), Sub638
	ComplexType Sub629, Sub925, Sub897, Sub665, Sub755, Sub815
	ComplexType Sub170(3,2,2), Sub476, Sub477, Sub945, Sub822
	ComplexType Sub946, pave1(2), pave2(2,2), pave3(2,2)
	ComplexType pave4(3,2), pave5(3,2), pave6(3,2), pave7(4)
	ComplexType pave8(4,4), pave9(4,4), pave10(2,2)
	ComplexType pave11(Ncc,2,2,2), pave12(Ncc,3,2,2,2)
	ComplexType pave13(4,4), pave14, pave15, pave16, pave17
	ComplexType pave18, pave19, pave20, pave21, pave22, pave23
	ComplexType pave24, pave25, pave26, pave27, pave28, pave29
	ComplexType pave30, pave31, pave32, pave33, pave34, pave35
	ComplexType pave36, pave37, pave38, pave39, pave40
	ComplexType pave41(Ncc), pave42(Ncc), pave43(Ncc)
	ComplexType pave44(Ncc), pave45(Ncc), pave46(Ncc)
	ComplexType pave47(Ncc), pave48(Ncc), pave49(Ncc)
	ComplexType pave50(Ncc), pave51(Ncc), pave52(Ncc)
	ComplexType pave53(Ncc), pave54(Ncc), pave55(Ncc)
	ComplexType pave56(Ncc), pave57(Ncc), pave58(Ncc)
	ComplexType pave59(Ncc), pave60(Ncc), pave61(Ncc)
	ComplexType pave62(Ncc), pave63(Ncc), pave64(Ncc)
	ComplexType pave65(Ncc), pave66(Ncc), pave67(Ncc)
	ComplexType pave68(Ncc), pave69(Ncc), pave70(Ncc)
	ComplexType pave71(Ncc), pave72(Ncc), pave73(Ncc)
	ComplexType pave74(Ncc), pave75(Ncc), pave76(Ncc)
	ComplexType pave77(Ncc), pave78(Ncc), pave79(Ncc)
	ComplexType pave80(Ncc), pave81(Ncc), pave82(Ncc)
	ComplexType pave83(Ncc), pave84(Ncc), pave85(Ncc)
	ComplexType pave86(Ncc), pave87(Ncc), pave88(Ncc)
	ComplexType pave89(Ncc), pave90(Ncc), pave91(Ncc)
	ComplexType pave92(Ncc), pave93(Ncc), pave94(Ncc)
	ComplexType pave95(Ncc), pave96(Ncc), pave97(Ncc)
	ComplexType pave98(Ncc), pave99(Ncc), pave100(Ncc)
	ComplexType pave101(Ncc), pave102(Ncc), pave103(Ncc)
	ComplexType pave104(Ncc), pave105(Ncc), pave106(Ncc)
	ComplexType pave107(Ncc), pave108(Ncc), pave109(Ncc)
	ComplexType pave110(Ncc), pave111(Ncc), pave112(Ncc)
	ComplexType pave113(Ncc), pave114(Ncc), pave115(Ncc)
	ComplexType pave116(Ncc), pave117(Ncc), pave118(Ncc)
	ComplexType pave119(Ncc), pave120(Ncc), pave121(Ncc)
	ComplexType pave122(Ncc), pave123(Ncc), pave124(Ncc)
	ComplexType pave125(Ncc), pave126(Ncc), pave127(Ncc)
	ComplexType pave128(Ncc), pave129(Ncc), pave130(Ncc)
	ComplexType pave131(Ncc), pave132(Ncc), pave133(Ncc)
	ComplexType pave134(Ncc), pave135(Ncc), pave136(Ncc)
	ComplexType pave137(Ncc), pave138(Ncc), pave139(Ncc)
	ComplexType pave140(Ncc), pave141(Ncc), pave142, pave143
	ComplexType pave144, pave145(Ncc), pave146, pave147(3)
	ComplexType pave148(3), pave149(3), pave150(3)
	ComplexType pave151(Ncc,3), pave152(Ncc,3), pave153(Ncc,3)
	ComplexType pave154(Ncc,3), pave155(3), pave156(3)
	ComplexType pave157(3), pave158(3), pave159(3), pave160(3)
	ComplexType pave161(3), pave162(3), pave163(3), pave164(3)
	ComplexType pave165(3,2,2), pave166(3,2,2), pave167(3,2,2)
	ComplexType pave168(Ncc,3,2,2,2), pave169(Ncc,3,2,2,2)
	ComplexType pave170, pave171, pave172(Ncc), pave173(Ncc)
	ComplexType pave174(Ncc), pave175, pave176(Ncc)
	ComplexType pave177(Ncc), pave178(Ncc), pave179(Ncc)
	ComplexType pave180(Ncc), pave181(Ncc), pave182(Ncc)
	ComplexType pave183(Ncc), pave184(Ncc), pave185(Ncc)
	ComplexType pave186(Ncc), pave187(Ncc), pave188
	ComplexType pave189(Ncc), pave190(Ncc), pave191(3)
	ComplexType pave192(3), pave193(3), pave194(3,2,2)
	ComplexType pave195(3,2,2), pave196(3,2,2), pave197(3,2,2)
	ComplexType pave198(3,2,2), pave199(Ncc,4,4,4), pave200
	ComplexType pave201, pave202, pave203, pave204(Ncc)
	ComplexType pave205(Ncc), pave206(Ncc), pave207(Ncc)
	ComplexType pave208, pave209, pave210, pave211, pave212
	ComplexType pave213, pave214(Ncc), pave215, pave216, pave217
	ComplexType pave218, pave219(3,2,2), pave220(3,2,2)
	ComplexType pave221(3,2,2), pave222(3,2,2), pave223, pave224
	common /hhh_varXs/ Sub3, Sub2, Sub4, Sub1, Sub6, Sub8, Sub7
	common /hhh_varXs/ Sub9, Sub5, Opt1, Sub483, Sub490, Sub486
	common /hhh_varXs/ Sub493, Sub350, Sub842, Sub496, Sub848
	common /hhh_varXs/ Sub413, Sub423, Sub418, Sub408, Sub478
	common /hhh_varXs/ Sub375, Sub371, Sub512, Sub367, Sub783
	common /hhh_varXs/ Sub509, Sub782, Sub364, Sub780, Sub779
	common /hhh_varXs/ Sub506, Sub777, Sub776, Sub686, Sub712
	common /hhh_varXs/ Sub635, Sub827, Sub833, Sub385, Sub610
	common /hhh_varXs/ Sub572, Sub388, Sub853, Sub647, Sub796
	common /hhh_varXs/ Sub547, Sub685, Sub389, Sub510, Sub513
	common /hhh_varXs/ Sub590, Sub482, Sub489, Sub386, Sub587
	common /hhh_varXs/ Sub485, Sub492, Sub830, Sub854, Sub611
	common /hhh_varXs/ Sub826, Sub507, Sub640, Sub711, Sub381
	common /hhh_varXs/ Sub573, Sub642, Sub383, Sub576, Sub578
	common /hhh_varXs/ Sub584, Sub495, Sub841, Sub834, Sub634
	common /hhh_varXs/ Sub615, Sub847, Sub836, Sub368, Sub365
	common /hhh_varXs/ Sub716, Sub549, Sub373, Sub394, Sub591
	common /hhh_varXs/ Sub377, Sub392, Sub588, Sub856, Sub673
	common /hhh_varXs/ Sub829, Sub651, Sub575, Sub579, Sub585
	common /hhh_varXs/ Sub689, Sub844, Sub614, Sub850, Sub837
	common /hhh_varXs/ Sub240, Sub244, Sub248, Sub250, Sub266
	common /hhh_varXs/ Sub269, Sub272, Sub274, Sub372, Sub376
	common /hhh_varXs/ Sub382, Sub384, Sub409, Sub414, Sub419
	common /hhh_varXs/ Sub443, Sub480, Sub479, Sub529, Sub528
	common /hhh_varXs/ Sub535, Sub863, Sub558, Sub560, Sub605
	common /hhh_varXs/ Sub620, Sub623, Sub626, Sub630, Sub633
	common /hhh_varXs/ Sub653, Sub663, Sub666, Sub670, Sub679
	common /hhh_varXs/ Sub680, Sub687, Sub744, Sub889, Sub883
	common /hhh_varXs/ Sub893, Sub895, Sub947, Sub404, Sub406
	common /hhh_varXs/ Sub426, Sub416, Sub412, Sub405, Sub422
	common /hhh_varXs/ Sub425, Sub359, Sub400, Sub407, Sub358
	common /hhh_varXs/ Sub246, Sub251, Sub397, Sub774, Sub794
	common /hhh_varXs/ Sub792, Sub772, Sub789, Sub787, Sub944
	common /hhh_varXs/ Sub452, Sub569, Sub668, Sub554, Sub361
	common /hhh_varXs/ Sub380, Sub355, Sub357, Sub595, Sub440
	common /hhh_varXs/ Sub676, Sub618, Sub556, Sub648, Sub441
	common /hhh_varXs/ Sub631, Sub624, Sub641, Sub652, Sub442
	common /hhh_varXs/ Sub625, Sub621, Sub552, Sub439, Sub677
	common /hhh_varXs/ Sub678, Sub840, Sub707, Sub619, Sub557
	common /hhh_varXs/ Sub462, Sub650, Sub859, Sub669, Sub470
	common /hhh_varXs/ Sub471, Sub516, Sub786, Sub655, Sub501
	common /hhh_varXs/ Sub637, Sub617, Sub559, Sub603, Sub553
	common /hhh_varXs/ Sub656, Sub448, Sub596, Sub472, Sub675
	common /hhh_varXs/ Sub644, Sub518, Sub598, Sub467, Sub658
	common /hhh_varXs/ Sub473, Sub747, Sub740, Sub627, Sub499
	common /hhh_varXs/ Sub659, Sub437, Sub756, Sub434, Sub561
	common /hhh_varXs/ Sub602, Sub697, Sub704, Sub654, Sub445
	common /hhh_varXs/ Sub597, Sub474, Sub739, Sub607, Sub517
	common /hhh_varXs/ Sub649, Sub741, Sub645, Sub667, Sub519
	common /hhh_varXs/ Sub502, Sub692, Sub734, Sub599, Sub468
	common /hhh_varXs/ Sub660, Sub475, Sub515, Sub743, Sub785
	common /hhh_varXs/ Sub582, Sub628, Sub593, Sub530, Sub498
	common /hhh_varXs/ Sub661, Sub488, Sub436, Sub433, Sub730
	common /hhh_varXs/ Sub562, Sub456, Sub604, Sub539, Sub696
	common /hhh_varXs/ Sub429, Sub662, Sub446, Sub752, Sub211
	common /hhh_varXs/ Sub195, Sub460, Sub431, Sub763, Sub356
	common /hhh_varXs/ Sub875, Sub758, Sub15, Sub454, Sub564
	common /hhh_varXs/ Sub432, Sub750, Sub714, Sub813, Sub360
	common /hhh_varXs/ Sub723, Sub798, Sub930, Sub16, Sub224
	common /hhh_varXs/ Sub227, Sub209, Sub212, Sub243, Sub263
	common /hhh_varXs/ Sub241, Sub267, Sub239, Sub271, Sub249
	common /hhh_varXs/ Sub273, Sub247, Sub291, Sub289, Sub287
	common /hhh_varXs/ Sub285, Sub352, Sub296, Sub363, Sub399
	common /hhh_varXs/ Sub217, Sub215, Sub216, Sub256, Sub260
	common /hhh_varXs/ Sub196, Sub283, Sub21, Sub461, Sub435
	common /hhh_varXs/ Sub762, Sub546, Sub876, Sub896, Sub197
	common /hhh_varXs/ Sub457, Sub567, Sub922, Sub222, Sub455
	common /hhh_varXs/ Sub565, Sub28, Sub721, Sub522, Sub503
	common /hhh_varXs/ Sub757, Sub923, Sub449, Sub525, Sub548
	common /hhh_varXs/ Sub531, Sub722, Sub523, Sub751, Sub720
	common /hhh_varXs/ Sub450, Sub526, Sub504, Sub532, Sub727
	common /hhh_varXs/ Sub369, Sub378, Sub390, Sub395, Sub481
	common /hhh_varXs/ Sub484, Sub487, Sub491, Sub494, Sub497
	common /hhh_varXs/ Sub508, Sub511, Sub514, Sub865, Sub544
	common /hhh_varXs/ Sub542, Sub864, Sub550, Sub612, Sub616
	common /hhh_varXs/ Sub636, Sub674, Sub719, Sub797, Sub832
	common /hhh_varXs/ Sub839, Sub846, Sub852, Sub858, Sub929
	common /hhh_varXs/ Sub927, Sub44, Sub259, Sub255, Sub234
	common /hhh_varXs/ Sub237, Sub949, Sub870, Sub911, Sub917
	common /hhh_varXs/ Sub242, Sub228, Sub225, Sub286, Sub284
	common /hhh_varXs/ Sub290, Sub288, Sub766, Sub768, Sub767
	common /hhh_varXs/ Sub681, Sub754, Sub765, Sub753, Sub760
	common /hhh_varXs/ Sub800, Sub759, Sub764, Sub799, Sub232
	common /hhh_varXs/ Sub231, Sub715, Sub444, Sub459, Sub463
	common /hhh_varXs/ Sub521, Sub570, Sub732, Sub745, Sub709
	common /hhh_varXs/ Sub464, Sub200, Sub293, Sub20, Sub466
	common /hhh_varXs/ Sub538, Sub555, Sub201, Sub807, Sub808
	common /hhh_varXs/ Sub223, Sub571, Sub710, Sub27, Sub683
	common /hhh_varXs/ Sub693, Sub698, Sub823, Sub583, Sub699
	common /hhh_varXs/ Sub694, Sub366, Sub374, Sub387, Sub393
	common /hhh_varXs/ Sub824, Sub574, Sub577, Sub580, Sub586
	common /hhh_varXs/ Sub589, Sub592, Sub688, Sub690, Sub713
	common /hhh_varXs/ Sub778, Sub781, Sub784, Sub803, Sub890
	common /hhh_varXs/ Sub828, Sub831, Sub835, Sub838, Sub845
	common /hhh_varXs/ Sub843, Sub851, Sub849, Sub855, Sub857
	common /hhh_varXs/ Sub891, Sub805, Sub72, Sub305, Sub957
	common /hhh_varXs/ Sub934, Sub938, Sub226, Sub229, Sub793
	common /hhh_varXs/ Sub795, Sub22, Sub29, Sub294, Sub370
	common /hhh_varXs/ Sub379, Sub391, Sub396, Sub788, Sub790
	common /hhh_varXs/ Sub245, Sub818, Sub817, Sub814, Sub300
	common /hhh_varXs/ Sub303, Sub820, Sub819, Sub728, Sub295
	common /hhh_varXs/ Sub301, Sub304, Sub204, Sub208, Sub199
	common /hhh_varXs/ Sub292, Sub252, Sub275, Sub67, Sub54
	common /hhh_varXs/ Sub66, Sub52, Sub61, Sub59, Sub979
	common /hhh_varXs/ Sub982, Sub987, Sub990, Sub996, Sub999
	common /hhh_varXs/ Sub107, Sub105, Sub100, Sub98, Sub113
	common /hhh_varXs/ Sub112, Sub147, Sub134, Sub146, Sub132
	common /hhh_varXs/ Sub141, Sub139, Sub58, Sub62, Sub41
	common /hhh_varXs/ Sub42, Sub189, Sub35, Sub36, Sub51, Sub55
	common /hhh_varXs/ Sub39, Sub38, Sub297, Sub48, Sub47, Sub97
	common /hhh_varXs/ Sub101, Sub93, Sub88, Sub89, Sub94
	common /hhh_varXs/ Sub191, Sub85, Sub86, Sub108, Sub104
	common /hhh_varXs/ Sub83, Sub82, Sub230, Sub138, Sub142
	common /hhh_varXs/ Sub122, Sub123, Sub193, Sub116, Sub117
	common /hhh_varXs/ Sub131, Sub135, Sub120, Sub119, Sub306
	common /hhh_varXs/ Sub128, Sub127, Sub205, Sub213, Sub206
	common /hhh_varXs/ Sub207, Sub214, Sub219, Sub220, Sub253
	common /hhh_varXs/ Sub254, Sub276, Sub298, Sub299, Sub307
	common /hhh_varXs/ Sub308, Sub309, Sub978, Sub981, Sub221
	common /hhh_varXs/ Sub986, Sub989, Sub995, Sub998, Sub312
	common /hhh_varXs/ Sub310, Sub315, Sub318, Sub327, Sub324
	common /hhh_varXs/ Sub330, Sub333, Sub336, Sub322, Sub311
	common /hhh_varXs/ Sub313, Sub316, Sub319, Sub328, Sub323
	common /hhh_varXs/ Sub331, Sub334, Sub337, Sub325, Sub1097
	common /hhh_varXs/ Sub1098, Sub1100, Sub1102, Sub1105
	common /hhh_varXs/ Sub1106, Sub1108, Sub1110, Sub23, Sub19
	common /hhh_varXs/ Sub30, Sub32, Sub26, Sub31, Sub33, Sub34
	common /hhh_varXs/ Sub18, Sub10, Sub948, Sub14, Sub959
	common /hhh_varXs/ Sub13, Sub950, Sub953, Sub956, Sub960
	common /hhh_varXs/ Sub958, Sub961, Sub952, Sub954, Sub1021
	common /hhh_varXs/ Sub1023, Sub1024, Sub1020, Sub190, Sub192
	common /hhh_varXs/ Sub194, Sub980, Sub983, Sub1009, Sub1010
	common /hhh_varXs/ Sub1054, Sub1055, Sub1057, Sub1058, Sub53
	common /hhh_varXs/ Sub56, Sub60, Sub63, Sub102, Sub106
	common /hhh_varXs/ Sub109, Sub99, Sub133, Sub136, Sub140
	common /hhh_varXs/ Sub143, Sub1004, Sub1005, Sub997, Sub1000
	common /hhh_varXs/ Sub1071, Sub1072, Sub1074, Sub1075
	common /hhh_varXs/ Sub1030, Sub1032, Sub1033, Sub1029
	common /hhh_varXs/ Sub988, Sub991, Sub1014, Sub1015, Sub1062
	common /hhh_varXs/ Sub1063, Sub1065, Sub1066, Sub314, Sub317
	common /hhh_varXs/ Sub320, Sub326, Sub329, Sub332, Sub335
	common /hhh_varXs/ Sub338, Sub347, Sub340, Sub344, Sub343
	common /hhh_varXs/ Sub345, Sub346, Sub348, Sub349, Sub342
	common /hhh_varXs/ Sub341, Sub1113, Sub1114, Sub1115
	common /hhh_varXs/ Sub1107, Sub1109, Sub1111, Sub1099
	common /hhh_varXs/ Sub1101, Sub1103, Sub1117, Sub1118
	common /hhh_varXs/ Sub1119, Sub962, Sub965, Sub969, Sub967
	common /hhh_varXs/ Sub974, Sub971, Sub970, Sub972, Sub975
	common /hhh_varXs/ Sub976, Sub977, Sub176, Sub179, Sub182
	common /hhh_varXs/ Sub183, Sub186, Sub188, Sub175, Sub171
	common /hhh_varXs/ Sub1006, Sub1080, Sub1081, Sub984
	common /hhh_varXs/ Sub1056, Sub1059, Sub57, Sub64, Sub68
	common /hhh_varXs/ Sub103, Sub110, Sub114, Sub137, Sub144
	common /hhh_varXs/ Sub148, Sub177, Sub1007, Sub173, Sub37
	common /hhh_varXs/ Sub40, Sub43, Sub49, Sub1038, Sub1039
	common /hhh_varXs/ Sub180, Sub181, Sub1041, Sub172, Sub84
	common /hhh_varXs/ Sub87, Sub90, Sub95, Sub184, Sub1083
	common /hhh_varXs/ Sub174, Sub118, Sub121, Sub124, Sub129
	common /hhh_varXs/ Sub1040, Sub1060, Sub1082, Sub160, Sub165
	common /hhh_varXs/ Sub76, Sub1008, Sub1042, Sub1084, Sub161
	common /hhh_varXs/ Sub1061, Sub166, Sub77, Sub985, Sub125
	common /hhh_varXs/ Sub45, Sub91, Sub150, Sub155, Sub70
	common /hhh_varXs/ Sub126, Sub46, Sub92, Sub151, Sub156
	common /hhh_varXs/ Sub71, Sub130, Sub50, Sub96, Sub157
	common /hhh_varXs/ Sub73, Sub152, Sub167, Sub78, Sub162
	common /hhh_varXs/ Sub111, Sub145, Sub65, Sub158, Sub74
	common /hhh_varXs/ Sub153, Sub168, Sub79, Sub163, Sub115
	common /hhh_varXs/ Sub149, Sub69, Sub159, Sub75, Sub154
	common /hhh_varXs/ Sub169, Sub80, Sub164, Sub992, Sub1064
	common /hhh_varXs/ Sub1067, Sub1011, Sub1085, Sub1086
	common /hhh_varXs/ Sub1012, Sub1043, Sub1044, Sub1046
	common /hhh_varXs/ Sub1088, Sub993, Sub1022, Sub1025
	common /hhh_varXs/ Sub1027, Sub1069, Sub1026, Sub1045
	common /hhh_varXs/ Sub1068, Sub1087, Sub1013, Sub1028
	common /hhh_varXs/ Sub1047, Sub1070, Sub1089, Sub994
	common /hhh_varXs/ Sub1016, Sub1090, Sub1091, Sub1001
	common /hhh_varXs/ Sub1073, Sub1076, Sub1002, Sub1031
	common /hhh_varXs/ Sub1034, Sub1036, Sub1078, Sub1017
	common /hhh_varXs/ Sub1048, Sub1049, Sub1051, Sub1093
	common /hhh_varXs/ Sub1035, Sub1050, Sub1077, Sub1092
	common /hhh_varXs/ Sub1003, Sub1018, Sub1037, Sub1052
	common /hhh_varXs/ Sub1079, Sub1094, Sub1126, Sub1129
	common /hhh_varXs/ Sub1127, Sub1130, Sub1131, Sub1121
	common /hhh_varXs/ Sub1123, Sub1128, Sub1122, Sub1095
	common /hhh_varXs/ Sub1096, Sub1053, Sub1019, Sub761, Sub718
	common /hhh_varXs/ Sub926, Sub898, Sub928, Sub871, Sub900
	common /hhh_varXs/ Sub438, Sub453, Sub469, Sub500, Sub520
	common /hhh_varXs/ Sub534, Sub600, Sub606, Sub646, Sub657
	common /hhh_varXs/ Sub671, Sub417, Sub738, Sub769, Sub770
	common /hhh_varXs/ Sub882, Sub427, Sub921, Sub402, Sub802
	common /hhh_varXs/ Sub804, Sub866, Sub411, Sub421, Sub424
	common /hhh_varXs/ Sub540, Sub410, Sub909, Sub912, Sub908
	common /hhh_varXs/ Sub415, Sub420, Sub403, Sub354, Sub398
	common /hhh_varXs/ Sub563, Sub771, Sub613, Sub465, Sub643
	common /hhh_varXs/ Sub581, Sub862, Sub861, Sub742, Sub594
	common /hhh_varXs/ Sub537, Sub447, Sub430, Sub737, Sub884
	common /hhh_varXs/ Sub888, Sub735, Sub887, Sub736, Sub749
	common /hhh_varXs/ Sub632, Sub622, Sub885, Sub701, Sub733
	common /hhh_varXs/ Sub748, Sub608, Sub609, Sub703, Sub879
	common /hhh_varXs/ Sub11, Sub941, Sub877, Sub12, Sub210
	common /hhh_varXs/ Sub17, Sub279, Sub282, Sub351, Sub362
	common /hhh_varXs/ Sub791, Sub874, Sub906, Sub902, Sub914
	common /hhh_varXs/ Sub919, Sub936, Sub940, Sub233, Sub236
	common /hhh_varXs/ Sub878, Sub955, Sub932, Sub880, Sub916
	common /hhh_varXs/ Sub910, Sub904, Sub899, Sub872, Sub873
	common /hhh_varXs/ Sub280, Sub264, Sub277, Sub265, Sub268
	common /hhh_varXs/ Sub278, Sub913, Sub918, Sub905, Sub901
	common /hhh_varXs/ Sub682, Sub942, Sub943, Sub524, Sub868
	common /hhh_varXs/ Sub198, Sub451, Sub731, Sub545, Sub505
	common /hhh_varXs/ Sub527, Sub533, Sub551, Sub924, Sub235
	common /hhh_varXs/ Sub238, Sub568, Sub458, Sub931, Sub708
	common /hhh_varXs/ Sub725, Sub867, Sub302, Sub903, Sub907
	common /hhh_varXs/ Sub951, Sub915, Sub920, Sub937, Sub933
	common /hhh_varXs/ Sub258, Sub262, Sub270, Sub935, Sub939
	common /hhh_varXs/ Sub886, Sub812, Sub202, Sub773, Sub806
	common /hhh_varXs/ Sub695, Sub700, Sub825, Sub809, Sub892
	common /hhh_varXs/ Sub684, Sub726, Sub203, Sub775, Sub810
	common /hhh_varXs/ Sub702, Sub705, Sub860, Sub691, Sub811
	common /hhh_varXs/ Sub894, Sub218, Sub25, Sub24, Sub321
	common /hhh_varXs/ Sub339, Sub1112, Sub1116, Sub1104
	common /hhh_varXs/ Sub1120, Sub966, Sub964, Sub963, Sub968
	common /hhh_varXs/ Sub187, Sub81, Sub178, Sub185, Sub1124
	common /hhh_varXs/ Sub1125, Sub1132, Sub401, Sub717, Sub536
	common /hhh_varXs/ Sub601, Sub639, Sub664, Sub672, Sub706
	common /hhh_varXs/ Sub746, Sub801, Sub881, Sub541, Sub543
	common /hhh_varXs/ Sub353, Sub566, Sub821, Sub724, Sub261
	common /hhh_varXs/ Sub257, Sub729, Sub428, Sub973, Sub638
	common /hhh_varXs/ Sub629, Sub925, Sub897, Sub665, Sub755
	common /hhh_varXs/ Sub815, Sub170, Sub476, Sub477, Sub945
	common /hhh_varXs/ Sub822, Sub946, pave1, pave2, pave3
	common /hhh_varXs/ pave4, pave5, pave6, pave7, pave8, pave9
	common /hhh_varXs/ pave10, pave11, pave12, pave13, pave14
	common /hhh_varXs/ pave15, pave16, pave17, pave18, pave19
	common /hhh_varXs/ pave20, pave21, pave22, pave23, pave24
	common /hhh_varXs/ pave25, pave26, pave27, pave28, pave29
	common /hhh_varXs/ pave30, pave31, pave32, pave33, pave34
	common /hhh_varXs/ pave35, pave36, pave37, pave38, pave39
	common /hhh_varXs/ pave40, pave41, pave42, pave43, pave44
	common /hhh_varXs/ pave45, pave46, pave47, pave48, pave49
	common /hhh_varXs/ pave50, pave51, pave52, pave53, pave54
	common /hhh_varXs/ pave55, pave56, pave57, pave58, pave59
	common /hhh_varXs/ pave60, pave61, pave62, pave63, pave64
	common /hhh_varXs/ pave65, pave66, pave67, pave68, pave69
	common /hhh_varXs/ pave70, pave71, pave72, pave73, pave74
	common /hhh_varXs/ pave75, pave76, pave77, pave78, pave79
	common /hhh_varXs/ pave80, pave81, pave82, pave83, pave84
	common /hhh_varXs/ pave85, pave86, pave87, pave88, pave89
	common /hhh_varXs/ pave90, pave91, pave92, pave93, pave94
	common /hhh_varXs/ pave95, pave96, pave97, pave98, pave99
	common /hhh_varXs/ pave100, pave101, pave102, pave103
	common /hhh_varXs/ pave104, pave105, pave106, pave107
	common /hhh_varXs/ pave108, pave109, pave110, pave111
	common /hhh_varXs/ pave112, pave113, pave114, pave115
	common /hhh_varXs/ pave116, pave117, pave118, pave119
	common /hhh_varXs/ pave120, pave121, pave122, pave123
	common /hhh_varXs/ pave124, pave125, pave126, pave127
	common /hhh_varXs/ pave128, pave129, pave130, pave131
	common /hhh_varXs/ pave132, pave133, pave134, pave135
	common /hhh_varXs/ pave136, pave137, pave138, pave139
	common /hhh_varXs/ pave140, pave141, pave142, pave143
	common /hhh_varXs/ pave144, pave145, pave146, pave147
	common /hhh_varXs/ pave148, pave149, pave150, pave151
	common /hhh_varXs/ pave152, pave153, pave154, pave155
	common /hhh_varXs/ pave156, pave157, pave158, pave159
	common /hhh_varXs/ pave160, pave161, pave162, pave163
	common /hhh_varXs/ pave164, pave165, pave166, pave167
	common /hhh_varXs/ pave168, pave169, pave170, pave171
	common /hhh_varXs/ pave172, pave173, pave174, pave175
	common /hhh_varXs/ pave176, pave177, pave178, pave179
	common /hhh_varXs/ pave180, pave181, pave182, pave183
	common /hhh_varXs/ pave184, pave185, pave186, pave187
	common /hhh_varXs/ pave188, pave189, pave190, pave191
	common /hhh_varXs/ pave192, pave193, pave194, pave195
	common /hhh_varXs/ pave196, pave197, pave198, pave199
	common /hhh_varXs/ pave200, pave201, pave202, pave203
	common /hhh_varXs/ pave204, pave205, pave206, pave207
	common /hhh_varXs/ pave208, pave209, pave210, pave211
	common /hhh_varXs/ pave212, pave213, pave214, pave215
	common /hhh_varXs/ pave216, pave217, pave218, pave219
	common /hhh_varXs/ pave220, pave221, pave222, pave223
	common /hhh_varXs/ pave224

	integer seq(2), Hel(3)
	common /hhh_helind/ seq, Hel

	integer Cha4, Cha5, Cha6, Gen4, Neu4, Neu5, Neu6, Sfe4, Sfe5
	integer Sfe6
	common /hhh_indices/ Cha4, Cha5, Cha6, Gen4, Neu4, Neu5, Neu6
	common /hhh_indices/ Sfe4, Sfe5, Sfe6

	ComplexType Ctree(1), Cloop(1)
	common /hhh_formfactors/ Ctree, Cloop

#endif
