#if 0
* huuSM-vars.h
* variable declarations
* generated by FormCalc 8.4 on 30-Apr-2014 7:28
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "huuSM-renconst.h"

	ComplexType Opt1(3), Sub47, Sub23, Sub60, Sub32, Sub42, Sub43
	ComplexType Sub30, Sub28, Sub31, Sub41, Sub11, Sub17
	ComplexType Sub20(3), Sub13(3), Sub16(3), Sub21(3), Sub48
	ComplexType Sub54, Sub44, Sub1(3), Sub2(3), Sub53, Sub4(3)
	ComplexType Sub12, Sub15(3), Sub6(3), Sub7(3), pave1(Ncc,3)
	ComplexType pave2, pave3(Ncc), pave4(Ncc), pave5, pave6(Ncc)
	ComplexType pave7(Ncc), pave8(3), pave9(Ncc,3)
	common /huuSM_varXs/ Opt1, Sub47, Sub23, Sub60, Sub32, Sub42
	common /huuSM_varXs/ Sub43, Sub30, Sub28, Sub31, Sub41
	common /huuSM_varXs/ Sub11, Sub17, Sub20, Sub13, Sub16
	common /huuSM_varXs/ Sub21, Sub48, Sub54, Sub44, Sub1, Sub2
	common /huuSM_varXs/ Sub53, Sub4, Sub12, Sub15, Sub6, Sub7
	common /huuSM_varXs/ pave1, pave2, pave3, pave4, pave5
	common /huuSM_varXs/ pave6, pave7, pave8, pave9

	ComplexType F1, F2
	ComplexType Sub57, Sub50, Sub34, Sub35, Sub46, Sub55, Sub33
	ComplexType Sub45, Sub25, Sub19, Sub40, Sub29, Sub37, Sub36
	ComplexType Sub52, Sub59, Sub63, Sub65, Sub64, Sub51, Sub58
	ComplexType Sub62, Sub14(3), Sub18(3)
	ComplexType Sub3(3), Sub22(3), Sub5(3)
	ComplexType Sub8(3), Sub9(3), Sub10(3)
	ComplexType Sub49, Sub27, Sub39, Sub38, Sub67, Sub24, Sub26
	ComplexType Sub66, Sub56, Sub61
	common /huuSM_varXh/ F1, F2, Sub57, Sub50, Sub34, Sub35
	common /huuSM_varXh/ Sub46, Sub55, Sub33, Sub45, Sub25
	common /huuSM_varXh/ Sub19, Sub40, Sub29, Sub37, Sub36
	common /huuSM_varXh/ Sub52, Sub59, Sub63, Sub65, Sub64
	common /huuSM_varXh/ Sub51, Sub58, Sub62, Sub14, Sub18, Sub3
	common /huuSM_varXh/ Sub22, Sub5, Sub8, Sub9, Sub10, Sub49
	common /huuSM_varXh/ Sub27, Sub39, Sub38, Sub67, Sub24
	common /huuSM_varXh/ Sub26, Sub66, Sub56, Sub61

	integer seq(2), Hel(3)
	common /huuSM_helind/ seq, Hel

	integer Gen4
	common /huuSM_indices/ Gen4

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /huuSM_formfactors/ Ctree, Cloop, MatSUN

#endif
