#if 0
* huuSM-vars.h
* variable declarations
* generated by FormCalc 9.6 (7 Mar 2018) on 13-Mar-2018 8:19
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "huuSM-RenConst.h.F"

#else

#include "Decay.h"
#include "huuSM-RenConst.h.F"

	ComplexType AaB03, AaB05(3), AaB07, AaC0i1(Ncc,3)
	ComplexType AaC0i2(Ncc), AaC0i4(Ncc), AaC0i6(Ncc)
	ComplexType AaC0i8(Ncc), AaC0i9(Ncc,3), Sub2, Sub3, Sub4(3)
	ComplexType Sub5(3), Sub9(3), Sub10(3), Sub11, Sub12(3)
	ComplexType Sub14(3), Sub15(3), Sub16(3), Sub17(3), Sub18(3)
	ComplexType Sub19(3), Sub23(3), Sub24(3), Sub26, Sub27
	ComplexType Sub28, Sub29(3), Sub30(3), Sub32, Sub35, Sub38
	ComplexType Sub45, Sub46, Sub47, Sub48, Sub50, Sub51, Sub52
	ComplexType Sub53, Sub54, Sub55, Sub58, Sub59, Sub60, Sub61
	ComplexType Sub62, Sub63, Sub64, Sub65, Sub66, Sub67, Sub68
	ComplexType Sub69, Sub70, Sub71, Sub72, Sub73, Sub76, Sub77
	ComplexType Sub78, Sub79, Sub83, Sub84, Sub85, Sub86, Sub39
	ComplexType Sub40, Sub41, Sub42, Sub43, Sub44
	common /huuSM_varXs/ AaB03, AaB05, AaB07, AaC0i1, AaC0i2
	common /huuSM_varXs/ AaC0i4, AaC0i6, AaC0i8, AaC0i9, Sub2
	common /huuSM_varXs/ Sub3, Sub4, Sub5, Sub9, Sub10, Sub11
	common /huuSM_varXs/ Sub12, Sub14, Sub15, Sub16, Sub17
	common /huuSM_varXs/ Sub18, Sub19, Sub23, Sub24, Sub26
	common /huuSM_varXs/ Sub27, Sub28, Sub29, Sub30, Sub32
	common /huuSM_varXs/ Sub35, Sub38, Sub45, Sub46, Sub47
	common /huuSM_varXs/ Sub48, Sub50, Sub51, Sub52, Sub53
	common /huuSM_varXs/ Sub54, Sub55, Sub58, Sub59, Sub60
	common /huuSM_varXs/ Sub61, Sub62, Sub63, Sub64, Sub65
	common /huuSM_varXs/ Sub66, Sub67, Sub68, Sub69, Sub70
	common /huuSM_varXs/ Sub71, Sub72, Sub73, Sub76, Sub77
	common /huuSM_varXs/ Sub78, Sub79, Sub83, Sub84, Sub85
	common /huuSM_varXs/ Sub86, Sub39, Sub40, Sub41, Sub42
	common /huuSM_varXs/ Sub43, Sub44

	ComplexType F1, F2
	ComplexType Sub1, Sub6(3), Sub7(3), Sub8, Sub13(3), Sub20(3)
	ComplexType Sub21(3), Sub22(3), Sub25(3), Sub31(3), Sub33
	ComplexType Sub34, Sub36, Sub37, Sub49, Sub56, Sub57, Sub74
	ComplexType Sub75, Sub80, Sub81, Sub82, Sub87, Sub88, Sub89
	ComplexType Sub90
	common /huuSM_varXh/ F1, F2, Sub1, Sub6, Sub7, Sub8, Sub13
	common /huuSM_varXh/ Sub20, Sub21, Sub22, Sub25, Sub31
	common /huuSM_varXh/ Sub33, Sub34, Sub36, Sub37, Sub49
	common /huuSM_varXh/ Sub56, Sub57, Sub74, Sub75, Sub80
	common /huuSM_varXh/ Sub81, Sub82, Sub87, Sub88, Sub89, Sub90

	integer Gen4
	common /huuSM_indices/ Gen4

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /huuSM_formfactors/ Ctree, Cloop, MatSUN

#endif

