#if 0
* huuSM-vars.h
* variable declarations
* generated by FormCalc 9.7 (3 Aug 2018) on 3-Aug-2018 10:00
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "huuSM-RenConst.h.F"

#else

#include "Decay.h"
#include "huuSM-RenConst.h.F"

	ComplexType B0i1, B0i2(3), B0i3, C0i1(Ncc,3), C0i2(Ncc)
	ComplexType C0i3(Ncc), C0i4(Ncc), C0i5(Ncc), C0i6(Ncc,3)
	ComplexType Sub2, Sub3, Sub4(3), Sub5(3), Sub9(3), Sub10(3)
	ComplexType Sub11, Sub12(3), Sub14(3), Sub15(3), Sub16(3)
	ComplexType Sub17(3), Sub18(3), Sub19(3), Sub23(3), Sub24(3)
	ComplexType Sub26, Sub27, Sub28, Sub29(3), Sub30(3), Sub32
	ComplexType Sub35, Sub38, Sub39, Sub40, Sub41, Sub42, Sub43
	ComplexType Sub44, Sub45, Sub46, Sub47, Sub54, Sub55, Sub56
	ComplexType Sub57, Sub59, Sub60, Sub61, Sub62, Sub63, Sub64
	ComplexType Sub68, Sub69, Sub70, Sub71, Sub72, Sub76, Sub77
	ComplexType Sub78, Sub79, Sub80, Sub82, Sub83, Sub84, Sub85
	ComplexType Sub86, Sub87, Sub88, Sub48, Sub49, Sub50, Sub51
	ComplexType Sub52, Sub53
	common /huuSM_varXs/ B0i1, B0i2, B0i3, C0i1, C0i2, C0i3, C0i4
	common /huuSM_varXs/ C0i5, C0i6, Sub2, Sub3, Sub4, Sub5
	common /huuSM_varXs/ Sub9, Sub10, Sub11, Sub12, Sub14, Sub15
	common /huuSM_varXs/ Sub16, Sub17, Sub18, Sub19, Sub23
	common /huuSM_varXs/ Sub24, Sub26, Sub27, Sub28, Sub29
	common /huuSM_varXs/ Sub30, Sub32, Sub35, Sub38, Sub39
	common /huuSM_varXs/ Sub40, Sub41, Sub42, Sub43, Sub44
	common /huuSM_varXs/ Sub45, Sub46, Sub47, Sub54, Sub55
	common /huuSM_varXs/ Sub56, Sub57, Sub59, Sub60, Sub61
	common /huuSM_varXs/ Sub62, Sub63, Sub64, Sub68, Sub69
	common /huuSM_varXs/ Sub70, Sub71, Sub72, Sub76, Sub77
	common /huuSM_varXs/ Sub78, Sub79, Sub80, Sub82, Sub83
	common /huuSM_varXs/ Sub84, Sub85, Sub86, Sub87, Sub88
	common /huuSM_varXs/ Sub48, Sub49, Sub50, Sub51, Sub52, Sub53

	ComplexType F1, F2
	ComplexType Sub1, Sub6(3), Sub7(3), Sub8, Sub13(3), Sub20(3)
	ComplexType Sub21(3), Sub22(3), Sub25(3), Sub31(3), Sub33
	ComplexType Sub34, Sub36, Sub37, Sub58, Sub65, Sub66, Sub67
	ComplexType Sub73, Sub74, Sub75, Sub81, Sub89, Sub90, Sub91
	ComplexType Sub92, Sub93
	common /huuSM_varXh/ F1, F2, Sub1, Sub6, Sub7, Sub8, Sub13
	common /huuSM_varXh/ Sub20, Sub21, Sub22, Sub25, Sub31
	common /huuSM_varXh/ Sub33, Sub34, Sub36, Sub37, Sub58
	common /huuSM_varXh/ Sub65, Sub66, Sub67, Sub73, Sub74
	common /huuSM_varXh/ Sub75, Sub81, Sub89, Sub90, Sub91
	common /huuSM_varXh/ Sub92, Sub93

	integer Gen4
	common /huuSM_indices/ Gen4

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /huuSM_formfactors/ Ctree, Cloop, MatSUN

#endif

