#if 0
* hgagaSM-vars.h
* variable declarations
* generated by FormCalc 9.6 (7 Mar 2018) on 13-Mar-2018 8:18
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType AaB02, AaB03(3), AaB05(3), AaB07(3), AaC0i1(Ncc)
	ComplexType AaC0i4(Ncc,3), AaC0i6(Ncc,3), AaC0i8(Ncc,3)
	ComplexType Sub1(3), Sub2(3), Sub4(3), Sub5(3), Sub7(3)
	ComplexType Sub8(3), Sub10, Sub12, Sub13
	common /hgagaSM_varXs/ AaB02, AaB03, AaB05, AaB07, AaC0i1
	common /hgagaSM_varXs/ AaC0i4, AaC0i6, AaC0i8, Sub1, Sub2
	common /hgagaSM_varXs/ Sub4, Sub5, Sub7, Sub8, Sub10, Sub12
	common /hgagaSM_varXs/ Sub13

	ComplexType Pair1, Pair2, Pair3, Sub11, Abb1, Abb2, Abb3
	ComplexType Abb4, Sub3(3), Sub6(3), Sub9(3), Sub14
	common /hgagaSM_varXh/ Pair1, Pair2, Pair3, Sub11, Abb1, Abb2
	common /hgagaSM_varXh/ Abb3, Abb4, Sub3, Sub6, Sub9, Sub14

	integer Gen4
	common /hgagaSM_indices/ Gen4

	ComplexType Cloop(1)
	common /hgagaSM_formfactors/ Cloop

#endif

