#if 0
* hgagaSM-vars.h
* variable declarations
* generated by FormCalc 9.7 (3 Aug 2018) on 3-Aug-2018 10:00
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType B0i1, B0i2(3), B0i3(3), B0i4(3), C0i1(Ncc)
	ComplexType C0i2(Ncc,3), C0i3(Ncc,3), C0i4(Ncc,3), Sub1(3)
	ComplexType Sub2(3), Sub4(3), Sub5(3), Sub7(3), Sub8(3)
	ComplexType Sub10, Sub12, Sub13
	common /hgagaSM_varXs/ B0i1, B0i2, B0i3, B0i4, C0i1, C0i2
	common /hgagaSM_varXs/ C0i3, C0i4, Sub1, Sub2, Sub4, Sub5
	common /hgagaSM_varXs/ Sub7, Sub8, Sub10, Sub12, Sub13

	ComplexType Pair1, Pair2, Pair3, Sub11, Abb1, Abb2, Abb3
	ComplexType Abb4, Sub3(3), Sub6(3), Sub9(3), Sub14
	common /hgagaSM_varXh/ Pair1, Pair2, Pair3, Sub11, Abb1, Abb2
	common /hgagaSM_varXh/ Abb3, Abb4, Sub3, Sub6, Sub9, Sub14

	integer Gen4
	common /hgagaSM_indices/ Gen4

	ComplexType Cloop(1)
	common /hgagaSM_formfactors/ Cloop

#endif

