#! /bin/sh

p="perl `dirname $0`/multinumericsloop.pl -p"

$p multiT11234mtmtmtmt0.input || exit 1
$p multiT11234ms1ms1ms1ms10.input || exit 1
$p multiT11234ms2ms2ms2ms20.input || exit 1

$p multiT11234ms2ms2ms1ms20.input || exit 1
$p multiT11234ms1ms1ms2ms10.input || exit 1

$p multiT11234ms1ms1ms1mtmg.input || exit 1
$p multiT11234ms1ms1ms2mtmg.input || exit 1
$p multiT11234ms2ms2ms1mtmg.input || exit 1
$p multiT11234ms2ms2ms2mtmg.input || exit 1
$p multiT11234mtmtmtms1mg.input || exit 1
$p multiT11234mtmtmtms2mg.input || exit 1

echo "Topologies T11234 done"

$p multiT12340mtmt0.input || exit 1

$p multiT12340mtms1mg.input || exit 1
$p multiT12340mtms2mg.input || exit 1

$p multiT1234ms1ms1ms10.input || exit 1
$p multiT1234ms2ms2ms20.input || exit 1
$p multiT1234mtmtmt0.input || exit 1

$p multiT1234ms1ms2ms10.input || exit 1
$p multiT1234ms2ms1ms20.input || exit 1

$p multiT1234ms1ms1mtmg.input || exit 1
$p multiT1234ms1ms2mtmg.input || exit 1
$p multiT1234ms2ms1mtmg.input || exit 1
$p multiT1234ms2ms2mtmg.input || exit 1
$p multiT1234mtmtms1mg.input || exit 1
$p multiT1234mtmtms2mg.input || exit 1

echo "Topologies T1234 done"

$p multiT12345mtmt0mtmt.input || exit 1
$p multiT12345ms1ms10ms1ms1.input || exit 1
$p multiT12345ms2ms20ms2ms2.input || exit 1

#$p multiT12345ms1ms20ms1ms2.input || exit 1
$p multiT12345ms2ms10ms2ms1.input || exit 1

$p multiT12345ms1ms1mgmtmt.input || exit 1
#$p multiT12345ms1ms2mgmtmt.input || exit 1
$p multiT12345ms2ms1mgmtmt.input || exit 1
$p multiT12345ms2ms2mgmtmt.input || exit 1

echo "Topologies T12345 done"

$p multiT234ms1mtmg.input || exit 1
$p multiT234ms2mtmg.input || exit 1

echo "Topologies T234 done"

