#! /bin/sh
PERL_PATH=`which perl | perl -e 'while(<>){\$_=~s/\\//\\\\\//g;print}'`
if [ -z "$PERL_PATH" ]
then
 echo "Could not find perl on your system!"
 exit
fi
OLD_PERL="\\/usr\\/bin\\/perl"
echo "path for perl: " `which perl`
perl -pi -e "s/$OLD_PERL/$PERL_PATH/" loop/*.pl general/*.pl
MATH_PATH=`which math | perl -e 'while(<>){\$_=~s/\\//\\\\\//g;print}'`
if [ -z "$MATH_PATH" ]
then
 echo "Could not find Mathematica on your system!"
 exit
fi
OLD_MATH="\\/old\\/math\\/path"
echo "path for Mathematica: " `which math`
perl -pi -e "s/$OLD_MATH/$MATH_PATH/" loop/perlsrc/mathlaunch.pl general/perlsrc/mathlaunch.pl
echo "Entering Cuba-3.2 directory. Compiling Cuba."
cd Cuba-3.2
./configure
make
echo "Leaving Cuba directory."
echo "Entering loop/src/util directory."
cd ../loop/src/util
echo "Compiling sobol random sampler..."
COMPILE_SOBOL=`gcc -O -c sobol.hh sobol.cc`
if [ "$COMPILE_SOBOL" != "" ]
then
    echo "Could not compile sobol random sampler. Retry manually in loop/src/util directory."
else 
    echo "Done."
fi
echo "Dryrun. Compilation of integration files. Please wait (takes around 5 min)."
cd ../../
perl makedryrun.pl
echo "Finished install."
