#! /bin/sh

IFS=$' \t\n]/,'
declare -a m

getintegral() {
  while read dir file dfk1 m0 dfk2 m1 dfk3 m2 dfk4 m3 dfk5 m4 rest ; do
    echo dir=$dir file=$file m1=$m1 m2=$m2 m3=$m3 m4=$m4 m5=$m5
    m=(0 0 0 0 0)
    code=${dir##*m}00000
    for i in 0 1 2 3 4 ; do
      eval m[${code:$i:1}]=\$m$i
    done
    eval perl helpmultiSB.pl $dir $name \$${m[1]} \$${m[2]} \$${m[3]} \$${m[4]} \$MHiggs21 \$MHiggs22 \$MA0
  done
}



cat integrals.tab | getintegral

