#if 0
* hddSM-vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Feb-2015 17:19
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hddSM-renconst.h"

	ComplexType Sub31, Sub82, Sub73, Sub76, Sub85, Sub47, Sub32
	ComplexType Sub81, Sub43, Sub59, Sub66, Sub57, Sub96, Sub54
	ComplexType Sub67, Sub24, Sub27, Sub1, Sub26, Sub15, Sub52
	ComplexType Sub56, Sub38, Sub45, Sub58, Sub46, Sub48, Sub55
	ComplexType Sub84, Sub87, Sub95, Sub77, Sub39, Sub92, Sub74
	ComplexType Sub40, Sub53, Sub61, Sub51, Sub37, Sub42, Sub94
	ComplexType Sub83, Sub86, Sub25, Sub2, Sub93, Sub68, Sub3(3)
	ComplexType Sub11(3), Sub13(3), Sub28(3), Sub21(3), Sub22(3)
	ComplexType Sub17(3), Sub29(3), Sub5(3), Sub12, Sub62, Sub60
	ComplexType Sub10, Sub75, Sub78, Sub16(3), Sub8(3), Sub9(3)
	ComplexType Sub4(3), Sub44, pave1(Ncc,3), pave2(Ncc)
	ComplexType pave3(Ncc), pave4(Ncc), pave5(Ncc), pave6, pave7
	ComplexType pave8(3), pave9(Ncc,3)
	common /hddSM_varXs/ Sub31, Sub82, Sub73, Sub76, Sub85, Sub47
	common /hddSM_varXs/ Sub32, Sub81, Sub43, Sub59, Sub66
	common /hddSM_varXs/ Sub57, Sub96, Sub54, Sub67, Sub24
	common /hddSM_varXs/ Sub27, Sub1, Sub26, Sub15, Sub52, Sub56
	common /hddSM_varXs/ Sub38, Sub45, Sub58, Sub46, Sub48
	common /hddSM_varXs/ Sub55, Sub84, Sub87, Sub95, Sub77
	common /hddSM_varXs/ Sub39, Sub92, Sub74, Sub40, Sub53
	common /hddSM_varXs/ Sub61, Sub51, Sub37, Sub42, Sub94
	common /hddSM_varXs/ Sub83, Sub86, Sub25, Sub2, Sub93, Sub68
	common /hddSM_varXs/ Sub3, Sub11, Sub13, Sub28, Sub21, Sub22
	common /hddSM_varXs/ Sub17, Sub29, Sub5, Sub12, Sub62, Sub60
	common /hddSM_varXs/ Sub10, Sub75, Sub78, Sub16, Sub8, Sub9
	common /hddSM_varXs/ Sub4, Sub44, pave1, pave2, pave3, pave4
	common /hddSM_varXs/ pave5, pave6, pave7, pave8, pave9

	ComplexType F1, F2
	ComplexType Sub90, Sub89, Sub71, Sub70, Sub63, Sub69, Sub79
	ComplexType Sub97, Sub41, Sub49, Sub72, Sub91, Sub64, Sub99
	ComplexType Sub50, Sub100, Sub35, Sub34, Sub33, Sub88, Sub80
	ComplexType Sub98, Sub7, Sub65, Sub20(3)
	ComplexType Sub23(3), Sub101, Sub36, Sub14(3)
	ComplexType Sub18(3), Sub30(3), Sub6(3)
	ComplexType Sub19(3)
	common /hddSM_varXh/ F1, F2, Sub90, Sub89, Sub71, Sub70
	common /hddSM_varXh/ Sub63, Sub69, Sub79, Sub97, Sub41
	common /hddSM_varXh/ Sub49, Sub72, Sub91, Sub64, Sub99
	common /hddSM_varXh/ Sub50, Sub100, Sub35, Sub34, Sub33
	common /hddSM_varXh/ Sub88, Sub80, Sub98, Sub7, Sub65, Sub20
	common /hddSM_varXh/ Sub23, Sub101, Sub36, Sub14, Sub18
	common /hddSM_varXh/ Sub30, Sub6, Sub19

	integer seq(2), Hel(3)
	common /hddSM_helind/ seq, Hel

	integer Gen4
	common /hddSM_indices/ Gen4

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /hddSM_formfactors/ Ctree, Cloop, MatSUN

#endif
