#if 0
* hddSM-vars.h
* variable declarations
* generated by FormCalc 8.4 on 30-Apr-2014 7:28
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hddSM-renconst.h"

	ComplexType Opt1(3), Sub46, Sub22, Sub59, Sub35, Sub42, Sub43
	ComplexType Sub33, Sub30, Sub34, Sub41, Sub14, Sub7
	ComplexType Sub19(3), Sub16(3), Sub20(3), Sub9(3), Sub47
	ComplexType Sub53, Sub44, Sub1(3), Sub2(3), Sub4(3), Sub52
	ComplexType Sub8(3), Sub15(3), Sub11(3), Sub12(3)
	ComplexType pave1(Ncc,3), pave2, pave3(Ncc), pave4
	ComplexType pave5(Ncc), pave6(Ncc), pave7(Ncc), pave8(3)
	ComplexType pave9(Ncc,3)
	common /hddSM_varXs/ Opt1, Sub46, Sub22, Sub59, Sub35, Sub42
	common /hddSM_varXs/ Sub43, Sub33, Sub30, Sub34, Sub41
	common /hddSM_varXs/ Sub14, Sub7, Sub19, Sub16, Sub20, Sub9
	common /hddSM_varXs/ Sub47, Sub53, Sub44, Sub1, Sub2, Sub4
	common /hddSM_varXs/ Sub52, Sub8, Sub15, Sub11, Sub12, pave1
	common /hddSM_varXs/ pave2, pave3, pave4, pave5, pave6
	common /hddSM_varXs/ pave7, pave8, pave9

	ComplexType F1, F2
	ComplexType Sub56, Sub49, Sub37, Sub38, Sub60, Sub45, Sub54
	ComplexType Sub36, Sub26, Sub24, Sub18, Sub28, Sub31, Sub40
	ComplexType Sub39, Sub51, Sub58, Sub62, Sub32, Sub64, Sub63
	ComplexType Sub50, Sub57, Sub61, Sub13(3)
	ComplexType Sub17(3), Sub3(3), Sub5(3)
	ComplexType Sub6(3), Sub10(3), Sub48, Sub66
	ComplexType Sub29, Sub27, Sub23, Sub25, Sub65, Sub55
	ComplexType Sub21(3)
	common /hddSM_varXh/ F1, F2, Sub56, Sub49, Sub37, Sub38
	common /hddSM_varXh/ Sub60, Sub45, Sub54, Sub36, Sub26
	common /hddSM_varXh/ Sub24, Sub18, Sub28, Sub31, Sub40
	common /hddSM_varXh/ Sub39, Sub51, Sub58, Sub62, Sub32
	common /hddSM_varXh/ Sub64, Sub63, Sub50, Sub57, Sub61
	common /hddSM_varXh/ Sub13, Sub17, Sub3, Sub5, Sub6, Sub10
	common /hddSM_varXh/ Sub48, Sub66, Sub29, Sub27, Sub23
	common /hddSM_varXh/ Sub25, Sub65, Sub55, Sub21

	integer seq(2), Hel(3)
	common /hddSM_helind/ seq, Hel

	integer Gen4
	common /hddSM_indices/ Gen4

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /hddSM_formfactors/ Ctree, Cloop, MatSUN

#endif
