#if 0
* hddSM-vars.h
* variable declarations
* generated by FormCalc 9.6 (7 Mar 2018) on 13-Mar-2018 8:19
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "hddSM-RenConst.h.F"

#else

#include "Decay.h"
#include "hddSM-RenConst.h.F"

	ComplexType AaB04, AaB07(3), AaB09, AaC0i1(Ncc,3)
	ComplexType AaC0i2(Ncc), AaC0i3(Ncc), AaC0i5(Ncc)
	ComplexType AaC0i6(Ncc,3), AaC0i8(Ncc), Sub2(3), Sub3(3)
	ComplexType Sub4(3), Sub5(3), Sub6, Sub7(3), Sub8, Sub9(3)
	ComplexType Sub11(3), Sub12(3), Sub13(3), Sub14(3), Sub20
	ComplexType Sub21, Sub22(3), Sub23(3), Sub24(3), Sub26(3)
	ComplexType Sub27(3), Sub28(3), Sub29(3), Sub30(3), Sub31(3)
	ComplexType Sub32, Sub33(3), Sub37, Sub40, Sub43, Sub44
	ComplexType Sub45, Sub46, Sub47, Sub48, Sub49, Sub50, Sub51
	ComplexType Sub52, Sub59, Sub60, Sub61, Sub62, Sub64, Sub65
	ComplexType Sub66, Sub67, Sub68, Sub69, Sub73, Sub74, Sub75
	ComplexType Sub76, Sub77, Sub81, Sub82, Sub83, Sub84, Sub85
	ComplexType Sub87, Sub88, Sub89, Sub90, Sub91, Sub92, Sub93
	ComplexType Sub53, Sub54, Sub55, Sub56, Sub57, Sub58
	common /hddSM_varXs/ AaB04, AaB07, AaB09, AaC0i1, AaC0i2
	common /hddSM_varXs/ AaC0i3, AaC0i5, AaC0i6, AaC0i8, Sub2
	common /hddSM_varXs/ Sub3, Sub4, Sub5, Sub6, Sub7, Sub8
	common /hddSM_varXs/ Sub9, Sub11, Sub12, Sub13, Sub14, Sub20
	common /hddSM_varXs/ Sub21, Sub22, Sub23, Sub24, Sub26
	common /hddSM_varXs/ Sub27, Sub28, Sub29, Sub30, Sub31
	common /hddSM_varXs/ Sub32, Sub33, Sub37, Sub40, Sub43
	common /hddSM_varXs/ Sub44, Sub45, Sub46, Sub47, Sub48
	common /hddSM_varXs/ Sub49, Sub50, Sub51, Sub52, Sub59
	common /hddSM_varXs/ Sub60, Sub61, Sub62, Sub64, Sub65
	common /hddSM_varXs/ Sub66, Sub67, Sub68, Sub69, Sub73
	common /hddSM_varXs/ Sub74, Sub75, Sub76, Sub77, Sub81
	common /hddSM_varXs/ Sub82, Sub83, Sub84, Sub85, Sub87
	common /hddSM_varXs/ Sub88, Sub89, Sub90, Sub91, Sub92
	common /hddSM_varXs/ Sub93, Sub53, Sub54, Sub55, Sub56
	common /hddSM_varXs/ Sub57, Sub58

	ComplexType F1, F2
	ComplexType Sub1, Sub10(3), Sub15(3), Sub16(3), Sub17(3)
	ComplexType Sub18(3), Sub19, Sub25(3), Sub34(3), Sub35(3)
	ComplexType Sub36(3), Sub38, Sub39, Sub41, Sub42, Sub63
	ComplexType Sub70, Sub71, Sub72, Sub78, Sub79, Sub80, Sub86
	ComplexType Sub94, Sub95, Sub96, Sub97, Sub98
	common /hddSM_varXh/ F1, F2, Sub1, Sub10, Sub15, Sub16, Sub17
	common /hddSM_varXh/ Sub18, Sub19, Sub25, Sub34, Sub35
	common /hddSM_varXh/ Sub36, Sub38, Sub39, Sub41, Sub42
	common /hddSM_varXh/ Sub63, Sub70, Sub71, Sub72, Sub78
	common /hddSM_varXh/ Sub79, Sub80, Sub86, Sub94, Sub95
	common /hddSM_varXh/ Sub96, Sub97, Sub98

	integer Gen4
	common /hddSM_indices/ Gen4

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /hddSM_formfactors/ Ctree, Cloop, MatSUN

#endif

