#if 0
* hgaZSM-vars.h
* variable declarations
* generated by FormCalc 9.6 (7 Mar 2018) on 13-Mar-2018 8:18
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "hgaZSM-RenConst.h.F"

#else

#include "Decay.h"
#include "hgaZSM-RenConst.h.F"

	ComplexType AaB01, AaB02, AaB04, AaB05(3), AaB07(3), AaB09(3)
	ComplexType AaC0i3(Ncc), AaC0i6(Ncc,3), AaC0i8(Ncc,3)
	ComplexType AaC0i10(Ncc,3), Sub1(3), Sub2(3), Sub4(3)
	ComplexType Sub5(3), Sub7(3), Sub8(3), Sub10, Sub11, Sub15
	ComplexType Sub18, Sub19, Sub20, Sub21
	common /hgaZSM_varXs/ AaB01, AaB02, AaB04, AaB05, AaB07
	common /hgaZSM_varXs/ AaB09, AaC0i3, AaC0i6, AaC0i8, AaC0i10
	common /hgaZSM_varXs/ Sub1, Sub2, Sub4, Sub5, Sub7, Sub8
	common /hgaZSM_varXs/ Sub10, Sub11, Sub15, Sub18, Sub19
	common /hgaZSM_varXs/ Sub20, Sub21

	ComplexType Eps1, Pair1, Pair2, Pair3, Abb1, Abb2, Abb3, Abb4
	ComplexType Abb5, Abb6, Abb7, Abb8, Abb9, Abb10, Sub3(3)
	ComplexType Sub6(3), Sub9(3), Sub12, Sub13, Sub14, Sub16
	ComplexType Sub17, Sub22, Sub23
	common /hgaZSM_varXh/ Eps1, Pair1, Pair2, Pair3, Abb1, Abb2
	common /hgaZSM_varXh/ Abb3, Abb4, Abb5, Abb6, Abb7, Abb8
	common /hgaZSM_varXh/ Abb9, Abb10, Sub3, Sub6, Sub9, Sub12
	common /hgaZSM_varXh/ Sub13, Sub14, Sub16, Sub17, Sub22
	common /hgaZSM_varXh/ Sub23

	integer Gen4
	common /hgaZSM_indices/ Gen4

	ComplexType Cloop(1)
	common /hgaZSM_formfactors/ Cloop

#endif

