#if 0
* hgg-vars.h
* variable declarations
* generated by FormCalc 9.6 (7 Mar 2018) on 13-Mar-2018 8:19
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType AaB01(6), AaB03(6), AaB05(3), AaB07(3)
	ComplexType AaC0i2(Ncc,6), AaC0i4(Ncc,6), AaC0i6(Ncc,3)
	ComplexType AaC0i8(Ncc,3), Sub1(6), Sub2(6), Sub4(3)
	ComplexType Sub5(3,3), Sub6(6,3,3), Sub7(3), Sub8(3,3)
	ComplexType Sub9(6,3,3), Sub10(6,3,3), Sub11(3), Sub12(3,3)
	ComplexType Sub13(6,3,3), Sub14(3), Sub15(3,3), Sub16(6,3,3)
	ComplexType Sub17(6,3,3), Sub18(6,3,3), Sub19(3,3)
	ComplexType Sub20(3,3), Sub21(6,3,3), Sub22(6,3,3), Sub23(6)
	ComplexType Sub24(6), Sub26(3), Sub27(3,3), Sub28(6,3,3)
	ComplexType Sub29(3), Sub30(3,3), Sub31(6,3,3), Sub32(6,3,3)
	ComplexType Sub33(3), Sub34(3,3), Sub35(6,3,3), Sub36(3)
	ComplexType Sub37(3,3), Sub38(6,3,3), Sub39(6,3,3)
	ComplexType Sub40(6,3,3), Sub41(3,3), Sub42(3,3)
	ComplexType Sub43(6,3,3), Sub44(6,3,3), Sub45(3), Sub46(3)
	ComplexType Sub48(3), Sub49(3), Sub50(3), Sub52(3), Sub53(3)
	ComplexType Sub54(3), Sub55(3), Sub56(3), Sub57(3), Sub58(3)
	ComplexType Sub60(3), Sub61(3), Sub62(3), Sub63(3), Sub64(3)
	ComplexType Sub65(3), Sub66(3), Sub67(3), Sub68(3), Sub69(3)
	ComplexType Sub70(3), Sub71(3)
	common /hgg_varXs/ AaB01, AaB03, AaB05, AaB07, AaC0i2, AaC0i4
	common /hgg_varXs/ AaC0i6, AaC0i8, Sub1, Sub2, Sub4, Sub5
	common /hgg_varXs/ Sub6, Sub7, Sub8, Sub9, Sub10, Sub11
	common /hgg_varXs/ Sub12, Sub13, Sub14, Sub15, Sub16, Sub17
	common /hgg_varXs/ Sub18, Sub19, Sub20, Sub21, Sub22, Sub23
	common /hgg_varXs/ Sub24, Sub26, Sub27, Sub28, Sub29, Sub30
	common /hgg_varXs/ Sub31, Sub32, Sub33, Sub34, Sub35, Sub36
	common /hgg_varXs/ Sub37, Sub38, Sub39, Sub40, Sub41, Sub42
	common /hgg_varXs/ Sub43, Sub44, Sub45, Sub46, Sub48, Sub49
	common /hgg_varXs/ Sub50, Sub52, Sub53, Sub54, Sub55, Sub56
	common /hgg_varXs/ Sub57, Sub58, Sub60, Sub61, Sub62, Sub63
	common /hgg_varXs/ Sub64, Sub65, Sub66, Sub67, Sub68, Sub69
	common /hgg_varXs/ Sub70, Sub71

	ComplexType Eps1, Pair1, Pair2, Pair3, Sub3(6), Sub25(6)
	ComplexType Abb1, Abb2, Abb3, Sub47(3), Sub51(3), Sub59(3)
	ComplexType Sub72(3)
	common /hgg_varXh/ Eps1, Pair1, Pair2, Pair3, Sub3, Sub25
	common /hgg_varXh/ Abb1, Abb2, Abb3, Sub47, Sub51, Sub59
	common /hgg_varXh/ Sub72

	integer All4, Gen4, Ind1, Ind2
	common /hgg_indices/ All4, Gen4, Ind1, Ind2

	ComplexType Cloop(1)
	ComplexType MatSUN(1,1)
	common /hgg_formfactors/ Cloop, MatSUN

#endif

