#if 0
* hgg-vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Feb-2015 17:19
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Sub1(6), Sub23(6), Sub45(3), Sub46(3), Sub55(3)
	ComplexType Sub56(3), Sub57(3), Sub52(3), Sub53(3), Sub62(3)
	ComplexType Sub63(3), Sub48(3), Sub49(3), Sub50(3), Sub11(3)
	ComplexType Sub14(3), Sub4(3), Sub7(3), Sub26(3), Sub29(3)
	ComplexType Sub36(3), Sub33(3), Sub20(3,3), Sub8(3,3)
	ComplexType Sub19(3,3), Sub5(3,3), Sub15(3,3), Sub12(3,3)
	ComplexType Sub37(3,3), Sub34(3,3), Sub30(3,3), Sub27(3,3)
	ComplexType Sub42(3,3), Sub41(3,3), Sub16(6,3,3)
	ComplexType Sub9(6,3,3), Sub31(6,3,3), Sub38(6,3,3)
	ComplexType Sub13(6,3,3), Sub6(6,3,3), Sub28(6,3,3)
	ComplexType Sub35(6,3,3), Sub17(6,3,3), Sub10(6,3,3)
	ComplexType Sub21(6,3,3), Sub32(6,3,3), Sub39(6,3,3)
	ComplexType Sub43(6,3,3), Sub18(6,3,3), Sub40(6,3,3)
	ComplexType Sub22(6,3,3), Sub44(6,3,3), Sub2(6), Sub24(6)
	ComplexType Sub59(3), Sub60(3), Sub66(3), Sub67(3), Sub58(3)
	ComplexType Sub65(3), pave1(6), pave2(Ncc,6), pave3(6)
	ComplexType pave4(Ncc,6), pave5(3), pave6(Ncc,3), pave7(3)
	ComplexType pave8(Ncc,3)
	common /hgg_varXs/ Sub1, Sub23, Sub45, Sub46, Sub55, Sub56
	common /hgg_varXs/ Sub57, Sub52, Sub53, Sub62, Sub63, Sub48
	common /hgg_varXs/ Sub49, Sub50, Sub11, Sub14, Sub4, Sub7
	common /hgg_varXs/ Sub26, Sub29, Sub36, Sub33, Sub20, Sub8
	common /hgg_varXs/ Sub19, Sub5, Sub15, Sub12, Sub37, Sub34
	common /hgg_varXs/ Sub30, Sub27, Sub42, Sub41, Sub16, Sub9
	common /hgg_varXs/ Sub31, Sub38, Sub13, Sub6, Sub28, Sub35
	common /hgg_varXs/ Sub17, Sub10, Sub21, Sub32, Sub39, Sub43
	common /hgg_varXs/ Sub18, Sub40, Sub22, Sub44, Sub2, Sub24
	common /hgg_varXs/ Sub59, Sub60, Sub66, Sub67, Sub58, Sub65
	common /hgg_varXs/ pave1, pave2, pave3, pave4, pave5, pave6
	common /hgg_varXs/ pave7, pave8

	ComplexType Pair1, Pair2, Pair3, Eps1, Abb3, Abb2, Abb1
	ComplexType Sub3(6), Sub25(6), Sub51(3)
	ComplexType Sub61(3), Sub68(3), Sub47(3)
	ComplexType Sub54(3), Sub64(3)
	common /hgg_varXh/ Pair1, Pair2, Pair3, Eps1, Abb3, Abb2
	common /hgg_varXh/ Abb1, Sub3, Sub25, Sub51, Sub61, Sub68
	common /hgg_varXh/ Sub47, Sub54, Sub64

	integer seq(2), Hel(3)
	common /hgg_helind/ seq, Hel

	integer All4, Gen4, Ind1, Ind2
	common /hgg_indices/ All4, Gen4, Ind1, Ind2

	ComplexType Cloop(1)
	ComplexType MatSUN(1,1)
	common /hgg_formfactors/ Cloop, MatSUN

#endif
