#if 0
* hgaga-vars.h
* variable declarations
* generated by FormCalc 9.6 (7 Mar 2018) on 13-Mar-2018 8:19
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType AaB03, AaB05, AaB06(6), AaB08(6), AaB010(6)
	ComplexType AaB012(2), AaB013(3), AaB015(3), AaB017(3)
	ComplexType AaC0i1(Ncc,2), AaC0i2(Ncc), AaC0i4(Ncc)
	ComplexType AaC0i7(Ncc,6), AaC0i9(Ncc,6), AaC0i11(Ncc,6)
	ComplexType AaC0i14(Ncc,3), AaC0i16(Ncc,3), AaC0i18(Ncc,3)
	ComplexType Sub1(6), Sub2(6), Sub4(3), Sub5(3,3)
	ComplexType Sub6(6,3,3), Sub7(3), Sub8(3,3), Sub9(6,3,3)
	ComplexType Sub10(6,3,3), Sub11(3), Sub12(3,3), Sub13(6,3,3)
	ComplexType Sub14(3), Sub15(3,3), Sub16(6,3,3), Sub17(6,3,3)
	ComplexType Sub18(6,3,3), Sub19(3,3), Sub20(3,3)
	ComplexType Sub21(6,3,3), Sub22(6,3,3), Sub23(6), Sub24(6)
	ComplexType Sub26(3), Sub27(3,3), Sub28(6,3,3), Sub29(3)
	ComplexType Sub30(3,3), Sub31(6,3,3), Sub32(6,3,3), Sub33(3)
	ComplexType Sub34(3,3), Sub35(6,3,3), Sub36(3), Sub37(3,3)
	ComplexType Sub38(6,3,3), Sub39(6,3,3), Sub40(6,3,3)
	ComplexType Sub41(3,3), Sub42(3,3), Sub43(6,3,3)
	ComplexType Sub44(6,3,3), Sub45(6), Sub46(6), Sub48(3)
	ComplexType Sub49(3,3), Sub50(6,3,3), Sub51(3), Sub52(3,3)
	ComplexType Sub53(6,3,3), Sub54(6,3,3), Sub55(3), Sub56(3,3)
	ComplexType Sub57(6,3,3), Sub58(3), Sub59(3,3), Sub60(6,3,3)
	ComplexType Sub61(6,3,3), Sub62(6,3,3), Sub63(3,3)
	ComplexType Sub64(3,3), Sub65(6,3,3), Sub66(6,3,3), Sub67(2)
	ComplexType Sub68(2), Sub70(2), Sub71(2), Sub72(2), Sub73(2)
	ComplexType Sub74(2), Sub75(2), Sub76(2), Sub77(2), Sub78(2)
	ComplexType Sub79(2), Sub80(2), Sub81(2), Sub82(2), Sub83(2)
	ComplexType Sub84(3), Sub85(3), Sub87, Sub88, Sub89
	ComplexType Sub91(3), Sub92(3), Sub94, Sub95, Sub96
	ComplexType Sub98(3), Sub99(3), Sub101(3), Sub102(3)
	ComplexType Sub103(3), Sub104(3), Sub105(3), Sub106(3)
	ComplexType Sub107(3), Sub108(3), Sub109(3), Sub111, Sub112
	ComplexType Sub113, Sub114, Sub118, Sub119, Sub120, Sub121
	ComplexType Sub122
	common /hgaga_varXs/ AaB03, AaB05, AaB06, AaB08, AaB010
	common /hgaga_varXs/ AaB012, AaB013, AaB015, AaB017, AaC0i1
	common /hgaga_varXs/ AaC0i2, AaC0i4, AaC0i7, AaC0i9, AaC0i11
	common /hgaga_varXs/ AaC0i14, AaC0i16, AaC0i18, Sub1, Sub2
	common /hgaga_varXs/ Sub4, Sub5, Sub6, Sub7, Sub8, Sub9
	common /hgaga_varXs/ Sub10, Sub11, Sub12, Sub13, Sub14
	common /hgaga_varXs/ Sub15, Sub16, Sub17, Sub18, Sub19
	common /hgaga_varXs/ Sub20, Sub21, Sub22, Sub23, Sub24
	common /hgaga_varXs/ Sub26, Sub27, Sub28, Sub29, Sub30
	common /hgaga_varXs/ Sub31, Sub32, Sub33, Sub34, Sub35
	common /hgaga_varXs/ Sub36, Sub37, Sub38, Sub39, Sub40
	common /hgaga_varXs/ Sub41, Sub42, Sub43, Sub44, Sub45
	common /hgaga_varXs/ Sub46, Sub48, Sub49, Sub50, Sub51
	common /hgaga_varXs/ Sub52, Sub53, Sub54, Sub55, Sub56
	common /hgaga_varXs/ Sub57, Sub58, Sub59, Sub60, Sub61
	common /hgaga_varXs/ Sub62, Sub63, Sub64, Sub65, Sub66
	common /hgaga_varXs/ Sub67, Sub68, Sub70, Sub71, Sub72
	common /hgaga_varXs/ Sub73, Sub74, Sub75, Sub76, Sub77
	common /hgaga_varXs/ Sub78, Sub79, Sub80, Sub81, Sub82
	common /hgaga_varXs/ Sub83, Sub84, Sub85, Sub87, Sub88
	common /hgaga_varXs/ Sub89, Sub91, Sub92, Sub94, Sub95
	common /hgaga_varXs/ Sub96, Sub98, Sub99, Sub101, Sub102
	common /hgaga_varXs/ Sub103, Sub104, Sub105, Sub106, Sub107
	common /hgaga_varXs/ Sub108, Sub109, Sub111, Sub112, Sub113
	common /hgaga_varXs/ Sub114, Sub118, Sub119, Sub120, Sub121
	common /hgaga_varXs/ Sub122

	ComplexType Eps1, Pair1, Pair2, Pair3, Sub3(6), Sub25(6)
	ComplexType Sub47(6), Sub115, Sub123, Abb1, Abb2, Abb3, Abb4
	ComplexType Abb5, Sub69(2), Sub86(3), Sub90(3), Sub93(3)
	ComplexType Sub97(3), Sub100(3), Sub110(3), Sub116, Sub117
	common /hgaga_varXh/ Eps1, Pair1, Pair2, Pair3, Sub3, Sub25
	common /hgaga_varXh/ Sub47, Sub115, Sub123, Abb1, Abb2, Abb3
	common /hgaga_varXh/ Abb4, Abb5, Sub69, Sub86, Sub90, Sub93
	common /hgaga_varXh/ Sub97, Sub100, Sub110, Sub116, Sub117

	integer All4, Cha4, Gen4, Ind1, Ind2
	common /hgaga_indices/ All4, Cha4, Gen4, Ind1, Ind2

	ComplexType Cloop(1)
	common /hgaga_formfactors/ Cloop

#endif

