#if 0
* hgaga-vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Feb-2015 17:19
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Sub116, Sub129, Sub122, Sub113, Sub120, Sub87
	ComplexType Sub112, Sub94, Sub117, Sub119, Sub95, Sub96
	ComplexType Sub88, Sub89, Sub1(6), Sub23(6), Sub67(2)
	ComplexType Sub68(2), Sub76(2), Sub78(2), Sub77(2), Sub73(2)
	ComplexType Sub70(2), Sub74(2), Sub71(2), Sub80(2), Sub82(2)
	ComplexType Sub81(2), Sub72(2), Sub75(2), Sub84(3), Sub98(3)
	ComplexType Sub91(3), Sub85(3), Sub99(3), Sub92(3)
	ComplexType Sub101(3), Sub102(3), Sub104(3), Sub106(3)
	ComplexType Sub108(3), Sub103(3), Sub107(3), Sub109(3)
	ComplexType Sub105(3), Sub11(3), Sub14(3), Sub4(3), Sub7(3)
	ComplexType Sub31(3), Sub34(3), Sub24(3), Sub27(3), Sub45(3)
	ComplexType Sub48(3), Sub55(3), Sub52(3), Sub20(3,3)
	ComplexType Sub8(3,3), Sub19(3,3), Sub5(3,3), Sub15(3,3)
	ComplexType Sub12(3,3), Sub40(3,3), Sub28(3,3), Sub39(3,3)
	ComplexType Sub25(3,3), Sub35(3,3), Sub32(3,3), Sub56(3,3)
	ComplexType Sub53(3,3), Sub49(3,3), Sub46(3,3), Sub61(3,3)
	ComplexType Sub60(3,3), Sub16(6,3,3), Sub9(6,3,3)
	ComplexType Sub29(6,3,3), Sub36(6,3,3), Sub50(6,3,3)
	ComplexType Sub57(6,3,3), Sub13(6,3,3), Sub6(6,3,3)
	ComplexType Sub26(6,3,3), Sub33(6,3,3), Sub47(6,3,3)
	ComplexType Sub54(6,3,3), Sub17(6,3,3), Sub10(6,3,3)
	ComplexType Sub21(6,3,3), Sub30(6,3,3), Sub37(6,3,3)
	ComplexType Sub41(6,3,3), Sub51(6,3,3), Sub58(6,3,3)
	ComplexType Sub62(6,3,3), Sub18(6,3,3), Sub38(6,3,3)
	ComplexType Sub59(6,3,3), Sub22(6,3,3), Sub42(6,3,3)
	ComplexType Sub63(6,3,3), Sub114, Sub2(6), Sub64(6)
	ComplexType Sub43(6), Sub79(2), Sub83(2), pave1(Ncc,2)
	ComplexType pave2, pave3(Ncc), pave4(Ncc), pave5(6)
	ComplexType pave6(Ncc,6), pave7(6), pave8(Ncc,6)
	ComplexType pave9(Ncc,6), pave10(2), pave11(3)
	ComplexType pave12(Ncc,3), pave13(3), pave14(Ncc,3)
	ComplexType pave15(3), pave16(Ncc,3), pave17(6), pave18
	common /hgaga_varXs/ Sub116, Sub129, Sub122, Sub113, Sub120
	common /hgaga_varXs/ Sub87, Sub112, Sub94, Sub117, Sub119
	common /hgaga_varXs/ Sub95, Sub96, Sub88, Sub89, Sub1, Sub23
	common /hgaga_varXs/ Sub67, Sub68, Sub76, Sub78, Sub77
	common /hgaga_varXs/ Sub73, Sub70, Sub74, Sub71, Sub80
	common /hgaga_varXs/ Sub82, Sub81, Sub72, Sub75, Sub84
	common /hgaga_varXs/ Sub98, Sub91, Sub85, Sub99, Sub92
	common /hgaga_varXs/ Sub101, Sub102, Sub104, Sub106, Sub108
	common /hgaga_varXs/ Sub103, Sub107, Sub109, Sub105, Sub11
	common /hgaga_varXs/ Sub14, Sub4, Sub7, Sub31, Sub34, Sub24
	common /hgaga_varXs/ Sub27, Sub45, Sub48, Sub55, Sub52
	common /hgaga_varXs/ Sub20, Sub8, Sub19, Sub5, Sub15, Sub12
	common /hgaga_varXs/ Sub40, Sub28, Sub39, Sub25, Sub35
	common /hgaga_varXs/ Sub32, Sub56, Sub53, Sub49, Sub46
	common /hgaga_varXs/ Sub61, Sub60, Sub16, Sub9, Sub29, Sub36
	common /hgaga_varXs/ Sub50, Sub57, Sub13, Sub6, Sub26, Sub33
	common /hgaga_varXs/ Sub47, Sub54, Sub17, Sub10, Sub21
	common /hgaga_varXs/ Sub30, Sub37, Sub41, Sub51, Sub58
	common /hgaga_varXs/ Sub62, Sub18, Sub38, Sub59, Sub22
	common /hgaga_varXs/ Sub42, Sub63, Sub114, Sub2, Sub64
	common /hgaga_varXs/ Sub43, Sub79, Sub83, pave1, pave2
	common /hgaga_varXs/ pave3, pave4, pave5, pave6, pave7
	common /hgaga_varXs/ pave8, pave9, pave10, pave11, pave12
	common /hgaga_varXs/ pave13, pave14, pave15, pave16, pave17
	common /hgaga_varXs/ pave18

	ComplexType Pair1, Pair2, Pair3, Eps1, Abb7, Abb3, Abb4, Abb6
	ComplexType Abb2, Abb1, Sub126, Sub123, Sub115, Sub125, Sub127
	ComplexType Sub130, Sub121, Sub118, Sub3(6)
	ComplexType Sub44(6), Sub110(3)
	ComplexType Sub90(3), Sub97(3)
	ComplexType Sub111(3), Sub65(6,3,3), Sub128
	ComplexType Sub69(2), Sub86(3), Sub93(3)
	ComplexType Sub100(3), Sub66(6,3,3), Sub131
	common /hgaga_varXh/ Pair1, Pair2, Pair3, Eps1, Abb7, Abb3
	common /hgaga_varXh/ Abb4, Abb6, Abb2, Abb1, Sub126, Sub123
	common /hgaga_varXh/ Sub115, Sub125, Sub127, Sub130, Sub121
	common /hgaga_varXh/ Sub118, Sub3, Sub44, Sub110, Sub90
	common /hgaga_varXh/ Sub97, Sub111, Sub65, Sub128, Sub69
	common /hgaga_varXh/ Sub86, Sub93, Sub100, Sub66, Sub131

	integer seq(2), Hel(3)
	common /hgaga_helind/ seq, Hel

	integer All4, Cha4, Gen4, Ind1, Ind2
	common /hgaga_indices/ All4, Cha4, Gen4, Ind1, Ind2

	ComplexType Cloop(1)
	common /hgaga_formfactors/ Cloop

#endif
