#if 0
* hgaga-vars.h
* variable declarations
* generated by FormCalc 8.4 on 30-Apr-2014 7:29
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Sub85, Sub86, Sub5, Sub98, Sub97, Sub6, Sub87
	ComplexType Sub1(6), Sub21(6), Sub57(2), Sub58(2), Sub66(2)
	ComplexType Sub60(2), Sub62(2), Sub61(2), Sub69(2), Sub80(3)
	ComplexType Sub70(3), Sub73(3), Sub81(3), Sub71(3), Sub74(3)
	ComplexType Sub8(3), Sub12(3), Sub7(3), Sub11(3), Sub24(3)
	ComplexType Sub28(3), Sub23(3), Sub27(3), Sub44(3), Sub40(3)
	ComplexType Sub41(3), Sub45(3), Sub13(3), Sub25(3), Sub29(3)
	ComplexType Sub42(3), Sub46(3), Sub9(3), Sub15(6,3)
	ComplexType Sub31(6,3), Sub48(6,3), Sub10(6,3), Sub14(6,3)
	ComplexType Sub26(6,3), Sub30(6,3), Sub47(6,3), Sub43(6,3)
	ComplexType Sub18(3,3), Sub17(3,3), Sub34(3,3), Sub33(3,3)
	ComplexType Sub51(3,3), Sub50(3,3), Sub32(6,3,3)
	ComplexType Sub16(6,3,3), Sub49(6,3,3), Sub4(6,3,3)
	ComplexType Sub19(6,3,3), Sub22(6,3,3), Sub35(6,3,3)
	ComplexType Sub39(6,3,3), Sub52(6,3,3), Sub20(6,3,3)
	ComplexType Sub36(6,3,3), Sub53(6,3,3), Sub95, Sub67, Sub63
	ComplexType Sub64, Sub68, Sub2(6), Sub54(6), Sub37(6)
	ComplexType Sub65(2), pave1(Ncc,2), pave2(Ncc), pave3
	ComplexType pave4(Ncc), pave5, pave6(6), pave7(Ncc,6)
	ComplexType pave8(6), pave9(Ncc,6), pave10(Ncc,6), pave11(2)
	ComplexType pave12(3), pave13(Ncc,3), pave14(3)
	ComplexType pave15(Ncc,3), pave16(3), pave17(Ncc,3)
	ComplexType pave18(6)
	common /hgaga_varXs/ Sub85, Sub86, Sub5, Sub98, Sub97, Sub6
	common /hgaga_varXs/ Sub87, Sub1, Sub21, Sub57, Sub58, Sub66
	common /hgaga_varXs/ Sub60, Sub62, Sub61, Sub69, Sub80
	common /hgaga_varXs/ Sub70, Sub73, Sub81, Sub71, Sub74, Sub8
	common /hgaga_varXs/ Sub12, Sub7, Sub11, Sub24, Sub28, Sub23
	common /hgaga_varXs/ Sub27, Sub44, Sub40, Sub41, Sub45
	common /hgaga_varXs/ Sub13, Sub25, Sub29, Sub42, Sub46, Sub9
	common /hgaga_varXs/ Sub15, Sub31, Sub48, Sub10, Sub14
	common /hgaga_varXs/ Sub26, Sub30, Sub47, Sub43, Sub18
	common /hgaga_varXs/ Sub17, Sub34, Sub33, Sub51, Sub50
	common /hgaga_varXs/ Sub32, Sub16, Sub49, Sub4, Sub19, Sub22
	common /hgaga_varXs/ Sub35, Sub39, Sub52, Sub20, Sub36
	common /hgaga_varXs/ Sub53, Sub95, Sub67, Sub63, Sub64
	common /hgaga_varXs/ Sub68, Sub2, Sub54, Sub37, Sub65, pave1
	common /hgaga_varXs/ pave2, pave3, pave4, pave5, pave6
	common /hgaga_varXs/ pave7, pave8, pave9, pave10, pave11
	common /hgaga_varXs/ pave12, pave13, pave14, pave15, pave16
	common /hgaga_varXs/ pave17, pave18

	ComplexType Pair1, Pair2, Pair3, Eps1, Abb7, Abb3, Abb4, Abb6
	ComplexType Abb2, Abb1, Sub100, Sub96, Sub99, Sub88, Sub89
	ComplexType Sub90, Sub93, Sub76, Sub79, Sub3(6)
	ComplexType Sub38(6), Sub77(3), Sub78(3)
	ComplexType Sub83(3), Sub84(3)
	ComplexType Sub55(6,3,3), Sub91, Sub92, Sub59(2)
	ComplexType Sub72(3), Sub75(3), Sub82(3)
	ComplexType Sub56(6,3,3), Sub94
	common /hgaga_varXh/ Pair1, Pair2, Pair3, Eps1, Abb7, Abb3
	common /hgaga_varXh/ Abb4, Abb6, Abb2, Abb1, Sub100, Sub96
	common /hgaga_varXh/ Sub99, Sub88, Sub89, Sub90, Sub93
	common /hgaga_varXh/ Sub76, Sub79, Sub3, Sub38, Sub77, Sub78
	common /hgaga_varXh/ Sub83, Sub84, Sub55, Sub91, Sub92
	common /hgaga_varXh/ Sub59, Sub72, Sub75, Sub82, Sub56, Sub94

	integer seq(2), Hel(3)
	common /hgaga_helind/ seq, Hel

	integer All4, Cha4, Gen4, Ind1, Ind2
	common /hgaga_indices/ All4, Cha4, Gen4, Ind1, Ind2

	ComplexType Cloop(1)
	common /hgaga_formfactors/ Cloop

#endif
