#if 0
* huu-vars.h
* variable declarations
* generated by FormCalc 9.6 (7 Mar 2018) on 13-Mar-2018 8:20
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "huu-RenConst.h.F"

#else

#include "Decay.h"
#include "huu-RenConst.h.F"

	ComplexType Sub1
	ComplexType AaA07(6), AaA08(6), AaA09(6), AaA010(2)
	ComplexType AaA013(4), AaA020, AaA021, AaA057(3), AaA058(3)
	ComplexType AaA063(3), AaA065(3), AaA080, AaA081, AaA082
	ComplexType AaA083, AaB01(6,6), AaB02(6,6), AaB03(6,6)
	ComplexType AaB012(2,2), AaB14(6,6), AaB015(4,4), AaB15(6,6)
	ComplexType AaB16(6,6), AaB019(6,2), AaB022, AaB023, AaB024
	ComplexType AaB025, AaB026, AaB027, AaB032, AaB034, AaB054
	ComplexType AaB055(3), AaB062(3), AaB064(3), AaB067(6,4)
	ComplexType AaB071, AaB084(3), AaB089(3), AaB090(3)
	ComplexType AaB111(2,2), AaB114(4,4), AaB128, AaB129, AaB130
	ComplexType AaB131, AaB133, AaB135, AaB156(3), AaB173(3)
	ComplexType AaB174(3), AaB175(3), AaC0i16(Ncc,6,6,2)
	ComplexType AaC0i17(Ncc,6,6,4), AaC0i18(Ncc,6,6)
	ComplexType AaC0i36(Ncc), AaC0i37(Ncc), AaC0i38(Ncc)
	ComplexType AaC0i39(Ncc), AaC0i40(Ncc), AaC0i41(Ncc)
	ComplexType AaC0i42(Ncc), AaC0i43(Ncc), AaC0i44(Ncc)
	ComplexType AaC0i45(Ncc), AaC0i46(Ncc), AaC0i47(Ncc)
	ComplexType AaC0i48(Ncc), AaC0i49(Ncc), AaC0i50(Ncc)
	ComplexType AaC0i51(Ncc), AaC0i52(Ncc), AaC0i53(Ncc)
	ComplexType AaC0i59(Ncc,3), AaC0i60(Ncc,3), AaC0i61(Ncc,3)
	ComplexType AaC0i66(Ncc,6,4,4), AaC0i68(Ncc), AaC0i69(Ncc)
	ComplexType AaC0i70(Ncc), AaC0i72(Ncc), AaC0i76(Ncc,3)
	ComplexType AaC0i77(Ncc,3), AaC0i78(Ncc,3)
	ComplexType AaC0i79(Ncc,6,2,2), AaC0i85(Ncc,3), AaC0i86(Ncc)
	ComplexType AaC0i87(Ncc), AaC0i88(Ncc,3), Sub3(3,3)
	ComplexType Sub4(3,3), Sub5(6,6,3,3), Sub6(3), Sub7(3,3)
	ComplexType Sub8(6,3,3), Sub9(3), Sub10(3,3), Sub11(6,3,3)
	ComplexType Sub12(6,6,3,3), Sub13(3), Sub14(3,3)
	ComplexType Sub15(6,3,3), Sub16(3), Sub17(3,3), Sub18(6,3,3)
	ComplexType Sub19(6,6,3,3), Sub21(3,3), Sub22(3,3)
	ComplexType Sub23(6,6,3,3), Sub25(3,3), Sub26(3,3)
	ComplexType Sub27(6,6,3,3), Sub28(3), Sub29(3,3)
	ComplexType Sub30(6,3,3), Sub31(3), Sub32(3,3), Sub33(6,3,3)
	ComplexType Sub34(6,6,3,3), Sub35(3), Sub36(3,3)
	ComplexType Sub37(6,3,3), Sub38(3), Sub39(3,3), Sub40(6,3,3)
	ComplexType Sub41(6,6,3,3), Sub42(3,3), Sub43(3,3)
	ComplexType Sub44(6,6,3,3), Sub45(6,6,3,3), Sub46(3)
	ComplexType Sub47(3,3), Sub48(6,3,3), Sub49(3), Sub50(3,3)
	ComplexType Sub51(6,3,3), Sub52(6,6,3,3), Sub53(3,3)
	ComplexType Sub54(3,3), Sub55(6,6,3,3), Sub56(3), Sub57(3,3)
	ComplexType Sub58(6,3,3), Sub59(3), Sub60(3,3), Sub61(6,3,3)
	ComplexType Sub62(6,6,3,3), Sub63(3,3), Sub64(3,3)
	ComplexType Sub65(6,6,3,3), Sub66(3,3), Sub67(3,3)
	ComplexType Sub68(6,6,3,3), Sub69(6,6,3,3,3,3), Sub70, Sub71
	ComplexType Sub72(6,6,3), Sub73(3), Sub74(3,3), Sub75(6,3,3)
	ComplexType Sub76(3), Sub77(3,3), Sub78(6,3,3)
	ComplexType Sub79(6,6,3,3), Sub80(3), Sub81(3,3)
	ComplexType Sub82(6,3,3), Sub83(3), Sub84(3,3), Sub85(6,3,3)
	ComplexType Sub86(6,6,3,3), Sub87(6,6,3,3), Sub88(3,3)
	ComplexType Sub89(3,3), Sub90(6,6,3,3), Sub91(6,6,3,3)
	ComplexType Sub92(6,6,3), Sub93(3), Sub94(3,3), Sub95(6,3,3)
	ComplexType Sub96(3), Sub97(3,3), Sub98(6,3,3)
	ComplexType Sub99(6,6,3,3), Sub100(3), Sub101(3,3)
	ComplexType Sub102(6,3,3), Sub103(3), Sub104(3,3)
	ComplexType Sub105(6,3,3), Sub106(6,6,3,3), Sub107(3,3)
	ComplexType Sub108(3,3), Sub109(6,6,3,3), Sub111(6,6,3)
	ComplexType Sub112(3), Sub113(3,3), Sub114(6,3,3), Sub115(3)
	ComplexType Sub116(3,3), Sub117(6,3,3), Sub118(6,6,3,3)
	ComplexType Sub119(3), Sub120(3,3), Sub121(6,3,3), Sub122(3)
	ComplexType Sub123(3,3), Sub124(6,3,3), Sub125(6,6,3,3)
	ComplexType Sub126(3,3), Sub127(3,3), Sub128(6,6,3,3)
	ComplexType Sub130(3), Sub131(3), Sub132(6,3), Sub133(3)
	ComplexType Sub134(3), Sub135(6,3), Sub136(3), Sub137(3)
	ComplexType Sub138(6,3), Sub139(2,2), Sub140(2,2)
	ComplexType Sub141(2,2), Sub142(2,2), Sub143(2,2)
	ComplexType Sub144(2,2), Sub145(2,2), Sub146(2,2)
	ComplexType Sub147(2,2), Sub148(2,2), Sub150(2,2)
	ComplexType Sub151(2,2), Sub152(2,2), Sub153(2,2), Sub157(3)
	ComplexType Sub159(3), Sub162(3), Sub166, Sub171, Sub172
	ComplexType Sub174, Sub175, Sub176(3), Sub178, Sub181(3)
	ComplexType Sub184(3), Sub187(3), Sub189(3), Sub192, Sub195
	ComplexType Sub197(3), Sub200, Sub201(3), Sub204(3)
	ComplexType Sub208(3), Sub211, Sub214(3), Sub215(3)
	ComplexType Sub216(3), Sub217(3), Sub219(3), Sub220(3)
	ComplexType Sub223(3), Sub224(3), Sub225(3), Sub226(3)
	ComplexType Sub231, Sub234(3), Sub235(3), Sub236(3), Sub242
	ComplexType Sub243, Sub247(3), Sub248(3), Sub250, Sub251(3)
	ComplexType Sub252, Sub253(3), Sub257, Sub258(3), Sub262(3)
	ComplexType Sub263(3), Sub265(3), Sub266(3), Sub272, Sub273
	ComplexType Sub274(3), Sub275, Sub276, Sub277, Sub279
	ComplexType Sub280, Sub285(3), Sub286, Sub287, Sub290
	ComplexType Sub291, Sub293, Sub294, Sub300(4), Sub301(4)
	ComplexType Sub302(4), Sub303(4), Sub304(4,4), Sub305(4)
	ComplexType Sub306(4), Sub307(4,4), Sub308(4), Sub309(4)
	ComplexType Sub310(4,4), Sub311(4,4), Sub312(4), Sub313(4)
	ComplexType Sub314(4), Sub315(4), Sub316(4,4), Sub317(4)
	ComplexType Sub318(4), Sub319(4,4), Sub320(4), Sub321(4)
	ComplexType Sub322(4,4), Sub323(4), Sub324(4), Sub325(4,4)
	ComplexType Sub326(4), Sub327(4), Sub328(4,4), Sub329(4,4)
	ComplexType Sub331(4,4), Sub332(4,4), Sub333(4,4)
	ComplexType Sub334(4,4), Sub338, Sub339, Sub340, Sub341
	ComplexType Sub344, Sub345, Sub346, Sub347, Sub349, Sub350
	ComplexType Sub351, Sub352, Sub356, Sub357, Sub363, Sub364
	ComplexType Sub365, Sub366, Sub371, Sub374, Sub375, Sub376
	ComplexType Sub380, Sub381, Sub382, Sub383, Sub388, Sub389
	ComplexType Sub390, Sub394, Sub395, Sub399, Sub400, Sub401
	ComplexType Sub402, Sub404, Sub408, Sub424, Sub425, Sub426
	ComplexType Sub427, Sub428, Sub429, Sub430, Sub432, Sub433
	ComplexType Sub434, Sub435, Sub436, Sub442, Sub443, Sub444
	ComplexType Sub446, Sub447, Sub448, Sub451, Sub452, Sub458
	ComplexType Sub459, Sub460, Sub461, Sub463, Sub465, Sub466
	ComplexType Sub467, Sub471, Sub472, Sub477, Sub478, Sub479
	ComplexType Sub480, Sub481, Sub483, Sub484, Sub485, Sub486
	ComplexType Sub487, Sub491, Sub492, Sub493, Sub494, Sub495
	ComplexType Sub502, Sub503, Sub504, Sub505, Sub506, Sub507
	ComplexType Sub508, Sub509, Sub510, Sub511, Sub512, Sub513
	ComplexType Sub514, Sub515, Sub517, Sub518, Sub519, Sub520
	ComplexType Sub521, Sub522, Sub523, Sub524, Sub525, Sub527
	ComplexType Sub528, Sub529, Sub531, Sub532, Sub533, Sub534
	ComplexType Sub536, Sub537, Sub544, Sub545, Sub546, Sub547
	ComplexType Sub550, Sub551, Sub552, Sub553, Sub555, Sub556
	ComplexType Sub557, Sub558, Sub559, Sub561, Sub562, Sub563
	ComplexType Sub564, Sub565, Sub566, Sub570, Sub571, Sub573
	ComplexType Sub574, Sub575, Sub577, Sub578, Sub579, Sub580
	ComplexType Sub585, Sub590, Sub591, Sub593, Sub594, Sub596
	ComplexType Sub597, Sub598, Sub600, Sub601, Sub603, Sub604
	ComplexType Sub605, Sub607, Sub609, Sub611, Sub618(6,2,3)
	ComplexType Sub619(6,2,3), Sub621(6,3,3), Sub622(6,3,3)
	ComplexType Sub623(6,6,3,3), Sub624(6,3,3), Sub625(6,3,3)
	ComplexType Sub626(6,6,3,3), Sub627(6,6,3,3)
	ComplexType Sub628(6,6,3,3), Sub629(6,6,3,3), Sub630(6,3,3)
	ComplexType Sub631(6,3,3), Sub632(6,6,3,3), Sub633(6,2,3)
	ComplexType Sub634(3), Sub635(3,3), Sub636(6,3,3), Sub637(3)
	ComplexType Sub638(3,3), Sub639(6,3,3), Sub640(6,6,3,3)
	ComplexType Sub642(6,3,3), Sub643(6,3,3), Sub644(6,6,3,3)
	ComplexType Sub645(3), Sub646(3,3), Sub647(6,3,3), Sub648(3)
	ComplexType Sub649(3,3), Sub650(6,3,3), Sub651(6,6,3,3)
	ComplexType Sub654(6,6,3,3), Sub655(3,3), Sub656(3,3)
	ComplexType Sub657(6,6,3,3), Sub666(3), Sub667(3,3)
	ComplexType Sub668(6,3,3), Sub669(3), Sub670(3,3)
	ComplexType Sub671(6,3,3), Sub672(6,6,3,3), Sub673(3)
	ComplexType Sub674(3,3), Sub675(6,3,3), Sub676(3)
	ComplexType Sub677(3,3), Sub678(6,3,3), Sub679(6,6,3,3)
	ComplexType Sub680(6,6,3,3), Sub681(6,6,3,3), Sub682(6,4)
	ComplexType Sub683(6,4), Sub684(4), Sub685(6,4), Sub686(6,4)
	ComplexType Sub687(6,4), Sub694(6,2,3), Sub710(6,4)
	ComplexType Sub711(6,4), Sub712(6,4), Sub409, Sub410, Sub411
	ComplexType Sub412, Sub413, Sub414, Sub416, Sub417, Sub418
	ComplexType Sub419, Sub420, Sub421, Sub449
	common /huu_varXs/ Sub1, AaA07, AaA08, AaA09, AaA010, AaA013
	common /huu_varXs/ AaA020, AaA021, AaA057, AaA058, AaA063
	common /huu_varXs/ AaA065, AaA080, AaA081, AaA082, AaA083
	common /huu_varXs/ AaB01, AaB02, AaB03, AaB012, AaB14
	common /huu_varXs/ AaB015, AaB15, AaB16, AaB019, AaB022
	common /huu_varXs/ AaB023, AaB024, AaB025, AaB026, AaB027
	common /huu_varXs/ AaB032, AaB034, AaB054, AaB055, AaB062
	common /huu_varXs/ AaB064, AaB067, AaB071, AaB084, AaB089
	common /huu_varXs/ AaB090, AaB111, AaB114, AaB128, AaB129
	common /huu_varXs/ AaB130, AaB131, AaB133, AaB135, AaB156
	common /huu_varXs/ AaB173, AaB174, AaB175, AaC0i16, AaC0i17
	common /huu_varXs/ AaC0i18, AaC0i36, AaC0i37, AaC0i38
	common /huu_varXs/ AaC0i39, AaC0i40, AaC0i41, AaC0i42
	common /huu_varXs/ AaC0i43, AaC0i44, AaC0i45, AaC0i46
	common /huu_varXs/ AaC0i47, AaC0i48, AaC0i49, AaC0i50
	common /huu_varXs/ AaC0i51, AaC0i52, AaC0i53, AaC0i59
	common /huu_varXs/ AaC0i60, AaC0i61, AaC0i66, AaC0i68
	common /huu_varXs/ AaC0i69, AaC0i70, AaC0i72, AaC0i76
	common /huu_varXs/ AaC0i77, AaC0i78, AaC0i79, AaC0i85
	common /huu_varXs/ AaC0i86, AaC0i87, AaC0i88, Sub3, Sub4
	common /huu_varXs/ Sub5, Sub6, Sub7, Sub8, Sub9, Sub10
	common /huu_varXs/ Sub11, Sub12, Sub13, Sub14, Sub15, Sub16
	common /huu_varXs/ Sub17, Sub18, Sub19, Sub21, Sub22, Sub23
	common /huu_varXs/ Sub25, Sub26, Sub27, Sub28, Sub29, Sub30
	common /huu_varXs/ Sub31, Sub32, Sub33, Sub34, Sub35, Sub36
	common /huu_varXs/ Sub37, Sub38, Sub39, Sub40, Sub41, Sub42
	common /huu_varXs/ Sub43, Sub44, Sub45, Sub46, Sub47, Sub48
	common /huu_varXs/ Sub49, Sub50, Sub51, Sub52, Sub53, Sub54
	common /huu_varXs/ Sub55, Sub56, Sub57, Sub58, Sub59, Sub60
	common /huu_varXs/ Sub61, Sub62, Sub63, Sub64, Sub65, Sub66
	common /huu_varXs/ Sub67, Sub68, Sub69, Sub70, Sub71, Sub72
	common /huu_varXs/ Sub73, Sub74, Sub75, Sub76, Sub77, Sub78
	common /huu_varXs/ Sub79, Sub80, Sub81, Sub82, Sub83, Sub84
	common /huu_varXs/ Sub85, Sub86, Sub87, Sub88, Sub89, Sub90
	common /huu_varXs/ Sub91, Sub92, Sub93, Sub94, Sub95, Sub96
	common /huu_varXs/ Sub97, Sub98, Sub99, Sub100, Sub101
	common /huu_varXs/ Sub102, Sub103, Sub104, Sub105, Sub106
	common /huu_varXs/ Sub107, Sub108, Sub109, Sub111, Sub112
	common /huu_varXs/ Sub113, Sub114, Sub115, Sub116, Sub117
	common /huu_varXs/ Sub118, Sub119, Sub120, Sub121, Sub122
	common /huu_varXs/ Sub123, Sub124, Sub125, Sub126, Sub127
	common /huu_varXs/ Sub128, Sub130, Sub131, Sub132, Sub133
	common /huu_varXs/ Sub134, Sub135, Sub136, Sub137, Sub138
	common /huu_varXs/ Sub139, Sub140, Sub141, Sub142, Sub143
	common /huu_varXs/ Sub144, Sub145, Sub146, Sub147, Sub148
	common /huu_varXs/ Sub150, Sub151, Sub152, Sub153, Sub157
	common /huu_varXs/ Sub159, Sub162, Sub166, Sub171, Sub172
	common /huu_varXs/ Sub174, Sub175, Sub176, Sub178, Sub181
	common /huu_varXs/ Sub184, Sub187, Sub189, Sub192, Sub195
	common /huu_varXs/ Sub197, Sub200, Sub201, Sub204, Sub208
	common /huu_varXs/ Sub211, Sub214, Sub215, Sub216, Sub217
	common /huu_varXs/ Sub219, Sub220, Sub223, Sub224, Sub225
	common /huu_varXs/ Sub226, Sub231, Sub234, Sub235, Sub236
	common /huu_varXs/ Sub242, Sub243, Sub247, Sub248, Sub250
	common /huu_varXs/ Sub251, Sub252, Sub253, Sub257, Sub258
	common /huu_varXs/ Sub262, Sub263, Sub265, Sub266, Sub272
	common /huu_varXs/ Sub273, Sub274, Sub275, Sub276, Sub277
	common /huu_varXs/ Sub279, Sub280, Sub285, Sub286, Sub287
	common /huu_varXs/ Sub290, Sub291, Sub293, Sub294, Sub300
	common /huu_varXs/ Sub301, Sub302, Sub303, Sub304, Sub305
	common /huu_varXs/ Sub306, Sub307, Sub308, Sub309, Sub310
	common /huu_varXs/ Sub311, Sub312, Sub313, Sub314, Sub315
	common /huu_varXs/ Sub316, Sub317, Sub318, Sub319, Sub320
	common /huu_varXs/ Sub321, Sub322, Sub323, Sub324, Sub325
	common /huu_varXs/ Sub326, Sub327, Sub328, Sub329, Sub331
	common /huu_varXs/ Sub332, Sub333, Sub334, Sub338, Sub339
	common /huu_varXs/ Sub340, Sub341, Sub344, Sub345, Sub346
	common /huu_varXs/ Sub347, Sub349, Sub350, Sub351, Sub352
	common /huu_varXs/ Sub356, Sub357, Sub363, Sub364, Sub365
	common /huu_varXs/ Sub366, Sub371, Sub374, Sub375, Sub376
	common /huu_varXs/ Sub380, Sub381, Sub382, Sub383, Sub388
	common /huu_varXs/ Sub389, Sub390, Sub394, Sub395, Sub399
	common /huu_varXs/ Sub400, Sub401, Sub402, Sub404, Sub408
	common /huu_varXs/ Sub424, Sub425, Sub426, Sub427, Sub428
	common /huu_varXs/ Sub429, Sub430, Sub432, Sub433, Sub434
	common /huu_varXs/ Sub435, Sub436, Sub442, Sub443, Sub444
	common /huu_varXs/ Sub446, Sub447, Sub448, Sub451, Sub452
	common /huu_varXs/ Sub458, Sub459, Sub460, Sub461, Sub463
	common /huu_varXs/ Sub465, Sub466, Sub467, Sub471, Sub472
	common /huu_varXs/ Sub477, Sub478, Sub479, Sub480, Sub481
	common /huu_varXs/ Sub483, Sub484, Sub485, Sub486, Sub487
	common /huu_varXs/ Sub491, Sub492, Sub493, Sub494, Sub495
	common /huu_varXs/ Sub502, Sub503, Sub504, Sub505, Sub506
	common /huu_varXs/ Sub507, Sub508, Sub509, Sub510, Sub511
	common /huu_varXs/ Sub512, Sub513, Sub514, Sub515, Sub517
	common /huu_varXs/ Sub518, Sub519, Sub520, Sub521, Sub522
	common /huu_varXs/ Sub523, Sub524, Sub525, Sub527, Sub528
	common /huu_varXs/ Sub529, Sub531, Sub532, Sub533, Sub534
	common /huu_varXs/ Sub536, Sub537, Sub544, Sub545, Sub546
	common /huu_varXs/ Sub547, Sub550, Sub551, Sub552, Sub553
	common /huu_varXs/ Sub555, Sub556, Sub557, Sub558, Sub559
	common /huu_varXs/ Sub561, Sub562, Sub563, Sub564, Sub565
	common /huu_varXs/ Sub566, Sub570, Sub571, Sub573, Sub574
	common /huu_varXs/ Sub575, Sub577, Sub578, Sub579, Sub580
	common /huu_varXs/ Sub585, Sub590, Sub591, Sub593, Sub594
	common /huu_varXs/ Sub596, Sub597, Sub598, Sub600, Sub601
	common /huu_varXs/ Sub603, Sub604, Sub605, Sub607, Sub609
	common /huu_varXs/ Sub611, Sub618, Sub619, Sub621, Sub622
	common /huu_varXs/ Sub623, Sub624, Sub625, Sub626, Sub627
	common /huu_varXs/ Sub628, Sub629, Sub630, Sub631, Sub632
	common /huu_varXs/ Sub633, Sub634, Sub635, Sub636, Sub637
	common /huu_varXs/ Sub638, Sub639, Sub640, Sub642, Sub643
	common /huu_varXs/ Sub644, Sub645, Sub646, Sub647, Sub648
	common /huu_varXs/ Sub649, Sub650, Sub651, Sub654, Sub655
	common /huu_varXs/ Sub656, Sub657, Sub666, Sub667, Sub668
	common /huu_varXs/ Sub669, Sub670, Sub671, Sub672, Sub673
	common /huu_varXs/ Sub674, Sub675, Sub676, Sub677, Sub678
	common /huu_varXs/ Sub679, Sub680, Sub681, Sub682, Sub683
	common /huu_varXs/ Sub684, Sub685, Sub686, Sub687, Sub694
	common /huu_varXs/ Sub710, Sub711, Sub712, Sub409, Sub410
	common /huu_varXs/ Sub411, Sub412, Sub413, Sub414, Sub416
	common /huu_varXs/ Sub417, Sub418, Sub419, Sub420, Sub421
	common /huu_varXs/ Sub449

	ComplexType F1, F2, Sub2
	ComplexType Sub20(6,6,3,3), Sub24(6,6,3,3), Sub110(6,6,3,3)
	ComplexType Sub129(6,6,3,3), Sub149(2,2), Sub154(2,2)
	ComplexType Sub155(2,2), Sub156(2,2), Sub158(3), Sub160(3)
	ComplexType Sub161, Sub163(3), Sub164(3), Sub165(3), Sub167
	ComplexType Sub168(3), Sub169(3), Sub170(3), Sub173(3)
	ComplexType Sub177(3), Sub179(3), Sub180(3), Sub182(3)
	ComplexType Sub183(3), Sub185(3), Sub186(3), Sub188(3)
	ComplexType Sub190(3), Sub191(3), Sub193(3), Sub194(3)
	ComplexType Sub196(3), Sub198(3), Sub199(3), Sub202(3)
	ComplexType Sub203(3), Sub205(3), Sub206(3), Sub207(3)
	ComplexType Sub209(3), Sub210(3), Sub212, Sub213(3)
	ComplexType Sub218(3), Sub221(3), Sub222(3), Sub227(3)
	ComplexType Sub228(3), Sub229(3), Sub232, Sub233(3)
	ComplexType Sub237(3), Sub238(3), Sub239(3), Sub240(3)
	ComplexType Sub241, Sub244, Sub245(3), Sub246(3), Sub249(3)
	ComplexType Sub254(3), Sub255(3), Sub256(3), Sub259(3)
	ComplexType Sub260(3), Sub261(3), Sub264(3), Sub267(3)
	ComplexType Sub268(3), Sub269(3), Sub270(3), Sub271(3)
	ComplexType Sub278, Sub281, Sub282(3), Sub283, Sub284(3)
	ComplexType Sub288, Sub289, Sub292, Sub295, Sub296(3)
	ComplexType Sub297(3), Sub298(3), Sub299(3), Sub330(4,4)
	ComplexType Sub335(4,4), Sub336(4,4), Sub337(4,4), Sub342
	ComplexType Sub343, Sub348, Sub353, Sub354, Sub355, Sub358
	ComplexType Sub359, Sub360, Sub361, Sub362, Sub367, Sub368
	ComplexType Sub369, Sub370, Sub372, Sub373, Sub377, Sub378
	ComplexType Sub379, Sub384, Sub385, Sub386, Sub387, Sub391
	ComplexType Sub392, Sub393, Sub396, Sub397, Sub398, Sub403
	ComplexType Sub405, Sub406, Sub407, Sub422, Sub423, Sub431
	ComplexType Sub437, Sub438, Sub439, Sub440, Sub441, Sub445
	ComplexType Sub450, Sub453, Sub454, Sub455, Sub457, Sub462
	ComplexType Sub464, Sub468, Sub469, Sub470, Sub473, Sub474
	ComplexType Sub475, Sub476, Sub482, Sub488, Sub489, Sub490
	ComplexType Sub496, Sub497, Sub498, Sub499, Sub500, Sub501
	ComplexType Sub516, Sub526, Sub530, Sub535, Sub538, Sub539
	ComplexType Sub540, Sub541, Sub542, Sub543, Sub548, Sub549
	ComplexType Sub554, Sub560, Sub567, Sub568, Sub569, Sub572
	ComplexType Sub576, Sub581, Sub582, Sub583, Sub584, Sub586
	ComplexType Sub587, Sub588, Sub589, Sub592, Sub595, Sub599
	ComplexType Sub602, Sub606, Sub608, Sub610, Sub612, Sub613
	ComplexType Sub614, Sub615, Sub616, Sub617
	ComplexType Sub620(6,6,2,3,3), Sub641(6,6,2,3,3,3,3)
	ComplexType Sub652(6,6,2,3,3,3,3), Sub653(6,6,2,3,3,3,3)
	ComplexType Sub658(6,6,2,3,3,3,3), Sub659(6,6,2,3,3,3,3)
	ComplexType Sub660(6,6,2,3,3,3,3), Sub661(6,6,2,3,3,3,3)
	ComplexType Sub662(6,6,2,3,3,3,3), Sub663(6,6,2,3,3,3,3)
	ComplexType Sub664(6,6,2,3,3,3,3), Sub665(6,6,2,3,3,3,3)
	ComplexType Sub688(6,6,4), Sub689(6,6,4), Sub690(6,6,4)
	ComplexType Sub691(6,6), Sub692(6,6), Sub693(6,6)
	ComplexType Sub695(6,2,2,3,3), Sub696(6,2,2,3,3)
	ComplexType Sub697(6,2,2,3,3), Sub698(6,2,2,3,3)
	ComplexType Sub699(6,2,2,3,3), Sub700(6,2,2,3,3)
	ComplexType Sub701(6,2,2,3,3), Sub702(6,2,2,3,3)
	ComplexType Sub703(6,2,2,3,3), Sub704(6,2,2,3,3)
	ComplexType Sub705(6,2,2,3,3), Sub706(6,2,2,3,3)
	ComplexType Sub707(6,2,2,3,3), Sub708(6,2,2,3,3)
	ComplexType Sub709(6,2,2,3,3), Sub713(6,4,4), Sub714(6,4,4)
	ComplexType Sub715(6,4,4), Sub716(6,4,4), Sub717(6,4,4)
	ComplexType Sub718(6,4,4), Sub719(6,4,4), Sub720(6,4,4)
	ComplexType Sub721(6,4,4), Sub722(6,4,4), Sub723(6,4,4)
	ComplexType Sub724(6,4,4), Sub725(6,4,4), Sub726(6,4,4)
	ComplexType Sub727(6,4,4), Sub728(6,4,4)
	common /huu_varXh/ F1, F2, Sub2, Sub20, Sub24, Sub110, Sub129
	common /huu_varXh/ Sub149, Sub154, Sub155, Sub156, Sub158
	common /huu_varXh/ Sub160, Sub161, Sub163, Sub164, Sub165
	common /huu_varXh/ Sub167, Sub168, Sub169, Sub170, Sub173
	common /huu_varXh/ Sub177, Sub179, Sub180, Sub182, Sub183
	common /huu_varXh/ Sub185, Sub186, Sub188, Sub190, Sub191
	common /huu_varXh/ Sub193, Sub194, Sub196, Sub198, Sub199
	common /huu_varXh/ Sub202, Sub203, Sub205, Sub206, Sub207
	common /huu_varXh/ Sub209, Sub210, Sub212, Sub213, Sub218
	common /huu_varXh/ Sub221, Sub222, Sub227, Sub228, Sub229
	common /huu_varXh/ Sub232, Sub233, Sub237, Sub238, Sub239
	common /huu_varXh/ Sub240, Sub241, Sub244, Sub245, Sub246
	common /huu_varXh/ Sub249, Sub254, Sub255, Sub256, Sub259
	common /huu_varXh/ Sub260, Sub261, Sub264, Sub267, Sub268
	common /huu_varXh/ Sub269, Sub270, Sub271, Sub278, Sub281
	common /huu_varXh/ Sub282, Sub283, Sub284, Sub288, Sub289
	common /huu_varXh/ Sub292, Sub295, Sub296, Sub297, Sub298
	common /huu_varXh/ Sub299, Sub330, Sub335, Sub336, Sub337
	common /huu_varXh/ Sub342, Sub343, Sub348, Sub353, Sub354
	common /huu_varXh/ Sub355, Sub358, Sub359, Sub360, Sub361
	common /huu_varXh/ Sub362, Sub367, Sub368, Sub369, Sub370
	common /huu_varXh/ Sub372, Sub373, Sub377, Sub378, Sub379
	common /huu_varXh/ Sub384, Sub385, Sub386, Sub387, Sub391
	common /huu_varXh/ Sub392, Sub393, Sub396, Sub397, Sub398
	common /huu_varXh/ Sub403, Sub405, Sub406, Sub407, Sub422
	common /huu_varXh/ Sub423, Sub431, Sub437, Sub438, Sub439
	common /huu_varXh/ Sub440, Sub441, Sub445, Sub450, Sub453
	common /huu_varXh/ Sub454, Sub455, Sub457, Sub462, Sub464
	common /huu_varXh/ Sub468, Sub469, Sub470, Sub473, Sub474
	common /huu_varXh/ Sub475, Sub476, Sub482, Sub488, Sub489
	common /huu_varXh/ Sub490, Sub496, Sub497, Sub498, Sub499
	common /huu_varXh/ Sub500, Sub501, Sub516, Sub526, Sub530
	common /huu_varXh/ Sub535, Sub538, Sub539, Sub540, Sub541
	common /huu_varXh/ Sub542, Sub543, Sub548, Sub549, Sub554
	common /huu_varXh/ Sub560, Sub567, Sub568, Sub569, Sub572
	common /huu_varXh/ Sub576, Sub581, Sub582, Sub583, Sub584
	common /huu_varXh/ Sub586, Sub587, Sub588, Sub589, Sub592
	common /huu_varXh/ Sub595, Sub599, Sub602, Sub606, Sub608
	common /huu_varXh/ Sub610, Sub612, Sub613, Sub614, Sub615
	common /huu_varXh/ Sub616, Sub617, Sub620, Sub641, Sub652
	common /huu_varXh/ Sub653, Sub658, Sub659, Sub660, Sub661
	common /huu_varXh/ Sub662, Sub663, Sub664, Sub665, Sub688
	common /huu_varXh/ Sub689, Sub690, Sub691, Sub692, Sub693
	common /huu_varXh/ Sub695, Sub696, Sub697, Sub698, Sub699
	common /huu_varXh/ Sub700, Sub701, Sub702, Sub703, Sub704
	common /huu_varXh/ Sub705, Sub706, Sub707, Sub708, Sub709
	common /huu_varXh/ Sub713, Sub714, Sub715, Sub716, Sub717
	common /huu_varXh/ Sub718, Sub719, Sub720, Sub721, Sub722
	common /huu_varXh/ Sub723, Sub724, Sub725, Sub726, Sub727
	common /huu_varXh/ Sub728

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /huu_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /huu_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /huu_formfactors/ Ctree, Cloop, MatSUN

#endif

