#if 0
* huu-vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Feb-2015 17:22
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "huu-renconst.h"

	ComplexType Sub1, Sub2, Sub3
	ComplexType Sub192, Sub680, Sub338, Sub173, Sub168, Sub422
	ComplexType Sub73, Sub448, Sub482, Sub392, Sub94, Sub450
	ComplexType Sub362, Sub394, Sub390, Sub379, Sub479, Sub460
	ComplexType Sub371, Sub473, Sub553, Sub558, Sub546, Sub486
	ComplexType Sub365, Sub477, Sub373, Sub470, Sub569, Sub557
	ComplexType Sub555, Sub442, Sub335, Sub436, Sub435, Sub446
	ComplexType Sub357, Sub356, Sub572, Sub464, Sub465, Sub415
	ComplexType Sub407, Sub443, Sub447, Sub578, Sub462, Sub463
	ComplexType Sub413, Sub405, Sub438, Sub453, Sub574, Sub439
	ComplexType Sub418, Sub440, Sub414, Sub410, Sub406, Sub441
	ComplexType Sub457, Sub388, Sub266, Sub585, Sub576, Sub497
	ComplexType Sub492, Sub393, Sub412, Sub451, Sub472, Sub478
	ComplexType Sub545, Sub547, Sub459, Sub511, Sub389, Sub382
	ComplexType Sub499, Sub563, Sub567, Sub539, Sub537, Sub458
	ComplexType Sub260, Sub398, Sub455, Sub522, Sub532, Sub525
	ComplexType Sub533, Sub529, Sub535, Sub262, Sub521, Sub531
	ComplexType Sub552, Sub543, Sub544, Sub554, Sub587, Sub575
	ComplexType Sub579, Sub424, Sub363, Sub366, Sub426, Sub408
	ComplexType Sub416, Sub444, Sub466, Sub483, Sub502, Sub487
	ComplexType Sub505, Sub566, Sub570, Sub471, Sub498, Sub493
	ComplexType Sub474, Sub380, Sub372, Sub494, Sub381, Sub374
	ComplexType Sub565, Sub419, Sub541, Sub580, Sub538, Sub588
	ComplexType Sub581, Sub589, Sub503, Sub506, Sub484, Sub488
	ComplexType Sub368, Sub564, Sub568, Sub170, Sub166, Sub411
	ComplexType Sub190, Sub328, Sub417, Sub420, Sub199, Sub404
	ComplexType Sub193, Sub526, Sub534, Sub200, Sub234, Sub358
	ComplexType Sub530, Sub536, Sub171, Sub172, Sub165(3)
	ComplexType Sub195(3), Sub253(3), Sub235(3), Sub213(3)
	ComplexType Sub210(3), Sub238(3), Sub188(3), Sub247(3)
	ComplexType Sub201(3), Sub248(3), Sub226(3), Sub219(3)
	ComplexType Sub258(3), Sub223(3), Sub240(3), Sub242(3)
	ComplexType Sub265(3), Sub263(3), Sub267(3), Sub268(3)
	ComplexType Sub169(3), Sub275(3), Sub280(3), Sub279(3)
	ComplexType Sub283(3), Sub282(3), Sub252(3), Sub174(3)
	ComplexType Sub196(3), Sub254(3), Sub264(3), Sub269(3)
	ComplexType Sub284(3), Sub139(3), Sub138(3), Sub623(3)
	ComplexType Sub626(3), Sub142(3), Sub141(3), Sub612(3)
	ComplexType Sub615(3), Sub644(3), Sub647(3), Sub145(3)
	ComplexType Sub144(3), Sub654(3), Sub651(3), Sub82(3)
	ComplexType Sub85(3), Sub75(3), Sub78(3), Sub104(3)
	ComplexType Sub107(3), Sub97(3), Sub100(3), Sub118(3)
	ComplexType Sub121(3), Sub128(3), Sub125(3), Sub14(3)
	ComplexType Sub17(3), Sub7(3), Sub10(3), Sub36(3), Sub39(3)
	ComplexType Sub29(3), Sub32(3), Sub51(3), Sub54(3), Sub61(3)
	ComplexType Sub58(3), Sub292(4), Sub662(4), Sub290(4)
	ComplexType Sub295(4), Sub298(4), Sub307(4), Sub304(4)
	ComplexType Sub310(4), Sub313(4), Sub316(4), Sub302(4)
	ComplexType Sub291(4), Sub293(4), Sub296(4), Sub299(4)
	ComplexType Sub308(4), Sub303(4), Sub311(4), Sub314(4)
	ComplexType Sub317(4), Sub305(4), Sub140(6,3), Sub143(6,3)
	ComplexType Sub146(6,3), Sub663(6,4), Sub661(6,4)
	ComplexType Sub693(6,4), Sub692(6,4), Sub691(6,4)
	ComplexType Sub660(6,4), Sub665(6,4), Sub664(6,4)
	ComplexType Sub158(2,2), Sub157(2,2), Sub163(2,2)
	ComplexType Sub161(2,2), Sub148(2,2), Sub150(2,2)
	ComplexType Sub149(2,2), Sub152(2,2), Sub147(2,2)
	ComplexType Sub153(2,2), Sub155(2,2), Sub154(2,2), Sub5(3,3)
	ComplexType Sub4(3,3), Sub634(3,3), Sub616(3,3), Sub633(3,3)
	ComplexType Sub613(3,3), Sub627(3,3), Sub624(3,3)
	ComplexType Sub27(3,3), Sub26(3,3), Sub49(3,3), Sub655(3,3)
	ComplexType Sub48(3,3), Sub652(3,3), Sub648(3,3)
	ComplexType Sub645(3,3), Sub67(3,3), Sub66(3,3), Sub91(3,3)
	ComplexType Sub79(3,3), Sub90(3,3), Sub76(3,3), Sub86(3,3)
	ComplexType Sub83(3,3), Sub113(3,3), Sub101(3,3)
	ComplexType Sub112(3,3), Sub98(3,3), Sub108(3,3)
	ComplexType Sub105(3,3), Sub129(3,3), Sub126(3,3)
	ComplexType Sub122(3,3), Sub119(3,3), Sub134(3,3)
	ComplexType Sub133(3,3), Sub23(3,3), Sub11(3,3), Sub22(3,3)
	ComplexType Sub8(3,3), Sub18(3,3), Sub15(3,3), Sub45(3,3)
	ComplexType Sub33(3,3), Sub44(3,3), Sub30(3,3), Sub40(3,3)
	ComplexType Sub37(3,3), Sub70(3,3), Sub62(3,3), Sub69(3,3)
	ComplexType Sub59(3,3), Sub55(3,3), Sub52(3,3), Sub294(4,4)
	ComplexType Sub297(4,4), Sub300(4,4), Sub306(4,4)
	ComplexType Sub309(4,4), Sub312(4,4), Sub315(4,4)
	ComplexType Sub318(4,4), Sub326(4,4), Sub320(4,4)
	ComplexType Sub324(4,4), Sub323(4,4), Sub322(4,4)
	ComplexType Sub321(4,4), Sub74(6,6,3), Sub96(6,6,3)
	ComplexType Sub117(6,6,3), Sub596(6,2,3), Sub611(6,2,3)
	ComplexType Sub672(6,2,3), Sub617(6,3,3), Sub628(6,3,3)
	ComplexType Sub649(6,3,3), Sub656(6,3,3), Sub614(6,3,3)
	ComplexType Sub625(6,3,3), Sub646(6,3,3), Sub653(6,3,3)
	ComplexType Sub600(6,3,3), Sub603(6,3,3), Sub602(6,3,3)
	ComplexType Sub599(6,3,3), Sub609(6,3,3), Sub621(6,3,3)
	ComplexType Sub608(6,3,3), Sub620(6,3,3), Sub597(6,2,3)
	ComplexType Sub80(6,3,3), Sub87(6,3,3), Sub102(6,3,3)
	ComplexType Sub109(6,3,3), Sub123(6,3,3), Sub130(6,3,3)
	ComplexType Sub77(6,3,3), Sub84(6,3,3), Sub106(6,3,3)
	ComplexType Sub99(6,3,3), Sub120(6,3,3), Sub127(6,3,3)
	ComplexType Sub12(6,3,3), Sub19(6,3,3), Sub34(6,3,3)
	ComplexType Sub41(6,3,3), Sub56(6,3,3), Sub63(6,3,3)
	ComplexType Sub16(6,3,3), Sub9(6,3,3), Sub31(6,3,3)
	ComplexType Sub38(6,3,3), Sub53(6,3,3), Sub60(6,3,3)
	ComplexType Sub68(6,6,3,3), Sub6(6,6,3,3), Sub618(6,6,3,3)
	ComplexType Sub629(6,6,3,3), Sub28(6,6,3,3), Sub635(6,6,3,3)
	ComplexType Sub650(6,6,3,3), Sub657(6,6,3,3), Sub50(6,6,3,3)
	ComplexType Sub659(6,6,3,3), Sub658(6,6,3,3), Sub81(6,6,3,3)
	ComplexType Sub88(6,6,3,3), Sub92(6,6,3,3), Sub103(6,6,3,3)
	ComplexType Sub110(6,6,3,3), Sub114(6,6,3,3)
	ComplexType Sub124(6,6,3,3), Sub131(6,6,3,3)
	ComplexType Sub135(6,6,3,3), Sub601(6,6,3,3)
	ComplexType Sub604(6,6,3,3), Sub606(6,6,3,3)
	ComplexType Sub111(6,6,3,3), Sub132(6,6,3,3)
	ComplexType Sub605(6,6,3,3), Sub89(6,6,3,3), Sub115(6,6,3,3)
	ComplexType Sub136(6,6,3,3), Sub607(6,6,3,3), Sub93(6,6,3,3)
	ComplexType Sub13(6,6,3,3), Sub20(6,6,3,3), Sub24(6,6,3,3)
	ComplexType Sub35(6,6,3,3), Sub42(6,6,3,3), Sub46(6,6,3,3)
	ComplexType Sub57(6,6,3,3), Sub64(6,6,3,3), Sub610(6,6,3,3)
	ComplexType Sub622(6,6,3,3), Sub632(6,6,3,3), Sub71(6,6,3,3)
	ComplexType Sub21(6,6,3,3), Sub43(6,6,3,3), Sub65(6,6,3,3)
	ComplexType Sub25(6,6,3,3), Sub47(6,6,3,3)
	ComplexType Sub72(6,6,3,3,3,3), Sub329, Sub523, Sub519
	ComplexType Sub425, Sub485, Sub504, Sub364, Sub527, Sub281
	ComplexType Sub454, Sub397, Sub421, Sub228, Sub202
	ComplexType Sub277(3), Sub159(2,2), Sub160(2,2), Sub151(2,2)
	ComplexType Sub156(2,2), Sub301(4,4), Sub319(4,4), Sub520
	ComplexType Sub524, Sub528, Sub336, Sub395, Sub449
	ComplexType pave1(6,6), pave2(6,6), pave3(6,6), pave4(6,6)
	ComplexType pave5(6,6), pave6(6,6), pave7(6), pave8(6)
	ComplexType pave9(6), pave10(2), pave11(2,2), pave12(2,2)
	ComplexType pave13(4), pave14(4,4), pave15(4,4)
	ComplexType pave16(Ncc,6,6,2), pave17(Ncc,6,6,4)
	ComplexType pave18(Ncc,6,6), pave19(6,2), pave20(6,4)
	ComplexType pave21, pave22, pave23, pave24, pave25, pave26
	ComplexType pave27, pave28, pave29, pave30, pave31, pave32
	ComplexType pave33, pave34(Ncc), pave35(Ncc), pave36(Ncc)
	ComplexType pave37(Ncc), pave38(Ncc), pave39(Ncc)
	ComplexType pave40(Ncc), pave41(Ncc), pave42(Ncc)
	ComplexType pave43(Ncc), pave44(Ncc), pave45(Ncc)
	ComplexType pave46(Ncc), pave47(Ncc), pave48(Ncc)
	ComplexType pave49(Ncc), pave50(Ncc), pave51, pave52(Ncc)
	ComplexType pave53(Ncc), pave54(Ncc), pave55(Ncc), pave56(3)
	ComplexType pave57(3), pave58(3), pave59(3), pave60(3)
	ComplexType pave61(3), pave62(3), pave63(3), pave64(3)
	ComplexType pave65(3), pave66(3), pave67(Ncc,3)
	ComplexType pave68(Ncc,3), pave69(Ncc,3), pave70(Ncc,3)
	ComplexType pave71(Ncc,3), pave72(Ncc,3), pave73(3)
	ComplexType pave74(3), pave75, pave76, pave77(Ncc)
	ComplexType pave78(Ncc), pave79(Ncc), pave80(Ncc,6,4,4)
	ComplexType pave81(Ncc,6,2,2), pave82, pave83, pave84
	ComplexType pave85, pave86, pave87, pave88(Ncc,3)
	ComplexType pave89(Ncc,3), pave90(3)
	common /huu_varXs/ Sub1, Sub2, Sub3, Sub192, Sub680, Sub338
	common /huu_varXs/ Sub173, Sub168, Sub422, Sub73, Sub448
	common /huu_varXs/ Sub482, Sub392, Sub94, Sub450, Sub362
	common /huu_varXs/ Sub394, Sub390, Sub379, Sub479, Sub460
	common /huu_varXs/ Sub371, Sub473, Sub553, Sub558, Sub546
	common /huu_varXs/ Sub486, Sub365, Sub477, Sub373, Sub470
	common /huu_varXs/ Sub569, Sub557, Sub555, Sub442, Sub335
	common /huu_varXs/ Sub436, Sub435, Sub446, Sub357, Sub356
	common /huu_varXs/ Sub572, Sub464, Sub465, Sub415, Sub407
	common /huu_varXs/ Sub443, Sub447, Sub578, Sub462, Sub463
	common /huu_varXs/ Sub413, Sub405, Sub438, Sub453, Sub574
	common /huu_varXs/ Sub439, Sub418, Sub440, Sub414, Sub410
	common /huu_varXs/ Sub406, Sub441, Sub457, Sub388, Sub266
	common /huu_varXs/ Sub585, Sub576, Sub497, Sub492, Sub393
	common /huu_varXs/ Sub412, Sub451, Sub472, Sub478, Sub545
	common /huu_varXs/ Sub547, Sub459, Sub511, Sub389, Sub382
	common /huu_varXs/ Sub499, Sub563, Sub567, Sub539, Sub537
	common /huu_varXs/ Sub458, Sub260, Sub398, Sub455, Sub522
	common /huu_varXs/ Sub532, Sub525, Sub533, Sub529, Sub535
	common /huu_varXs/ Sub262, Sub521, Sub531, Sub552, Sub543
	common /huu_varXs/ Sub544, Sub554, Sub587, Sub575, Sub579
	common /huu_varXs/ Sub424, Sub363, Sub366, Sub426, Sub408
	common /huu_varXs/ Sub416, Sub444, Sub466, Sub483, Sub502
	common /huu_varXs/ Sub487, Sub505, Sub566, Sub570, Sub471
	common /huu_varXs/ Sub498, Sub493, Sub474, Sub380, Sub372
	common /huu_varXs/ Sub494, Sub381, Sub374, Sub565, Sub419
	common /huu_varXs/ Sub541, Sub580, Sub538, Sub588, Sub581
	common /huu_varXs/ Sub589, Sub503, Sub506, Sub484, Sub488
	common /huu_varXs/ Sub368, Sub564, Sub568, Sub170, Sub166
	common /huu_varXs/ Sub411, Sub190, Sub328, Sub417, Sub420
	common /huu_varXs/ Sub199, Sub404, Sub193, Sub526, Sub534
	common /huu_varXs/ Sub200, Sub234, Sub358, Sub530, Sub536
	common /huu_varXs/ Sub171, Sub172, Sub165, Sub195, Sub253
	common /huu_varXs/ Sub235, Sub213, Sub210, Sub238, Sub188
	common /huu_varXs/ Sub247, Sub201, Sub248, Sub226, Sub219
	common /huu_varXs/ Sub258, Sub223, Sub240, Sub242, Sub265
	common /huu_varXs/ Sub263, Sub267, Sub268, Sub169, Sub275
	common /huu_varXs/ Sub280, Sub279, Sub283, Sub282, Sub252
	common /huu_varXs/ Sub174, Sub196, Sub254, Sub264, Sub269
	common /huu_varXs/ Sub284, Sub139, Sub138, Sub623, Sub626
	common /huu_varXs/ Sub142, Sub141, Sub612, Sub615, Sub644
	common /huu_varXs/ Sub647, Sub145, Sub144, Sub654, Sub651
	common /huu_varXs/ Sub82, Sub85, Sub75, Sub78, Sub104
	common /huu_varXs/ Sub107, Sub97, Sub100, Sub118, Sub121
	common /huu_varXs/ Sub128, Sub125, Sub14, Sub17, Sub7, Sub10
	common /huu_varXs/ Sub36, Sub39, Sub29, Sub32, Sub51, Sub54
	common /huu_varXs/ Sub61, Sub58, Sub292, Sub662, Sub290
	common /huu_varXs/ Sub295, Sub298, Sub307, Sub304, Sub310
	common /huu_varXs/ Sub313, Sub316, Sub302, Sub291, Sub293
	common /huu_varXs/ Sub296, Sub299, Sub308, Sub303, Sub311
	common /huu_varXs/ Sub314, Sub317, Sub305, Sub140, Sub143
	common /huu_varXs/ Sub146, Sub663, Sub661, Sub693, Sub692
	common /huu_varXs/ Sub691, Sub660, Sub665, Sub664, Sub158
	common /huu_varXs/ Sub157, Sub163, Sub161, Sub148, Sub150
	common /huu_varXs/ Sub149, Sub152, Sub147, Sub153, Sub155
	common /huu_varXs/ Sub154, Sub5, Sub4, Sub634, Sub616
	common /huu_varXs/ Sub633, Sub613, Sub627, Sub624, Sub27
	common /huu_varXs/ Sub26, Sub49, Sub655, Sub48, Sub652
	common /huu_varXs/ Sub648, Sub645, Sub67, Sub66, Sub91
	common /huu_varXs/ Sub79, Sub90, Sub76, Sub86, Sub83, Sub113
	common /huu_varXs/ Sub101, Sub112, Sub98, Sub108, Sub105
	common /huu_varXs/ Sub129, Sub126, Sub122, Sub119, Sub134
	common /huu_varXs/ Sub133, Sub23, Sub11, Sub22, Sub8, Sub18
	common /huu_varXs/ Sub15, Sub45, Sub33, Sub44, Sub30, Sub40
	common /huu_varXs/ Sub37, Sub70, Sub62, Sub69, Sub59, Sub55
	common /huu_varXs/ Sub52, Sub294, Sub297, Sub300, Sub306
	common /huu_varXs/ Sub309, Sub312, Sub315, Sub318, Sub326
	common /huu_varXs/ Sub320, Sub324, Sub323, Sub322, Sub321
	common /huu_varXs/ Sub74, Sub96, Sub117, Sub596, Sub611
	common /huu_varXs/ Sub672, Sub617, Sub628, Sub649, Sub656
	common /huu_varXs/ Sub614, Sub625, Sub646, Sub653, Sub600
	common /huu_varXs/ Sub603, Sub602, Sub599, Sub609, Sub621
	common /huu_varXs/ Sub608, Sub620, Sub597, Sub80, Sub87
	common /huu_varXs/ Sub102, Sub109, Sub123, Sub130, Sub77
	common /huu_varXs/ Sub84, Sub106, Sub99, Sub120, Sub127
	common /huu_varXs/ Sub12, Sub19, Sub34, Sub41, Sub56, Sub63
	common /huu_varXs/ Sub16, Sub9, Sub31, Sub38, Sub53, Sub60
	common /huu_varXs/ Sub68, Sub6, Sub618, Sub629, Sub28
	common /huu_varXs/ Sub635, Sub650, Sub657, Sub50, Sub659
	common /huu_varXs/ Sub658, Sub81, Sub88, Sub92, Sub103
	common /huu_varXs/ Sub110, Sub114, Sub124, Sub131, Sub135
	common /huu_varXs/ Sub601, Sub604, Sub606, Sub111, Sub132
	common /huu_varXs/ Sub605, Sub89, Sub115, Sub136, Sub607
	common /huu_varXs/ Sub93, Sub13, Sub20, Sub24, Sub35, Sub42
	common /huu_varXs/ Sub46, Sub57, Sub64, Sub610, Sub622
	common /huu_varXs/ Sub632, Sub71, Sub21, Sub43, Sub65, Sub25
	common /huu_varXs/ Sub47, Sub72, Sub329, Sub523, Sub519
	common /huu_varXs/ Sub425, Sub485, Sub504, Sub364, Sub527
	common /huu_varXs/ Sub281, Sub454, Sub397, Sub421, Sub228
	common /huu_varXs/ Sub202, Sub277, Sub159, Sub160, Sub151
	common /huu_varXs/ Sub156, Sub301, Sub319, Sub520, Sub524
	common /huu_varXs/ Sub528, Sub336, Sub395, Sub449, pave1
	common /huu_varXs/ pave2, pave3, pave4, pave5, pave6, pave7
	common /huu_varXs/ pave8, pave9, pave10, pave11, pave12
	common /huu_varXs/ pave13, pave14, pave15, pave16, pave17
	common /huu_varXs/ pave18, pave19, pave20, pave21, pave22
	common /huu_varXs/ pave23, pave24, pave25, pave26, pave27
	common /huu_varXs/ pave28, pave29, pave30, pave31, pave32
	common /huu_varXs/ pave33, pave34, pave35, pave36, pave37
	common /huu_varXs/ pave38, pave39, pave40, pave41, pave42
	common /huu_varXs/ pave43, pave44, pave45, pave46, pave47
	common /huu_varXs/ pave48, pave49, pave50, pave51, pave52
	common /huu_varXs/ pave53, pave54, pave55, pave56, pave57
	common /huu_varXs/ pave58, pave59, pave60, pave61, pave62
	common /huu_varXs/ pave63, pave64, pave65, pave66, pave67
	common /huu_varXs/ pave68, pave69, pave70, pave71, pave72
	common /huu_varXs/ pave73, pave74, pave75, pave76, pave77
	common /huu_varXs/ pave78, pave79, pave80, pave81, pave82
	common /huu_varXs/ pave83, pave84, pave85, pave86, pave87
	common /huu_varXs/ pave88, pave89, pave90

	ComplexType F1, F2
	ComplexType Sub437, Sub237, Sub349, Sub369, Sub377, Sub385
	ComplexType Sub542, Sub548, Sub571, Sub353, Sub182, Sub351
	ComplexType Sub340, Sub343, Sub337, Sub345, Sub352, Sub355
	ComplexType Sub391, Sub396, Sub399, Sub468, Sub452, Sub456
	ComplexType Sub461, Sub445, Sub387, Sub469, Sub512, Sub361
	ComplexType Sub179, Sub176, Sub177, Sub378, Sub370, Sub423
	ComplexType Sub592, Sub334, Sub347, Sub490, Sub508, Sub400
	ComplexType Sub562, Sub491, Sub509, Sub403, Sub401, Sub595
	ComplexType Sub518, Sub344, Sub332, Sub333, Sub341, Sub346
	ComplexType Sub342, Sub180, Sub183, Sub184, Sub330, Sub339
	ComplexType Sub367, Sub427, Sub376, Sub384, Sub434, Sub430
	ComplexType Sub432, Sub510, Sub481, Sub489, Sub476, Sub501
	ComplexType Sub507, Sub496, Sub514, Sub590, Sub582, Sub556
	ComplexType Sub559, Sub550, Sub561, Sub383, Sub375, Sub431
	ComplexType Sub429, Sub593, Sub475, Sub495, Sub480, Sub500
	ComplexType Sub251, Sub274, Sub191, Sub244, Sub230, Sub218
	ComplexType Sub246, Sub257, Sub586, Sub560, Sub549, Sub551
	ComplexType Sub428, Sub516, Sub584, Sub573, Sub577, Sub331
	ComplexType Sub515, Sub513, Sub360, Sub181(3)
	ComplexType Sub194(3), Sub215(3)
	ComplexType Sub245(3), Sub231(3)
	ComplexType Sub222(3), Sub207(3)
	ComplexType Sub208(3), Sub178(3)
	ComplexType Sub185(3), Sub175(3)
	ComplexType Sub187(3), Sub189(3)
	ComplexType Sub197(3), Sub198(3)
	ComplexType Sub203(3), Sub204(3)
	ComplexType Sub205(3), Sub209(3)
	ComplexType Sub211(3), Sub212(3)
	ComplexType Sub214(3), Sub216(3)
	ComplexType Sub217(3), Sub220(3)
	ComplexType Sub221(3), Sub224(3)
	ComplexType Sub225(3), Sub227(3)
	ComplexType Sub232(3), Sub233(3)
	ComplexType Sub236(3), Sub239(3)
	ComplexType Sub241(3), Sub243(3)
	ComplexType Sub261(3), Sub249(3)
	ComplexType Sub250(3), Sub255(3)
	ComplexType Sub256(3), Sub259(3)
	ComplexType Sub271(3), Sub272(3)
	ComplexType Sub276(3), Sub278(3)
	ComplexType Sub286(3), Sub287(3)
	ComplexType Sub167(3), Sub669(6,6)
	ComplexType Sub670(6,6), Sub671(6,6)
	ComplexType Sub668(6,6,4), Sub666(6,6,4)
	ComplexType Sub667(6,6,4), Sub699(6,4,4)
	ComplexType Sub698(6,4,4), Sub695(6,4,4)
	ComplexType Sub696(6,4,4), Sub703(6,4,4)
	ComplexType Sub694(6,4,4), Sub706(6,4,4)
	ComplexType Sub702(6,4,4), Sub697(6,4,4)
	ComplexType Sub700(6,4,4), Sub707(6,4,4)
	ComplexType Sub704(6,4,4), Sub705(6,4,4)
	ComplexType Sub708(6,4,4), Sub709(6,4,4)
	ComplexType Sub598(6,6,2,3,3), Sub137(6,6,3,3,3)
	ComplexType Sub95(6,6,3,3,3), Sub116(6,6,3,3,3)
	ComplexType Sub675(6,2,2,3,3), Sub678(6,2,2,3,3)
	ComplexType Sub679(6,2,2,3,3), Sub682(6,2,2,3,3)
	ComplexType Sub684(6,2,2,3,3), Sub687(6,2,2,3,3)
	ComplexType Sub688(6,2,2,3,3), Sub689(6,2,2,3,3)
	ComplexType Sub676(6,2,2,3,3), Sub673(6,2,2,3,3)
	ComplexType Sub686(6,2,2,3,3), Sub674(6,2,2,3,3)
	ComplexType Sub681(6,2,2,3,3), Sub677(6,2,2,3,3)
	ComplexType Sub683(6,2,2,3,3)
	ComplexType Sub643(6,6,2,3,3,3,3)
	ComplexType Sub619(6,6,2,3,3,3,3)
	ComplexType Sub638(6,6,2,3,3,3,3)
	ComplexType Sub630(6,6,2,3,3,3,3)
	ComplexType Sub639(6,6,2,3,3,3,3)
	ComplexType Sub636(6,6,2,3,3,3,3)
	ComplexType Sub641(6,6,2,3,3,3,3)
	ComplexType Sub631(6,6,2,3,3,3,3)
	ComplexType Sub640(6,6,2,3,3,3,3)
	ComplexType Sub637(6,6,2,3,3,3,3)
	ComplexType Sub642(6,6,2,3,3,3,3), Sub517, Sub359
	ComplexType Sub594, Sub402, Sub433, Sub386, Sub583, Sub591
	ComplexType Sub273(3), Sub186(3)
	ComplexType Sub270(3), Sub285(3)
	ComplexType Sub701(6,4,4), Sub710(6,4,4)
	ComplexType Sub685(6,2,2,3,3), Sub690(6,2,2,3,3)
	ComplexType Sub348, Sub206(3), Sub289(3)
	ComplexType Sub162(2,2), Sub327(4,4), Sub467
	ComplexType Sub288(3), Sub164(2,2)
	ComplexType Sub325(4,4), Sub229(3)
	common /huu_varXh/ F1, F2, Sub437, Sub237, Sub349, Sub369
	common /huu_varXh/ Sub377, Sub385, Sub542, Sub548, Sub571
	common /huu_varXh/ Sub353, Sub182, Sub351, Sub340, Sub343
	common /huu_varXh/ Sub337, Sub345, Sub352, Sub355, Sub391
	common /huu_varXh/ Sub396, Sub399, Sub468, Sub452, Sub456
	common /huu_varXh/ Sub461, Sub445, Sub387, Sub469, Sub512
	common /huu_varXh/ Sub361, Sub179, Sub176, Sub177, Sub378
	common /huu_varXh/ Sub370, Sub423, Sub592, Sub334, Sub347
	common /huu_varXh/ Sub490, Sub508, Sub400, Sub562, Sub491
	common /huu_varXh/ Sub509, Sub403, Sub401, Sub595, Sub518
	common /huu_varXh/ Sub344, Sub332, Sub333, Sub341, Sub346
	common /huu_varXh/ Sub342, Sub180, Sub183, Sub184, Sub330
	common /huu_varXh/ Sub339, Sub367, Sub427, Sub376, Sub384
	common /huu_varXh/ Sub434, Sub430, Sub432, Sub510, Sub481
	common /huu_varXh/ Sub489, Sub476, Sub501, Sub507, Sub496
	common /huu_varXh/ Sub514, Sub590, Sub582, Sub556, Sub559
	common /huu_varXh/ Sub550, Sub561, Sub383, Sub375, Sub431
	common /huu_varXh/ Sub429, Sub593, Sub475, Sub495, Sub480
	common /huu_varXh/ Sub500, Sub251, Sub274, Sub191, Sub244
	common /huu_varXh/ Sub230, Sub218, Sub246, Sub257, Sub586
	common /huu_varXh/ Sub560, Sub549, Sub551, Sub428, Sub516
	common /huu_varXh/ Sub584, Sub573, Sub577, Sub331, Sub515
	common /huu_varXh/ Sub513, Sub360, Sub181, Sub194, Sub215
	common /huu_varXh/ Sub245, Sub231, Sub222, Sub207, Sub208
	common /huu_varXh/ Sub178, Sub185, Sub175, Sub187, Sub189
	common /huu_varXh/ Sub197, Sub198, Sub203, Sub204, Sub205
	common /huu_varXh/ Sub209, Sub211, Sub212, Sub214, Sub216
	common /huu_varXh/ Sub217, Sub220, Sub221, Sub224, Sub225
	common /huu_varXh/ Sub227, Sub232, Sub233, Sub236, Sub239
	common /huu_varXh/ Sub241, Sub243, Sub261, Sub249, Sub250
	common /huu_varXh/ Sub255, Sub256, Sub259, Sub271, Sub272
	common /huu_varXh/ Sub276, Sub278, Sub286, Sub287, Sub167
	common /huu_varXh/ Sub669, Sub670, Sub671, Sub668, Sub666
	common /huu_varXh/ Sub667, Sub699, Sub698, Sub695, Sub696
	common /huu_varXh/ Sub703, Sub694, Sub706, Sub702, Sub697
	common /huu_varXh/ Sub700, Sub707, Sub704, Sub705, Sub708
	common /huu_varXh/ Sub709, Sub598, Sub137, Sub95, Sub116
	common /huu_varXh/ Sub675, Sub678, Sub679, Sub682, Sub684
	common /huu_varXh/ Sub687, Sub688, Sub689, Sub676, Sub673
	common /huu_varXh/ Sub686, Sub674, Sub681, Sub677, Sub683
	common /huu_varXh/ Sub643, Sub619, Sub638, Sub630, Sub639
	common /huu_varXh/ Sub636, Sub641, Sub631, Sub640, Sub637
	common /huu_varXh/ Sub642, Sub517, Sub359, Sub594, Sub402
	common /huu_varXh/ Sub433, Sub386, Sub583, Sub591, Sub273
	common /huu_varXh/ Sub186, Sub270, Sub285, Sub701, Sub710
	common /huu_varXh/ Sub685, Sub690, Sub348, Sub206, Sub289
	common /huu_varXh/ Sub162, Sub327, Sub467, Sub288, Sub164
	common /huu_varXh/ Sub325, Sub229

	integer seq(2), Hel(3)
	common /huu_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /huu_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /huu_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /huu_formfactors/ Ctree, Cloop, MatSUN

#endif
