#if 0
* hdd-vars.h
* variable declarations
* generated by FormCalc 8.4 on 30-Apr-2014 7:45
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hdd-renconst.h"

	ComplexType Sub365, Sub407, Sub333, Sub335, Sub332, Sub453
	ComplexType Sub239, Sub241, Sub477, Sub422, Sub353, Sub330
	ComplexType Sub331, Sub481, Sub456, Sub478, Sub480, Sub394
	ComplexType Sub404, Sub446, Sub398, Sub395, Sub447, Sub448
	ComplexType Sub454, Sub482, Sub450, Sub405, Sub451, Sub402
	ComplexType Sub399, Sub396, Sub452, Sub460, Sub315, Sub325
	ComplexType Sub318, Sub326, Sub322, Sub328, Sub314, Sub324
	ComplexType Sub379, Sub582, Sub410, Sub437, Sub438, Sub479
	ComplexType Sub216, Sub184, Sub183, Sub219, Sub5, Sub135
	ComplexType Sub400, Sub165, Sub190, Sub167, Sub364, Sub6
	ComplexType Sub403, Sub406, Sub393, Sub434, Sub185, Sub319
	ComplexType Sub327, Sub334, Sub122, Sub584, Sub144, Sub248
	ComplexType Sub246, Sub145, Sub140, Sub146, Sub214, Sub323
	ComplexType Sub329, Sub134(3), Sub136(3), Sub141(3)
	ComplexType Sub200(3), Sub218(3), Sub158(3), Sub221(3)
	ComplexType Sub217(3), Sub192(3), Sub196(3), Sub232(3)
	ComplexType Sub231(3), Sub191(3), Sub195(3), Sub240(3)
	ComplexType Sub242(3), Sub247(3), Sub249(3), Sub263(3)
	ComplexType Sub252(3), Sub264(3), Sub253(3), Sub243(3)
	ComplexType Sub137(3), Sub138(3), Sub143(3), Sub222(3)
	ComplexType Sub255(3), Sub188(3), Sub193(3), Sub197(3)
	ComplexType Sub237(3), Sub256(3), Sub142(3), Sub261(3)
	ComplexType Sub109(3), Sub108(3), Sub546(3), Sub550(3)
	ComplexType Sub112(3), Sub111(3), Sub545(3), Sub549(3)
	ComplexType Sub503(3), Sub506(3), Sub115(3), Sub114(3)
	ComplexType Sub521(3), Sub518(3), Sub547(3), Sub551(3)
	ComplexType Sub63(3), Sub67(3), Sub66(3), Sub62(3), Sub79(3)
	ComplexType Sub83(3), Sub82(3), Sub78(3), Sub496(3)
	ComplexType Sub94(3), Sub98(3), Sub95(3), Sub99(3), Sub64(3)
	ComplexType Sub68(3), Sub80(3), Sub84(3), Sub96(3)
	ComplexType Sub497(3), Sub100(3), Sub8(3), Sub12(3)
	ComplexType Sub11(3), Sub7(3), Sub26(3), Sub30(3), Sub29(3)
	ComplexType Sub25(3), Sub510(3), Sub43(3), Sub47(3)
	ComplexType Sub44(3), Sub48(3), Sub13(3), Sub27(3), Sub31(3)
	ComplexType Sub45(3), Sub49(3), Sub9(3), Sub559(4)
	ComplexType Sub275(4), Sub273(4), Sub278(4), Sub281(4)
	ComplexType Sub290(4), Sub561(4), Sub287(4), Sub293(4)
	ComplexType Sub296(4), Sub299(4), Sub285(4), Sub274(4)
	ComplexType Sub276(4), Sub279(4), Sub282(4), Sub291(4)
	ComplexType Sub595(4), Sub286(4), Sub294(4), Sub297(4)
	ComplexType Sub300(4), Sub288(4), Sub110(6,3), Sub113(6,3)
	ComplexType Sub116(6,3), Sub65(6,3), Sub69(6,3), Sub81(6,3)
	ComplexType Sub85(6,3), Sub101(6,3), Sub97(6,3), Sub10(6,3)
	ComplexType Sub14(6,3), Sub28(6,3), Sub32(6,3), Sub50(6,3)
	ComplexType Sub46(6,3), Sub560(6,4), Sub563(6,4)
	ComplexType Sub597(6,4), Sub596(6,4), Sub548(6,3)
	ComplexType Sub552(6,3), Sub498(6,3), Sub495(6,3)
	ComplexType Sub558(6,4), Sub562(6,4), Sub129(2,2)
	ComplexType Sub125(2,2), Sub132(2,2), Sub128(2,2)
	ComplexType Sub130(2,2), Sub131(2,2), Sub124(2,2)
	ComplexType Sub117(2,2), Sub573(2,2), Sub121(2,2)
	ComplexType Sub571(2,2), Sub585(2,2), Sub120(2,2), Sub2(3,3)
	ComplexType Sub1(3,3), Sub556(3,3), Sub555(3,3), Sub22(3,3)
	ComplexType Sub21(3,3), Sub40(3,3), Sub522(3,3), Sub39(3,3)
	ComplexType Sub519(3,3), Sub507(3,3), Sub504(3,3)
	ComplexType Sub54(3,3), Sub53(3,3), Sub73(3,3), Sub72(3,3)
	ComplexType Sub89(3,3), Sub88(3,3), Sub105(3,3), Sub104(3,3)
	ComplexType Sub18(3,3), Sub17(3,3), Sub36(3,3), Sub35(3,3)
	ComplexType Sub57(3,3), Sub527(3,3), Sub56(3,3), Sub525(3,3)
	ComplexType Sub513(3,3), Sub511(3,3), Sub534(3,3)
	ComplexType Sub533(3,3), Sub277(4,4), Sub280(4,4)
	ComplexType Sub283(4,4), Sub289(4,4), Sub292(4,4)
	ComplexType Sub295(4,4), Sub298(4,4), Sub301(4,4)
	ComplexType Sub309(4,4), Sub303(4,4), Sub307(4,4)
	ComplexType Sub306(4,4), Sub310(4,4), Sub311(4,4)
	ComplexType Sub305(4,4), Sub304(4,4), Sub553(6,6,3)
	ComplexType Sub60(6,6,3), Sub76(6,6,3), Sub92(6,6,3)
	ComplexType Sub499(6,6,3), Sub70(6,6,3), Sub86(6,6,3)
	ComplexType Sub102(6,6,3), Sub15(6,6,3), Sub33(6,6,3)
	ComplexType Sub51(6,6,3), Sub491(6,2,3), Sub516(6,2,3)
	ComplexType Sub572(6,2,3), Sub508(6,3,3), Sub523(6,3,3)
	ComplexType Sub505(6,3,3), Sub520(6,3,3), Sub514(6,3,3)
	ComplexType Sub528(6,3,3), Sub512(6,3,3), Sub526(6,3,3)
	ComplexType Sub492(6,2,3), Sub554(6,6,3,3), Sub55(6,6,3,3)
	ComplexType Sub3(6,6,3,3), Sub544(6,6,3,3), Sub23(6,6,3,3)
	ComplexType Sub557(6,6,3,3), Sub509(6,6,3,3)
	ComplexType Sub524(6,6,3,3), Sub41(6,6,3,3), Sub532(6,6,3,3)
	ComplexType Sub500(6,6,3,3), Sub71(6,6,3,3), Sub87(6,6,3,3)
	ComplexType Sub103(6,6,3,3), Sub61(6,6,3,3), Sub74(6,6,3,3)
	ComplexType Sub77(6,6,3,3), Sub90(6,6,3,3), Sub93(6,6,3,3)
	ComplexType Sub106(6,6,3,3), Sub494(6,6,3,3)
	ComplexType Sub501(6,6,3,3), Sub107(6,6,3,3)
	ComplexType Sub502(6,6,3,3), Sub75(6,6,3,3), Sub91(6,6,3,3)
	ComplexType Sub34(6,6,3,3), Sub16(6,6,3,3), Sub52(6,6,3,3)
	ComplexType Sub4(6,6,3,3), Sub19(6,6,3,3), Sub24(6,6,3,3)
	ComplexType Sub37(6,6,3,3), Sub42(6,6,3,3), Sub515(6,6,3,3)
	ComplexType Sub529(6,6,3,3), Sub535(6,6,3,3), Sub58(6,6,3,3)
	ComplexType Sub20(6,6,3,3), Sub38(6,6,3,3)
	ComplexType Sub59(6,6,3,3,3,3), Sub312, Sub316, Sub408
	ComplexType Sub320, Sub449, Sub397, Sub337, Sub423, Sub424
	ComplexType Sub236, Sub202, Sub171, Sub118, Sub173, Sub181
	ComplexType Sub230, Sub431, Sub119, Sub139, Sub123, Sub439
	ComplexType Sub258(3), Sub204(3), Sub260(3), Sub211(3)
	ComplexType Sub208(3), Sub259(3), Sub187(3), Sub186(3)
	ComplexType Sub162(3), Sub235(3), Sub233(3), Sub254(3)
	ComplexType Sub265(3), Sub244(3), Sub133(2,2), Sub127(2,2)
	ComplexType Sub126(2,2), Sub308(4,4), Sub284(4,4)
	ComplexType Sub302(4,4), Sub313, Sub317, Sub321, Sub336
	ComplexType Sub401, Sub386, Sub226, Sub169, Sub589
	ComplexType Sub160(3), Sub212(3), pave1(6,6), pave2(6,6)
	ComplexType pave3(6,6), pave4(6,6), pave5(6,6), pave6(6,6)
	ComplexType pave7(6), pave8(6), pave9(6), pave10(2)
	ComplexType pave11(2,2), pave12(2,2), pave13(4), pave14(4,4)
	ComplexType pave15(4,4), pave16(Ncc,6,6,2)
	ComplexType pave17(Ncc,6,6,4), pave18(Ncc,6,6), pave19(6,2)
	ComplexType pave20(6,4), pave21, pave22, pave23, pave24
	ComplexType pave25, pave26, pave27, pave28, pave29, pave30
	ComplexType pave31(Ncc), pave32(Ncc), pave33(Ncc)
	ComplexType pave34(Ncc), pave35, pave36(Ncc), pave37(Ncc)
	ComplexType pave38(Ncc), pave39(Ncc), pave40(Ncc)
	ComplexType pave41(Ncc), pave42(Ncc), pave43(Ncc)
	ComplexType pave44(Ncc), pave45(Ncc), pave46(Ncc)
	ComplexType pave47(Ncc), pave48(Ncc), pave49, pave50(Ncc)
	ComplexType pave51(Ncc), pave52(3), pave53(3), pave54(3)
	ComplexType pave55(3), pave56(3), pave57(3), pave58(3)
	ComplexType pave59(3), pave60(3), pave61(3), pave62(3)
	ComplexType pave63(3), pave64(Ncc,3), pave65(Ncc,3)
	ComplexType pave66(Ncc,3), pave67(Ncc,3), pave68(3)
	ComplexType pave69(3), pave70, pave71, pave72(Ncc)
	ComplexType pave73(Ncc), pave74(Ncc), pave75(Ncc)
	ComplexType pave76(Ncc,3), pave77(Ncc,3), pave78(Ncc,3)
	ComplexType pave79(Ncc,3), pave80(Ncc,6,4,4)
	ComplexType pave81(Ncc,6,2,2), pave82, pave83, pave84
	ComplexType pave85, pave86, pave87, pave88, pave89
	ComplexType pave90(Ncc)
	common /hdd_varXs/ Sub365, Sub407, Sub333, Sub335, Sub332
	common /hdd_varXs/ Sub453, Sub239, Sub241, Sub477, Sub422
	common /hdd_varXs/ Sub353, Sub330, Sub331, Sub481, Sub456
	common /hdd_varXs/ Sub478, Sub480, Sub394, Sub404, Sub446
	common /hdd_varXs/ Sub398, Sub395, Sub447, Sub448, Sub454
	common /hdd_varXs/ Sub482, Sub450, Sub405, Sub451, Sub402
	common /hdd_varXs/ Sub399, Sub396, Sub452, Sub460, Sub315
	common /hdd_varXs/ Sub325, Sub318, Sub326, Sub322, Sub328
	common /hdd_varXs/ Sub314, Sub324, Sub379, Sub582, Sub410
	common /hdd_varXs/ Sub437, Sub438, Sub479, Sub216, Sub184
	common /hdd_varXs/ Sub183, Sub219, Sub5, Sub135, Sub400
	common /hdd_varXs/ Sub165, Sub190, Sub167, Sub364, Sub6
	common /hdd_varXs/ Sub403, Sub406, Sub393, Sub434, Sub185
	common /hdd_varXs/ Sub319, Sub327, Sub334, Sub122, Sub584
	common /hdd_varXs/ Sub144, Sub248, Sub246, Sub145, Sub140
	common /hdd_varXs/ Sub146, Sub214, Sub323, Sub329, Sub134
	common /hdd_varXs/ Sub136, Sub141, Sub200, Sub218, Sub158
	common /hdd_varXs/ Sub221, Sub217, Sub192, Sub196, Sub232
	common /hdd_varXs/ Sub231, Sub191, Sub195, Sub240, Sub242
	common /hdd_varXs/ Sub247, Sub249, Sub263, Sub252, Sub264
	common /hdd_varXs/ Sub253, Sub243, Sub137, Sub138, Sub143
	common /hdd_varXs/ Sub222, Sub255, Sub188, Sub193, Sub197
	common /hdd_varXs/ Sub237, Sub256, Sub142, Sub261, Sub109
	common /hdd_varXs/ Sub108, Sub546, Sub550, Sub112, Sub111
	common /hdd_varXs/ Sub545, Sub549, Sub503, Sub506, Sub115
	common /hdd_varXs/ Sub114, Sub521, Sub518, Sub547, Sub551
	common /hdd_varXs/ Sub63, Sub67, Sub66, Sub62, Sub79, Sub83
	common /hdd_varXs/ Sub82, Sub78, Sub496, Sub94, Sub98, Sub95
	common /hdd_varXs/ Sub99, Sub64, Sub68, Sub80, Sub84, Sub96
	common /hdd_varXs/ Sub497, Sub100, Sub8, Sub12, Sub11, Sub7
	common /hdd_varXs/ Sub26, Sub30, Sub29, Sub25, Sub510, Sub43
	common /hdd_varXs/ Sub47, Sub44, Sub48, Sub13, Sub27, Sub31
	common /hdd_varXs/ Sub45, Sub49, Sub9, Sub559, Sub275
	common /hdd_varXs/ Sub273, Sub278, Sub281, Sub290, Sub561
	common /hdd_varXs/ Sub287, Sub293, Sub296, Sub299, Sub285
	common /hdd_varXs/ Sub274, Sub276, Sub279, Sub282, Sub291
	common /hdd_varXs/ Sub595, Sub286, Sub294, Sub297, Sub300
	common /hdd_varXs/ Sub288, Sub110, Sub113, Sub116, Sub65
	common /hdd_varXs/ Sub69, Sub81, Sub85, Sub101, Sub97, Sub10
	common /hdd_varXs/ Sub14, Sub28, Sub32, Sub50, Sub46, Sub560
	common /hdd_varXs/ Sub563, Sub597, Sub596, Sub548, Sub552
	common /hdd_varXs/ Sub498, Sub495, Sub558, Sub562, Sub129
	common /hdd_varXs/ Sub125, Sub132, Sub128, Sub130, Sub131
	common /hdd_varXs/ Sub124, Sub117, Sub573, Sub121, Sub571
	common /hdd_varXs/ Sub585, Sub120, Sub2, Sub1, Sub556
	common /hdd_varXs/ Sub555, Sub22, Sub21, Sub40, Sub522
	common /hdd_varXs/ Sub39, Sub519, Sub507, Sub504, Sub54
	common /hdd_varXs/ Sub53, Sub73, Sub72, Sub89, Sub88, Sub105
	common /hdd_varXs/ Sub104, Sub18, Sub17, Sub36, Sub35, Sub57
	common /hdd_varXs/ Sub527, Sub56, Sub525, Sub513, Sub511
	common /hdd_varXs/ Sub534, Sub533, Sub277, Sub280, Sub283
	common /hdd_varXs/ Sub289, Sub292, Sub295, Sub298, Sub301
	common /hdd_varXs/ Sub309, Sub303, Sub307, Sub306, Sub310
	common /hdd_varXs/ Sub311, Sub305, Sub304, Sub553, Sub60
	common /hdd_varXs/ Sub76, Sub92, Sub499, Sub70, Sub86
	common /hdd_varXs/ Sub102, Sub15, Sub33, Sub51, Sub491
	common /hdd_varXs/ Sub516, Sub572, Sub508, Sub523, Sub505
	common /hdd_varXs/ Sub520, Sub514, Sub528, Sub512, Sub526
	common /hdd_varXs/ Sub492, Sub554, Sub55, Sub3, Sub544
	common /hdd_varXs/ Sub23, Sub557, Sub509, Sub524, Sub41
	common /hdd_varXs/ Sub532, Sub500, Sub71, Sub87, Sub103
	common /hdd_varXs/ Sub61, Sub74, Sub77, Sub90, Sub93, Sub106
	common /hdd_varXs/ Sub494, Sub501, Sub107, Sub502, Sub75
	common /hdd_varXs/ Sub91, Sub34, Sub16, Sub52, Sub4, Sub19
	common /hdd_varXs/ Sub24, Sub37, Sub42, Sub515, Sub529
	common /hdd_varXs/ Sub535, Sub58, Sub20, Sub38, Sub59
	common /hdd_varXs/ Sub312, Sub316, Sub408, Sub320, Sub449
	common /hdd_varXs/ Sub397, Sub337, Sub423, Sub424, Sub236
	common /hdd_varXs/ Sub202, Sub171, Sub118, Sub173, Sub181
	common /hdd_varXs/ Sub230, Sub431, Sub119, Sub139, Sub123
	common /hdd_varXs/ Sub439, Sub258, Sub204, Sub260, Sub211
	common /hdd_varXs/ Sub208, Sub259, Sub187, Sub186, Sub162
	common /hdd_varXs/ Sub235, Sub233, Sub254, Sub265, Sub244
	common /hdd_varXs/ Sub133, Sub127, Sub126, Sub308, Sub284
	common /hdd_varXs/ Sub302, Sub313, Sub317, Sub321, Sub336
	common /hdd_varXs/ Sub401, Sub386, Sub226, Sub169, Sub589
	common /hdd_varXs/ Sub160, Sub212, pave1, pave2, pave3
	common /hdd_varXs/ pave4, pave5, pave6, pave7, pave8, pave9
	common /hdd_varXs/ pave10, pave11, pave12, pave13, pave14
	common /hdd_varXs/ pave15, pave16, pave17, pave18, pave19
	common /hdd_varXs/ pave20, pave21, pave22, pave23, pave24
	common /hdd_varXs/ pave25, pave26, pave27, pave28, pave29
	common /hdd_varXs/ pave30, pave31, pave32, pave33, pave34
	common /hdd_varXs/ pave35, pave36, pave37, pave38, pave39
	common /hdd_varXs/ pave40, pave41, pave42, pave43, pave44
	common /hdd_varXs/ pave45, pave46, pave47, pave48, pave49
	common /hdd_varXs/ pave50, pave51, pave52, pave53, pave54
	common /hdd_varXs/ pave55, pave56, pave57, pave58, pave59
	common /hdd_varXs/ pave60, pave61, pave62, pave63, pave64
	common /hdd_varXs/ pave65, pave66, pave67, pave68, pave69
	common /hdd_varXs/ pave70, pave71, pave72, pave73, pave74
	common /hdd_varXs/ pave75, pave76, pave77, pave78, pave79
	common /hdd_varXs/ pave80, pave81, pave82, pave83, pave84
	common /hdd_varXs/ pave85, pave86, pave87, pave88, pave89
	common /hdd_varXs/ pave90

	ComplexType F1, F2
	ComplexType Sub338, Sub354, Sub357, Sub346, Sub350, Sub362
	ComplexType Sub413, Sub414, Sub485, Sub489, Sub372, Sub421
	ComplexType Sub383, Sub384, Sub355, Sub378, Sub358, Sub443
	ComplexType Sub369, Sub419, Sub442, Sub381, Sub432, Sub388
	ComplexType Sub366, Sub342, Sub340, Sub349, Sub345, Sub343
	ComplexType Sub347, Sub351, Sub151, Sub153, Sub436, Sub149
	ComplexType Sub360, Sub490, Sub166, Sub178, Sub375, Sub371
	ComplexType Sub376, Sub373, Sub417, Sub412, Sub463, Sub464
	ComplexType Sub469, Sub470, Sub389, Sub418, Sub409, Sub416
	ComplexType Sub476, Sub483, Sub433, Sub444, Sub458, Sub466
	ComplexType Sub472, Sub486, Sub385, Sub387, Sub461, Sub429
	ComplexType Sub459, Sub462, Sub467, Sub473, Sub445, Sub425
	ComplexType Sub441, Sub391, Sub390, Sub415, Sub430, Sub427
	ComplexType Sub428, Sub150, Sub152, Sub148, Sub363, Sub367
	ComplexType Sub426, Sub487, Sub368, Sub435, Sub154(3)
	ComplexType Sub179(3), Sub175(3)
	ComplexType Sub172(3), Sub176(3)
	ComplexType Sub227(3), Sub170(3)
	ComplexType Sub205(3), Sub228(3)
	ComplexType Sub155(3), Sub156(3)
	ComplexType Sub157(3), Sub159(3)
	ComplexType Sub161(3), Sub163(3)
	ComplexType Sub168(3), Sub174(3)
	ComplexType Sub177(3), Sub182(3)
	ComplexType Sub189(3), Sub194(3)
	ComplexType Sub198(3), Sub201(3)
	ComplexType Sub203(3), Sub206(3)
	ComplexType Sub207(3), Sub209(3)
	ComplexType Sub210(3), Sub213(3)
	ComplexType Sub215(3), Sub220(3)
	ComplexType Sub224(3), Sub225(3)
	ComplexType Sub270(3), Sub229(3)
	ComplexType Sub234(3), Sub238(3)
	ComplexType Sub245(3), Sub250(3)
	ComplexType Sub257(3), Sub262(3)
	ComplexType Sub266(3), Sub267(3)
	ComplexType Sub268(3), Sub269(3)
	ComplexType Sub568(6,6), Sub569(6,6)
	ComplexType Sub570(6,6), Sub565(6,6,4)
	ComplexType Sub566(6,6,4), Sub564(6,6,4)
	ComplexType Sub567(6,6,4), Sub609(6,4,4)
	ComplexType Sub598(6,4,4), Sub606(6,4,4)
	ComplexType Sub603(6,4,4), Sub602(6,4,4)
	ComplexType Sub599(6,4,4), Sub600(6,4,4)
	ComplexType Sub601(6,4,4), Sub604(6,4,4)
	ComplexType Sub608(6,4,4), Sub610(6,4,4)
	ComplexType Sub611(6,4,4), Sub612(6,4,4)
	ComplexType Sub493(6,6,2,3,3), Sub576(6,2,2,3,3)
	ComplexType Sub579(6,2,2,3,3), Sub580(6,2,2,3,3)
	ComplexType Sub583(6,2,2,3,3), Sub587(6,2,2,3,3)
	ComplexType Sub588(6,2,2,3,3), Sub591(6,2,2,3,3)
	ComplexType Sub592(6,2,2,3,3), Sub593(6,2,2,3,3)
	ComplexType Sub575(6,2,2,3,3), Sub581(6,2,2,3,3)
	ComplexType Sub574(6,2,2,3,3), Sub578(6,2,2,3,3)
	ComplexType Sub577(6,2,2,3,3), Sub586(6,2,2,3,3)
	ComplexType Sub590(6,2,2,3,3)
	ComplexType Sub543(6,6,2,3,3,3,3)
	ComplexType Sub538(6,6,2,3,3,3,3)
	ComplexType Sub517(6,6,2,3,3,3,3)
	ComplexType Sub539(6,6,2,3,3,3,3)
	ComplexType Sub530(6,6,2,3,3,3,3)
	ComplexType Sub541(6,6,2,3,3,3,3)
	ComplexType Sub536(6,6,2,3,3,3,3)
	ComplexType Sub531(6,6,2,3,3,3,3)
	ComplexType Sub540(6,6,2,3,3,3,3)
	ComplexType Sub537(6,6,2,3,3,3,3)
	ComplexType Sub542(6,6,2,3,3,3,3), Sub361, Sub147
	ComplexType Sub457, Sub370, Sub374, Sub356, Sub465, Sub344
	ComplexType Sub348, Sub341, Sub339, Sub471, Sub359, Sub377
	ComplexType Sub440, Sub420, Sub468, Sub474, Sub382, Sub380
	ComplexType Sub411, Sub484, Sub455, Sub164(3)
	ComplexType Sub180(3), Sub271(3)
	ComplexType Sub199(3), Sub223(3)
	ComplexType Sub272(3), Sub605(6,4,4)
	ComplexType Sub607(6,4,4), Sub613(6,4,4)
	ComplexType Sub594(6,2,2,3,3), Sub352, Sub488, Sub392
	ComplexType Sub251(3), Sub475
	common /hdd_varXh/ F1, F2, Sub338, Sub354, Sub357, Sub346
	common /hdd_varXh/ Sub350, Sub362, Sub413, Sub414, Sub485
	common /hdd_varXh/ Sub489, Sub372, Sub421, Sub383, Sub384
	common /hdd_varXh/ Sub355, Sub378, Sub358, Sub443, Sub369
	common /hdd_varXh/ Sub419, Sub442, Sub381, Sub432, Sub388
	common /hdd_varXh/ Sub366, Sub342, Sub340, Sub349, Sub345
	common /hdd_varXh/ Sub343, Sub347, Sub351, Sub151, Sub153
	common /hdd_varXh/ Sub436, Sub149, Sub360, Sub490, Sub166
	common /hdd_varXh/ Sub178, Sub375, Sub371, Sub376, Sub373
	common /hdd_varXh/ Sub417, Sub412, Sub463, Sub464, Sub469
	common /hdd_varXh/ Sub470, Sub389, Sub418, Sub409, Sub416
	common /hdd_varXh/ Sub476, Sub483, Sub433, Sub444, Sub458
	common /hdd_varXh/ Sub466, Sub472, Sub486, Sub385, Sub387
	common /hdd_varXh/ Sub461, Sub429, Sub459, Sub462, Sub467
	common /hdd_varXh/ Sub473, Sub445, Sub425, Sub441, Sub391
	common /hdd_varXh/ Sub390, Sub415, Sub430, Sub427, Sub428
	common /hdd_varXh/ Sub150, Sub152, Sub148, Sub363, Sub367
	common /hdd_varXh/ Sub426, Sub487, Sub368, Sub435, Sub154
	common /hdd_varXh/ Sub179, Sub175, Sub172, Sub176, Sub227
	common /hdd_varXh/ Sub170, Sub205, Sub228, Sub155, Sub156
	common /hdd_varXh/ Sub157, Sub159, Sub161, Sub163, Sub168
	common /hdd_varXh/ Sub174, Sub177, Sub182, Sub189, Sub194
	common /hdd_varXh/ Sub198, Sub201, Sub203, Sub206, Sub207
	common /hdd_varXh/ Sub209, Sub210, Sub213, Sub215, Sub220
	common /hdd_varXh/ Sub224, Sub225, Sub270, Sub229, Sub234
	common /hdd_varXh/ Sub238, Sub245, Sub250, Sub257, Sub262
	common /hdd_varXh/ Sub266, Sub267, Sub268, Sub269, Sub568
	common /hdd_varXh/ Sub569, Sub570, Sub565, Sub566, Sub564
	common /hdd_varXh/ Sub567, Sub609, Sub598, Sub606, Sub603
	common /hdd_varXh/ Sub602, Sub599, Sub600, Sub601, Sub604
	common /hdd_varXh/ Sub608, Sub610, Sub611, Sub612, Sub493
	common /hdd_varXh/ Sub576, Sub579, Sub580, Sub583, Sub587
	common /hdd_varXh/ Sub588, Sub591, Sub592, Sub593, Sub575
	common /hdd_varXh/ Sub581, Sub574, Sub578, Sub577, Sub586
	common /hdd_varXh/ Sub590, Sub543, Sub538, Sub517, Sub539
	common /hdd_varXh/ Sub530, Sub541, Sub536, Sub531, Sub540
	common /hdd_varXh/ Sub537, Sub542, Sub361, Sub147, Sub457
	common /hdd_varXh/ Sub370, Sub374, Sub356, Sub465, Sub344
	common /hdd_varXh/ Sub348, Sub341, Sub339, Sub471, Sub359
	common /hdd_varXh/ Sub377, Sub440, Sub420, Sub468, Sub474
	common /hdd_varXh/ Sub382, Sub380, Sub411, Sub484, Sub455
	common /hdd_varXh/ Sub164, Sub180, Sub271, Sub199, Sub223
	common /hdd_varXh/ Sub272, Sub605, Sub607, Sub613, Sub594
	common /hdd_varXh/ Sub352, Sub488, Sub392, Sub251, Sub475

	integer seq(2), Hel(3)
	common /hdd_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /hdd_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hdd_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /hdd_formfactors/ Ctree, Cloop, MatSUN

#endif
