#if 0
* hdd-vars.h
* variable declarations
* generated by FormCalc 9.9 (29 Jan 2020) on 21-Apr-2020 10:42
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "hdd-RenConst.h.F"

#else

#include "Decay.h"
#include "hdd-RenConst.h.F"

	ComplexType A0i1(6), A0i2(6), A0i3(6), A0i4(2), A0i5(4), A0i6
	ComplexType A0i7, A0i8(3), A0i9(3), A0i10(3), A0i11(3)
	ComplexType A0i12, A0i13, A0i14, A0i15, B0i1(6,6), B0i2(6,6)
	ComplexType B0i3(6,6), B0i4(2,2), B0i5(4,4), B0i6(6,2), B0i7
	ComplexType B0i8, B0i9, B0i10, B0i11, B0i12, B0i13, B0i14
	ComplexType B0i15(3), B0i16(3), B0i17(3), B0i18(6,4), B0i19
	ComplexType B0i20, B0i21(3), B0i22(3), B0i23(3), B1i1(6,6)
	ComplexType B1i2(6,6), B1i3(6,6), B1i4(2,2), B1i5(4,4), B1i6
	ComplexType B1i7, B1i8, B1i9, B1i10, B1i11, B1i12(3)
	ComplexType B1i13(3), B1i14(3), B1i15(3), C0i1(Ncc,6,6,2)
	ComplexType C0i2(Ncc,6,6,4), C0i3(Ncc,6,6), C0i4(Ncc,6,4,4)
	ComplexType C0i5(Ncc), C0i6(Ncc), C0i7(Ncc), C0i8(Ncc)
	ComplexType C0i9(Ncc), C0i10(Ncc), C0i11(Ncc), C0i12(Ncc)
	ComplexType C0i13(Ncc), C0i14(Ncc), C0i15(Ncc), C0i16(Ncc)
	ComplexType C0i17(Ncc), C0i18(Ncc), C0i19(Ncc), C0i20(Ncc)
	ComplexType C0i21(Ncc), C0i22(Ncc), C0i23(Ncc), C0i24(Ncc)
	ComplexType C0i25(Ncc,3), C0i26(Ncc,3), C0i27(Ncc,3)
	ComplexType C0i28(Ncc,3), C0i29(Ncc), C0i30(Ncc), C0i31(Ncc)
	ComplexType C0i32(Ncc), C0i33(Ncc,3), C0i34(Ncc,3)
	ComplexType C0i35(Ncc,3), C0i36(Ncc,6,2,2), C0i37(Ncc,3)
	ComplexType Sub1(3,3), Sub2(3,3), Sub3(6,6,3,3), Sub4(3)
	ComplexType Sub5(3,3), Sub6(6,3,3), Sub7(3), Sub8(3,3)
	ComplexType Sub9(6,3,3), Sub10(6,6,3,3), Sub11(3)
	ComplexType Sub12(3,3), Sub13(6,3,3), Sub14(3), Sub15(3,3)
	ComplexType Sub16(6,3,3), Sub17(6,6,3,3), Sub19(3,3)
	ComplexType Sub20(3,3), Sub21(6,6,3,3), Sub23(3,3)
	ComplexType Sub24(3,3), Sub25(6,6,3,3), Sub26(3), Sub27(3,3)
	ComplexType Sub28(6,3,3), Sub29(3), Sub30(3,3), Sub31(6,3,3)
	ComplexType Sub32(6,6,3,3), Sub33(3), Sub34(3,3)
	ComplexType Sub35(6,3,3), Sub36(3), Sub37(3,3), Sub38(6,3,3)
	ComplexType Sub39(6,6,3,3), Sub40(3,3), Sub41(3,3)
	ComplexType Sub42(6,6,3,3), Sub43(6,6,3,3), Sub44(3)
	ComplexType Sub45(3,3), Sub46(6,3,3), Sub47(3), Sub48(3,3)
	ComplexType Sub49(6,3,3), Sub50(6,6,3,3), Sub51(3,3)
	ComplexType Sub52(3,3), Sub53(6,6,3,3), Sub54(3), Sub55(3,3)
	ComplexType Sub56(6,3,3), Sub57(3), Sub58(3,3), Sub59(6,3,3)
	ComplexType Sub60(6,6,3,3), Sub61(3,3), Sub62(3,3)
	ComplexType Sub63(6,6,3,3), Sub64(3,3), Sub65(3,3)
	ComplexType Sub66(6,6,3,3), Sub67(6,6,3,3,3,3), Sub68(6,6,3)
	ComplexType Sub69, Sub70(3), Sub71(3,3), Sub72(6,3,3)
	ComplexType Sub73(3), Sub74(3,3), Sub75(6,3,3)
	ComplexType Sub76(6,6,3,3), Sub77(3), Sub78(3,3)
	ComplexType Sub79(6,3,3), Sub80(3), Sub81(3,3), Sub82(6,3,3)
	ComplexType Sub83(6,6,3,3), Sub84(6,6,3,3), Sub85
	ComplexType Sub86(3,3), Sub87(3,3), Sub88(6,6,3,3)
	ComplexType Sub90(6,6,3), Sub91(3), Sub92(3,3), Sub93(6,3,3)
	ComplexType Sub94(3), Sub95(3,3), Sub96(6,3,3)
	ComplexType Sub97(6,6,3,3), Sub98(3), Sub99(3,3)
	ComplexType Sub100(6,3,3), Sub101(3), Sub102(3,3)
	ComplexType Sub103(6,3,3), Sub104(6,6,3,3), Sub105(3,3)
	ComplexType Sub106(3,3), Sub107(6,6,3,3), Sub109(6,6,3)
	ComplexType Sub110(3), Sub111(3,3), Sub112(6,3,3), Sub113(3)
	ComplexType Sub114(3,3), Sub115(6,3,3), Sub116(6,6,3,3)
	ComplexType Sub117(3), Sub118(3,3), Sub119(6,3,3), Sub120(3)
	ComplexType Sub121(3,3), Sub122(6,3,3), Sub123(6,6,3,3)
	ComplexType Sub124(3,3), Sub125(3,3), Sub126(6,6,3,3)
	ComplexType Sub128(3), Sub129(3), Sub130(6,3), Sub131(3)
	ComplexType Sub132(3), Sub133(6,3), Sub134(3), Sub135(3)
	ComplexType Sub136(6,3), Sub137(2,2), Sub138(2,2)
	ComplexType Sub139(2,2), Sub140(2,2), Sub141(2,2)
	ComplexType Sub142(2,2), Sub143(2,2), Sub144(2,2)
	ComplexType Sub145(2,2), Sub146(2,2), Sub148(2,2)
	ComplexType Sub149(2,2), Sub150(2,2), Sub151(2,2), Sub155(3)
	ComplexType Sub157(3), Sub160(3), Sub164, Sub169, Sub170
	ComplexType Sub171, Sub172, Sub173, Sub175(3), Sub176(3)
	ComplexType Sub178(3), Sub179(3), Sub186, Sub187(3)
	ComplexType Sub189(3), Sub192, Sub194(3), Sub195(3)
	ComplexType Sub198(3), Sub199(3), Sub203, Sub204(3)
	ComplexType Sub207(3), Sub211(3), Sub214(3), Sub215(3)
	ComplexType Sub216(3), Sub217(3), Sub219, Sub220, Sub226(3)
	ComplexType Sub227(3), Sub229, Sub230(3), Sub231, Sub232(3)
	ComplexType Sub235, Sub239, Sub240, Sub243(3), Sub244(3)
	ComplexType Sub245(3), Sub246(3), Sub250, Sub251(3), Sub252
	ComplexType Sub255(3), Sub256(3), Sub257(3), Sub258(3)
	ComplexType Sub259(3), Sub260(3), Sub266, Sub267, Sub268(3)
	ComplexType Sub269, Sub270, Sub271, Sub273, Sub274
	ComplexType Sub279(3), Sub280, Sub281, Sub284, Sub285
	ComplexType Sub287, Sub288, Sub294(4), Sub295(4), Sub296(4)
	ComplexType Sub297(4), Sub298(4,4), Sub299(4), Sub300(4)
	ComplexType Sub301(4,4), Sub302(4), Sub303(4), Sub304(4,4)
	ComplexType Sub305(4,4), Sub306(4), Sub307(4), Sub308(4)
	ComplexType Sub309(4), Sub310(4,4), Sub311(4), Sub312(4)
	ComplexType Sub313(4,4), Sub314(4), Sub315(4), Sub316(4,4)
	ComplexType Sub317(4), Sub318(4), Sub319(4,4), Sub320(4)
	ComplexType Sub321(4), Sub322(4,4), Sub323(4,4), Sub325(4,4)
	ComplexType Sub326(4,4), Sub327(4,4), Sub328(4,4), Sub332
	ComplexType Sub333, Sub334, Sub335, Sub336, Sub339, Sub340
	ComplexType Sub341, Sub342, Sub344, Sub345, Sub351, Sub352
	ComplexType Sub353, Sub354, Sub357, Sub358, Sub359, Sub360
	ComplexType Sub365, Sub368, Sub369, Sub370, Sub374, Sub375
	ComplexType Sub376, Sub377, Sub382, Sub383, Sub384, Sub385
	ComplexType Sub388, Sub389, Sub390, Sub391, Sub398, Sub399
	ComplexType Sub400, Sub402, Sub403, Sub404, Sub407, Sub408
	ComplexType Sub414, Sub415, Sub416, Sub417, Sub419, Sub421
	ComplexType Sub422, Sub423, Sub427, Sub428, Sub433, Sub434
	ComplexType Sub435, Sub436, Sub437, Sub439, Sub440, Sub441
	ComplexType Sub442, Sub443, Sub447, Sub448, Sub449, Sub450
	ComplexType Sub451, Sub456, Sub460, Sub461, Sub462, Sub463
	ComplexType Sub464, Sub465, Sub466, Sub467, Sub468, Sub469
	ComplexType Sub470, Sub471, Sub472, Sub473, Sub474, Sub475
	ComplexType Sub477, Sub478, Sub479, Sub480, Sub481, Sub482
	ComplexType Sub483, Sub484, Sub485, Sub487, Sub488, Sub489
	ComplexType Sub491, Sub492, Sub493, Sub494, Sub496, Sub497
	ComplexType Sub504, Sub505, Sub508, Sub509, Sub510, Sub511
	ComplexType Sub512, Sub514, Sub515, Sub516, Sub517, Sub520
	ComplexType Sub521, Sub523, Sub524, Sub525, Sub527, Sub528
	ComplexType Sub531, Sub532, Sub533, Sub534, Sub535, Sub536
	ComplexType Sub538, Sub539, Sub540, Sub541, Sub546, Sub551
	ComplexType Sub559, Sub568, Sub569, Sub570, Sub571, Sub574
	ComplexType Sub578, Sub579, Sub580, Sub581, Sub582, Sub583
	ComplexType Sub584, Sub588, Sub589, Sub590, Sub591, Sub592
	ComplexType Sub598, Sub599, Sub600, Sub602, Sub603, Sub605
	ComplexType Sub606, Sub607, Sub609, Sub610, Sub611, Sub614
	ComplexType Sub615, Sub618, Sub619, Sub621, Sub622, Sub623
	ComplexType Sub625, Sub626, Sub627, Sub634(6,2,3)
	ComplexType Sub635(6,2,3), Sub637(6,3,3), Sub638(6,3,3)
	ComplexType Sub639(6,6,3,3), Sub640(6,3,3), Sub641(6,3,3)
	ComplexType Sub642(6,6,3,3), Sub643(6,6,3,3)
	ComplexType Sub644(6,6,3,3), Sub645(6,6,3,3), Sub646(3)
	ComplexType Sub647(3,3), Sub648(6,3,3), Sub649(3)
	ComplexType Sub650(3,3), Sub651(6,3,3), Sub652(6,6,3,3)
	ComplexType Sub653(6,3,3), Sub654(6,3,3), Sub655(6,6,3,3)
	ComplexType Sub656(6,2,3), Sub658(3), Sub659(3,3)
	ComplexType Sub660(6,3,3), Sub661(3), Sub662(3,3)
	ComplexType Sub663(6,3,3), Sub664(6,6,3,3), Sub665(6,3,3)
	ComplexType Sub666(6,3,3), Sub667(6,6,3,3), Sub670(6,6,3,3)
	ComplexType Sub671(3,3), Sub672(3,3), Sub673(6,6,3,3)
	ComplexType Sub682(3), Sub683(3,3), Sub684(6,3,3), Sub685(3)
	ComplexType Sub686(3,3), Sub687(6,3,3), Sub688(6,6,3,3)
	ComplexType Sub689(3), Sub690(3,3), Sub691(6,3,3), Sub692(3)
	ComplexType Sub693(3,3), Sub694(6,3,3), Sub695(6,6,3,3)
	ComplexType Sub696(6,6,3,3), Sub697(3,3), Sub698(3,3)
	ComplexType Sub699(6,6,3,3), Sub700(6,4), Sub701(4)
	ComplexType Sub702(6,4), Sub703(6,4), Sub704(6,4)
	ComplexType Sub705(6,4), Sub713(6,2,3), Sub714(2,2)
	ComplexType Sub715(2,2), Sub716(2,2), Sub717(2,2)
	ComplexType Sub718(2,2), Sub719(2,2), Sub720(2,2)
	ComplexType Sub721(2,2), Sub739(6,4), Sub740(6,4)
	ComplexType Sub741(6,4), Sub236(3), Sub405, Sub552, Sub553
	ComplexType Sub554, Sub555, Sub556, Sub557, Sub560, Sub561
	ComplexType Sub562, Sub563, Sub564, Sub565
	common /hdd_varXs/ A0i1, A0i2, A0i3, A0i4, A0i5, A0i6, A0i7
	common /hdd_varXs/ A0i8, A0i9, A0i10, A0i11, A0i12, A0i13
	common /hdd_varXs/ A0i14, A0i15, B0i1, B0i2, B0i3, B0i4
	common /hdd_varXs/ B0i5, B0i6, B0i7, B0i8, B0i9, B0i10
	common /hdd_varXs/ B0i11, B0i12, B0i13, B0i14, B0i15, B0i16
	common /hdd_varXs/ B0i17, B0i18, B0i19, B0i20, B0i21, B0i22
	common /hdd_varXs/ B0i23, B1i1, B1i2, B1i3, B1i4, B1i5, B1i6
	common /hdd_varXs/ B1i7, B1i8, B1i9, B1i10, B1i11, B1i12
	common /hdd_varXs/ B1i13, B1i14, B1i15, C0i1, C0i2, C0i3
	common /hdd_varXs/ C0i4, C0i5, C0i6, C0i7, C0i8, C0i9, C0i10
	common /hdd_varXs/ C0i11, C0i12, C0i13, C0i14, C0i15, C0i16
	common /hdd_varXs/ C0i17, C0i18, C0i19, C0i20, C0i21, C0i22
	common /hdd_varXs/ C0i23, C0i24, C0i25, C0i26, C0i27, C0i28
	common /hdd_varXs/ C0i29, C0i30, C0i31, C0i32, C0i33, C0i34
	common /hdd_varXs/ C0i35, C0i36, C0i37, Sub1, Sub2, Sub3
	common /hdd_varXs/ Sub4, Sub5, Sub6, Sub7, Sub8, Sub9, Sub10
	common /hdd_varXs/ Sub11, Sub12, Sub13, Sub14, Sub15, Sub16
	common /hdd_varXs/ Sub17, Sub19, Sub20, Sub21, Sub23, Sub24
	common /hdd_varXs/ Sub25, Sub26, Sub27, Sub28, Sub29, Sub30
	common /hdd_varXs/ Sub31, Sub32, Sub33, Sub34, Sub35, Sub36
	common /hdd_varXs/ Sub37, Sub38, Sub39, Sub40, Sub41, Sub42
	common /hdd_varXs/ Sub43, Sub44, Sub45, Sub46, Sub47, Sub48
	common /hdd_varXs/ Sub49, Sub50, Sub51, Sub52, Sub53, Sub54
	common /hdd_varXs/ Sub55, Sub56, Sub57, Sub58, Sub59, Sub60
	common /hdd_varXs/ Sub61, Sub62, Sub63, Sub64, Sub65, Sub66
	common /hdd_varXs/ Sub67, Sub68, Sub69, Sub70, Sub71, Sub72
	common /hdd_varXs/ Sub73, Sub74, Sub75, Sub76, Sub77, Sub78
	common /hdd_varXs/ Sub79, Sub80, Sub81, Sub82, Sub83, Sub84
	common /hdd_varXs/ Sub85, Sub86, Sub87, Sub88, Sub90, Sub91
	common /hdd_varXs/ Sub92, Sub93, Sub94, Sub95, Sub96, Sub97
	common /hdd_varXs/ Sub98, Sub99, Sub100, Sub101, Sub102
	common /hdd_varXs/ Sub103, Sub104, Sub105, Sub106, Sub107
	common /hdd_varXs/ Sub109, Sub110, Sub111, Sub112, Sub113
	common /hdd_varXs/ Sub114, Sub115, Sub116, Sub117, Sub118
	common /hdd_varXs/ Sub119, Sub120, Sub121, Sub122, Sub123
	common /hdd_varXs/ Sub124, Sub125, Sub126, Sub128, Sub129
	common /hdd_varXs/ Sub130, Sub131, Sub132, Sub133, Sub134
	common /hdd_varXs/ Sub135, Sub136, Sub137, Sub138, Sub139
	common /hdd_varXs/ Sub140, Sub141, Sub142, Sub143, Sub144
	common /hdd_varXs/ Sub145, Sub146, Sub148, Sub149, Sub150
	common /hdd_varXs/ Sub151, Sub155, Sub157, Sub160, Sub164
	common /hdd_varXs/ Sub169, Sub170, Sub171, Sub172, Sub173
	common /hdd_varXs/ Sub175, Sub176, Sub178, Sub179, Sub186
	common /hdd_varXs/ Sub187, Sub189, Sub192, Sub194, Sub195
	common /hdd_varXs/ Sub198, Sub199, Sub203, Sub204, Sub207
	common /hdd_varXs/ Sub211, Sub214, Sub215, Sub216, Sub217
	common /hdd_varXs/ Sub219, Sub220, Sub226, Sub227, Sub229
	common /hdd_varXs/ Sub230, Sub231, Sub232, Sub235, Sub239
	common /hdd_varXs/ Sub240, Sub243, Sub244, Sub245, Sub246
	common /hdd_varXs/ Sub250, Sub251, Sub252, Sub255, Sub256
	common /hdd_varXs/ Sub257, Sub258, Sub259, Sub260, Sub266
	common /hdd_varXs/ Sub267, Sub268, Sub269, Sub270, Sub271
	common /hdd_varXs/ Sub273, Sub274, Sub279, Sub280, Sub281
	common /hdd_varXs/ Sub284, Sub285, Sub287, Sub288, Sub294
	common /hdd_varXs/ Sub295, Sub296, Sub297, Sub298, Sub299
	common /hdd_varXs/ Sub300, Sub301, Sub302, Sub303, Sub304
	common /hdd_varXs/ Sub305, Sub306, Sub307, Sub308, Sub309
	common /hdd_varXs/ Sub310, Sub311, Sub312, Sub313, Sub314
	common /hdd_varXs/ Sub315, Sub316, Sub317, Sub318, Sub319
	common /hdd_varXs/ Sub320, Sub321, Sub322, Sub323, Sub325
	common /hdd_varXs/ Sub326, Sub327, Sub328, Sub332, Sub333
	common /hdd_varXs/ Sub334, Sub335, Sub336, Sub339, Sub340
	common /hdd_varXs/ Sub341, Sub342, Sub344, Sub345, Sub351
	common /hdd_varXs/ Sub352, Sub353, Sub354, Sub357, Sub358
	common /hdd_varXs/ Sub359, Sub360, Sub365, Sub368, Sub369
	common /hdd_varXs/ Sub370, Sub374, Sub375, Sub376, Sub377
	common /hdd_varXs/ Sub382, Sub383, Sub384, Sub385, Sub388
	common /hdd_varXs/ Sub389, Sub390, Sub391, Sub398, Sub399
	common /hdd_varXs/ Sub400, Sub402, Sub403, Sub404, Sub407
	common /hdd_varXs/ Sub408, Sub414, Sub415, Sub416, Sub417
	common /hdd_varXs/ Sub419, Sub421, Sub422, Sub423, Sub427
	common /hdd_varXs/ Sub428, Sub433, Sub434, Sub435, Sub436
	common /hdd_varXs/ Sub437, Sub439, Sub440, Sub441, Sub442
	common /hdd_varXs/ Sub443, Sub447, Sub448, Sub449, Sub450
	common /hdd_varXs/ Sub451, Sub456, Sub460, Sub461, Sub462
	common /hdd_varXs/ Sub463, Sub464, Sub465, Sub466, Sub467
	common /hdd_varXs/ Sub468, Sub469, Sub470, Sub471, Sub472
	common /hdd_varXs/ Sub473, Sub474, Sub475, Sub477, Sub478
	common /hdd_varXs/ Sub479, Sub480, Sub481, Sub482, Sub483
	common /hdd_varXs/ Sub484, Sub485, Sub487, Sub488, Sub489
	common /hdd_varXs/ Sub491, Sub492, Sub493, Sub494, Sub496
	common /hdd_varXs/ Sub497, Sub504, Sub505, Sub508, Sub509
	common /hdd_varXs/ Sub510, Sub511, Sub512, Sub514, Sub515
	common /hdd_varXs/ Sub516, Sub517, Sub520, Sub521, Sub523
	common /hdd_varXs/ Sub524, Sub525, Sub527, Sub528, Sub531
	common /hdd_varXs/ Sub532, Sub533, Sub534, Sub535, Sub536
	common /hdd_varXs/ Sub538, Sub539, Sub540, Sub541, Sub546
	common /hdd_varXs/ Sub551, Sub559, Sub568, Sub569, Sub570
	common /hdd_varXs/ Sub571, Sub574, Sub578, Sub579, Sub580
	common /hdd_varXs/ Sub581, Sub582, Sub583, Sub584, Sub588
	common /hdd_varXs/ Sub589, Sub590, Sub591, Sub592, Sub598
	common /hdd_varXs/ Sub599, Sub600, Sub602, Sub603, Sub605
	common /hdd_varXs/ Sub606, Sub607, Sub609, Sub610, Sub611
	common /hdd_varXs/ Sub614, Sub615, Sub618, Sub619, Sub621
	common /hdd_varXs/ Sub622, Sub623, Sub625, Sub626, Sub627
	common /hdd_varXs/ Sub634, Sub635, Sub637, Sub638, Sub639
	common /hdd_varXs/ Sub640, Sub641, Sub642, Sub643, Sub644
	common /hdd_varXs/ Sub645, Sub646, Sub647, Sub648, Sub649
	common /hdd_varXs/ Sub650, Sub651, Sub652, Sub653, Sub654
	common /hdd_varXs/ Sub655, Sub656, Sub658, Sub659, Sub660
	common /hdd_varXs/ Sub661, Sub662, Sub663, Sub664, Sub665
	common /hdd_varXs/ Sub666, Sub667, Sub670, Sub671, Sub672
	common /hdd_varXs/ Sub673, Sub682, Sub683, Sub684, Sub685
	common /hdd_varXs/ Sub686, Sub687, Sub688, Sub689, Sub690
	common /hdd_varXs/ Sub691, Sub692, Sub693, Sub694, Sub695
	common /hdd_varXs/ Sub696, Sub697, Sub698, Sub699, Sub700
	common /hdd_varXs/ Sub701, Sub702, Sub703, Sub704, Sub705
	common /hdd_varXs/ Sub713, Sub714, Sub715, Sub716, Sub717
	common /hdd_varXs/ Sub718, Sub719, Sub720, Sub721, Sub739
	common /hdd_varXs/ Sub740, Sub741, Sub236, Sub405, Sub552
	common /hdd_varXs/ Sub553, Sub554, Sub555, Sub556, Sub557
	common /hdd_varXs/ Sub560, Sub561, Sub562, Sub563, Sub564
	common /hdd_varXs/ Sub565

	ComplexType F1, F2
	ComplexType Sub18(6,6,3,3), Sub22(6,6,3,3), Sub89(6,6,3,3)
	ComplexType Sub108(6,6,3,3), Sub127(6,6,3,3), Sub147(2,2)
	ComplexType Sub152(2,2), Sub153(2,2), Sub154(2,2), Sub156(3)
	ComplexType Sub158(3), Sub159, Sub161(3), Sub162(3)
	ComplexType Sub163(3), Sub165, Sub166(3), Sub167(3)
	ComplexType Sub168(3), Sub174, Sub177(3), Sub180(3)
	ComplexType Sub181(3), Sub182(3), Sub183(3), Sub184(3)
	ComplexType Sub185(3), Sub188(3), Sub190(3), Sub191(3)
	ComplexType Sub193(3), Sub196(3), Sub197(3), Sub200(3)
	ComplexType Sub201(3), Sub202(3), Sub205(3), Sub206(3)
	ComplexType Sub208(3), Sub209(3), Sub210(3), Sub212(3)
	ComplexType Sub213(3), Sub218(3), Sub222, Sub223(3), Sub224
	ComplexType Sub225(3), Sub228(3), Sub233(3), Sub234(3)
	ComplexType Sub237(3), Sub238, Sub241, Sub242(3), Sub247(3)
	ComplexType Sub248(3), Sub249(3), Sub253(3), Sub254(3)
	ComplexType Sub261(3), Sub262(3), Sub263(3), Sub264(3)
	ComplexType Sub265(3), Sub272, Sub275, Sub276(3), Sub277
	ComplexType Sub278(3), Sub282, Sub283, Sub286, Sub289
	ComplexType Sub290(3), Sub291(3), Sub292(3), Sub293(3)
	ComplexType Sub324(4,4), Sub329(4,4), Sub330(4,4)
	ComplexType Sub331(4,4), Sub337, Sub338, Sub343, Sub346
	ComplexType Sub347, Sub348, Sub349, Sub350, Sub355, Sub356
	ComplexType Sub361, Sub362, Sub363, Sub364, Sub366, Sub367
	ComplexType Sub371, Sub372, Sub373, Sub378, Sub379, Sub380
	ComplexType Sub381, Sub386, Sub387, Sub392, Sub393, Sub394
	ComplexType Sub395, Sub396, Sub397, Sub401, Sub406, Sub409
	ComplexType Sub410, Sub411, Sub413, Sub418, Sub420, Sub424
	ComplexType Sub425, Sub426, Sub429, Sub430, Sub431, Sub432
	ComplexType Sub438, Sub444, Sub445, Sub446, Sub452, Sub453
	ComplexType Sub454, Sub455, Sub457, Sub458, Sub459, Sub476
	ComplexType Sub486, Sub490, Sub495, Sub498, Sub499, Sub500
	ComplexType Sub501, Sub502, Sub503, Sub506, Sub507, Sub513
	ComplexType Sub518, Sub519, Sub522, Sub526, Sub529, Sub530
	ComplexType Sub537, Sub542, Sub543, Sub544, Sub545, Sub547
	ComplexType Sub548, Sub549, Sub550, Sub558, Sub566, Sub567
	ComplexType Sub572, Sub573, Sub575, Sub576, Sub577, Sub585
	ComplexType Sub586, Sub587, Sub593, Sub594, Sub595, Sub596
	ComplexType Sub597, Sub601, Sub604, Sub608, Sub612, Sub613
	ComplexType Sub617, Sub620, Sub624, Sub628, Sub629, Sub630
	ComplexType Sub631, Sub632, Sub633, Sub636(6,6,2,3,3)
	ComplexType Sub657(6,6,2,3,3,3,3), Sub668(6,6,2,3,3,3,3)
	ComplexType Sub669(6,6,2,3,3,3,3), Sub674(6,6,2,3,3,3,3)
	ComplexType Sub675(6,6,2,3,3,3,3), Sub676(6,6,2,3,3,3,3)
	ComplexType Sub677(6,6,2,3,3,3,3), Sub678(6,6,2,3,3,3,3)
	ComplexType Sub679(6,6,2,3,3,3,3), Sub680(6,6,2,3,3,3,3)
	ComplexType Sub681(6,6,2,3,3,3,3), Sub706(6,6,4)
	ComplexType Sub707(6,6,4), Sub708(6,6,4), Sub709(6,6,4)
	ComplexType Sub710(6,6), Sub711(6,6), Sub712(6,6)
	ComplexType Sub722(6,2,2,3,3), Sub723(6,2,2,3,3)
	ComplexType Sub724(6,2,2,3,3), Sub725(6,2,2,3,3)
	ComplexType Sub726(6,2,2,3,3), Sub727(6,2,2,3,3)
	ComplexType Sub728(6,2,2,3,3), Sub729(6,2,3)
	ComplexType Sub730(6,2,2,3,3), Sub731(6,2,2,3,3)
	ComplexType Sub732(6,2,2,3,3), Sub733(6,2,3), Sub734(6,2,3)
	ComplexType Sub735(6,2,2,3,3), Sub736(6,2,2,3,3)
	ComplexType Sub737(6,2,2,3,3), Sub738(6,2,2,3,3)
	ComplexType Sub742(6,4,4), Sub743(6,4,4), Sub744(6,4,4)
	ComplexType Sub745(6,4,4), Sub746(6,4,4), Sub747(6,4,4)
	ComplexType Sub748(6,4,4), Sub749(6,4,4), Sub750(6,4,4)
	ComplexType Sub751(6,4,4), Sub752(6,4,4), Sub753(6,4,4)
	ComplexType Sub754(6,4,4), Sub755(6,4,4), Sub756(6,4,4)
	common /hdd_varXh/ F1, F2, Sub18, Sub22, Sub89, Sub108
	common /hdd_varXh/ Sub127, Sub147, Sub152, Sub153, Sub154
	common /hdd_varXh/ Sub156, Sub158, Sub159, Sub161, Sub162
	common /hdd_varXh/ Sub163, Sub165, Sub166, Sub167, Sub168
	common /hdd_varXh/ Sub174, Sub177, Sub180, Sub181, Sub182
	common /hdd_varXh/ Sub183, Sub184, Sub185, Sub188, Sub190
	common /hdd_varXh/ Sub191, Sub193, Sub196, Sub197, Sub200
	common /hdd_varXh/ Sub201, Sub202, Sub205, Sub206, Sub208
	common /hdd_varXh/ Sub209, Sub210, Sub212, Sub213, Sub218
	common /hdd_varXh/ Sub222, Sub223, Sub224, Sub225, Sub228
	common /hdd_varXh/ Sub233, Sub234, Sub237, Sub238, Sub241
	common /hdd_varXh/ Sub242, Sub247, Sub248, Sub249, Sub253
	common /hdd_varXh/ Sub254, Sub261, Sub262, Sub263, Sub264
	common /hdd_varXh/ Sub265, Sub272, Sub275, Sub276, Sub277
	common /hdd_varXh/ Sub278, Sub282, Sub283, Sub286, Sub289
	common /hdd_varXh/ Sub290, Sub291, Sub292, Sub293, Sub324
	common /hdd_varXh/ Sub329, Sub330, Sub331, Sub337, Sub338
	common /hdd_varXh/ Sub343, Sub346, Sub347, Sub348, Sub349
	common /hdd_varXh/ Sub350, Sub355, Sub356, Sub361, Sub362
	common /hdd_varXh/ Sub363, Sub364, Sub366, Sub367, Sub371
	common /hdd_varXh/ Sub372, Sub373, Sub378, Sub379, Sub380
	common /hdd_varXh/ Sub381, Sub386, Sub387, Sub392, Sub393
	common /hdd_varXh/ Sub394, Sub395, Sub396, Sub397, Sub401
	common /hdd_varXh/ Sub406, Sub409, Sub410, Sub411, Sub413
	common /hdd_varXh/ Sub418, Sub420, Sub424, Sub425, Sub426
	common /hdd_varXh/ Sub429, Sub430, Sub431, Sub432, Sub438
	common /hdd_varXh/ Sub444, Sub445, Sub446, Sub452, Sub453
	common /hdd_varXh/ Sub454, Sub455, Sub457, Sub458, Sub459
	common /hdd_varXh/ Sub476, Sub486, Sub490, Sub495, Sub498
	common /hdd_varXh/ Sub499, Sub500, Sub501, Sub502, Sub503
	common /hdd_varXh/ Sub506, Sub507, Sub513, Sub518, Sub519
	common /hdd_varXh/ Sub522, Sub526, Sub529, Sub530, Sub537
	common /hdd_varXh/ Sub542, Sub543, Sub544, Sub545, Sub547
	common /hdd_varXh/ Sub548, Sub549, Sub550, Sub558, Sub566
	common /hdd_varXh/ Sub567, Sub572, Sub573, Sub575, Sub576
	common /hdd_varXh/ Sub577, Sub585, Sub586, Sub587, Sub593
	common /hdd_varXh/ Sub594, Sub595, Sub596, Sub597, Sub601
	common /hdd_varXh/ Sub604, Sub608, Sub612, Sub613, Sub617
	common /hdd_varXh/ Sub620, Sub624, Sub628, Sub629, Sub630
	common /hdd_varXh/ Sub631, Sub632, Sub633, Sub636, Sub657
	common /hdd_varXh/ Sub668, Sub669, Sub674, Sub675, Sub676
	common /hdd_varXh/ Sub677, Sub678, Sub679, Sub680, Sub681
	common /hdd_varXh/ Sub706, Sub707, Sub708, Sub709, Sub710
	common /hdd_varXh/ Sub711, Sub712, Sub722, Sub723, Sub724
	common /hdd_varXh/ Sub725, Sub726, Sub727, Sub728, Sub729
	common /hdd_varXh/ Sub730, Sub731, Sub732, Sub733, Sub734
	common /hdd_varXh/ Sub735, Sub736, Sub737, Sub738, Sub742
	common /hdd_varXh/ Sub743, Sub744, Sub745, Sub746, Sub747
	common /hdd_varXh/ Sub748, Sub749, Sub750, Sub751, Sub752
	common /hdd_varXh/ Sub753, Sub754, Sub755, Sub756

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /hdd_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hdd_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /hdd_formfactors/ Ctree, Cloop, MatSUN

#endif

