#if 0
* hdd-vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Feb-2015 17:26
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hdd-renconst.h"

	ComplexType Sub210, Sub705, Sub340, Sub168, Sub173, Sub70
	ComplexType Sub454, Sub483, Sub394, Sub91, Sub456, Sub364
	ComplexType Sub396, Sub392, Sub381, Sub480, Sub450, Sub373
	ComplexType Sub474, Sub540, Sub545, Sub557, Sub487, Sub367
	ComplexType Sub478, Sub375, Sub471, Sub569, Sub544, Sub542
	ComplexType Sub231, Sub443, Sub337, Sub438, Sub437, Sub452
	ComplexType Sub359, Sub358, Sub580, Sub465, Sub466, Sub419
	ComplexType Sub411, Sub444, Sub453, Sub586, Sub463, Sub464
	ComplexType Sub417, Sub409, Sub440, Sub459, Sub582, Sub422
	ComplexType Sub418, Sub414, Sub410, Sub442, Sub446, Sub390
	ComplexType Sub573, Sub584, Sub498, Sub493, Sub395, Sub457
	ComplexType Sub473, Sub479, Sub449, Sub512, Sub391, Sub384
	ComplexType Sub500, Sub563, Sub567, Sub551, Sub549, Sub261
	ComplexType Sub448, Sub400, Sub461, Sub523, Sub533, Sub526
	ComplexType Sub534, Sub530, Sub536, Sub257, Sub522, Sub532
	ComplexType Sub539, Sub555, Sub541, Sub575, Sub583, Sub587
	ComplexType Sub427, Sub365, Sub368, Sub429, Sub412, Sub420
	ComplexType Sub445, Sub467, Sub484, Sub503, Sub488, Sub506
	ComplexType Sub566, Sub570, Sub472, Sub499, Sub494, Sub475
	ComplexType Sub382, Sub374, Sub495, Sub383, Sub376, Sub565
	ComplexType Sub423, Sub415, Sub553, Sub588, Sub550, Sub576
	ComplexType Sub589, Sub577, Sub504, Sub507, Sub485, Sub489
	ComplexType Sub370, Sub564, Sub568, Sub170, Sub163, Sub416
	ComplexType Sub191, Sub330, Sub165, Sub421, Sub424, Sub201
	ComplexType Sub408, Sub211, Sub527, Sub535, Sub216, Sub202
	ComplexType Sub360, Sub166, Sub167, Sub171, Sub172, Sub531
	ComplexType Sub537, Sub162(3), Sub169(3), Sub219(3)
	ComplexType Sub273(3), Sub278(3), Sub235(3), Sub198(3)
	ComplexType Sub242(3), Sub193(3), Sub260(3), Sub258(3)
	ComplexType Sub254(3), Sub228(3), Sub189(3), Sub223(3)
	ComplexType Sub237(3), Sub240(3), Sub262(3), Sub263(3)
	ComplexType Sub244(3), Sub247(3), Sub268(3), Sub282(3)
	ComplexType Sub281(3), Sub285(3), Sub284(3), Sub277(3)
	ComplexType Sub174(3), Sub220(3), Sub259(3), Sub264(3)
	ComplexType Sub279(3), Sub286(3), Sub136(3), Sub135(3)
	ComplexType Sub650(3), Sub653(3), Sub139(3), Sub138(3)
	ComplexType Sub643(3), Sub646(3), Sub607(3), Sub610(3)
	ComplexType Sub142(3), Sub141(3), Sub622(3), Sub619(3)
	ComplexType Sub79(3), Sub82(3), Sub72(3), Sub75(3)
	ComplexType Sub101(3), Sub104(3), Sub94(3), Sub97(3)
	ComplexType Sub115(3), Sub118(3), Sub125(3), Sub122(3)
	ComplexType Sub11(3), Sub14(3), Sub4(3), Sub7(3), Sub33(3)
	ComplexType Sub36(3), Sub26(3), Sub29(3), Sub48(3), Sub51(3)
	ComplexType Sub58(3), Sub55(3), Sub662(4), Sub294(4)
	ComplexType Sub292(4), Sub297(4), Sub300(4), Sub309(4)
	ComplexType Sub306(4), Sub312(4), Sub315(4), Sub318(4)
	ComplexType Sub304(4), Sub293(4), Sub295(4), Sub298(4)
	ComplexType Sub301(4), Sub310(4), Sub305(4), Sub313(4)
	ComplexType Sub316(4), Sub319(4), Sub307(4), Sub137(6,3)
	ComplexType Sub140(6,3), Sub143(6,3), Sub663(6,4)
	ComplexType Sub664(6,4), Sub703(6,4), Sub702(6,4)
	ComplexType Sub701(6,4), Sub661(6,4), Sub666(6,4)
	ComplexType Sub665(6,4), Sub155(2,2), Sub154(2,2)
	ComplexType Sub160(2,2), Sub158(2,2), Sub145(2,2)
	ComplexType Sub147(2,2), Sub146(2,2), Sub675(2,2)
	ComplexType Sub677(2,2), Sub676(2,2), Sub149(2,2)
	ComplexType Sub679(2,2), Sub681(2,2), Sub680(2,2)
	ComplexType Sub144(2,2), Sub150(2,2), Sub152(2,2)
	ComplexType Sub151(2,2), Sub2(3,3), Sub1(3,3), Sub659(3,3)
	ComplexType Sub647(3,3), Sub658(3,3), Sub644(3,3)
	ComplexType Sub654(3,3), Sub651(3,3), Sub24(3,3), Sub23(3,3)
	ComplexType Sub46(3,3), Sub623(3,3), Sub45(3,3), Sub620(3,3)
	ComplexType Sub611(3,3), Sub608(3,3), Sub64(3,3), Sub63(3,3)
	ComplexType Sub88(3,3), Sub76(3,3), Sub87(3,3), Sub73(3,3)
	ComplexType Sub83(3,3), Sub80(3,3), Sub110(3,3), Sub98(3,3)
	ComplexType Sub109(3,3), Sub95(3,3), Sub105(3,3)
	ComplexType Sub102(3,3), Sub126(3,3), Sub123(3,3)
	ComplexType Sub119(3,3), Sub116(3,3), Sub131(3,3)
	ComplexType Sub130(3,3), Sub20(3,3), Sub8(3,3), Sub19(3,3)
	ComplexType Sub5(3,3), Sub15(3,3), Sub12(3,3), Sub42(3,3)
	ComplexType Sub30(3,3), Sub41(3,3), Sub27(3,3), Sub37(3,3)
	ComplexType Sub34(3,3), Sub67(3,3), Sub59(3,3), Sub66(3,3)
	ComplexType Sub56(3,3), Sub52(3,3), Sub49(3,3), Sub633(3,3)
	ComplexType Sub632(3,3), Sub296(4,4), Sub299(4,4)
	ComplexType Sub302(4,4), Sub308(4,4), Sub311(4,4)
	ComplexType Sub314(4,4), Sub317(4,4), Sub320(4,4)
	ComplexType Sub328(4,4), Sub322(4,4), Sub326(4,4)
	ComplexType Sub325(4,4), Sub324(4,4), Sub323(4,4)
	ComplexType Sub71(6,6,3), Sub93(6,6,3), Sub114(6,6,3)
	ComplexType Sub595(6,2,3), Sub617(6,2,3), Sub674(6,2,3)
	ComplexType Sub648(6,3,3), Sub655(6,3,3), Sub612(6,3,3)
	ComplexType Sub624(6,3,3), Sub645(6,3,3), Sub652(6,3,3)
	ComplexType Sub609(6,3,3), Sub621(6,3,3), Sub599(6,3,3)
	ComplexType Sub602(6,3,3), Sub598(6,3,3), Sub601(6,3,3)
	ComplexType Sub615(6,3,3), Sub627(6,3,3), Sub614(6,3,3)
	ComplexType Sub626(6,3,3), Sub596(6,2,3), Sub77(6,3,3)
	ComplexType Sub84(6,3,3), Sub106(6,3,3), Sub99(6,3,3)
	ComplexType Sub120(6,3,3), Sub127(6,3,3), Sub74(6,3,3)
	ComplexType Sub81(6,3,3), Sub103(6,3,3), Sub96(6,3,3)
	ComplexType Sub117(6,3,3), Sub124(6,3,3), Sub16(6,3,3)
	ComplexType Sub9(6,3,3), Sub31(6,3,3), Sub38(6,3,3)
	ComplexType Sub53(6,3,3), Sub60(6,3,3), Sub13(6,3,3)
	ComplexType Sub6(6,3,3), Sub28(6,3,3), Sub35(6,3,3)
	ComplexType Sub50(6,3,3), Sub57(6,3,3), Sub65(6,6,3,3)
	ComplexType Sub3(6,6,3,3), Sub649(6,6,3,3), Sub656(6,6,3,3)
	ComplexType Sub25(6,6,3,3), Sub660(6,6,3,3), Sub613(6,6,3,3)
	ComplexType Sub625(6,6,3,3), Sub47(6,6,3,3), Sub631(6,6,3,3)
	ComplexType Sub657(6,6,3,3), Sub78(6,6,3,3), Sub85(6,6,3,3)
	ComplexType Sub89(6,6,3,3), Sub107(6,6,3,3), Sub100(6,6,3,3)
	ComplexType Sub111(6,6,3,3), Sub121(6,6,3,3)
	ComplexType Sub128(6,6,3,3), Sub132(6,6,3,3)
	ComplexType Sub600(6,6,3,3), Sub603(6,6,3,3)
	ComplexType Sub605(6,6,3,3), Sub108(6,6,3,3)
	ComplexType Sub129(6,6,3,3), Sub604(6,6,3,3), Sub86(6,6,3,3)
	ComplexType Sub112(6,6,3,3), Sub133(6,6,3,3)
	ComplexType Sub606(6,6,3,3), Sub90(6,6,3,3), Sub17(6,6,3,3)
	ComplexType Sub10(6,6,3,3), Sub21(6,6,3,3), Sub32(6,6,3,3)
	ComplexType Sub39(6,6,3,3), Sub43(6,6,3,3), Sub54(6,6,3,3)
	ComplexType Sub61(6,6,3,3), Sub616(6,6,3,3), Sub628(6,6,3,3)
	ComplexType Sub634(6,6,3,3), Sub68(6,6,3,3), Sub18(6,6,3,3)
	ComplexType Sub40(6,6,3,3), Sub62(6,6,3,3), Sub22(6,6,3,3)
	ComplexType Sub44(6,6,3,3), Sub69(6,6,3,3,3,3), Sub331
	ComplexType Sub520, Sub524, Sub425, Sub428, Sub486, Sub505
	ComplexType Sub366, Sub528, Sub283, Sub460, Sub404, Sub399
	ComplexType Sub556, Sub558, Sub199, Sub251, Sub270(3)
	ComplexType Sub156(2,2), Sub157(2,2), Sub148(2,2)
	ComplexType Sub153(2,2), Sub678(2,2), Sub682(2,2)
	ComplexType Sub303(4,4), Sub321(4,4), Sub521, Sub525, Sub529
	ComplexType Sub338, Sub441, Sub397, Sub455, pave1(6,6)
	ComplexType pave2(6,6), pave3(6,6), pave4(6,6), pave5(6,6)
	ComplexType pave6(6,6), pave7(6), pave8(6), pave9(6)
	ComplexType pave10(2), pave11(2,2), pave12(2,2), pave13(4)
	ComplexType pave14(4,4), pave15(4,4), pave16(Ncc,6,6,2)
	ComplexType pave17(Ncc,6,6,4), pave18(Ncc,6,6), pave19(6,2)
	ComplexType pave20(6,4), pave21, pave22, pave23, pave24
	ComplexType pave25, pave26, pave27, pave28, pave29, pave30
	ComplexType pave31, pave32, pave33, pave34(Ncc), pave35(Ncc)
	ComplexType pave36(Ncc), pave37(Ncc), pave38(Ncc)
	ComplexType pave39(Ncc), pave40(Ncc), pave41(Ncc)
	ComplexType pave42(Ncc), pave43(Ncc), pave44(Ncc)
	ComplexType pave45(Ncc), pave46(Ncc), pave47(Ncc)
	ComplexType pave48(Ncc), pave49(Ncc), pave50(Ncc)
	ComplexType pave51(Ncc), pave52(Ncc), pave53(Ncc), pave54
	ComplexType pave55(3), pave56(3), pave57(3), pave58(3)
	ComplexType pave59(3), pave60(3), pave61(3), pave62(3)
	ComplexType pave63(3), pave64(3), pave65(3), pave66(Ncc,3)
	ComplexType pave67(Ncc,3), pave68(Ncc,3), pave69(Ncc,3)
	ComplexType pave70(3), pave71, pave72, pave73(Ncc)
	ComplexType pave74(Ncc), pave75(Ncc), pave76(Ncc)
	ComplexType pave77(Ncc,3), pave78(Ncc,3), pave79(Ncc,3)
	ComplexType pave80(Ncc,6,4,4), pave81(Ncc,6,2,2), pave82
	ComplexType pave83, pave84, pave85, pave86, pave87
	ComplexType pave88(3), pave89(Ncc,3), pave90(3)
	common /hdd_varXs/ Sub210, Sub705, Sub340, Sub168, Sub173
	common /hdd_varXs/ Sub70, Sub454, Sub483, Sub394, Sub91
	common /hdd_varXs/ Sub456, Sub364, Sub396, Sub392, Sub381
	common /hdd_varXs/ Sub480, Sub450, Sub373, Sub474, Sub540
	common /hdd_varXs/ Sub545, Sub557, Sub487, Sub367, Sub478
	common /hdd_varXs/ Sub375, Sub471, Sub569, Sub544, Sub542
	common /hdd_varXs/ Sub231, Sub443, Sub337, Sub438, Sub437
	common /hdd_varXs/ Sub452, Sub359, Sub358, Sub580, Sub465
	common /hdd_varXs/ Sub466, Sub419, Sub411, Sub444, Sub453
	common /hdd_varXs/ Sub586, Sub463, Sub464, Sub417, Sub409
	common /hdd_varXs/ Sub440, Sub459, Sub582, Sub422, Sub418
	common /hdd_varXs/ Sub414, Sub410, Sub442, Sub446, Sub390
	common /hdd_varXs/ Sub573, Sub584, Sub498, Sub493, Sub395
	common /hdd_varXs/ Sub457, Sub473, Sub479, Sub449, Sub512
	common /hdd_varXs/ Sub391, Sub384, Sub500, Sub563, Sub567
	common /hdd_varXs/ Sub551, Sub549, Sub261, Sub448, Sub400
	common /hdd_varXs/ Sub461, Sub523, Sub533, Sub526, Sub534
	common /hdd_varXs/ Sub530, Sub536, Sub257, Sub522, Sub532
	common /hdd_varXs/ Sub539, Sub555, Sub541, Sub575, Sub583
	common /hdd_varXs/ Sub587, Sub427, Sub365, Sub368, Sub429
	common /hdd_varXs/ Sub412, Sub420, Sub445, Sub467, Sub484
	common /hdd_varXs/ Sub503, Sub488, Sub506, Sub566, Sub570
	common /hdd_varXs/ Sub472, Sub499, Sub494, Sub475, Sub382
	common /hdd_varXs/ Sub374, Sub495, Sub383, Sub376, Sub565
	common /hdd_varXs/ Sub423, Sub415, Sub553, Sub588, Sub550
	common /hdd_varXs/ Sub576, Sub589, Sub577, Sub504, Sub507
	common /hdd_varXs/ Sub485, Sub489, Sub370, Sub564, Sub568
	common /hdd_varXs/ Sub170, Sub163, Sub416, Sub191, Sub330
	common /hdd_varXs/ Sub165, Sub421, Sub424, Sub201, Sub408
	common /hdd_varXs/ Sub211, Sub527, Sub535, Sub216, Sub202
	common /hdd_varXs/ Sub360, Sub166, Sub167, Sub171, Sub172
	common /hdd_varXs/ Sub531, Sub537, Sub162, Sub169, Sub219
	common /hdd_varXs/ Sub273, Sub278, Sub235, Sub198, Sub242
	common /hdd_varXs/ Sub193, Sub260, Sub258, Sub254, Sub228
	common /hdd_varXs/ Sub189, Sub223, Sub237, Sub240, Sub262
	common /hdd_varXs/ Sub263, Sub244, Sub247, Sub268, Sub282
	common /hdd_varXs/ Sub281, Sub285, Sub284, Sub277, Sub174
	common /hdd_varXs/ Sub220, Sub259, Sub264, Sub279, Sub286
	common /hdd_varXs/ Sub136, Sub135, Sub650, Sub653, Sub139
	common /hdd_varXs/ Sub138, Sub643, Sub646, Sub607, Sub610
	common /hdd_varXs/ Sub142, Sub141, Sub622, Sub619, Sub79
	common /hdd_varXs/ Sub82, Sub72, Sub75, Sub101, Sub104
	common /hdd_varXs/ Sub94, Sub97, Sub115, Sub118, Sub125
	common /hdd_varXs/ Sub122, Sub11, Sub14, Sub4, Sub7, Sub33
	common /hdd_varXs/ Sub36, Sub26, Sub29, Sub48, Sub51, Sub58
	common /hdd_varXs/ Sub55, Sub662, Sub294, Sub292, Sub297
	common /hdd_varXs/ Sub300, Sub309, Sub306, Sub312, Sub315
	common /hdd_varXs/ Sub318, Sub304, Sub293, Sub295, Sub298
	common /hdd_varXs/ Sub301, Sub310, Sub305, Sub313, Sub316
	common /hdd_varXs/ Sub319, Sub307, Sub137, Sub140, Sub143
	common /hdd_varXs/ Sub663, Sub664, Sub703, Sub702, Sub701
	common /hdd_varXs/ Sub661, Sub666, Sub665, Sub155, Sub154
	common /hdd_varXs/ Sub160, Sub158, Sub145, Sub147, Sub146
	common /hdd_varXs/ Sub675, Sub677, Sub676, Sub149, Sub679
	common /hdd_varXs/ Sub681, Sub680, Sub144, Sub150, Sub152
	common /hdd_varXs/ Sub151, Sub2, Sub1, Sub659, Sub647
	common /hdd_varXs/ Sub658, Sub644, Sub654, Sub651, Sub24
	common /hdd_varXs/ Sub23, Sub46, Sub623, Sub45, Sub620
	common /hdd_varXs/ Sub611, Sub608, Sub64, Sub63, Sub88
	common /hdd_varXs/ Sub76, Sub87, Sub73, Sub83, Sub80, Sub110
	common /hdd_varXs/ Sub98, Sub109, Sub95, Sub105, Sub102
	common /hdd_varXs/ Sub126, Sub123, Sub119, Sub116, Sub131
	common /hdd_varXs/ Sub130, Sub20, Sub8, Sub19, Sub5, Sub15
	common /hdd_varXs/ Sub12, Sub42, Sub30, Sub41, Sub27, Sub37
	common /hdd_varXs/ Sub34, Sub67, Sub59, Sub66, Sub56, Sub52
	common /hdd_varXs/ Sub49, Sub633, Sub632, Sub296, Sub299
	common /hdd_varXs/ Sub302, Sub308, Sub311, Sub314, Sub317
	common /hdd_varXs/ Sub320, Sub328, Sub322, Sub326, Sub325
	common /hdd_varXs/ Sub324, Sub323, Sub71, Sub93, Sub114
	common /hdd_varXs/ Sub595, Sub617, Sub674, Sub648, Sub655
	common /hdd_varXs/ Sub612, Sub624, Sub645, Sub652, Sub609
	common /hdd_varXs/ Sub621, Sub599, Sub602, Sub598, Sub601
	common /hdd_varXs/ Sub615, Sub627, Sub614, Sub626, Sub596
	common /hdd_varXs/ Sub77, Sub84, Sub106, Sub99, Sub120
	common /hdd_varXs/ Sub127, Sub74, Sub81, Sub103, Sub96
	common /hdd_varXs/ Sub117, Sub124, Sub16, Sub9, Sub31, Sub38
	common /hdd_varXs/ Sub53, Sub60, Sub13, Sub6, Sub28, Sub35
	common /hdd_varXs/ Sub50, Sub57, Sub65, Sub3, Sub649, Sub656
	common /hdd_varXs/ Sub25, Sub660, Sub613, Sub625, Sub47
	common /hdd_varXs/ Sub631, Sub657, Sub78, Sub85, Sub89
	common /hdd_varXs/ Sub107, Sub100, Sub111, Sub121, Sub128
	common /hdd_varXs/ Sub132, Sub600, Sub603, Sub605, Sub108
	common /hdd_varXs/ Sub129, Sub604, Sub86, Sub112, Sub133
	common /hdd_varXs/ Sub606, Sub90, Sub17, Sub10, Sub21, Sub32
	common /hdd_varXs/ Sub39, Sub43, Sub54, Sub61, Sub616
	common /hdd_varXs/ Sub628, Sub634, Sub68, Sub18, Sub40
	common /hdd_varXs/ Sub62, Sub22, Sub44, Sub69, Sub331
	common /hdd_varXs/ Sub520, Sub524, Sub425, Sub428, Sub486
	common /hdd_varXs/ Sub505, Sub366, Sub528, Sub283, Sub460
	common /hdd_varXs/ Sub404, Sub399, Sub556, Sub558, Sub199
	common /hdd_varXs/ Sub251, Sub270, Sub156, Sub157, Sub148
	common /hdd_varXs/ Sub153, Sub678, Sub682, Sub303, Sub321
	common /hdd_varXs/ Sub521, Sub525, Sub529, Sub338, Sub441
	common /hdd_varXs/ Sub397, Sub455, pave1, pave2, pave3
	common /hdd_varXs/ pave4, pave5, pave6, pave7, pave8, pave9
	common /hdd_varXs/ pave10, pave11, pave12, pave13, pave14
	common /hdd_varXs/ pave15, pave16, pave17, pave18, pave19
	common /hdd_varXs/ pave20, pave21, pave22, pave23, pave24
	common /hdd_varXs/ pave25, pave26, pave27, pave28, pave29
	common /hdd_varXs/ pave30, pave31, pave32, pave33, pave34
	common /hdd_varXs/ pave35, pave36, pave37, pave38, pave39
	common /hdd_varXs/ pave40, pave41, pave42, pave43, pave44
	common /hdd_varXs/ pave45, pave46, pave47, pave48, pave49
	common /hdd_varXs/ pave50, pave51, pave52, pave53, pave54
	common /hdd_varXs/ pave55, pave56, pave57, pave58, pave59
	common /hdd_varXs/ pave60, pave61, pave62, pave63, pave64
	common /hdd_varXs/ pave65, pave66, pave67, pave68, pave69
	common /hdd_varXs/ pave70, pave71, pave72, pave73, pave74
	common /hdd_varXs/ pave75, pave76, pave77, pave78, pave79
	common /hdd_varXs/ pave80, pave81, pave82, pave83, pave84
	common /hdd_varXs/ pave85, pave86, pave87, pave88, pave89
	common /hdd_varXs/ pave90

	ComplexType F1, F2
	ComplexType Sub439, Sub239, Sub351, Sub371, Sub379, Sub387
	ComplexType Sub554, Sub559, Sub571, Sub355, Sub182, Sub353
	ComplexType Sub342, Sub345, Sub339, Sub347, Sub354, Sub357
	ComplexType Sub393, Sub398, Sub401, Sub405, Sub469, Sub451
	ComplexType Sub458, Sub462, Sub593, Sub179, Sub176, Sub447
	ComplexType Sub389, Sub470, Sub513, Sub363, Sub177, Sub380
	ComplexType Sub372, Sub426, Sub336, Sub407, Sub349, Sub491
	ComplexType Sub509, Sub402, Sub492, Sub510, Sub403, Sub594
	ComplexType Sub519, Sub346, Sub334, Sub335, Sub343, Sub348
	ComplexType Sub344, Sub180, Sub183, Sub184, Sub332, Sub341
	ComplexType Sub369, Sub430, Sub378, Sub386, Sub433, Sub435
	ComplexType Sub511, Sub482, Sub490, Sub477, Sub502, Sub508
	ComplexType Sub497, Sub515, Sub543, Sub546, Sub578, Sub590
	ComplexType Sub561, Sub548, Sub385, Sub377, Sub434, Sub432
	ComplexType Sub592, Sub476, Sub496, Sub481, Sub501, Sub276
	ComplexType Sub267, Sub188, Sub232, Sub226, Sub212, Sub272
	ComplexType Sub253, Sub574, Sub547, Sub560, Sub538, Sub431
	ComplexType Sub517, Sub572, Sub581, Sub585, Sub333, Sub516
	ComplexType Sub514, Sub362, Sub181(3), Sub178(3)
	ComplexType Sub185(3), Sub218(3)
	ComplexType Sub195(3), Sub252(3)
	ComplexType Sub200(3), Sub213(3)
	ComplexType Sub206(3), Sub207(3)
	ComplexType Sub256(3), Sub175(3)
	ComplexType Sub187(3), Sub190(3)
	ComplexType Sub192(3), Sub194(3)
	ComplexType Sub196(3), Sub197(3)
	ComplexType Sub203(3), Sub204(3)
	ComplexType Sub208(3), Sub209(3)
	ComplexType Sub214(3), Sub215(3)
	ComplexType Sub217(3), Sub221(3)
	ComplexType Sub222(3), Sub224(3)
	ComplexType Sub225(3), Sub227(3)
	ComplexType Sub229(3), Sub230(3)
	ComplexType Sub236(3), Sub243(3)
	ComplexType Sub245(3), Sub246(3)
	ComplexType Sub248(3), Sub249(3)
	ComplexType Sub250(3), Sub255(3)
	ComplexType Sub266(3), Sub269(3)
	ComplexType Sub271(3), Sub274(3)
	ComplexType Sub275(3), Sub280(3)
	ComplexType Sub289(3), Sub164(3)
	ComplexType Sub671(6,6), Sub672(6,6)
	ComplexType Sub673(6,6), Sub668(6,6,4)
	ComplexType Sub669(6,6,4), Sub667(6,6,4)
	ComplexType Sub670(6,6,4), Sub716(6,4,4)
	ComplexType Sub704(6,4,4), Sub713(6,4,4)
	ComplexType Sub710(6,4,4), Sub709(6,4,4)
	ComplexType Sub706(6,4,4), Sub707(6,4,4)
	ComplexType Sub708(6,4,4), Sub711(6,4,4)
	ComplexType Sub715(6,4,4), Sub717(6,4,4)
	ComplexType Sub718(6,4,4), Sub719(6,4,4)
	ComplexType Sub597(6,6,2,3,3), Sub134(6,6,3,3,3)
	ComplexType Sub92(6,6,3,3,3), Sub113(6,6,3,3,3)
	ComplexType Sub690(6,2,2,3,3), Sub686(6,2,2,3,3)
	ComplexType Sub688(6,2,2,3,3), Sub689(6,2,2,3,3)
	ComplexType Sub693(6,2,2,3,3), Sub694(6,2,2,3,3)
	ComplexType Sub697(6,2,2,3,3), Sub698(6,2,2,3,3)
	ComplexType Sub699(6,2,2,3,3), Sub691(6,2,2,3,3)
	ComplexType Sub683(6,2,2,3,3), Sub687(6,2,2,3,3)
	ComplexType Sub692(6,2,2,3,3), Sub696(6,2,2,3,3)
	ComplexType Sub684(6,2,2,3,3), Sub685(6,2,2,3,3)
	ComplexType Sub642(6,6,2,3,3,3,3)
	ComplexType Sub637(6,6,2,3,3,3,3)
	ComplexType Sub618(6,6,2,3,3,3,3)
	ComplexType Sub638(6,6,2,3,3,3,3)
	ComplexType Sub629(6,6,2,3,3,3,3)
	ComplexType Sub640(6,6,2,3,3,3,3)
	ComplexType Sub635(6,6,2,3,3,3,3)
	ComplexType Sub630(6,6,2,3,3,3,3)
	ComplexType Sub639(6,6,2,3,3,3,3)
	ComplexType Sub636(6,6,2,3,3,3,3)
	ComplexType Sub641(6,6,2,3,3,3,3), Sub468, Sub361
	ComplexType Sub562, Sub436, Sub388, Sub406, Sub518, Sub591
	ComplexType Sub579, Sub233(3), Sub186(3)
	ComplexType Sub205(3), Sub238(3)
	ComplexType Sub241(3), Sub265(3)
	ComplexType Sub287(3), Sub712(6,4,4)
	ComplexType Sub714(6,4,4), Sub720(6,4,4)
	ComplexType Sub700(6,2,2,3,3), Sub350, Sub234(3)
	ComplexType Sub288(3), Sub290(3)
	ComplexType Sub291(3), Sub159(2,2)
	ComplexType Sub329(4,4), Sub161(2,2)
	ComplexType Sub327(4,4)
	common /hdd_varXh/ F1, F2, Sub439, Sub239, Sub351, Sub371
	common /hdd_varXh/ Sub379, Sub387, Sub554, Sub559, Sub571
	common /hdd_varXh/ Sub355, Sub182, Sub353, Sub342, Sub345
	common /hdd_varXh/ Sub339, Sub347, Sub354, Sub357, Sub393
	common /hdd_varXh/ Sub398, Sub401, Sub405, Sub469, Sub451
	common /hdd_varXh/ Sub458, Sub462, Sub593, Sub179, Sub176
	common /hdd_varXh/ Sub447, Sub389, Sub470, Sub513, Sub363
	common /hdd_varXh/ Sub177, Sub380, Sub372, Sub426, Sub336
	common /hdd_varXh/ Sub407, Sub349, Sub491, Sub509, Sub402
	common /hdd_varXh/ Sub492, Sub510, Sub403, Sub594, Sub519
	common /hdd_varXh/ Sub346, Sub334, Sub335, Sub343, Sub348
	common /hdd_varXh/ Sub344, Sub180, Sub183, Sub184, Sub332
	common /hdd_varXh/ Sub341, Sub369, Sub430, Sub378, Sub386
	common /hdd_varXh/ Sub433, Sub435, Sub511, Sub482, Sub490
	common /hdd_varXh/ Sub477, Sub502, Sub508, Sub497, Sub515
	common /hdd_varXh/ Sub543, Sub546, Sub578, Sub590, Sub561
	common /hdd_varXh/ Sub548, Sub385, Sub377, Sub434, Sub432
	common /hdd_varXh/ Sub592, Sub476, Sub496, Sub481, Sub501
	common /hdd_varXh/ Sub276, Sub267, Sub188, Sub232, Sub226
	common /hdd_varXh/ Sub212, Sub272, Sub253, Sub574, Sub547
	common /hdd_varXh/ Sub560, Sub538, Sub431, Sub517, Sub572
	common /hdd_varXh/ Sub581, Sub585, Sub333, Sub516, Sub514
	common /hdd_varXh/ Sub362, Sub181, Sub178, Sub185, Sub218
	common /hdd_varXh/ Sub195, Sub252, Sub200, Sub213, Sub206
	common /hdd_varXh/ Sub207, Sub256, Sub175, Sub187, Sub190
	common /hdd_varXh/ Sub192, Sub194, Sub196, Sub197, Sub203
	common /hdd_varXh/ Sub204, Sub208, Sub209, Sub214, Sub215
	common /hdd_varXh/ Sub217, Sub221, Sub222, Sub224, Sub225
	common /hdd_varXh/ Sub227, Sub229, Sub230, Sub236, Sub243
	common /hdd_varXh/ Sub245, Sub246, Sub248, Sub249, Sub250
	common /hdd_varXh/ Sub255, Sub266, Sub269, Sub271, Sub274
	common /hdd_varXh/ Sub275, Sub280, Sub289, Sub164, Sub671
	common /hdd_varXh/ Sub672, Sub673, Sub668, Sub669, Sub667
	common /hdd_varXh/ Sub670, Sub716, Sub704, Sub713, Sub710
	common /hdd_varXh/ Sub709, Sub706, Sub707, Sub708, Sub711
	common /hdd_varXh/ Sub715, Sub717, Sub718, Sub719, Sub597
	common /hdd_varXh/ Sub134, Sub92, Sub113, Sub690, Sub686
	common /hdd_varXh/ Sub688, Sub689, Sub693, Sub694, Sub697
	common /hdd_varXh/ Sub698, Sub699, Sub691, Sub683, Sub687
	common /hdd_varXh/ Sub692, Sub696, Sub684, Sub685, Sub642
	common /hdd_varXh/ Sub637, Sub618, Sub638, Sub629, Sub640
	common /hdd_varXh/ Sub635, Sub630, Sub639, Sub636, Sub641
	common /hdd_varXh/ Sub468, Sub361, Sub562, Sub436, Sub388
	common /hdd_varXh/ Sub406, Sub518, Sub591, Sub579, Sub233
	common /hdd_varXh/ Sub186, Sub205, Sub238, Sub241, Sub265
	common /hdd_varXh/ Sub287, Sub712, Sub714, Sub720, Sub700
	common /hdd_varXh/ Sub350, Sub234, Sub288, Sub290, Sub291
	common /hdd_varXh/ Sub159, Sub329, Sub161, Sub327

	integer seq(2), Hel(3)
	common /hdd_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /hdd_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hdd_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	ComplexType MatSUN(1,1)
	common /hdd_formfactors/ Ctree, Cloop, MatSUN

#endif
