#if 0
* hgaZ-vars.h
* variable declarations
* generated by FormCalc 9.7 (3 Aug 2018) on 3-Aug-2018 10:00
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "hgaZ-RenConst.h.F"

#else

#include "Decay.h"
#include "hgaZ-RenConst.h.F"

	ComplexType B0i1(2,2), B0i2, B0i3, B0i4, B0i5, B0i6(6,6)
	ComplexType B0i7(3), B0i8(3), B0i9(3), B0i10(6,6)
	ComplexType B0i11(6,6), C0i1(Ncc), C0i2(Ncc), C0i3(Ncc,6,6)
	ComplexType C0i4(Ncc,2,2), C0i5(Ncc,3), C0i6(Ncc,3)
	ComplexType C0i7(Ncc,3), C0i8(Ncc,6,6), C0i9(Ncc,6,6)
	ComplexType Sub1(6,6), Sub2(3), Sub3(3,3), Sub4(6,3,3)
	ComplexType Sub5(3), Sub6(3,3), Sub7(6,3,3), Sub8(6,6,3,3)
	ComplexType Sub9(6,6,3), Sub10(6,6,3), Sub11(6,3,3)
	ComplexType Sub12(6,3,3), Sub13(6,6,3,3), Sub14(6,6,3,3,3)
	ComplexType Sub15(3), Sub16(3,3), Sub17(6,3,3), Sub18(3)
	ComplexType Sub19(3,3), Sub20(6,3,3), Sub21(6,6,3,3)
	ComplexType Sub22(6,3,3), Sub23(6,3,3), Sub24(6,6,3,3)
	ComplexType Sub25(6,6,3,3,3), Sub26(6,6,3,3,3), Sub27(3,3)
	ComplexType Sub28(3,3), Sub29(6,6,3,3), Sub30(6,6,3,3)
	ComplexType Sub31(6,6,3,3,3), Sub32(6,6,3,3,3), Sub33(6,6)
	ComplexType Sub34(3), Sub35(3,3), Sub36(6,3,3), Sub37(3)
	ComplexType Sub38(3,3), Sub39(6,3,3), Sub40(6,6,3,3)
	ComplexType Sub41(6,6,3), Sub42(6,6,3), Sub43(6,3,3)
	ComplexType Sub44(6,3,3), Sub45(6,6,3,3), Sub46(6,6,3,3,3)
	ComplexType Sub47(3), Sub48(3,3), Sub49(6,3,3), Sub50(3)
	ComplexType Sub51(3,3), Sub52(6,3,3), Sub53(6,6,3,3)
	ComplexType Sub54(6,3,3), Sub55(6,3,3), Sub56(6,6,3,3)
	ComplexType Sub57(6,6,3,3,3), Sub58(6,6,3,3,3), Sub59(3,3)
	ComplexType Sub60(3,3), Sub61(6,6,3,3), Sub62(6,6,3,3)
	ComplexType Sub63(6,6,3,3,3), Sub64(6,6,3,3,3), Sub65(6,6)
	ComplexType Sub66(3), Sub67(3,3), Sub68(6,3,3), Sub69(3)
	ComplexType Sub70(3,3), Sub71(6,3,3), Sub72(6,6,3,3)
	ComplexType Sub73(6,6,3), Sub74(6,6,3), Sub75(6,3,3)
	ComplexType Sub76(6,3,3), Sub77(6,6,3,3), Sub78(6,6,3,3,3)
	ComplexType Sub79(3), Sub80(3,3), Sub81(6,3,3), Sub82(3)
	ComplexType Sub83(3,3), Sub84(6,3,3), Sub85(6,6,3,3)
	ComplexType Sub86(6,3,3), Sub87(6,3,3), Sub88(6,6,3,3)
	ComplexType Sub89(6,6,3,3,3), Sub90(6,6,3,3,3), Sub91(3,3)
	ComplexType Sub92(3,3), Sub93(6,6,3,3), Sub94(6,6,3,3)
	ComplexType Sub95(6,6,3,3,3), Sub96(6,6,3,3,3)
	ComplexType Sub97(6,6,3,3,3), Sub98(6,6,3,3), Sub99(6,6,3,3)
	ComplexType Sub100(6,6,3,3), Sub101(6,6,3,3)
	ComplexType Sub102(6,6,3,3), Sub103(6,6,3,3)
	ComplexType Sub104(6,6,3,3,3), Sub105(6,6,3,3,3)
	ComplexType Sub106(2,2), Sub107(2,2), Sub108(2,2)
	ComplexType Sub109(2,2), Sub110(2,2), Sub111(2,2)
	ComplexType Sub112(2,2), Sub113(2,2), Sub114(2,2)
	ComplexType Sub115(2,2), Sub116(2,2), Sub117(2,2)
	ComplexType Sub118(2,2), Sub119(2,2), Sub120(2,2)
	ComplexType Sub121(2,2), Sub122(2,2), Sub123(2,2)
	ComplexType Sub124(2,2), Sub125(2,2), Sub127(2,2)
	ComplexType Sub131(2,2), Sub132(2,2), Sub134(2,2)
	ComplexType Sub135(2,2), Sub140(3), Sub141(3), Sub143
	ComplexType Sub144, Sub145, Sub149(3), Sub150(3), Sub152
	ComplexType Sub153, Sub154, Sub158(3), Sub159(3), Sub161(3)
	ComplexType Sub162(3), Sub163(3), Sub164(3), Sub165(3)
	ComplexType Sub166(3), Sub167(3), Sub168(3), Sub169(3)
	ComplexType Sub173, Sub174, Sub176, Sub179, Sub181, Sub182
	ComplexType Sub183, Sub184, Sub186, Sub189, Sub190, Sub191
	ComplexType Sub192, Sub126(2,2), Sub129(2,2), Sub130(2,2)
	common /hgaZ_varXs/ B0i1, B0i2, B0i3, B0i4, B0i5, B0i6, B0i7
	common /hgaZ_varXs/ B0i8, B0i9, B0i10, B0i11, C0i1, C0i2
	common /hgaZ_varXs/ C0i3, C0i4, C0i5, C0i6, C0i7, C0i8, C0i9
	common /hgaZ_varXs/ Sub1, Sub2, Sub3, Sub4, Sub5, Sub6, Sub7
	common /hgaZ_varXs/ Sub8, Sub9, Sub10, Sub11, Sub12, Sub13
	common /hgaZ_varXs/ Sub14, Sub15, Sub16, Sub17, Sub18, Sub19
	common /hgaZ_varXs/ Sub20, Sub21, Sub22, Sub23, Sub24, Sub25
	common /hgaZ_varXs/ Sub26, Sub27, Sub28, Sub29, Sub30, Sub31
	common /hgaZ_varXs/ Sub32, Sub33, Sub34, Sub35, Sub36, Sub37
	common /hgaZ_varXs/ Sub38, Sub39, Sub40, Sub41, Sub42, Sub43
	common /hgaZ_varXs/ Sub44, Sub45, Sub46, Sub47, Sub48, Sub49
	common /hgaZ_varXs/ Sub50, Sub51, Sub52, Sub53, Sub54, Sub55
	common /hgaZ_varXs/ Sub56, Sub57, Sub58, Sub59, Sub60, Sub61
	common /hgaZ_varXs/ Sub62, Sub63, Sub64, Sub65, Sub66, Sub67
	common /hgaZ_varXs/ Sub68, Sub69, Sub70, Sub71, Sub72, Sub73
	common /hgaZ_varXs/ Sub74, Sub75, Sub76, Sub77, Sub78, Sub79
	common /hgaZ_varXs/ Sub80, Sub81, Sub82, Sub83, Sub84, Sub85
	common /hgaZ_varXs/ Sub86, Sub87, Sub88, Sub89, Sub90, Sub91
	common /hgaZ_varXs/ Sub92, Sub93, Sub94, Sub95, Sub96, Sub97
	common /hgaZ_varXs/ Sub98, Sub99, Sub100, Sub101, Sub102
	common /hgaZ_varXs/ Sub103, Sub104, Sub105, Sub106, Sub107
	common /hgaZ_varXs/ Sub108, Sub109, Sub110, Sub111, Sub112
	common /hgaZ_varXs/ Sub113, Sub114, Sub115, Sub116, Sub117
	common /hgaZ_varXs/ Sub118, Sub119, Sub120, Sub121, Sub122
	common /hgaZ_varXs/ Sub123, Sub124, Sub125, Sub127, Sub131
	common /hgaZ_varXs/ Sub132, Sub134, Sub135, Sub140, Sub141
	common /hgaZ_varXs/ Sub143, Sub144, Sub145, Sub149, Sub150
	common /hgaZ_varXs/ Sub152, Sub153, Sub154, Sub158, Sub159
	common /hgaZ_varXs/ Sub161, Sub162, Sub163, Sub164, Sub165
	common /hgaZ_varXs/ Sub166, Sub167, Sub168, Sub169, Sub173
	common /hgaZ_varXs/ Sub174, Sub176, Sub179, Sub181, Sub182
	common /hgaZ_varXs/ Sub183, Sub184, Sub186, Sub189, Sub190
	common /hgaZ_varXs/ Sub191, Sub192, Sub126, Sub129, Sub130

	ComplexType Eps1, Pair1, Pair2, Pair3, Sub128(2,2), Sub142(3)
	ComplexType Sub151(3), Sub160(3), Abb1, Abb2, Abb3, Abb4
	ComplexType Abb5, Abb6, Abb7, Abb8, Abb9, Abb10, Sub133(2,2)
	ComplexType Sub136(2,2), Sub137(2,2), Sub138(2,2)
	ComplexType Sub139(2,2), Sub146, Sub147(3), Sub148(3)
	ComplexType Sub155, Sub156(3), Sub157(3), Sub170(3)
	ComplexType Sub171(3), Sub172(3), Sub175, Sub177, Sub178
	ComplexType Sub180, Sub185, Sub187, Sub188, Sub193
	common /hgaZ_varXh/ Eps1, Pair1, Pair2, Pair3, Sub128, Sub142
	common /hgaZ_varXh/ Sub151, Sub160, Abb1, Abb2, Abb3, Abb4
	common /hgaZ_varXh/ Abb5, Abb6, Abb7, Abb8, Abb9, Abb10
	common /hgaZ_varXh/ Sub133, Sub136, Sub137, Sub138, Sub139
	common /hgaZ_varXh/ Sub146, Sub147, Sub148, Sub155, Sub156
	common /hgaZ_varXh/ Sub157, Sub170, Sub171, Sub172, Sub175
	common /hgaZ_varXh/ Sub177, Sub178, Sub180, Sub185, Sub187
	common /hgaZ_varXh/ Sub188, Sub193

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3
	common /hgaZ_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1
	common /hgaZ_indices/ Ind2, Ind3

	ComplexType Cloop(1)
	common /hgaZ_formfactors/ Cloop

#endif

