#if 0
* hgaZ-vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Feb-2015 17:19
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hgaZ-renconst.h"

	ComplexType Sub182, Sub175, Sub192, Sub189, Sub186, Sub190
	ComplexType Sub179, Sub187, Sub174, Sub152, Sub173, Sub143
	ComplexType Sub183, Sub185, Sub144, Sub145, Sub153, Sub154
	ComplexType Sub149(3), Sub158(3), Sub140(3), Sub150(3)
	ComplexType Sub159(3), Sub141(3), Sub161(3), Sub162(3)
	ComplexType Sub164(3), Sub166(3), Sub168(3), Sub163(3)
	ComplexType Sub167(3), Sub169(3), Sub165(3), Sub15(3)
	ComplexType Sub18(3), Sub2(3), Sub5(3), Sub48(3), Sub51(3)
	ComplexType Sub35(3), Sub38(3), Sub68(3), Sub71(3), Sub84(3)
	ComplexType Sub81(3), Sub127(2,2), Sub134(2,2), Sub131(2,2)
	ComplexType Sub132(2,2), Sub135(2,2), Sub130(2,2)
	ComplexType Sub107(2,2), Sub109(2,2), Sub108(2,2)
	ComplexType Sub112(2,2), Sub114(2,2), Sub113(2,2)
	ComplexType Sub117(2,2), Sub119(2,2), Sub118(2,2)
	ComplexType Sub122(2,2), Sub124(2,2), Sub123(2,2)
	ComplexType Sub28(3,3), Sub6(3,3), Sub27(3,3), Sub3(3,3)
	ComplexType Sub19(3,3), Sub16(3,3), Sub61(3,3), Sub39(3,3)
	ComplexType Sub60(3,3), Sub36(3,3), Sub52(3,3), Sub49(3,3)
	ComplexType Sub85(3,3), Sub82(3,3), Sub72(3,3), Sub69(3,3)
	ComplexType Sub94(3,3), Sub93(3,3), Sub10(6,6,3)
	ComplexType Sub43(6,6,3), Sub76(6,6,3), Sub9(6,6,3)
	ComplexType Sub42(6,6,3), Sub75(6,6,3), Sub23(6,3,3)
	ComplexType Sub12(6,3,3), Sub45(6,3,3), Sub56(6,3,3)
	ComplexType Sub78(6,3,3), Sub89(6,3,3), Sub22(6,3,3)
	ComplexType Sub11(6,3,3), Sub44(6,3,3), Sub55(6,3,3)
	ComplexType Sub77(6,3,3), Sub88(6,3,3), Sub20(6,3,3)
	ComplexType Sub7(6,3,3), Sub40(6,3,3), Sub53(6,3,3)
	ComplexType Sub73(6,3,3), Sub86(6,3,3), Sub17(6,3,3)
	ComplexType Sub4(6,3,3), Sub37(6,3,3), Sub50(6,3,3)
	ComplexType Sub70(6,3,3), Sub83(6,3,3), Sub21(6,6,3,3)
	ComplexType Sub8(6,6,3,3), Sub29(6,6,3,3), Sub41(6,6,3,3)
	ComplexType Sub54(6,6,3,3), Sub62(6,6,3,3), Sub74(6,6,3,3)
	ComplexType Sub87(6,6,3,3), Sub95(6,6,3,3), Sub13(6,6,3,3)
	ComplexType Sub24(6,6,3,3), Sub30(6,6,3,3), Sub46(6,6,3,3)
	ComplexType Sub57(6,6,3,3), Sub63(6,6,3,3), Sub79(6,6,3,3)
	ComplexType Sub90(6,6,3,3), Sub96(6,6,3,3), Sub99(6,6,3,3)
	ComplexType Sub101(6,6,3,3), Sub103(6,6,3,3)
	ComplexType Sub100(6,6,3,3), Sub102(6,6,3,3)
	ComplexType Sub104(6,6,3,3), Sub47(6,6,3,3,3)
	ComplexType Sub58(6,6,3,3,3), Sub64(6,6,3,3,3)
	ComplexType Sub80(6,6,3,3,3), Sub25(6,6,3,3,3)
	ComplexType Sub31(6,6,3,3,3), Sub14(6,6,3,3,3)
	ComplexType Sub91(6,6,3,3,3), Sub97(6,6,3,3,3)
	ComplexType Sub26(6,6,3,3,3), Sub59(6,6,3,3,3)
	ComplexType Sub92(6,6,3,3,3), Sub32(6,6,3,3,3)
	ComplexType Sub65(6,6,3,3,3), Sub98(6,6,3,3,3), Sub180
	ComplexType Sub1(6,6), Sub33(6,6), Sub66(6,6), Sub111(2,2)
	ComplexType Sub121(2,2), Sub106(2,2), Sub116(2,2)
	ComplexType Sub110(2,2), Sub115(2,2), Sub120(2,2)
	ComplexType Sub125(2,2), Sub129(2,2), Sub126(2,2)
	ComplexType Sub105(6,6,3,3,3), pave1(2,2), pave2, pave3
	ComplexType pave4(Ncc), pave5(Ncc), pave6, pave7, pave8(3)
	ComplexType pave9(Ncc,3), pave10(3), pave11(Ncc,3)
	ComplexType pave12(3), pave13(Ncc,3), pave14(Ncc,6,6)
	ComplexType pave15(Ncc,6,6), pave16(Ncc,2,2)
	ComplexType pave17(Ncc,6,6), pave18(6,6), pave19(6,6)
	ComplexType pave20(6,6)
	common /hgaZ_varXs/ Sub182, Sub175, Sub192, Sub189, Sub186
	common /hgaZ_varXs/ Sub190, Sub179, Sub187, Sub174, Sub152
	common /hgaZ_varXs/ Sub173, Sub143, Sub183, Sub185, Sub144
	common /hgaZ_varXs/ Sub145, Sub153, Sub154, Sub149, Sub158
	common /hgaZ_varXs/ Sub140, Sub150, Sub159, Sub141, Sub161
	common /hgaZ_varXs/ Sub162, Sub164, Sub166, Sub168, Sub163
	common /hgaZ_varXs/ Sub167, Sub169, Sub165, Sub15, Sub18
	common /hgaZ_varXs/ Sub2, Sub5, Sub48, Sub51, Sub35, Sub38
	common /hgaZ_varXs/ Sub68, Sub71, Sub84, Sub81, Sub127
	common /hgaZ_varXs/ Sub134, Sub131, Sub132, Sub135, Sub130
	common /hgaZ_varXs/ Sub107, Sub109, Sub108, Sub112, Sub114
	common /hgaZ_varXs/ Sub113, Sub117, Sub119, Sub118, Sub122
	common /hgaZ_varXs/ Sub124, Sub123, Sub28, Sub6, Sub27, Sub3
	common /hgaZ_varXs/ Sub19, Sub16, Sub61, Sub39, Sub60, Sub36
	common /hgaZ_varXs/ Sub52, Sub49, Sub85, Sub82, Sub72, Sub69
	common /hgaZ_varXs/ Sub94, Sub93, Sub10, Sub43, Sub76, Sub9
	common /hgaZ_varXs/ Sub42, Sub75, Sub23, Sub12, Sub45, Sub56
	common /hgaZ_varXs/ Sub78, Sub89, Sub22, Sub11, Sub44, Sub55
	common /hgaZ_varXs/ Sub77, Sub88, Sub20, Sub7, Sub40, Sub53
	common /hgaZ_varXs/ Sub73, Sub86, Sub17, Sub4, Sub37, Sub50
	common /hgaZ_varXs/ Sub70, Sub83, Sub21, Sub8, Sub29, Sub41
	common /hgaZ_varXs/ Sub54, Sub62, Sub74, Sub87, Sub95, Sub13
	common /hgaZ_varXs/ Sub24, Sub30, Sub46, Sub57, Sub63, Sub79
	common /hgaZ_varXs/ Sub90, Sub96, Sub99, Sub101, Sub103
	common /hgaZ_varXs/ Sub100, Sub102, Sub104, Sub47, Sub58
	common /hgaZ_varXs/ Sub64, Sub80, Sub25, Sub31, Sub14, Sub91
	common /hgaZ_varXs/ Sub97, Sub26, Sub59, Sub92, Sub32, Sub65
	common /hgaZ_varXs/ Sub98, Sub180, Sub1, Sub33, Sub66
	common /hgaZ_varXs/ Sub111, Sub121, Sub106, Sub116, Sub110
	common /hgaZ_varXs/ Sub115, Sub120, Sub125, Sub129, Sub126
	common /hgaZ_varXs/ Sub105, pave1, pave2, pave3, pave4
	common /hgaZ_varXs/ pave5, pave6, pave7, pave8, pave9
	common /hgaZ_varXs/ pave10, pave11, pave12, pave13, pave14
	common /hgaZ_varXs/ pave15, pave16, pave17, pave18, pave19
	common /hgaZ_varXs/ pave20

	ComplexType Pair1, Pair2, Pair3, Eps1, Abb6, Abb10, Abb9, Abb11
	ComplexType Abb8, Abb5, Abb7, Abb2, Abb1, Abb4, Abb3, Sub146
	ComplexType Sub155, Sub181, Sub195, Sub176, Sub196, Sub177
	ComplexType Sub194, Sub197, Sub184, Sub198, Sub191, Sub188
	ComplexType Sub178, Sub199, Sub156(3), Sub147(3)
	ComplexType Sub142(3), Sub148(3)
	ComplexType Sub151(3), Sub157(3)
	ComplexType Sub160(3), Sub170(3)
	ComplexType Sub171(3), Sub172(3)
	ComplexType Sub34(6,6), Sub67(6,6)
	ComplexType Sub128(2,2), Sub133(2,2)
	ComplexType Sub137(2,2), Sub136(2,2)
	ComplexType Sub138(2,2), Sub139(2,2), Sub200
	ComplexType Sub193
	common /hgaZ_varXh/ Pair1, Pair2, Pair3, Eps1, Abb6, Abb10
	common /hgaZ_varXh/ Abb9, Abb11, Abb8, Abb5, Abb7, Abb2
	common /hgaZ_varXh/ Abb1, Abb4, Abb3, Sub146, Sub155, Sub181
	common /hgaZ_varXh/ Sub195, Sub176, Sub196, Sub177, Sub194
	common /hgaZ_varXh/ Sub197, Sub184, Sub198, Sub191, Sub188
	common /hgaZ_varXh/ Sub178, Sub199, Sub156, Sub147, Sub142
	common /hgaZ_varXh/ Sub148, Sub151, Sub157, Sub160, Sub170
	common /hgaZ_varXh/ Sub171, Sub172, Sub34, Sub67, Sub128
	common /hgaZ_varXh/ Sub133, Sub137, Sub136, Sub138, Sub139
	common /hgaZ_varXh/ Sub200, Sub193

	integer seq(2), Hel(3)
	common /hgaZ_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3
	common /hgaZ_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1
	common /hgaZ_indices/ Ind2, Ind3

	ComplexType Cloop(1)
	common /hgaZ_formfactors/ Cloop

#endif
