#if 0
* hgaZ-vars.h
* variable declarations
* generated by FormCalc 8.4 on 30-Apr-2014 7:29
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hgaZ-renconst.h"

	ComplexType Sub171, Sub175, Sub183, Sub180, Sub185, Sub181
	ComplexType Sub186, Sub173, Sub100, Sub172, Sub177, Sub101
	ComplexType Sub182, Sub187, Sub134, Sub155(3), Sub152(3)
	ComplexType Sub164(3), Sub156(3), Sub153(3), Sub165(3)
	ComplexType Sub159(3), Sub161(3), Sub15(3), Sub18(3)
	ComplexType Sub2(3), Sub5(3), Sub48(3), Sub51(3), Sub35(3)
	ComplexType Sub38(3), Sub68(3), Sub71(3), Sub84(3), Sub81(3)
	ComplexType Sub102(3), Sub104(3), Sub110(3), Sub112(3)
	ComplexType Sub120(3), Sub118(3), Sub103(6,3), Sub105(6,3)
	ComplexType Sub111(6,3), Sub113(6,3), Sub121(6,3)
	ComplexType Sub119(6,3), Sub141(2,2), Sub132(2,2)
	ComplexType Sub143(2,2), Sub144(2,2), Sub139(2,2)
	ComplexType Sub140(2,2), Sub145(2,2), Sub146(2,2)
	ComplexType Sub136(2,2), Sub138(2,2), Sub129(2,2)
	ComplexType Sub131(2,2), Sub28(3,3), Sub6(3,3), Sub27(3,3)
	ComplexType Sub3(3,3), Sub19(3,3), Sub16(3,3), Sub61(3,3)
	ComplexType Sub39(3,3), Sub60(3,3), Sub36(3,3), Sub52(3,3)
	ComplexType Sub49(3,3), Sub85(3,3), Sub82(3,3), Sub72(3,3)
	ComplexType Sub69(3,3), Sub94(3,3), Sub93(3,3), Sub10(6,6,3)
	ComplexType Sub43(6,6,3), Sub76(6,6,3), Sub9(6,6,3)
	ComplexType Sub42(6,6,3), Sub75(6,6,3), Sub106(6,6,3)
	ComplexType Sub114(6,6,3), Sub122(6,6,3), Sub23(6,3,3)
	ComplexType Sub12(6,3,3), Sub45(6,3,3), Sub56(6,3,3)
	ComplexType Sub78(6,3,3), Sub89(6,3,3), Sub22(6,3,3)
	ComplexType Sub11(6,3,3), Sub44(6,3,3), Sub55(6,3,3)
	ComplexType Sub77(6,3,3), Sub88(6,3,3), Sub20(6,3,3)
	ComplexType Sub7(6,3,3), Sub40(6,3,3), Sub53(6,3,3)
	ComplexType Sub73(6,3,3), Sub86(6,3,3), Sub17(6,3,3)
	ComplexType Sub4(6,3,3), Sub37(6,3,3), Sub50(6,3,3)
	ComplexType Sub70(6,3,3), Sub83(6,3,3), Sub115(6,6,3,3)
	ComplexType Sub123(6,6,3,3), Sub107(6,6,3,3), Sub21(6,6,3,3)
	ComplexType Sub8(6,6,3,3), Sub99(6,6,3,3), Sub29(6,6,3,3)
	ComplexType Sub41(6,6,3,3), Sub54(6,6,3,3), Sub109(6,6,3,3)
	ComplexType Sub62(6,6,3,3), Sub74(6,6,3,3), Sub87(6,6,3,3)
	ComplexType Sub117(6,6,3,3), Sub95(6,6,3,3), Sub13(6,6,3,3)
	ComplexType Sub24(6,6,3,3), Sub30(6,6,3,3), Sub46(6,6,3,3)
	ComplexType Sub57(6,6,3,3), Sub63(6,6,3,3), Sub79(6,6,3,3)
	ComplexType Sub90(6,6,3,3), Sub96(6,6,3,3), Sub108(6,6,3,3)
	ComplexType Sub116(6,6,3,3), Sub124(6,6,3,3)
	ComplexType Sub47(6,6,3,3,3), Sub58(6,6,3,3,3)
	ComplexType Sub64(6,6,3,3,3), Sub80(6,6,3,3,3)
	ComplexType Sub25(6,6,3,3,3), Sub31(6,6,3,3,3)
	ComplexType Sub14(6,6,3,3,3), Sub91(6,6,3,3,3)
	ComplexType Sub97(6,6,3,3,3), Sub26(6,6,3,3,3)
	ComplexType Sub59(6,6,3,3,3), Sub92(6,6,3,3,3)
	ComplexType Sub32(6,6,3,3,3), Sub65(6,6,3,3,3)
	ComplexType Sub98(6,6,3,3,3), Sub176, Sub127, Sub128, Sub135
	ComplexType Sub1(6,6), Sub33(6,6), Sub66(6,6), Sub137(2,2)
	ComplexType Sub130(2,2), Sub133(2,2), Sub126(2,2)
	ComplexType Sub125(6,6,3,3,3), pave1(2,2), pave2, pave3
	ComplexType pave4, pave5(Ncc), pave6(Ncc), pave7(3)
	ComplexType pave8(Ncc,3), pave9(3), pave10(Ncc,3), pave11(3)
	ComplexType pave12(Ncc,3), pave13(Ncc,6,6), pave14(Ncc,6,6)
	ComplexType pave15(Ncc,2,2), pave16, pave17(Ncc,6,6)
	ComplexType pave18(6,6), pave19(6,6), pave20(6,6)
	common /hgaZ_varXs/ Sub171, Sub175, Sub183, Sub180, Sub185
	common /hgaZ_varXs/ Sub181, Sub186, Sub173, Sub100, Sub172
	common /hgaZ_varXs/ Sub177, Sub101, Sub182, Sub187, Sub134
	common /hgaZ_varXs/ Sub155, Sub152, Sub164, Sub156, Sub153
	common /hgaZ_varXs/ Sub165, Sub159, Sub161, Sub15, Sub18
	common /hgaZ_varXs/ Sub2, Sub5, Sub48, Sub51, Sub35, Sub38
	common /hgaZ_varXs/ Sub68, Sub71, Sub84, Sub81, Sub102
	common /hgaZ_varXs/ Sub104, Sub110, Sub112, Sub120, Sub118
	common /hgaZ_varXs/ Sub103, Sub105, Sub111, Sub113, Sub121
	common /hgaZ_varXs/ Sub119, Sub141, Sub132, Sub143, Sub144
	common /hgaZ_varXs/ Sub139, Sub140, Sub145, Sub146, Sub136
	common /hgaZ_varXs/ Sub138, Sub129, Sub131, Sub28, Sub6
	common /hgaZ_varXs/ Sub27, Sub3, Sub19, Sub16, Sub61, Sub39
	common /hgaZ_varXs/ Sub60, Sub36, Sub52, Sub49, Sub85, Sub82
	common /hgaZ_varXs/ Sub72, Sub69, Sub94, Sub93, Sub10, Sub43
	common /hgaZ_varXs/ Sub76, Sub9, Sub42, Sub75, Sub106
	common /hgaZ_varXs/ Sub114, Sub122, Sub23, Sub12, Sub45
	common /hgaZ_varXs/ Sub56, Sub78, Sub89, Sub22, Sub11, Sub44
	common /hgaZ_varXs/ Sub55, Sub77, Sub88, Sub20, Sub7, Sub40
	common /hgaZ_varXs/ Sub53, Sub73, Sub86, Sub17, Sub4, Sub37
	common /hgaZ_varXs/ Sub50, Sub70, Sub83, Sub115, Sub123
	common /hgaZ_varXs/ Sub107, Sub21, Sub8, Sub99, Sub29, Sub41
	common /hgaZ_varXs/ Sub54, Sub109, Sub62, Sub74, Sub87
	common /hgaZ_varXs/ Sub117, Sub95, Sub13, Sub24, Sub30
	common /hgaZ_varXs/ Sub46, Sub57, Sub63, Sub79, Sub90, Sub96
	common /hgaZ_varXs/ Sub108, Sub116, Sub124, Sub47, Sub58
	common /hgaZ_varXs/ Sub64, Sub80, Sub25, Sub31, Sub14, Sub91
	common /hgaZ_varXs/ Sub97, Sub26, Sub59, Sub92, Sub32, Sub65
	common /hgaZ_varXs/ Sub98, Sub176, Sub127, Sub128, Sub135
	common /hgaZ_varXs/ Sub1, Sub33, Sub66, Sub137, Sub130
	common /hgaZ_varXs/ Sub133, Sub126, Sub125, pave1, pave2
	common /hgaZ_varXs/ pave3, pave4, pave5, pave6, pave7, pave8
	common /hgaZ_varXs/ pave9, pave10, pave11, pave12, pave13
	common /hgaZ_varXs/ pave14, pave15, pave16, pave17, pave18
	common /hgaZ_varXs/ pave19, pave20

	ComplexType Pair1, Pair2, Pair3, Eps1, Abb6, Abb10, Abb9, Abb11
	ComplexType Abb8, Abb5, Abb7, Abb2, Abb1, Abb4, Abb3, Sub179
	ComplexType Sub184, Sub178, Sub196, Sub193, Sub194, Sub195
	ComplexType Sub191, Sub167, Sub160, Sub162, Sub168
	ComplexType Sub169(3), Sub154(3)
	ComplexType Sub157(3), Sub158(3)
	ComplexType Sub166(3), Sub170(3)
	ComplexType Sub34(6,6), Sub67(6,6)
	ComplexType Sub148(2,2), Sub142(2,2)
	ComplexType Sub147(2,2), Sub149(2,2)
	ComplexType Sub150(2,2), Sub151(2,2), Sub174
	ComplexType Sub197, Sub189, Sub190, Sub163(3), Sub188
	ComplexType Sub192
	common /hgaZ_varXh/ Pair1, Pair2, Pair3, Eps1, Abb6, Abb10
	common /hgaZ_varXh/ Abb9, Abb11, Abb8, Abb5, Abb7, Abb2
	common /hgaZ_varXh/ Abb1, Abb4, Abb3, Sub179, Sub184, Sub178
	common /hgaZ_varXh/ Sub196, Sub193, Sub194, Sub195, Sub191
	common /hgaZ_varXh/ Sub167, Sub160, Sub162, Sub168, Sub169
	common /hgaZ_varXh/ Sub154, Sub157, Sub158, Sub166, Sub170
	common /hgaZ_varXh/ Sub34, Sub67, Sub148, Sub142, Sub147
	common /hgaZ_varXh/ Sub149, Sub150, Sub151, Sub174, Sub197
	common /hgaZ_varXh/ Sub189, Sub190, Sub163, Sub188, Sub192

	integer seq(2), Hel(3)
	common /hgaZ_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3
	common /hgaZ_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1
	common /hgaZ_indices/ Ind2, Ind3

	ComplexType Cloop(1)
	common /hgaZ_formfactors/ Cloop

#endif
