#! /bin/bash -x

test $# -eq 6 || {
  echo "Usage: $0 mhpfrom mhpto mhpstep tbfrom tbto tbstep"
  exit 1
}

dir="$0.$1.$2.$4.$5"
mkdir -p "$dir"

num=0

varsets() {
  bc -l << _EOF_
	scale=4
	for( mhp = $1; mhp <= $2; mhp += $3 ) {
	  for( tb = $4; tb <= $5; tb += $6 ) {
	    m3sq = 750 - 2*(mhp - 150)
	    mue = (5800 + 20*(mhp - 150))*m3sq/750
	    at = m3sq*650/1000
	    m1 = m3sq - 75
            num = num+1
	    print "MHp=",mhp,";"
	    print "M3SQ=",m3sq,";"
	    print "MUE=",mue,";"
	    print "At=",at,";"
	    print "M1=",m1,";"
	    print "TB=",tb,";\n"
	    print "num=",num,";\n"
	  }
	}
_EOF_
}

for varset in `varsets "$@"` ; do
  eval $varset
  file="$dir/mHH125-LHCHXSWG-br01.in.fh-$num"
###  build/FeynHiggs - 42423111
  cat << _EOF_ > $file
MT      173.2
TB      $TB
MHp     $MHp
M3SQ    $M3SQ
M3SU    $M3SQ
M3SD    2000
M3SL    2000
M3SE    2000
MUE     $MUE
At      $At
M_1     $M1
M_2     1000
M_3     2500
_EOF_

  PAGER= build/FeynHiggs "$file#SLHA" 42423111 > "$file.log"

done

