#if 0
* hggSM-vars.h
* variable declarations
* generated by FormCalc 9.6 (7 Mar 2018) on 13-Mar-2018 8:18
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType AaB01(3), AaB03(3), AaC0i2(Ncc,3), AaC0i4(Ncc,3)
	ComplexType Sub1(3), Sub2(3), Sub4(3), Sub5(3), Sub7(3)
	ComplexType Sub8(3)
	common /hggSM_varXs/ AaB01, AaB03, AaC0i2, AaC0i4, Sub1, Sub2
	common /hggSM_varXs/ Sub4, Sub5, Sub7, Sub8

	ComplexType Pair1, Pair2, Pair3, Abb1, Abb2, Sub3(3), Sub6(3)
	ComplexType Sub9(3)
	common /hggSM_varXh/ Pair1, Pair2, Pair3, Abb1, Abb2, Sub3
	common /hggSM_varXh/ Sub6, Sub9

	integer Gen4
	common /hggSM_indices/ Gen4

	ComplexType Cloop(1)
	ComplexType MatSUN(1,1)
	common /hggSM_formfactors/ Cloop, MatSUN

#endif

