#if 0
* hggSM-vars.h
* variable declarations
* generated by FormCalc 9.8 (22 Apr 2019) on 20-Dec-2019 10:10
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType B0i1(3), B0i2(3), C0i1(Ncc,3), C0i2(Ncc,3)
	ComplexType Sub1(3), Sub2(3), Sub4(3), Sub5(3), Sub7(3)
	ComplexType Sub8(3)
	common /hggSM_varXs/ B0i1, B0i2, C0i1, C0i2, Sub1, Sub2, Sub4
	common /hggSM_varXs/ Sub5, Sub7, Sub8

	ComplexType Pair1, Pair2, Pair3, Abb1, Abb2, Sub3(3), Sub6(3)
	ComplexType Sub9(3)
	common /hggSM_varXh/ Pair1, Pair2, Pair3, Abb1, Abb2, Sub3
	common /hggSM_varXh/ Sub6, Sub9

	integer Gen4
	common /hggSM_indices/ Gen4

	ComplexType Cloop(1)
	ComplexType MatSUN(1,1)
	common /hggSM_formfactors/ Cloop, MatSUN

#endif

