#if 0
* hggSM-vars.h
* variable declarations
* generated by FormCalc 8.4 on 30-Apr-2014 7:27
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"

	ComplexType Sub1(3), Sub4(3), Sub2(3), Sub5(3), Sub7(3)
	ComplexType Sub8(3), pave1(3), pave2(Ncc,3), pave3(3)
	ComplexType pave4(Ncc,3)
	common /hggSM_varXs/ Sub1, Sub4, Sub2, Sub5, Sub7, Sub8
	common /hggSM_varXs/ pave1, pave2, pave3, pave4

	ComplexType Pair1, Pair2, Pair3, Abb1, Abb2, Sub3(3)
	ComplexType Sub6(3), Sub9(3)
	common /hggSM_varXh/ Pair1, Pair2, Pair3, Abb1, Abb2, Sub3
	common /hggSM_varXh/ Sub6, Sub9

	integer seq(2), Hel(3)
	common /hggSM_helind/ seq, Hel

	integer Gen4
	common /hggSM_indices/ Gen4

	ComplexType Cloop(1)
	ComplexType MatSUN(1,1)
	common /hggSM_formfactors/ Cloop, MatSUN

#endif
