#if 0
* heeSM-vars.h
* variable declarations
* generated by FormCalc 9.7 (3 Aug 2018) on 3-Aug-2018 10:00
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "heeSM-RenConst.h.F"

#else

#include "Decay.h"
#include "heeSM-RenConst.h.F"

	ComplexType B0i1, B0i2, B0i3, C0i1(Ncc), C0i2(Ncc), C0i3(Ncc)
	ComplexType C0i4(Ncc), C0i5(Ncc), Sub2, Sub3, Sub5, Sub7
	ComplexType Sub8, Sub9, Sub10, Sub11, Sub12, Sub13, Sub14
	ComplexType Sub15, Sub16, Sub17, Sub18, Sub21, Sub22, Sub23
	ComplexType Sub26, Sub27, Sub28, Sub32, Sub33, Sub34, Sub35
	ComplexType Sub36, Sub37, Sub38, Sub41, Sub42, Sub43, Sub44
	ComplexType Sub45, Sub46, Sub47, Sub52, Sub53, Sub54, Sub55
	ComplexType Sub56, Sub57, Sub60, Sub61, Sub63, Sub64, Sub66
	ComplexType Sub67, Sub70, Sub71, Sub72, Sub73, Sub74, Sub75
	common /heeSM_varXs/ B0i1, B0i2, B0i3, C0i1, C0i2, C0i3, C0i4
	common /heeSM_varXs/ C0i5, Sub2, Sub3, Sub5, Sub7, Sub8
	common /heeSM_varXs/ Sub9, Sub10, Sub11, Sub12, Sub13, Sub14
	common /heeSM_varXs/ Sub15, Sub16, Sub17, Sub18, Sub21
	common /heeSM_varXs/ Sub22, Sub23, Sub26, Sub27, Sub28
	common /heeSM_varXs/ Sub32, Sub33, Sub34, Sub35, Sub36
	common /heeSM_varXs/ Sub37, Sub38, Sub41, Sub42, Sub43
	common /heeSM_varXs/ Sub44, Sub45, Sub46, Sub47, Sub52
	common /heeSM_varXs/ Sub53, Sub54, Sub55, Sub56, Sub57
	common /heeSM_varXs/ Sub60, Sub61, Sub63, Sub64, Sub66
	common /heeSM_varXs/ Sub67, Sub70, Sub71, Sub72, Sub73
	common /heeSM_varXs/ Sub74, Sub75

	ComplexType F1, F2
	ComplexType Sub1, Sub4, Sub6, Sub19, Sub20, Sub24, Sub25
	ComplexType Sub29, Sub30, Sub31, Sub39, Sub40, Sub48, Sub49
	ComplexType Sub50, Sub51, Sub58, Sub59, Sub62, Sub65, Sub68
	ComplexType Sub69, Sub76, Sub77, Sub78, Sub79, Sub80
	common /heeSM_varXh/ F1, F2, Sub1, Sub4, Sub6, Sub19, Sub20
	common /heeSM_varXh/ Sub24, Sub25, Sub29, Sub30, Sub31
	common /heeSM_varXh/ Sub39, Sub40, Sub48, Sub49, Sub50
	common /heeSM_varXh/ Sub51, Sub58, Sub59, Sub62, Sub65
	common /heeSM_varXh/ Sub68, Sub69, Sub76, Sub77, Sub78
	common /heeSM_varXh/ Sub79, Sub80

	ComplexType Ctree(1), Cloop(1)
	common /heeSM_formfactors/ Ctree, Cloop

#endif

