#if 0
* heeSM-vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Feb-2015 17:19
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "heeSM-renconst.h"

	ComplexType Sub1, Sub55, Sub57, Sub4, Sub15, Sub14, Sub31
	ComplexType Sub21, Sub9, Sub10, Sub34, Sub67, Sub72, Sub12
	ComplexType Sub53, Sub24, Sub32, Sub38, Sub66, Sub5, Sub54
	ComplexType Sub69, Sub71, Sub58, Sub46, Sub56, Sub44, Sub2
	ComplexType Sub19, Sub23, Sub27, Sub20, Sub16, Sub17, Sub52
	ComplexType Sub61, Sub68, Sub70, Sub35, Sub39, Sub3, Sub6
	ComplexType Sub50, Sub59, Sub28, Sub51, Sub60, Sub45, Sub47
	ComplexType pave1(Ncc), pave2, pave3, pave4(Ncc), pave5(Ncc)
	ComplexType pave6(Ncc), pave7, pave8(Ncc)
	common /heeSM_varXs/ Sub1, Sub55, Sub57, Sub4, Sub15, Sub14
	common /heeSM_varXs/ Sub31, Sub21, Sub9, Sub10, Sub34, Sub67
	common /heeSM_varXs/ Sub72, Sub12, Sub53, Sub24, Sub32
	common /heeSM_varXs/ Sub38, Sub66, Sub5, Sub54, Sub69, Sub71
	common /heeSM_varXs/ Sub58, Sub46, Sub56, Sub44, Sub2, Sub19
	common /heeSM_varXs/ Sub23, Sub27, Sub20, Sub16, Sub17
	common /heeSM_varXs/ Sub52, Sub61, Sub68, Sub70, Sub35
	common /heeSM_varXs/ Sub39, Sub3, Sub6, Sub50, Sub59, Sub28
	common /heeSM_varXs/ Sub51, Sub60, Sub45, Sub47, pave1
	common /heeSM_varXs/ pave2, pave3, pave4, pave5, pave6
	common /heeSM_varXs/ pave7, pave8

	ComplexType F2, F1
	ComplexType Sub64, Sub33, Sub42, Sub37, Sub48, Sub62, Sub73
	ComplexType Sub77, Sub63, Sub65, Sub43, Sub22, Sub26, Sub11
	ComplexType Sub8, Sub7, Sub49, Sub74, Sub36, Sub18, Sub25, Sub29
	ComplexType Sub75, Sub76, Sub40, Sub13, Sub30, Sub41
	common /heeSM_varXh/ F2, F1, Sub64, Sub33, Sub42, Sub37
	common /heeSM_varXh/ Sub48, Sub62, Sub73, Sub77, Sub63
	common /heeSM_varXh/ Sub65, Sub43, Sub22, Sub26, Sub11, Sub8
	common /heeSM_varXh/ Sub7, Sub49, Sub74, Sub36, Sub18, Sub25
	common /heeSM_varXh/ Sub29, Sub75, Sub76, Sub40, Sub13
	common /heeSM_varXh/ Sub30, Sub41

	integer seq(2), Hel(3)
	common /heeSM_helind/ seq, Hel

	ComplexType Ctree(1), Cloop(1)
	common /heeSM_formfactors/ Ctree, Cloop

#endif
