#if 0
* heeSM-vars.h
* variable declarations
* generated by FormCalc 9.6 (7 Mar 2018) on 13-Mar-2018 8:18
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "heeSM-RenConst.h.F"

#else

#include "Decay.h"
#include "heeSM-RenConst.h.F"

	ComplexType AaB01, AaB02, AaB08, AaC0i3(Ncc), AaC0i4(Ncc)
	ComplexType AaC0i5(Ncc), AaC0i6(Ncc), AaC0i7(Ncc), Sub2
	ComplexType Sub3, Sub5, Sub7, Sub8, Sub9, Sub10, Sub11
	ComplexType Sub12, Sub13, Sub14, Sub15, Sub16, Sub17, Sub18
	ComplexType Sub21, Sub22, Sub23, Sub26, Sub27, Sub28, Sub32
	ComplexType Sub33, Sub34, Sub35, Sub36, Sub37, Sub38, Sub41
	ComplexType Sub42, Sub43, Sub44, Sub45, Sub46, Sub47, Sub52
	ComplexType Sub53, Sub54, Sub55, Sub56, Sub57, Sub60, Sub61
	ComplexType Sub63, Sub64, Sub66, Sub67, Sub70, Sub71, Sub72
	ComplexType Sub73, Sub74, Sub75
	common /heeSM_varXs/ AaB01, AaB02, AaB08, AaC0i3, AaC0i4
	common /heeSM_varXs/ AaC0i5, AaC0i6, AaC0i7, Sub2, Sub3
	common /heeSM_varXs/ Sub5, Sub7, Sub8, Sub9, Sub10, Sub11
	common /heeSM_varXs/ Sub12, Sub13, Sub14, Sub15, Sub16
	common /heeSM_varXs/ Sub17, Sub18, Sub21, Sub22, Sub23
	common /heeSM_varXs/ Sub26, Sub27, Sub28, Sub32, Sub33
	common /heeSM_varXs/ Sub34, Sub35, Sub36, Sub37, Sub38
	common /heeSM_varXs/ Sub41, Sub42, Sub43, Sub44, Sub45
	common /heeSM_varXs/ Sub46, Sub47, Sub52, Sub53, Sub54
	common /heeSM_varXs/ Sub55, Sub56, Sub57, Sub60, Sub61
	common /heeSM_varXs/ Sub63, Sub64, Sub66, Sub67, Sub70
	common /heeSM_varXs/ Sub71, Sub72, Sub73, Sub74, Sub75

	ComplexType F1, F2
	ComplexType Sub1, Sub4, Sub6, Sub19, Sub20, Sub24, Sub25
	ComplexType Sub29, Sub30, Sub31, Sub39, Sub40, Sub48, Sub49
	ComplexType Sub50, Sub51, Sub58, Sub59, Sub62, Sub65, Sub68
	ComplexType Sub69, Sub76, Sub77, Sub78, Sub79, Sub80
	common /heeSM_varXh/ F1, F2, Sub1, Sub4, Sub6, Sub19, Sub20
	common /heeSM_varXh/ Sub24, Sub25, Sub29, Sub30, Sub31
	common /heeSM_varXh/ Sub39, Sub40, Sub48, Sub49, Sub50
	common /heeSM_varXh/ Sub51, Sub58, Sub59, Sub62, Sub65
	common /heeSM_varXh/ Sub68, Sub69, Sub76, Sub77, Sub78
	common /heeSM_varXh/ Sub79, Sub80

	ComplexType Ctree(1), Cloop(1)
	common /heeSM_formfactors/ Ctree, Cloop

#endif

