.TH FHSETFLAGSSTRING 1 "30-Jan-2018"
.SH NAME
.PP
FHSetFlagsString \- set the FeynHiggs flags from a string
.SH SYNOPSIS (Fortran version)
.PP
integer error
.br
character*8 flags
.sp
subroutine FHSetFlagsString(error, flags)
.SH SYNOPSIS (Mathematica version)
.PP
FHSetFlagsString[flags]
.SH DESCRIPTION
FHSetFlagsString works just like FHSetFlags except that the flags
are given as a 8-digit character string rather than as 8 integers.
.SH SEE ALSO
.PP
libFH(1)
