.TH FHSETFLAGSSTRING 1 "1-Feb-2016"
.SH NAME
.PP
FHSetFlagsString \- set the FeynHiggs flags from a string
.SH SYNOPSIS (Fortran version)
.PP
integer error
.br
character*10 flags
.sp
subroutine FHSetFlagsString(error, flags)
.SH SYNOPSIS (Mathematica version)
.PP
FHSetFlagsString[flags]
.SH DESCRIPTION
FHSetFlagsString works just like FHSetFlags except that the flags
are given as a 10-digit character string rather than as 10 integers.
.SH SEE ALSO
.PP
libFH(1)
