#if 0
* hee-vars.h
* variable declarations
* generated by FormCalc 9.9 (29 Jan 2020) on 21-Apr-2020 10:38
* this file is part of FeynHiggs
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME

#include "externals.h"
#include "types.h"
#include "debug.h"
#include "hee-RenConst.h.F"

#else

#include "Decay.h"
#include "hee-RenConst.h.F"

	ComplexType Sub1, Sub2, Sub3
	ComplexType A0i1(6), A0i2(6), A0i3(6), A0i4(3), A0i5(3)
	ComplexType A0i6(3), A0i7(3), A0i8(4), A0i9, A0i10, A0i11(2)
	ComplexType A0i12, A0i13, A0i14, A0i15, B0i1(6,6), B0i2(6,6)
	ComplexType B0i3(6,6), B0i4(2), B0i5(3), B0i6(3), B0i7(3)
	ComplexType B0i8(3), B0i9(4,4), B0i10, B0i11, B0i12, B0i13
	ComplexType B0i14, B0i15, B0i16, B0i17, B0i18, B0i19, B0i20
	ComplexType B0i21, B0i22(2,2), B0i23(6,4), B1i1(6,6)
	ComplexType B1i2(6,6), B1i3(6,6), B1i4(3), B1i5(3), B1i6(3)
	ComplexType B1i7(3), B1i8(4,4), B1i9, B1i10, B1i11, B1i12
	ComplexType B1i13, B1i14, B1i15(2,2), C0i1(Ncc,6,6,4)
	ComplexType C0i2(Ncc,6,4,4), C0i3(Ncc,2), C0i4(Ncc)
	ComplexType C0i5(Ncc), C0i6(Ncc), C0i7(Ncc), C0i8(Ncc)
	ComplexType C0i9(Ncc), C0i10(Ncc), C0i11(Ncc), C0i12(Ncc)
	ComplexType C0i13(Ncc), C0i14(Ncc), C0i15(Ncc), C0i16(Ncc)
	ComplexType C0i17(Ncc), C0i18(Ncc), C0i19(Ncc), C0i20(Ncc)
	ComplexType C0i21(Ncc), C0i22(Ncc), C0i23(Ncc), C0i24(Ncc)
	ComplexType C0i25(Ncc), C0i26(Ncc), C0i27(Ncc), C0i28(Ncc)
	ComplexType C0i29(Ncc), C0i30(Ncc), C0i31(Ncc), C0i32(Ncc)
	ComplexType C0i33(Ncc,2,2), C0i34(Ncc), C0i35(Ncc), Opt1
	ComplexType Sub4(3,3), Sub5(3,3), Sub6(6,6,3,3), Sub7(3)
	ComplexType Sub8(3,3), Sub9(6,3,3), Sub10(3), Sub11(3,3)
	ComplexType Sub12(6,3,3), Sub13(6,6,3,3), Sub14(3)
	ComplexType Sub15(3,3), Sub16(6,3,3), Sub17(3), Sub18(3,3)
	ComplexType Sub19(6,3,3), Sub20(6,6,3,3), Sub22(3,3)
	ComplexType Sub23(3,3), Sub24(6,6,3,3), Sub26(3,3)
	ComplexType Sub27(3,3), Sub28(6,6,3,3), Sub29(3), Sub30(3,3)
	ComplexType Sub31(6,3,3), Sub32(3), Sub33(3,3), Sub34(6,3,3)
	ComplexType Sub35(6,6,3,3), Sub36(3), Sub37(3,3)
	ComplexType Sub38(6,3,3), Sub39(3), Sub40(3,3), Sub41(6,3,3)
	ComplexType Sub42(6,6,3,3), Sub43(3,3), Sub44(3,3)
	ComplexType Sub45(6,6,3,3), Sub46(6,6,3,3), Sub47(3)
	ComplexType Sub48(3,3), Sub49(6,3,3), Sub50(3), Sub51(3,3)
	ComplexType Sub52(6,3,3), Sub53(6,6,3,3), Sub54(3,3)
	ComplexType Sub55(3,3), Sub56(6,6,3,3), Sub57(3), Sub58(3,3)
	ComplexType Sub59(6,3,3), Sub60(3), Sub61(3,3), Sub62(6,3,3)
	ComplexType Sub63(6,6,3,3), Sub64(3,3), Sub65(3,3)
	ComplexType Sub66(6,6,3,3), Sub67(3,3), Sub68(3,3)
	ComplexType Sub69(6,6,3,3), Sub70(6,6,3,3,3,3), Sub71(6,6,3)
	ComplexType Sub72(3), Sub73(3,3), Sub74(6,3,3), Sub75(3)
	ComplexType Sub76(3,3), Sub77(6,3,3), Sub78(6,6,3,3)
	ComplexType Sub79(3), Sub80(3,3), Sub81(6,3,3), Sub82(3)
	ComplexType Sub83(3,3), Sub84(6,3,3), Sub85(6,6,3,3)
	ComplexType Sub86(6,6,3,3), Sub87(3,3), Sub88(3,3)
	ComplexType Sub89(6,6,3,3), Sub91(6,6,3), Sub92(3)
	ComplexType Sub93(3,3), Sub94(6,3,3), Sub95(3), Sub96(3,3)
	ComplexType Sub97(6,3,3), Sub98(6,6,3,3), Sub99(3)
	ComplexType Sub100(3,3), Sub101(6,3,3), Sub102(3)
	ComplexType Sub103(3,3), Sub104(6,3,3), Sub105(6,6,3,3)
	ComplexType Sub106(3,3), Sub107(3,3), Sub108(6,6,3,3)
	ComplexType Sub110(6,6,3), Sub111(3), Sub112(3,3)
	ComplexType Sub113(6,3,3), Sub114(3), Sub115(3,3)
	ComplexType Sub116(6,3,3), Sub117(6,6,3,3), Sub118(3)
	ComplexType Sub119(3,3), Sub120(6,3,3), Sub121(3)
	ComplexType Sub122(3,3), Sub123(6,3,3), Sub124(6,6,3,3)
	ComplexType Sub125(3,3), Sub126(3,3), Sub127(6,6,3,3)
	ComplexType Sub129(3), Sub130(3), Sub131(6,3), Sub132(3)
	ComplexType Sub133(3), Sub134(6,3), Sub135(3), Sub136(3)
	ComplexType Sub137(6,3), Sub138(2,2), Sub139(2,2)
	ComplexType Sub140(2,2), Sub141(2,2), Sub142(2,2)
	ComplexType Sub143(2,2), Sub144(2,2), Sub145(2,2)
	ComplexType Sub162(2,2), Sub163(2,2), Sub164(2,2)
	ComplexType Sub165(2,2), Sub166(2,2), Sub167(2,2)
	ComplexType Sub168(2,2), Sub169(2,2), Sub170(2,2)
	ComplexType Sub171(2,2), Sub172(2,2), Sub174(2,2)
	ComplexType Sub175(2,2), Sub176(2,2), Sub177(2,2)
	ComplexType Sub178(2,2), Sub180(2,2), Sub181(2,2), Sub185
	ComplexType Sub186, Sub187, Sub188, Sub194, Sub195, Sub197
	ComplexType Sub198, Sub200, Sub201, Sub203(4), Sub204(4)
	ComplexType Sub205(4), Sub206(4), Sub207(4,4), Sub208(4)
	ComplexType Sub209(4), Sub210(4,4), Sub211(4), Sub212(4)
	ComplexType Sub213(4,4), Sub214(4,4), Sub215(4), Sub216(4)
	ComplexType Sub217(4), Sub218(4), Sub219(4,4), Sub220(4)
	ComplexType Sub221(4), Sub222(4,4), Sub223(4), Sub224(4)
	ComplexType Sub225(4,4), Sub226(4), Sub227(4), Sub228(4,4)
	ComplexType Sub229(4), Sub230(4), Sub231(4,4), Sub232(4,4)
	ComplexType Sub234(4,4), Sub235(4,4), Sub236(4,4)
	ComplexType Sub237(4,4), Sub241, Sub242, Sub243, Sub244
	ComplexType Sub245, Sub248, Sub249, Sub251, Sub252, Sub257
	ComplexType Sub258, Sub259, Sub260, Sub261, Sub262, Sub263
	ComplexType Sub264, Sub267, Sub268, Sub269, Sub270, Sub271
	ComplexType Sub272, Sub273, Sub278, Sub280, Sub282, Sub283
	ComplexType Sub284, Sub285, Sub286, Sub294, Sub295, Sub296
	ComplexType Sub297, Sub299, Sub300, Sub301, Sub302, Sub303
	ComplexType Sub305, Sub309, Sub312, Sub313, Sub317, Sub319
	ComplexType Sub323, Sub324, Sub325, Sub328, Sub329, Sub330
	ComplexType Sub331, Sub333, Sub335, Sub336, Sub337, Sub338
	ComplexType Sub341, Sub342, Sub343, Sub344, Sub348, Sub349
	ComplexType Sub350, Sub351, Sub352, Sub353, Sub354, Sub355
	ComplexType Sub356, Sub357, Sub359, Sub360, Sub361, Sub364
	ComplexType Sub365, Sub366, Sub367, Sub368, Sub369, Sub371
	ComplexType Sub372, Sub373, Sub375, Sub376, Sub377, Sub378
	ComplexType Sub379, Sub380, Sub384, Sub385, Sub386, Sub387
	ComplexType Sub388, Sub391, Sub392, Sub393, Sub396, Sub397
	ComplexType Sub398, Sub399, Sub400, Sub401, Sub402, Sub406
	ComplexType Sub407, Sub408, Sub411, Sub412, Sub413, Sub416
	ComplexType Sub417, Sub418, Sub419, Sub420, Sub425, Sub426
	ComplexType Sub427, Sub428, Sub431, Sub432, Sub433, Sub437
	ComplexType Sub438, Sub439, Sub440, Sub441, Sub445, Sub453
	ComplexType Sub454, Sub455, Sub458, Sub459, Sub460, Sub462
	ComplexType Sub463, Sub469, Sub470, Sub471, Sub472, Sub473
	ComplexType Sub474, Sub475, Sub476, Sub481, Sub482, Sub483
	ComplexType Sub484, Sub485, Sub486, Sub487, Sub488, Sub489
	ComplexType Sub490, Sub491, Sub492, Sub493, Sub494, Sub495
	ComplexType Sub496, Sub497, Sub499, Sub500, Sub509, Sub510
	ComplexType Sub511, Sub512, Sub513, Sub515, Sub516, Sub517
	ComplexType Sub519, Sub521, Sub522, Sub524, Sub525
	ComplexType Sub532(3), Sub533(3,3), Sub534(6,3,3), Sub535(3)
	ComplexType Sub536(3,3), Sub537(6,3,3), Sub538(6,6,3,3)
	ComplexType Sub539(3), Sub540(3,3), Sub541(6,3,3), Sub542(3)
	ComplexType Sub543(3,3), Sub544(6,3,3), Sub545(6,6,3,3)
	ComplexType Sub546(6,6,3,3), Sub547(3,3), Sub548(3,3)
	ComplexType Sub549(6,6,3,3), Sub550(6,4), Sub551(6,4)
	ComplexType Sub552(4), Sub553(6,4), Sub554(6,4), Sub555(6,4)
	ComplexType Sub559(6,4), Sub560(6,4), Sub561(6,4)
	common /hee_varXs/ Sub1, Sub2, Sub3, A0i1, A0i2, A0i3, A0i4
	common /hee_varXs/ A0i5, A0i6, A0i7, A0i8, A0i9, A0i10
	common /hee_varXs/ A0i11, A0i12, A0i13, A0i14, A0i15, B0i1
	common /hee_varXs/ B0i2, B0i3, B0i4, B0i5, B0i6, B0i7, B0i8
	common /hee_varXs/ B0i9, B0i10, B0i11, B0i12, B0i13, B0i14
	common /hee_varXs/ B0i15, B0i16, B0i17, B0i18, B0i19, B0i20
	common /hee_varXs/ B0i21, B0i22, B0i23, B1i1, B1i2, B1i3
	common /hee_varXs/ B1i4, B1i5, B1i6, B1i7, B1i8, B1i9, B1i10
	common /hee_varXs/ B1i11, B1i12, B1i13, B1i14, B1i15, C0i1
	common /hee_varXs/ C0i2, C0i3, C0i4, C0i5, C0i6, C0i7, C0i8
	common /hee_varXs/ C0i9, C0i10, C0i11, C0i12, C0i13, C0i14
	common /hee_varXs/ C0i15, C0i16, C0i17, C0i18, C0i19, C0i20
	common /hee_varXs/ C0i21, C0i22, C0i23, C0i24, C0i25, C0i26
	common /hee_varXs/ C0i27, C0i28, C0i29, C0i30, C0i31, C0i32
	common /hee_varXs/ C0i33, C0i34, C0i35, Opt1, Sub4, Sub5
	common /hee_varXs/ Sub6, Sub7, Sub8, Sub9, Sub10, Sub11
	common /hee_varXs/ Sub12, Sub13, Sub14, Sub15, Sub16, Sub17
	common /hee_varXs/ Sub18, Sub19, Sub20, Sub22, Sub23, Sub24
	common /hee_varXs/ Sub26, Sub27, Sub28, Sub29, Sub30, Sub31
	common /hee_varXs/ Sub32, Sub33, Sub34, Sub35, Sub36, Sub37
	common /hee_varXs/ Sub38, Sub39, Sub40, Sub41, Sub42, Sub43
	common /hee_varXs/ Sub44, Sub45, Sub46, Sub47, Sub48, Sub49
	common /hee_varXs/ Sub50, Sub51, Sub52, Sub53, Sub54, Sub55
	common /hee_varXs/ Sub56, Sub57, Sub58, Sub59, Sub60, Sub61
	common /hee_varXs/ Sub62, Sub63, Sub64, Sub65, Sub66, Sub67
	common /hee_varXs/ Sub68, Sub69, Sub70, Sub71, Sub72, Sub73
	common /hee_varXs/ Sub74, Sub75, Sub76, Sub77, Sub78, Sub79
	common /hee_varXs/ Sub80, Sub81, Sub82, Sub83, Sub84, Sub85
	common /hee_varXs/ Sub86, Sub87, Sub88, Sub89, Sub91, Sub92
	common /hee_varXs/ Sub93, Sub94, Sub95, Sub96, Sub97, Sub98
	common /hee_varXs/ Sub99, Sub100, Sub101, Sub102, Sub103
	common /hee_varXs/ Sub104, Sub105, Sub106, Sub107, Sub108
	common /hee_varXs/ Sub110, Sub111, Sub112, Sub113, Sub114
	common /hee_varXs/ Sub115, Sub116, Sub117, Sub118, Sub119
	common /hee_varXs/ Sub120, Sub121, Sub122, Sub123, Sub124
	common /hee_varXs/ Sub125, Sub126, Sub127, Sub129, Sub130
	common /hee_varXs/ Sub131, Sub132, Sub133, Sub134, Sub135
	common /hee_varXs/ Sub136, Sub137, Sub138, Sub139, Sub140
	common /hee_varXs/ Sub141, Sub142, Sub143, Sub144, Sub145
	common /hee_varXs/ Sub162, Sub163, Sub164, Sub165, Sub166
	common /hee_varXs/ Sub167, Sub168, Sub169, Sub170, Sub171
	common /hee_varXs/ Sub172, Sub174, Sub175, Sub176, Sub177
	common /hee_varXs/ Sub178, Sub180, Sub181, Sub185, Sub186
	common /hee_varXs/ Sub187, Sub188, Sub194, Sub195, Sub197
	common /hee_varXs/ Sub198, Sub200, Sub201, Sub203, Sub204
	common /hee_varXs/ Sub205, Sub206, Sub207, Sub208, Sub209
	common /hee_varXs/ Sub210, Sub211, Sub212, Sub213, Sub214
	common /hee_varXs/ Sub215, Sub216, Sub217, Sub218, Sub219
	common /hee_varXs/ Sub220, Sub221, Sub222, Sub223, Sub224
	common /hee_varXs/ Sub225, Sub226, Sub227, Sub228, Sub229
	common /hee_varXs/ Sub230, Sub231, Sub232, Sub234, Sub235
	common /hee_varXs/ Sub236, Sub237, Sub241, Sub242, Sub243
	common /hee_varXs/ Sub244, Sub245, Sub248, Sub249, Sub251
	common /hee_varXs/ Sub252, Sub257, Sub258, Sub259, Sub260
	common /hee_varXs/ Sub261, Sub262, Sub263, Sub264, Sub267
	common /hee_varXs/ Sub268, Sub269, Sub270, Sub271, Sub272
	common /hee_varXs/ Sub273, Sub278, Sub280, Sub282, Sub283
	common /hee_varXs/ Sub284, Sub285, Sub286, Sub294, Sub295
	common /hee_varXs/ Sub296, Sub297, Sub299, Sub300, Sub301
	common /hee_varXs/ Sub302, Sub303, Sub305, Sub309, Sub312
	common /hee_varXs/ Sub313, Sub317, Sub319, Sub323, Sub324
	common /hee_varXs/ Sub325, Sub328, Sub329, Sub330, Sub331
	common /hee_varXs/ Sub333, Sub335, Sub336, Sub337, Sub338
	common /hee_varXs/ Sub341, Sub342, Sub343, Sub344, Sub348
	common /hee_varXs/ Sub349, Sub350, Sub351, Sub352, Sub353
	common /hee_varXs/ Sub354, Sub355, Sub356, Sub357, Sub359
	common /hee_varXs/ Sub360, Sub361, Sub364, Sub365, Sub366
	common /hee_varXs/ Sub367, Sub368, Sub369, Sub371, Sub372
	common /hee_varXs/ Sub373, Sub375, Sub376, Sub377, Sub378
	common /hee_varXs/ Sub379, Sub380, Sub384, Sub385, Sub386
	common /hee_varXs/ Sub387, Sub388, Sub391, Sub392, Sub393
	common /hee_varXs/ Sub396, Sub397, Sub398, Sub399, Sub400
	common /hee_varXs/ Sub401, Sub402, Sub406, Sub407, Sub408
	common /hee_varXs/ Sub411, Sub412, Sub413, Sub416, Sub417
	common /hee_varXs/ Sub418, Sub419, Sub420, Sub425, Sub426
	common /hee_varXs/ Sub427, Sub428, Sub431, Sub432, Sub433
	common /hee_varXs/ Sub437, Sub438, Sub439, Sub440, Sub441
	common /hee_varXs/ Sub445, Sub453, Sub454, Sub455, Sub458
	common /hee_varXs/ Sub459, Sub460, Sub462, Sub463, Sub469
	common /hee_varXs/ Sub470, Sub471, Sub472, Sub473, Sub474
	common /hee_varXs/ Sub475, Sub476, Sub481, Sub482, Sub483
	common /hee_varXs/ Sub484, Sub485, Sub486, Sub487, Sub488
	common /hee_varXs/ Sub489, Sub490, Sub491, Sub492, Sub493
	common /hee_varXs/ Sub494, Sub495, Sub496, Sub497, Sub499
	common /hee_varXs/ Sub500, Sub509, Sub510, Sub511, Sub512
	common /hee_varXs/ Sub513, Sub515, Sub516, Sub517, Sub519
	common /hee_varXs/ Sub521, Sub522, Sub524, Sub525, Sub532
	common /hee_varXs/ Sub533, Sub534, Sub535, Sub536, Sub537
	common /hee_varXs/ Sub538, Sub539, Sub540, Sub541, Sub542
	common /hee_varXs/ Sub543, Sub544, Sub545, Sub546, Sub547
	common /hee_varXs/ Sub548, Sub549, Sub550, Sub551, Sub552
	common /hee_varXs/ Sub553, Sub554, Sub555, Sub559, Sub560
	common /hee_varXs/ Sub561

	ComplexType F1, F2
	ComplexType Sub21(6,6,3,3), Sub25(6,6,3,3), Sub90(6,6,3,3)
	ComplexType Sub109(6,6,3,3), Sub128(6,6,3,3), Sub146(2,2)
	ComplexType Sub147(2,2), Sub148(2,2), Sub149(2,2)
	ComplexType Sub150(2,2), Sub151(2,2), Sub152(2,2)
	ComplexType Sub153(2,2), Sub154(2,2), Sub155(2,2)
	ComplexType Sub156(2,2), Sub157(2,2), Sub158(2,2)
	ComplexType Sub159(2,2), Sub160(2,2), Sub161(2,2), Sub173
	ComplexType Sub179(2,2), Sub182(2,2), Sub183(2,2), Sub184
	ComplexType Sub189, Sub190, Sub191, Sub192, Sub193, Sub196
	ComplexType Sub199, Sub202, Sub233(4,4), Sub238(4,4)
	ComplexType Sub239(4,4), Sub240(4,4), Sub246, Sub247, Sub250
	ComplexType Sub253, Sub254, Sub255, Sub256, Sub265, Sub266
	ComplexType Sub274, Sub275, Sub276, Sub277, Sub279, Sub281
	ComplexType Sub287, Sub288, Sub289, Sub290, Sub291, Sub292
	ComplexType Sub293, Sub304, Sub306, Sub307, Sub308, Sub310
	ComplexType Sub311, Sub314, Sub315, Sub316, Sub318, Sub320
	ComplexType Sub321, Sub322, Sub326, Sub327, Sub332, Sub334
	ComplexType Sub339, Sub340, Sub345, Sub346, Sub347, Sub358
	ComplexType Sub362, Sub363, Sub370, Sub374, Sub381, Sub382
	ComplexType Sub383, Sub389, Sub390, Sub394, Sub395, Sub403
	ComplexType Sub404, Sub405, Sub409, Sub410, Sub414, Sub415
	ComplexType Sub421, Sub422, Sub423, Sub424, Sub429, Sub430
	ComplexType Sub434, Sub435, Sub436, Sub442, Sub443, Sub444
	ComplexType Sub446, Sub447, Sub448, Sub449, Sub450, Sub451
	ComplexType Sub452, Sub456, Sub457, Sub461, Sub464, Sub465
	ComplexType Sub466, Sub467, Sub468, Sub477, Sub478, Sub479
	ComplexType Sub480, Sub498, Sub501, Sub502, Sub503, Sub504
	ComplexType Sub505, Sub506, Sub507, Sub508, Sub514, Sub518
	ComplexType Sub520, Sub523, Sub526, Sub527, Sub528, Sub529
	ComplexType Sub530, Sub531, Sub556(6,6,4), Sub557(6,6,4)
	ComplexType Sub558(6,6,4), Sub562(6,4,4), Sub563(6,4,4)
	ComplexType Sub564(6,4,4), Sub565(6,4,4), Sub566(6,4,4)
	ComplexType Sub567(6,4,4), Sub568(6,4,4), Sub569(6,4,4)
	ComplexType Sub570(6,4,4), Sub571(6,4,4), Sub572(6,4,4)
	ComplexType Sub573(6,4,4), Sub574(6,4,4), Sub575(6,4,4)
	ComplexType Sub576(6,4,4), Sub577(2), Sub578(2), Sub579(2)
	ComplexType Sub580(2)
	common /hee_varXh/ F1, F2, Sub21, Sub25, Sub90, Sub109
	common /hee_varXh/ Sub128, Sub146, Sub147, Sub148, Sub149
	common /hee_varXh/ Sub150, Sub151, Sub152, Sub153, Sub154
	common /hee_varXh/ Sub155, Sub156, Sub157, Sub158, Sub159
	common /hee_varXh/ Sub160, Sub161, Sub173, Sub179, Sub182
	common /hee_varXh/ Sub183, Sub184, Sub189, Sub190, Sub191
	common /hee_varXh/ Sub192, Sub193, Sub196, Sub199, Sub202
	common /hee_varXh/ Sub233, Sub238, Sub239, Sub240, Sub246
	common /hee_varXh/ Sub247, Sub250, Sub253, Sub254, Sub255
	common /hee_varXh/ Sub256, Sub265, Sub266, Sub274, Sub275
	common /hee_varXh/ Sub276, Sub277, Sub279, Sub281, Sub287
	common /hee_varXh/ Sub288, Sub289, Sub290, Sub291, Sub292
	common /hee_varXh/ Sub293, Sub304, Sub306, Sub307, Sub308
	common /hee_varXh/ Sub310, Sub311, Sub314, Sub315, Sub316
	common /hee_varXh/ Sub318, Sub320, Sub321, Sub322, Sub326
	common /hee_varXh/ Sub327, Sub332, Sub334, Sub339, Sub340
	common /hee_varXh/ Sub345, Sub346, Sub347, Sub358, Sub362
	common /hee_varXh/ Sub363, Sub370, Sub374, Sub381, Sub382
	common /hee_varXh/ Sub383, Sub389, Sub390, Sub394, Sub395
	common /hee_varXh/ Sub403, Sub404, Sub405, Sub409, Sub410
	common /hee_varXh/ Sub414, Sub415, Sub421, Sub422, Sub423
	common /hee_varXh/ Sub424, Sub429, Sub430, Sub434, Sub435
	common /hee_varXh/ Sub436, Sub442, Sub443, Sub444, Sub446
	common /hee_varXh/ Sub447, Sub448, Sub449, Sub450, Sub451
	common /hee_varXh/ Sub452, Sub456, Sub457, Sub461, Sub464
	common /hee_varXh/ Sub465, Sub466, Sub467, Sub468, Sub477
	common /hee_varXh/ Sub478, Sub479, Sub480, Sub498, Sub501
	common /hee_varXh/ Sub502, Sub503, Sub504, Sub505, Sub506
	common /hee_varXh/ Sub507, Sub508, Sub514, Sub518, Sub520
	common /hee_varXh/ Sub523, Sub526, Sub527, Sub528, Sub529
	common /hee_varXh/ Sub530, Sub531, Sub556, Sub557, Sub558
	common /hee_varXh/ Sub562, Sub563, Sub564, Sub565, Sub566
	common /hee_varXh/ Sub567, Sub568, Sub569, Sub570, Sub571
	common /hee_varXh/ Sub572, Sub573, Sub574, Sub575, Sub576
	common /hee_varXh/ Sub577, Sub578, Sub579, Sub580

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /hee_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hee_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	common /hee_formfactors/ Ctree, Cloop

#endif

