#if 0
* hee-vars.h
* variable declarations
* generated by FormCalc 8.4 on 30-Apr-2014 7:34
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hee-renconst.h"

	ComplexType Sub1, Sub2, Sub3
	ComplexType Sub248, Sub284, Sub217, Sub219, Sub216, Sub141
	ComplexType Sub344, Sub222, Sub213, Sub215, Sub311, Sub308
	ComplexType Sub352, Sub303, Sub305, Sub271, Sub281, Sub363
	ComplexType Sub275, Sub272, Sub364, Sub365, Sub350, Sub322
	ComplexType Sub307, Sub367, Sub282, Sub348, Sub279, Sub276
	ComplexType Sub273, Sub349, Sub368, Sub190, Sub200, Sub193
	ComplexType Sub201, Sub197, Sub203, Sub189, Sub199, Sub316
	ComplexType Sub329, Sub206, Sub328, Sub207, Sub312, Sub136
	ComplexType Sub277, Sub266, Sub326, Sub214, Sub247, Sub8
	ComplexType Sub280, Sub283, Sub269, Sub380, Sub194, Sub202
	ComplexType Sub218, Sub330, Sub124, Sub446, Sub137, Sub138
	ComplexType Sub140, Sub198, Sub204, Sub461(2), Sub464(2)
	ComplexType Sub445(2), Sub438(2), Sub454(2), Sub396(3)
	ComplexType Sub400(3), Sub111(3), Sub110(3), Sub395(3)
	ComplexType Sub399(3), Sub114(3), Sub113(3), Sub117(3)
	ComplexType Sub116(3), Sub397(3), Sub401(3), Sub65(3)
	ComplexType Sub69(3), Sub68(3), Sub64(3), Sub81(3), Sub85(3)
	ComplexType Sub84(3), Sub80(3), Sub96(3), Sub100(3)
	ComplexType Sub97(3), Sub101(3), Sub102(3), Sub66(3)
	ComplexType Sub70(3), Sub82(3), Sub86(3), Sub98(3), Sub10(3)
	ComplexType Sub14(3), Sub13(3), Sub9(3), Sub28(3), Sub32(3)
	ComplexType Sub31(3), Sub27(3), Sub45(3), Sub49(3), Sub46(3)
	ComplexType Sub50(3), Sub11(3), Sub15(3), Sub29(3), Sub33(3)
	ComplexType Sub47(3), Sub51(3), Sub150(4), Sub408(4)
	ComplexType Sub148(4), Sub153(4), Sub156(4), Sub165(4)
	ComplexType Sub162(4), Sub410(4), Sub168(4), Sub171(4)
	ComplexType Sub174(4), Sub160(4), Sub149(4), Sub151(4)
	ComplexType Sub154(4), Sub157(4), Sub166(4), Sub161(4)
	ComplexType Sub417(4), Sub169(4), Sub172(4), Sub175(4)
	ComplexType Sub163(4), Sub112(6,3), Sub115(6,3), Sub118(6,3)
	ComplexType Sub67(6,3), Sub71(6,3), Sub83(6,3), Sub87(6,3)
	ComplexType Sub103(6,3), Sub99(6,3), Sub12(6,3), Sub16(6,3)
	ComplexType Sub30(6,3), Sub34(6,3), Sub52(6,3), Sub48(6,3)
	ComplexType Sub409(6,4), Sub413(6,4), Sub419(6,4)
	ComplexType Sub418(6,4), Sub398(6,3), Sub402(6,3)
	ComplexType Sub412(6,4), Sub411(6,4), Sub131(2,2)
	ComplexType Sub127(2,2), Sub134(2,2), Sub130(2,2)
	ComplexType Sub132(2,2), Sub133(2,2), Sub463(2,2)
	ComplexType Sub457(2,2), Sub126(2,2), Sub119(2,2)
	ComplexType Sub443(2,2), Sub442(2,2), Sub123(2,2)
	ComplexType Sub440(2,2), Sub448(2,2), Sub444(2,2)
	ComplexType Sub449(2,2), Sub466(2,2), Sub462(2,2)
	ComplexType Sub465(2,2), Sub456(2,2), Sub455(2,2)
	ComplexType Sub122(2,2), Sub406(3,3), Sub405(3,3), Sub5(3,3)
	ComplexType Sub4(3,3), Sub24(3,3), Sub23(3,3), Sub42(3,3)
	ComplexType Sub41(3,3), Sub56(3,3), Sub55(3,3), Sub75(3,3)
	ComplexType Sub74(3,3), Sub91(3,3), Sub90(3,3), Sub107(3,3)
	ComplexType Sub106(3,3), Sub20(3,3), Sub19(3,3), Sub38(3,3)
	ComplexType Sub37(3,3), Sub59(3,3), Sub58(3,3), Sub152(4,4)
	ComplexType Sub155(4,4), Sub158(4,4), Sub164(4,4)
	ComplexType Sub167(4,4), Sub170(4,4), Sub173(4,4)
	ComplexType Sub176(4,4), Sub184(4,4), Sub178(4,4)
	ComplexType Sub182(4,4), Sub181(4,4), Sub185(4,4)
	ComplexType Sub186(4,4), Sub180(4,4), Sub179(4,4)
	ComplexType Sub403(6,6,3), Sub62(6,6,3), Sub78(6,6,3)
	ComplexType Sub94(6,6,3), Sub72(6,6,3), Sub88(6,6,3)
	ComplexType Sub104(6,6,3), Sub17(6,6,3), Sub35(6,6,3)
	ComplexType Sub53(6,6,3), Sub404(6,6,3,3), Sub57(6,6,3,3)
	ComplexType Sub394(6,6,3,3), Sub407(6,6,3,3), Sub6(6,6,3,3)
	ComplexType Sub25(6,6,3,3), Sub43(6,6,3,3), Sub73(6,6,3,3)
	ComplexType Sub89(6,6,3,3), Sub105(6,6,3,3), Sub63(6,6,3,3)
	ComplexType Sub76(6,6,3,3), Sub79(6,6,3,3), Sub92(6,6,3,3)
	ComplexType Sub95(6,6,3,3), Sub108(6,6,3,3), Sub109(6,6,3,3)
	ComplexType Sub77(6,6,3,3), Sub93(6,6,3,3), Sub36(6,6,3,3)
	ComplexType Sub54(6,6,3,3), Sub18(6,6,3,3), Sub7(6,6,3,3)
	ComplexType Sub21(6,6,3,3), Sub26(6,6,3,3), Sub39(6,6,3,3)
	ComplexType Sub44(6,6,3,3), Sub60(6,6,3,3), Sub22(6,6,3,3)
	ComplexType Sub40(6,6,3,3), Sub61(6,6,3,3,3,3), Sub187
	ComplexType Sub191, Sub285, Sub195, Sub366, Sub274, Sub221
	ComplexType Sub304, Sub306, Sub345, Sub346, Sub297, Sub205
	ComplexType Sub315, Sub120, Sub441, Sub301, Sub319, Sub383
	ComplexType Sub139, Sub125, Sub447, Sub209, Sub324
	ComplexType Sub135(2,2), Sub129(2,2), Sub128(2,2)
	ComplexType Sub183(4,4), Sub159(4,4), Sub177(4,4), Sub188
	ComplexType Sub192, Sub196, Sub220, Sub278, Sub378, Sub255
	ComplexType Sub208, Sub309, Sub421, pave1(6,6), pave2(6,6)
	ComplexType pave3(6,6), pave4(6,6), pave5(6,6), pave6(6,6)
	ComplexType pave7(6), pave8(6), pave9(6), pave10(2)
	ComplexType pave11(2,2), pave12(2,2), pave13(3), pave14(3)
	ComplexType pave15(3), pave16(3), pave17(3), pave18(3)
	ComplexType pave19(3), pave20(3), pave21(3), pave22(3)
	ComplexType pave23(3), pave24(3), pave25(4), pave26(4,4)
	ComplexType pave27(4,4), pave28(Ncc,6,6,4), pave29(6,4)
	ComplexType pave30(Ncc,6,4,4), pave31(Ncc,2,2,3)
	ComplexType pave32(Ncc,2,3), pave33, pave34, pave35, pave36
	ComplexType pave37, pave38, pave39, pave40, pave41, pave42
	ComplexType pave43, pave44, pave45(Ncc), pave46(Ncc)
	ComplexType pave47(Ncc), pave48(Ncc), pave49(Ncc)
	ComplexType pave50(Ncc), pave51(Ncc), pave52(Ncc)
	ComplexType pave53(Ncc), pave54(Ncc), pave55(Ncc)
	ComplexType pave56(Ncc), pave57(Ncc), pave58(Ncc)
	ComplexType pave59(Ncc), pave60(Ncc), pave61(Ncc)
	ComplexType pave62(Ncc), pave63(Ncc), pave64(Ncc)
	ComplexType pave65(Ncc), pave66(Ncc), pave67(Ncc)
	ComplexType pave68(Ncc), pave69(Ncc), pave70(Ncc)
	ComplexType pave71(Ncc), pave72(Ncc), pave73, pave74(Ncc)
	ComplexType pave75, pave76, pave77(Ncc), pave78(2,3), pave79
	ComplexType pave80, pave81, pave82, pave83, pave84, pave85
	ComplexType pave86, pave87, pave88(Ncc)
	common /hee_varXs/ Sub1, Sub2, Sub3, Sub248, Sub284, Sub217
	common /hee_varXs/ Sub219, Sub216, Sub141, Sub344, Sub222
	common /hee_varXs/ Sub213, Sub215, Sub311, Sub308, Sub352
	common /hee_varXs/ Sub303, Sub305, Sub271, Sub281, Sub363
	common /hee_varXs/ Sub275, Sub272, Sub364, Sub365, Sub350
	common /hee_varXs/ Sub322, Sub307, Sub367, Sub282, Sub348
	common /hee_varXs/ Sub279, Sub276, Sub273, Sub349, Sub368
	common /hee_varXs/ Sub190, Sub200, Sub193, Sub201, Sub197
	common /hee_varXs/ Sub203, Sub189, Sub199, Sub316, Sub329
	common /hee_varXs/ Sub206, Sub328, Sub207, Sub312, Sub136
	common /hee_varXs/ Sub277, Sub266, Sub326, Sub214, Sub247
	common /hee_varXs/ Sub8, Sub280, Sub283, Sub269, Sub380
	common /hee_varXs/ Sub194, Sub202, Sub218, Sub330, Sub124
	common /hee_varXs/ Sub446, Sub137, Sub138, Sub140, Sub198
	common /hee_varXs/ Sub204, Sub461, Sub464, Sub445, Sub438
	common /hee_varXs/ Sub454, Sub396, Sub400, Sub111, Sub110
	common /hee_varXs/ Sub395, Sub399, Sub114, Sub113, Sub117
	common /hee_varXs/ Sub116, Sub397, Sub401, Sub65, Sub69
	common /hee_varXs/ Sub68, Sub64, Sub81, Sub85, Sub84, Sub80
	common /hee_varXs/ Sub96, Sub100, Sub97, Sub101, Sub102
	common /hee_varXs/ Sub66, Sub70, Sub82, Sub86, Sub98, Sub10
	common /hee_varXs/ Sub14, Sub13, Sub9, Sub28, Sub32, Sub31
	common /hee_varXs/ Sub27, Sub45, Sub49, Sub46, Sub50, Sub11
	common /hee_varXs/ Sub15, Sub29, Sub33, Sub47, Sub51, Sub150
	common /hee_varXs/ Sub408, Sub148, Sub153, Sub156, Sub165
	common /hee_varXs/ Sub162, Sub410, Sub168, Sub171, Sub174
	common /hee_varXs/ Sub160, Sub149, Sub151, Sub154, Sub157
	common /hee_varXs/ Sub166, Sub161, Sub417, Sub169, Sub172
	common /hee_varXs/ Sub175, Sub163, Sub112, Sub115, Sub118
	common /hee_varXs/ Sub67, Sub71, Sub83, Sub87, Sub103, Sub99
	common /hee_varXs/ Sub12, Sub16, Sub30, Sub34, Sub52, Sub48
	common /hee_varXs/ Sub409, Sub413, Sub419, Sub418, Sub398
	common /hee_varXs/ Sub402, Sub412, Sub411, Sub131, Sub127
	common /hee_varXs/ Sub134, Sub130, Sub132, Sub133, Sub463
	common /hee_varXs/ Sub457, Sub126, Sub119, Sub443, Sub442
	common /hee_varXs/ Sub123, Sub440, Sub448, Sub444, Sub449
	common /hee_varXs/ Sub466, Sub462, Sub465, Sub456, Sub455
	common /hee_varXs/ Sub122, Sub406, Sub405, Sub5, Sub4, Sub24
	common /hee_varXs/ Sub23, Sub42, Sub41, Sub56, Sub55, Sub75
	common /hee_varXs/ Sub74, Sub91, Sub90, Sub107, Sub106
	common /hee_varXs/ Sub20, Sub19, Sub38, Sub37, Sub59, Sub58
	common /hee_varXs/ Sub152, Sub155, Sub158, Sub164, Sub167
	common /hee_varXs/ Sub170, Sub173, Sub176, Sub184, Sub178
	common /hee_varXs/ Sub182, Sub181, Sub185, Sub186, Sub180
	common /hee_varXs/ Sub179, Sub403, Sub62, Sub78, Sub94
	common /hee_varXs/ Sub72, Sub88, Sub104, Sub17, Sub35, Sub53
	common /hee_varXs/ Sub404, Sub57, Sub394, Sub407, Sub6
	common /hee_varXs/ Sub25, Sub43, Sub73, Sub89, Sub105, Sub63
	common /hee_varXs/ Sub76, Sub79, Sub92, Sub95, Sub108
	common /hee_varXs/ Sub109, Sub77, Sub93, Sub36, Sub54, Sub18
	common /hee_varXs/ Sub7, Sub21, Sub26, Sub39, Sub44, Sub60
	common /hee_varXs/ Sub22, Sub40, Sub61, Sub187, Sub191
	common /hee_varXs/ Sub285, Sub195, Sub366, Sub274, Sub221
	common /hee_varXs/ Sub304, Sub306, Sub345, Sub346, Sub297
	common /hee_varXs/ Sub205, Sub315, Sub120, Sub441, Sub301
	common /hee_varXs/ Sub319, Sub383, Sub139, Sub125, Sub447
	common /hee_varXs/ Sub209, Sub324, Sub135, Sub129, Sub128
	common /hee_varXs/ Sub183, Sub159, Sub177, Sub188, Sub192
	common /hee_varXs/ Sub196, Sub220, Sub278, Sub378, Sub255
	common /hee_varXs/ Sub208, Sub309, Sub421, pave1, pave2
	common /hee_varXs/ pave3, pave4, pave5, pave6, pave7, pave8
	common /hee_varXs/ pave9, pave10, pave11, pave12, pave13
	common /hee_varXs/ pave14, pave15, pave16, pave17, pave18
	common /hee_varXs/ pave19, pave20, pave21, pave22, pave23
	common /hee_varXs/ pave24, pave25, pave26, pave27, pave28
	common /hee_varXs/ pave29, pave30, pave31, pave32, pave33
	common /hee_varXs/ pave34, pave35, pave36, pave37, pave38
	common /hee_varXs/ pave39, pave40, pave41, pave42, pave43
	common /hee_varXs/ pave44, pave45, pave46, pave47, pave48
	common /hee_varXs/ pave49, pave50, pave51, pave52, pave53
	common /hee_varXs/ pave54, pave55, pave56, pave57, pave58
	common /hee_varXs/ pave59, pave60, pave61, pave62, pave63
	common /hee_varXs/ pave64, pave65, pave66, pave67, pave68
	common /hee_varXs/ pave69, pave70, pave71, pave72, pave73
	common /hee_varXs/ pave74, pave75, pave76, pave77, pave78
	common /hee_varXs/ pave79, pave80, pave81, pave82, pave83
	common /hee_varXs/ pave84, pave85, pave86, pave87, pave88

	ComplexType F1, F2
	ComplexType Sub236, Sub211, Sub230, Sub234, Sub244, Sub245
	ComplexType Sub286, Sub391, Sub392, Sub290, Sub343, Sub252
	ComplexType Sub296, Sub237, Sub386, Sub341, Sub385, Sub299
	ComplexType Sub333, Sub334, Sub382, Sub223, Sub249, Sub240
	ComplexType Sub225, Sub224, Sub241, Sub226, Sub233, Sub229
	ComplexType Sub231, Sub235, Sub147, Sub143, Sub145, Sub227
	ComplexType Sub242, Sub254, Sub268, Sub321, Sub338, Sub373
	ComplexType Sub376, Sub263, Sub270, Sub300, Sub332, Sub342
	ComplexType Sub264, Sub393, Sub212, Sub293, Sub289, Sub253
	ComplexType Sub294, Sub291, Sub339, Sub210, Sub371, Sub372
	ComplexType Sub374, Sub375, Sub261, Sub340, Sub287, Sub379
	ComplexType Sub314, Sub323, Sub320, Sub325, Sub327, Sub336
	ComplexType Sub337, Sub354, Sub357, Sub360, Sub384, Sub387
	ComplexType Sub257, Sub259, Sub369, Sub351, Sub258, Sub262
	ComplexType Sub355, Sub358, Sub361, Sub370, Sub347, Sub317
	ComplexType Sub256, Sub388, Sub335, Sub310, Sub313, Sub142
	ComplexType Sub144, Sub146, Sub246, Sub250, Sub251, Sub381
	ComplexType Sub452(2), Sub469(2)
	ComplexType Sub470(2), Sub471(2)
	ComplexType Sub439(2,2), Sub459(2,2)
	ComplexType Sub451(2,2), Sub453(2,2)
	ComplexType Sub460(2,2), Sub472(2,3)
	ComplexType Sub416(6,6,4), Sub414(6,6,4)
	ComplexType Sub415(6,6,4), Sub430(6,4,4)
	ComplexType Sub420(6,4,4), Sub433(6,4,4)
	ComplexType Sub426(6,4,4), Sub425(6,4,4)
	ComplexType Sub422(6,4,4), Sub423(6,4,4)
	ComplexType Sub429(6,4,4), Sub424(6,4,4)
	ComplexType Sub427(6,4,4), Sub434(6,4,4)
	ComplexType Sub431(6,4,4), Sub432(6,4,4)
	ComplexType Sub435(6,4,4), Sub436(6,4,4)
	ComplexType Sub437(6,4,4), Sub468(2,2,3), Sub390
	ComplexType Sub260, Sub353, Sub288, Sub292, Sub356, Sub239
	ComplexType Sub228, Sub232, Sub359, Sub295, Sub238, Sub243
	ComplexType Sub265, Sub267, Sub318, Sub298, Sub331
	ComplexType Sub467(2,2), Sub450(2,2)
	ComplexType Sub428(6,4,4), Sub377, Sub389
	ComplexType Sub458(2,2), Sub302, Sub362
	common /hee_varXh/ F1, F2, Sub236, Sub211, Sub230, Sub234
	common /hee_varXh/ Sub244, Sub245, Sub286, Sub391, Sub392
	common /hee_varXh/ Sub290, Sub343, Sub252, Sub296, Sub237
	common /hee_varXh/ Sub386, Sub341, Sub385, Sub299, Sub333
	common /hee_varXh/ Sub334, Sub382, Sub223, Sub249, Sub240
	common /hee_varXh/ Sub225, Sub224, Sub241, Sub226, Sub233
	common /hee_varXh/ Sub229, Sub231, Sub235, Sub147, Sub143
	common /hee_varXh/ Sub145, Sub227, Sub242, Sub254, Sub268
	common /hee_varXh/ Sub321, Sub338, Sub373, Sub376, Sub263
	common /hee_varXh/ Sub270, Sub300, Sub332, Sub342, Sub264
	common /hee_varXh/ Sub393, Sub212, Sub293, Sub289, Sub253
	common /hee_varXh/ Sub294, Sub291, Sub339, Sub210, Sub371
	common /hee_varXh/ Sub372, Sub374, Sub375, Sub261, Sub340
	common /hee_varXh/ Sub287, Sub379, Sub314, Sub323, Sub320
	common /hee_varXh/ Sub325, Sub327, Sub336, Sub337, Sub354
	common /hee_varXh/ Sub357, Sub360, Sub384, Sub387, Sub257
	common /hee_varXh/ Sub259, Sub369, Sub351, Sub258, Sub262
	common /hee_varXh/ Sub355, Sub358, Sub361, Sub370, Sub347
	common /hee_varXh/ Sub317, Sub256, Sub388, Sub335, Sub310
	common /hee_varXh/ Sub313, Sub142, Sub144, Sub146, Sub246
	common /hee_varXh/ Sub250, Sub251, Sub381, Sub452, Sub469
	common /hee_varXh/ Sub470, Sub471, Sub439, Sub459, Sub451
	common /hee_varXh/ Sub453, Sub460, Sub472, Sub416, Sub414
	common /hee_varXh/ Sub415, Sub430, Sub420, Sub433, Sub426
	common /hee_varXh/ Sub425, Sub422, Sub423, Sub429, Sub424
	common /hee_varXh/ Sub427, Sub434, Sub431, Sub432, Sub435
	common /hee_varXh/ Sub436, Sub437, Sub468, Sub390, Sub260
	common /hee_varXh/ Sub353, Sub288, Sub292, Sub356, Sub239
	common /hee_varXh/ Sub228, Sub232, Sub359, Sub295, Sub238
	common /hee_varXh/ Sub243, Sub265, Sub267, Sub318, Sub298
	common /hee_varXh/ Sub331, Sub467, Sub450, Sub428, Sub377
	common /hee_varXh/ Sub389, Sub458, Sub302, Sub362

	integer seq(2), Hel(3)
	common /hee_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /hee_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hee_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	common /hee_formfactors/ Ctree, Cloop

#endif
