#if 0
* hee-vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Feb-2015 17:20
* this file is part of FeynHiggs
#endif

#ifndef VARS_H
#define VARS_H

#include "externals.h"
#include "types.h"
#include "debug.h"

#else

#include "Decay.h"
#include "hee-renconst.h"

	ComplexType Sub1, Sub2, Sub3
	ComplexType Sub278, Sub168, Sub261, Sub263, Sub200, Sub201
	ComplexType Sub463, Sub73, Sub416, Sub94, Sub301, Sub424
	ComplexType Sub387, Sub293, Sub409, Sub420, Sub287, Sub425
	ComplexType Sub295, Sub411, Sub318, Sub459, Sub380, Sub259
	ComplexType Sub461, Sub390, Sub462, Sub280, Sub277, Sub520
	ComplexType Sub507, Sub403, Sub404, Sub335, Sub327, Sub381
	ComplexType Sub391, Sub515, Sub509, Sub401, Sub402, Sub333
	ComplexType Sub325, Sub377, Sub397, Sub522, Sub502, Sub338
	ComplexType Sub334, Sub330, Sub326, Sub379, Sub383, Sub316
	ComplexType Sub504, Sub524, Sub442, Sub431, Sub353, Sub413
	ComplexType Sub426, Sub499, Sub498, Sub496, Sub497, Sub317
	ComplexType Sub304, Sub444, Sub385, Sub311, Sub398, Sub476
	ComplexType Sub486, Sub479, Sub487, Sub483, Sub489, Sub395
	ComplexType Sub454, Sub475, Sub485, Sub505, Sub495, Sub503
	ComplexType Sub510, Sub523, Sub516, Sub288, Sub368, Sub328
	ComplexType Sub336, Sub382, Sub405, Sub417, Sub436, Sub421
	ComplexType Sub439, Sub410, Sub302, Sub294, Sub433, Sub303
	ComplexType Sub296, Sub366, Sub285, Sub339, Sub331, Sub517
	ComplexType Sub513, Sub511, Sub512, Sub518, Sub437, Sub440
	ComplexType Sub418, Sub422, Sub412, Sub443, Sub432, Sub271
	ComplexType Sub332, Sub273, Sub254, Sub197, Sub337, Sub340
	ComplexType Sub351, Sub323, Sub279, Sub480, Sub488, Sub196
	ComplexType Sub356, Sub352, Sub281, Sub198, Sub199, Sub484
	ComplexType Sub490, Sub537(3), Sub540(3), Sub139(3)
	ComplexType Sub138(3), Sub530(3), Sub533(3), Sub142(3)
	ComplexType Sub141(3), Sub145(3), Sub144(3), Sub82(3)
	ComplexType Sub85(3), Sub75(3), Sub78(3), Sub104(3)
	ComplexType Sub107(3), Sub97(3), Sub100(3), Sub118(3)
	ComplexType Sub121(3), Sub128(3), Sub125(3), Sub14(3)
	ComplexType Sub17(3), Sub7(3), Sub10(3), Sub36(3), Sub39(3)
	ComplexType Sub29(3), Sub32(3), Sub51(3), Sub54(3), Sub61(3)
	ComplexType Sub58(3), Sub216(4), Sub550(4), Sub214(4)
	ComplexType Sub219(4), Sub222(4), Sub231(4), Sub228(4)
	ComplexType Sub234(4), Sub237(4), Sub240(4), Sub226(4)
	ComplexType Sub215(4), Sub217(4), Sub220(4), Sub223(4)
	ComplexType Sub232(4), Sub227(4), Sub235(4), Sub238(4)
	ComplexType Sub241(4), Sub229(4), Sub140(6,3), Sub143(6,3)
	ComplexType Sub146(6,3), Sub551(6,4), Sub549(6,4)
	ComplexType Sub559(6,4), Sub558(6,4), Sub557(6,4)
	ComplexType Sub548(6,4), Sub553(6,4), Sub552(6,4)
	ComplexType Sub188(2,2), Sub183(2,2), Sub192(2,2)
	ComplexType Sub187(2,2), Sub189(2,2), Sub193(2,2)
	ComplexType Sub174(2,2), Sub176(2,2), Sub175(2,2)
	ComplexType Sub147(2,2), Sub149(2,2), Sub148(2,2)
	ComplexType Sub178(2,2), Sub151(2,2), Sub153(2,2)
	ComplexType Sub152(2,2), Sub173(2,2), Sub179(2,2)
	ComplexType Sub181(2,2), Sub180(2,2), Sub546(3,3)
	ComplexType Sub534(3,3), Sub545(3,3), Sub531(3,3)
	ComplexType Sub541(3,3), Sub538(3,3), Sub5(3,3), Sub4(3,3)
	ComplexType Sub27(3,3), Sub26(3,3), Sub49(3,3), Sub48(3,3)
	ComplexType Sub67(3,3), Sub66(3,3), Sub91(3,3), Sub79(3,3)
	ComplexType Sub90(3,3), Sub76(3,3), Sub86(3,3), Sub83(3,3)
	ComplexType Sub113(3,3), Sub101(3,3), Sub112(3,3)
	ComplexType Sub98(3,3), Sub108(3,3), Sub105(3,3)
	ComplexType Sub129(3,3), Sub126(3,3), Sub122(3,3)
	ComplexType Sub119(3,3), Sub134(3,3), Sub133(3,3)
	ComplexType Sub23(3,3), Sub11(3,3), Sub22(3,3), Sub8(3,3)
	ComplexType Sub18(3,3), Sub15(3,3), Sub45(3,3), Sub33(3,3)
	ComplexType Sub44(3,3), Sub30(3,3), Sub40(3,3), Sub37(3,3)
	ComplexType Sub70(3,3), Sub62(3,3), Sub69(3,3), Sub59(3,3)
	ComplexType Sub55(3,3), Sub52(3,3), Sub218(4,4), Sub221(4,4)
	ComplexType Sub224(4,4), Sub230(4,4), Sub233(4,4)
	ComplexType Sub236(4,4), Sub239(4,4), Sub242(4,4)
	ComplexType Sub250(4,4), Sub244(4,4), Sub248(4,4)
	ComplexType Sub247(4,4), Sub246(4,4), Sub245(4,4)
	ComplexType Sub74(6,6,3), Sub96(6,6,3), Sub117(6,6,3)
	ComplexType Sub535(6,3,3), Sub542(6,3,3), Sub532(6,3,3)
	ComplexType Sub539(6,3,3), Sub80(6,3,3), Sub87(6,3,3)
	ComplexType Sub102(6,3,3), Sub109(6,3,3), Sub123(6,3,3)
	ComplexType Sub130(6,3,3), Sub77(6,3,3), Sub84(6,3,3)
	ComplexType Sub106(6,3,3), Sub99(6,3,3), Sub120(6,3,3)
	ComplexType Sub127(6,3,3), Sub12(6,3,3), Sub19(6,3,3)
	ComplexType Sub34(6,3,3), Sub41(6,3,3), Sub56(6,3,3)
	ComplexType Sub63(6,3,3), Sub16(6,3,3), Sub9(6,3,3)
	ComplexType Sub31(6,3,3), Sub38(6,3,3), Sub53(6,3,3)
	ComplexType Sub60(6,3,3), Sub68(6,6,3,3), Sub536(6,6,3,3)
	ComplexType Sub543(6,6,3,3), Sub6(6,6,3,3), Sub547(6,6,3,3)
	ComplexType Sub28(6,6,3,3), Sub50(6,6,3,3), Sub544(6,6,3,3)
	ComplexType Sub81(6,6,3,3), Sub88(6,6,3,3), Sub92(6,6,3,3)
	ComplexType Sub103(6,6,3,3), Sub110(6,6,3,3)
	ComplexType Sub114(6,6,3,3), Sub124(6,6,3,3)
	ComplexType Sub131(6,6,3,3), Sub135(6,6,3,3)
	ComplexType Sub111(6,6,3,3), Sub132(6,6,3,3), Sub89(6,6,3,3)
	ComplexType Sub115(6,6,3,3), Sub136(6,6,3,3), Sub93(6,6,3,3)
	ComplexType Sub13(6,6,3,3), Sub20(6,6,3,3), Sub24(6,6,3,3)
	ComplexType Sub35(6,6,3,3), Sub42(6,6,3,3), Sub46(6,6,3,3)
	ComplexType Sub57(6,6,3,3), Sub64(6,6,3,3), Sub71(6,6,3,3)
	ComplexType Sub21(6,6,3,3), Sub43(6,6,3,3), Sub65(6,6,3,3)
	ComplexType Sub25(6,6,3,3), Sub47(6,6,3,3)
	ComplexType Sub72(6,6,3,3,3,3), Sub473, Sub477, Sub341
	ComplexType Sub392, Sub367, Sub419, Sub438, Sub286, Sub481
	ComplexType Sub453, Sub394, Sub386, Sub310, Sub314, Sub399
	ComplexType Sub350, Sub358, Sub202(3), Sub203(3), Sub205(3)
	ComplexType Sub206(3), Sub208(3), Sub209(3), Sub185(2,2)
	ComplexType Sub186(2,2), Sub150(2,2), Sub154(2,2)
	ComplexType Sub177(2,2), Sub182(2,2), Sub225(4,4)
	ComplexType Sub243(4,4), Sub474, Sub478, Sub482, Sub260
	ComplexType Sub378, Sub393, Sub313, pave1(6,6), pave2(6,6)
	ComplexType pave3(6,6), pave4(6,6), pave5(6,6), pave6(6,6)
	ComplexType pave7(6), pave8(6), pave9(6), pave10(2)
	ComplexType pave11(3), pave12(3), pave13(3), pave14(3)
	ComplexType pave15(3), pave16(3), pave17(3), pave18(3)
	ComplexType pave19(3), pave20(3), pave21(3), pave22(3)
	ComplexType pave23(4), pave24(4,4), pave25(4,4)
	ComplexType pave26(Ncc,6,6,4), pave27(6,4), pave28(Ncc,2)
	ComplexType pave29, pave30, pave31, pave32, pave33, pave34
	ComplexType pave35, pave36, pave37, pave38, pave39, pave40
	ComplexType pave41, pave42, pave43(Ncc), pave44(Ncc)
	ComplexType pave45(Ncc), pave46(Ncc), pave47(Ncc)
	ComplexType pave48(Ncc), pave49(Ncc), pave50(Ncc)
	ComplexType pave51(Ncc), pave52(Ncc), pave53(Ncc)
	ComplexType pave54(Ncc), pave55(Ncc), pave56(Ncc)
	ComplexType pave57(Ncc), pave58(Ncc), pave59(Ncc)
	ComplexType pave60(Ncc), pave61(Ncc), pave62(Ncc)
	ComplexType pave63(Ncc), pave64(Ncc), pave65(Ncc)
	ComplexType pave66(Ncc), pave67, pave68(Ncc), pave69, pave70
	ComplexType pave71, pave72(Ncc), pave73(Ncc), pave74(Ncc)
	ComplexType pave75(Ncc), pave76(Ncc), pave77(Ncc)
	ComplexType pave78(Ncc,2,2), pave79(2), pave80(2,2)
	ComplexType pave81(2,2), pave82(Ncc,6,4,4), pave83, pave84
	ComplexType pave85, pave86, pave87, pave88
	common /hee_varXs/ Sub1, Sub2, Sub3, Sub278, Sub168, Sub261
	common /hee_varXs/ Sub263, Sub200, Sub201, Sub463, Sub73
	common /hee_varXs/ Sub416, Sub94, Sub301, Sub424, Sub387
	common /hee_varXs/ Sub293, Sub409, Sub420, Sub287, Sub425
	common /hee_varXs/ Sub295, Sub411, Sub318, Sub459, Sub380
	common /hee_varXs/ Sub259, Sub461, Sub390, Sub462, Sub280
	common /hee_varXs/ Sub277, Sub520, Sub507, Sub403, Sub404
	common /hee_varXs/ Sub335, Sub327, Sub381, Sub391, Sub515
	common /hee_varXs/ Sub509, Sub401, Sub402, Sub333, Sub325
	common /hee_varXs/ Sub377, Sub397, Sub522, Sub502, Sub338
	common /hee_varXs/ Sub334, Sub330, Sub326, Sub379, Sub383
	common /hee_varXs/ Sub316, Sub504, Sub524, Sub442, Sub431
	common /hee_varXs/ Sub353, Sub413, Sub426, Sub499, Sub498
	common /hee_varXs/ Sub496, Sub497, Sub317, Sub304, Sub444
	common /hee_varXs/ Sub385, Sub311, Sub398, Sub476, Sub486
	common /hee_varXs/ Sub479, Sub487, Sub483, Sub489, Sub395
	common /hee_varXs/ Sub454, Sub475, Sub485, Sub505, Sub495
	common /hee_varXs/ Sub503, Sub510, Sub523, Sub516, Sub288
	common /hee_varXs/ Sub368, Sub328, Sub336, Sub382, Sub405
	common /hee_varXs/ Sub417, Sub436, Sub421, Sub439, Sub410
	common /hee_varXs/ Sub302, Sub294, Sub433, Sub303, Sub296
	common /hee_varXs/ Sub366, Sub285, Sub339, Sub331, Sub517
	common /hee_varXs/ Sub513, Sub511, Sub512, Sub518, Sub437
	common /hee_varXs/ Sub440, Sub418, Sub422, Sub412, Sub443
	common /hee_varXs/ Sub432, Sub271, Sub332, Sub273, Sub254
	common /hee_varXs/ Sub197, Sub337, Sub340, Sub351, Sub323
	common /hee_varXs/ Sub279, Sub480, Sub488, Sub196, Sub356
	common /hee_varXs/ Sub352, Sub281, Sub198, Sub199, Sub484
	common /hee_varXs/ Sub490, Sub537, Sub540, Sub139, Sub138
	common /hee_varXs/ Sub530, Sub533, Sub142, Sub141, Sub145
	common /hee_varXs/ Sub144, Sub82, Sub85, Sub75, Sub78
	common /hee_varXs/ Sub104, Sub107, Sub97, Sub100, Sub118
	common /hee_varXs/ Sub121, Sub128, Sub125, Sub14, Sub17
	common /hee_varXs/ Sub7, Sub10, Sub36, Sub39, Sub29, Sub32
	common /hee_varXs/ Sub51, Sub54, Sub61, Sub58, Sub216
	common /hee_varXs/ Sub550, Sub214, Sub219, Sub222, Sub231
	common /hee_varXs/ Sub228, Sub234, Sub237, Sub240, Sub226
	common /hee_varXs/ Sub215, Sub217, Sub220, Sub223, Sub232
	common /hee_varXs/ Sub227, Sub235, Sub238, Sub241, Sub229
	common /hee_varXs/ Sub140, Sub143, Sub146, Sub551, Sub549
	common /hee_varXs/ Sub559, Sub558, Sub557, Sub548, Sub553
	common /hee_varXs/ Sub552, Sub188, Sub183, Sub192, Sub187
	common /hee_varXs/ Sub189, Sub193, Sub174, Sub176, Sub175
	common /hee_varXs/ Sub147, Sub149, Sub148, Sub178, Sub151
	common /hee_varXs/ Sub153, Sub152, Sub173, Sub179, Sub181
	common /hee_varXs/ Sub180, Sub546, Sub534, Sub545, Sub531
	common /hee_varXs/ Sub541, Sub538, Sub5, Sub4, Sub27, Sub26
	common /hee_varXs/ Sub49, Sub48, Sub67, Sub66, Sub91, Sub79
	common /hee_varXs/ Sub90, Sub76, Sub86, Sub83, Sub113
	common /hee_varXs/ Sub101, Sub112, Sub98, Sub108, Sub105
	common /hee_varXs/ Sub129, Sub126, Sub122, Sub119, Sub134
	common /hee_varXs/ Sub133, Sub23, Sub11, Sub22, Sub8, Sub18
	common /hee_varXs/ Sub15, Sub45, Sub33, Sub44, Sub30, Sub40
	common /hee_varXs/ Sub37, Sub70, Sub62, Sub69, Sub59, Sub55
	common /hee_varXs/ Sub52, Sub218, Sub221, Sub224, Sub230
	common /hee_varXs/ Sub233, Sub236, Sub239, Sub242, Sub250
	common /hee_varXs/ Sub244, Sub248, Sub247, Sub246, Sub245
	common /hee_varXs/ Sub74, Sub96, Sub117, Sub535, Sub542
	common /hee_varXs/ Sub532, Sub539, Sub80, Sub87, Sub102
	common /hee_varXs/ Sub109, Sub123, Sub130, Sub77, Sub84
	common /hee_varXs/ Sub106, Sub99, Sub120, Sub127, Sub12
	common /hee_varXs/ Sub19, Sub34, Sub41, Sub56, Sub63, Sub16
	common /hee_varXs/ Sub9, Sub31, Sub38, Sub53, Sub60, Sub68
	common /hee_varXs/ Sub536, Sub543, Sub6, Sub547, Sub28
	common /hee_varXs/ Sub50, Sub544, Sub81, Sub88, Sub92
	common /hee_varXs/ Sub103, Sub110, Sub114, Sub124, Sub131
	common /hee_varXs/ Sub135, Sub111, Sub132, Sub89, Sub115
	common /hee_varXs/ Sub136, Sub93, Sub13, Sub20, Sub24, Sub35
	common /hee_varXs/ Sub42, Sub46, Sub57, Sub64, Sub71, Sub21
	common /hee_varXs/ Sub43, Sub65, Sub25, Sub47, Sub72, Sub473
	common /hee_varXs/ Sub477, Sub341, Sub392, Sub367, Sub419
	common /hee_varXs/ Sub438, Sub286, Sub481, Sub453, Sub394
	common /hee_varXs/ Sub386, Sub310, Sub314, Sub399, Sub350
	common /hee_varXs/ Sub358, Sub202, Sub203, Sub205, Sub206
	common /hee_varXs/ Sub208, Sub209, Sub185, Sub186, Sub150
	common /hee_varXs/ Sub154, Sub177, Sub182, Sub225, Sub243
	common /hee_varXs/ Sub474, Sub478, Sub482, Sub260, Sub378
	common /hee_varXs/ Sub393, Sub313, pave1, pave2, pave3
	common /hee_varXs/ pave4, pave5, pave6, pave7, pave8, pave9
	common /hee_varXs/ pave10, pave11, pave12, pave13, pave14
	common /hee_varXs/ pave15, pave16, pave17, pave18, pave19
	common /hee_varXs/ pave20, pave21, pave22, pave23, pave24
	common /hee_varXs/ pave25, pave26, pave27, pave28, pave29
	common /hee_varXs/ pave30, pave31, pave32, pave33, pave34
	common /hee_varXs/ pave35, pave36, pave37, pave38, pave39
	common /hee_varXs/ pave40, pave41, pave42, pave43, pave44
	common /hee_varXs/ pave45, pave46, pave47, pave48, pave49
	common /hee_varXs/ pave50, pave51, pave52, pave53, pave54
	common /hee_varXs/ pave55, pave56, pave57, pave58, pave59
	common /hee_varXs/ pave60, pave61, pave62, pave63, pave64
	common /hee_varXs/ pave65, pave66, pave67, pave68, pave69
	common /hee_varXs/ pave70, pave71, pave72, pave73, pave74
	common /hee_varXs/ pave75, pave76, pave77, pave78, pave79
	common /hee_varXs/ pave80, pave81, pave82, pave83, pave84
	common /hee_varXs/ pave85, pave86, pave87, pave88

	ComplexType F1, F2
	ComplexType Sub376, Sub162, Sub163, Sub346, Sub361, Sub360
	ComplexType Sub270, Sub299, Sub307, Sub184, Sub272, Sub492
	ComplexType Sub494, Sub276, Sub274, Sub312, Sub315, Sub320
	ComplexType Sub407, Sub389, Sub396, Sub400, Sub455, Sub500
	ComplexType Sub384, Sub309, Sub408, Sub466, Sub284, Sub300
	ComplexType Sub292, Sub319, Sub388, Sub343, Sub365, Sub258
	ComplexType Sub322, Sub268, Sub429, Sub447, Sub456, Sub324
	ComplexType Sub355, Sub349, Sub430, Sub448, Sub457, Sub529
	ComplexType Sub472, Sub465, Sub252, Sub266, Sub344, Sub253
	ComplexType Sub256, Sub257, Sub264, Sub267, Sub262, Sub265
	ComplexType Sub289, Sub369, Sub298, Sub306, Sub348, Sub354
	ComplexType Sub364, Sub363, Sub372, Sub374, Sub449, Sub428
	ComplexType Sub423, Sub415, Sub446, Sub441, Sub435, Sub458
	ComplexType Sub460, Sub468, Sub528, Sub519, Sub514, Sub291
	ComplexType Sub305, Sub297, Sub373, Sub371, Sub491, Sub493
	ComplexType Sub342, Sub469, Sub359, Sub452, Sub414, Sub434
	ComplexType Sub427, Sub445, Sub347, Sub345, Sub506, Sub464
	ComplexType Sub290, Sub370, Sub508, Sub521, Sub525, Sub450
	ComplexType Sub467, Sub255, Sub283, Sub580(2)
	ComplexType Sub577(2), Sub578(2)
	ComplexType Sub579(2), Sub158(2,2)
	ComplexType Sub160(2,2), Sub161(2,2)
	ComplexType Sub166(2,2), Sub167(2,2)
	ComplexType Sub170(2,2), Sub171(2,2)
	ComplexType Sub190(2,2), Sub194(2,2)
	ComplexType Sub159(2,2), Sub155(2,2)
	ComplexType Sub165(2,2), Sub156(2,2)
	ComplexType Sub157(2,2), Sub164(2,2)
	ComplexType Sub169(2,2), Sub556(6,6,4)
	ComplexType Sub554(6,6,4), Sub555(6,6,4)
	ComplexType Sub565(6,4,4), Sub564(6,4,4)
	ComplexType Sub561(6,4,4), Sub562(6,4,4)
	ComplexType Sub569(6,4,4), Sub560(6,4,4)
	ComplexType Sub572(6,4,4), Sub568(6,4,4)
	ComplexType Sub563(6,4,4), Sub566(6,4,4)
	ComplexType Sub573(6,4,4), Sub570(6,4,4)
	ComplexType Sub571(6,4,4), Sub574(6,4,4)
	ComplexType Sub575(6,4,4), Sub137(6,6,3,3,3)
	ComplexType Sub95(6,6,3,3,3), Sub116(6,6,3,3,3)
	ComplexType Sub470, Sub406, Sub282, Sub501, Sub375, Sub308
	ComplexType Sub362, Sub451, Sub321, Sub357, Sub526
	ComplexType Sub212(3), Sub213(3)
	ComplexType Sub211(3), Sub172(2,2)
	ComplexType Sub195(2,2), Sub567(6,4,4)
	ComplexType Sub576(6,4,4), Sub269, Sub527
	ComplexType Sub204(3), Sub207(3)
	ComplexType Sub210(3), Sub251(4,4), Sub471
	ComplexType Sub249(4,4)
	common /hee_varXh/ F1, F2, Sub376, Sub162, Sub163, Sub346
	common /hee_varXh/ Sub361, Sub360, Sub270, Sub299, Sub307
	common /hee_varXh/ Sub184, Sub272, Sub492, Sub494, Sub276
	common /hee_varXh/ Sub274, Sub312, Sub315, Sub320, Sub407
	common /hee_varXh/ Sub389, Sub396, Sub400, Sub455, Sub500
	common /hee_varXh/ Sub384, Sub309, Sub408, Sub466, Sub284
	common /hee_varXh/ Sub300, Sub292, Sub319, Sub388, Sub343
	common /hee_varXh/ Sub365, Sub258, Sub322, Sub268, Sub429
	common /hee_varXh/ Sub447, Sub456, Sub324, Sub355, Sub349
	common /hee_varXh/ Sub430, Sub448, Sub457, Sub529, Sub472
	common /hee_varXh/ Sub465, Sub252, Sub266, Sub344, Sub253
	common /hee_varXh/ Sub256, Sub257, Sub264, Sub267, Sub262
	common /hee_varXh/ Sub265, Sub289, Sub369, Sub298, Sub306
	common /hee_varXh/ Sub348, Sub354, Sub364, Sub363, Sub372
	common /hee_varXh/ Sub374, Sub449, Sub428, Sub423, Sub415
	common /hee_varXh/ Sub446, Sub441, Sub435, Sub458, Sub460
	common /hee_varXh/ Sub468, Sub528, Sub519, Sub514, Sub291
	common /hee_varXh/ Sub305, Sub297, Sub373, Sub371, Sub491
	common /hee_varXh/ Sub493, Sub342, Sub469, Sub359, Sub452
	common /hee_varXh/ Sub414, Sub434, Sub427, Sub445, Sub347
	common /hee_varXh/ Sub345, Sub506, Sub464, Sub290, Sub370
	common /hee_varXh/ Sub508, Sub521, Sub525, Sub450, Sub467
	common /hee_varXh/ Sub255, Sub283, Sub580, Sub577, Sub578
	common /hee_varXh/ Sub579, Sub158, Sub160, Sub161, Sub166
	common /hee_varXh/ Sub167, Sub170, Sub171, Sub190, Sub194
	common /hee_varXh/ Sub159, Sub155, Sub165, Sub156, Sub157
	common /hee_varXh/ Sub164, Sub169, Sub556, Sub554, Sub555
	common /hee_varXh/ Sub565, Sub564, Sub561, Sub562, Sub569
	common /hee_varXh/ Sub560, Sub572, Sub568, Sub563, Sub566
	common /hee_varXh/ Sub573, Sub570, Sub571, Sub574, Sub575
	common /hee_varXh/ Sub137, Sub95, Sub116, Sub470, Sub406
	common /hee_varXh/ Sub282, Sub501, Sub375, Sub308, Sub362
	common /hee_varXh/ Sub451, Sub321, Sub357, Sub526, Sub212
	common /hee_varXh/ Sub213, Sub211, Sub172, Sub195, Sub567
	common /hee_varXh/ Sub576, Sub269, Sub527, Sub204, Sub207
	common /hee_varXh/ Sub210, Sub251, Sub471, Sub249

	integer seq(2), Hel(3)
	common /hee_helind/ seq, Hel

	integer All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2, Ind3, Ind4
	integer Neu4, Neu5
	common /hee_indices/ All4, All5, Cha4, Cha5, Gen4, Ind1, Ind2
	common /hee_indices/ Ind3, Ind4, Neu4, Neu5

	ComplexType Ctree(1), Cloop(1)
	common /hee_formfactors/ Ctree, Cloop

#endif
